### PR TITLE
Heart logic

### PR DESCRIPTION
**Pull request by puddydoo**
Hearts (and double defense) considered in Glitchless logic. Normally only starting hearts are counted (which is not necessarily 3 hearts), but there are tricks for considering extra heart containers or pieces of heart. Checks for multiple bottles are in logic but currently no function to count them. The logic allows for starting hearts to be lowered, down to 0 hearts (technically 1/8 of a heart, which gives 1 second on timers). There are also placeholders for more heart-related settings like bridge/LACS conditions and replacing starting hearts with random items.

Certain areas that hard-required tunic now have their own tricks separate from Fewer Tunic Requirements. Many of the DMC checks probably should be limited to FTR and there could be added routes that require more hearts but not FTR.

### CODE REVIEW

**Comment by Zannick** [comment]
I am not sure if this is a feature we will want. Soliciting opinions.

**Comment by r0bd0g** [comment]
I worry about whether heart logic is actually reasonable to account for. When you respawn after a death, it's still only with 3 hearts. To logically make use of them, you'd have to ensure that the health could be refilled, which sounds actually really difficult to do perfectly.

**Comment by Zannick** [comment]
Hm, that's true. Or modify the game to always return you at full health.

**Comment by puddydoo** [comment]
Modifying the game to always return you to full health would also be necessary to be able to set starting hearts lower than 3 because you respawn with 3 hearts of health even with fewer heart containers.

**Comment by Zannick** [comment]
I'm not really happy introducing heart requirements to glitchless logic, just out of fear of making things too difficult with FTR and complicated in the logic (some of which I can already tell is too complicated). As a general rule, we don't have to model every possible way to complete a check, just have some reasonable minimum requirements. It will be absolutely no fun to require 4 bottles of fairies and then mess up anyway and need to go all the way back across the map to restock on fairies. And Volvagia should continue to require tunic, full stop. I don't think adding tricks like that is worth the additional complexity.

And there are too many other features and refactors going on that this is just not feasible to review in this state.

If there's interest from the glitched community on having this available, then please redo with just the heart logic stuff for glitched, and require at most one fairy per health check.

**Pull request closed without merging**
