### PR TITLE
New cosmetic option : Display d-pad on the left of the screen

### PR DESCRIPTION
**Pull request by GSKirox**
image

This option puts the custom HUD for d-pad on the left of the screen instead of the right, putting in more in line in both where the d-pad is on the controller, and with the following Zelda games that have a d-pad HUD.
dpadleft1
dpadleft2
dpadleft3
dpadleft4
The top coordinate will slightly lower if you get a 2nd row of hearts, to accomodate for the magic bar and timer placement.
It will also lower if a timer shows up on screen, and go back up once the timer is gone : 

https://github.com/OoTRandomizer/OoT-Randomizer/assets/65768236/5ca0d5cc-2d05-4083-aeaf-9177c6205e3c

Took the occasion to rename the d-pad drawing function since it does a little more than what was originally intended, and cleaned the code so that there's less hard-coded XY values, and more modular values.

### CODE REVIEW

**Comment by fenhl** [comment]
I think it would be more intuitive to combine this setting with the existing “Display D-Pad HUD” setting into a combobox with “Left”, “Right”, and “Off” options.

We should also consider making left the default option. I can't think of any reason to have the display on the right other than people being used to it from previous versions of the randomizer, and those people can still use that option to go back to how it was if they so choose.

**Comment by GSKirox** [comment]
I kinda nobrained the UI but it would make more sense to have a Combobox, i agree, makes the UI less cluttered. Will try it.
As for the default value i have no strong opinion.

**Comment by GSKirox** [comment]
There we go, much better indeed
image

**Comment by ETR-BTF** [comment]
I like it on the right because then it's with the other items. You don't have to move your eyes across the screen to see your available items.

**Review by cjohnson57 — APPROVED** [review]

**Comment by cjohnson57** [comment]
I'm fine with leaving the default as is

**Pull request merged**
