### PR TITLE
Cache shop item models to avoid lookups every frame

### PR DESCRIPTION
**Pull request by cjohnson57**
This PR changes the `shop_draw` function introduced in #1986 and #2027 to cache results from the item table lookups which occur here, as the 2 lookups every frame were causing some lag on the encryption branch.

The only thing we really need from the lookups are the `graphic_id` and `object_id` for the model, which are 2 and 1 bytes, respectively. `EnGirlA` happens to have a field that's 4 bytes despite only being used as a boolean, so the byte that holds a value of 1 (as the field is initialized to `true`) is ignored while the other 3 bytes are used for our purposes.

[EnGirlA isInitialized](https://github.com/zeldaret/oot/blob/main/src/overlays/actors/ovl_En_GirlA/z_en_girla.h#L20) at 0x019C (We start at 0x10 less due to debug actors adding 0x10 padding)

[EnGirlA setting isInitialized](https://github.com/zeldaret/oot/blob/main/src/overlays/actors/ovl_En_GirlA/z_en_girla.c#L1067) The value is never changed after this, only being checked on object destruction.

Everything seemed to be working from my initial testing, but it could definitely use some more, especially on the encrypt branch. Testing can be done using the [same plandos used for #2027](https://github.com/OoTRandomizer/OoT-Randomizer/pull/2027#issuecomment-1613801485)

There is one unfortunate regression this PR brings. Since the item model is cached, then if there are multiple copies of the same progressive item in a shop, and you purchase one, you have to reload the scene for the model change to take effect. But this is a fairly niche situation, and I'm not sure how to get around it.

Huge thanks to @TestRunnerSRL for helping me on this. 

@mracsys as the original coder of this function, you might want to take a look.

### CODE REVIEW

**Comment by r0bd0g** [comment]
"Since the item model is cached, then if there are multiple copies of the same progressive item in a shop, and you purchase one, you have to reload the scene for the model change to take effect"
Is that exactly what those two PRs were trying to fix?
I assume the same issue also occurs if you get the item from the freestanding in Kokiri Shop or from another MW player?

I don't think the encryption is worth getting in the way of functionality like this. Most players aren't even racers.

**Comment by cjohnson57** [comment]
No, those PRs fixed the fact that shop models were previously not progressive at all

**Comment by fenhl** [comment]
Since this is a regression, can this change be made conditional on a config symbol and only be enabled on the encryption branch?

**Comment by cjohnson57** [comment]
> Since this is a regression, can this change be made conditional on a config symbol and only be enabled on the encryption branch?

I'm fine with that, not sure how to implement it though

**Comment by ETR-BTF** [comment]
> Since this is a regression, can this change be made conditional on a config symbol and only be enabled on the encryption branch?

This might lead to confusion and questions due to the inconsistent behavior of shops. I think it's better to just open an issue and fix the bug in the future.

**Comment by flagrama** [comment]
> There is one unfortunate regression this PR brings. Since the item model is cached, then if there are multiple copies of the same progressive item in a shop, and you purchase one, you have to reload the scene for the model change to take effect. But this is a fairly niche situation, and I'm not sure how to get around it.

Requires additional ROM hacking, but would clearing the cache of values with the same getItemId on item purchase (`EnOssan_State_ItemPurchased` in decomp I believe `C69658` in 1.0, probably after the `buyEventFunc` is called but before the message) not force the model to update on the next draw? It seems to be the same general place masks get added/removed from display.

**Comment by flagrama** [comment]
Something like

```c
void shop_item_purchased_clear_cached_model(z64_actor_t *actor) {
    EnOssan *this = (EnOssan *)actor;

    for (int i = 0; i < 8; i++) {
        EnGirlA *item = this->shelfSlots[i];
        ((uint8_t*)item)[0x18D] = 0;
        ((uint8_t*)item)[0x18E] = 0;
        ((uint8_t*)item)[0x18F] = 0xFF;
    }
}
```

at the very basic of levels

**Comment by cjohnson57** [comment]
That'd be a good solution too. I'll see if I can look into it today

**Comment by cjohnson57** [comment]
Closing in favor of #2130

**Pull request closed without merging**
