### PR TITLE
Use Table for item restrictions

### PR DESCRIPTION
**Pull request by louist103**
Updated #1931

### CODE REVIEW

**Comment by fenhl** [comment]
For potential future changes to these flags, it would be useful to include a comment in the added code documenting the structure of this data.

**Comment by louist103** [comment]
> For potential future changes to these flags, it would be useful to include a comment in the added code documenting the structure of this data.

Its this:
https://github.com/OoTRandomizer/OoT-Randomizer/blob/c5c4d70500deea855e0e6ba97997cfde1b5d3693/ASM/src/item_restriction_flags.asm#L3

**Comment by fenhl** [comment]
I'd like to see more detail. Presumably `flags1`, `flags2`, and `flags3` are bitfields. What do the individual bits do?

**Comment by mracsys** [comment]
> I'd like to see more detail. Presumably `flags1`, `flags2`, and `flags3` are bitfields. What do the individual bits do?

Those are the names as-is from decomp at the moment. Adding https://wiki.cloudmodding.com/oot/Scenes#Restriction_Flags to the comment might be good.

@louist103 The PR doesn't change the payload. You need to add the new asm file to build.asm in the base game editing region.

**Comment by mracsys** [comment]
Thanks for the update! Everything looks good to me.

**Comment by cjohnson57** [comment]
They're working for Granny's shop and GTG, but I don't seem allowed to use ocarina in shooting gallery (as adult or child)
image

**Comment by cjohnson57** [comment]
Awesome, ty, seems good

**Review by cjohnson57 — APPROVED** [review]

**Pull request merged**
