### PR TITLE
Add visual stone of agony marker

### PR DESCRIPTION
**Pull request by rlbond86**
This PR adds an option that makes Navi turn green and fly to nearby hidden grottos (i.e., those revealed by the Song of Storms or by an explosion/hammer). Navi will behave similarly to a fairy spot, turning green without being Z-targetable and with no checkable message. Navi will not fly to non-hidden grottos or to hidden grottos that have become visible.

The reasoning behind this feature is that the Randomizer logic requires knowledge of these grottos, but an inexperienced player would have no chance of actually finding the grotto locations without the Stone of Agony (not required in logic) and a controller with vibration (which many players do not have). Originally, these grottos contained only non-essential items, so a player without a Rumble Pack could still complete the game. With the "grotto shuffle" option, even somewhat experienced players may have difficulty locating or remembering some of the previously-useless hidden locations.

### CODE REVIEW

**Comment by aofengen** [comment]
does changing Navi's color affect the color she turns when near a hidden grotto? that might be an issue if players are expecting a certain color

**Comment by rlbond86** [comment]
It works exactly like any other attractable object. Basically, this sets the bits that tell Navi to fly to the object.

**Comment by aofengen** [comment]
come to think of it, doesn't navi already turn green for some hidden items that aren't grottos? I think she goes green for the hidden big fairies you can summon with a song

**Comment by rlbond86** [comment]
Yes, this makes Navi behave exactly the same way as she does around big fairies and around scarecrow spots.

**Comment by aofengen** [comment]
would it be worth making her turn a different color? just to make it more obvious. Idk - I actually really like this

**Comment by rlbond86** [comment]
That would require big changes to the Navi code as far as I can tell.

**Comment by aofengen** [comment]
ah ok. If that's the case, it's not worth it, then. But yeah, this is a great idea

**Comment by r0bd0g** [comment]
This is interesting...

I think I would prefer something like how the shard of agony works in oot3d, with logic option to require it for those grottos, but then given that that item can already be logically required for certain checks in some settings, maybe this is better.

**Comment by KevinPal** [comment]
This doesn't need to be an option in my opinion, it shouldn't bother most people, and only help out new people. Less GUI clutter is better.

**Comment by rlbond86** [comment]
Oooooooo

**Comment by flagrama** [comment]
I think I'd prefer a shard of agony version better as well.

As it is now though, which prop color does Navi use for this? Completely Random means there are about 7 different random colors involved with props (7 prop, 1 npc, 2 enemy, 1 idle color). Is there a particular one you are using? Do you know which other props normally use this color?

Also I don't think specifying the color as green in the settings text works well since that isn't a consistent color.

I also agree this shouldn't be an option, just always on.

**Comment by rlbond86** [comment]
It's "Navi Targeting Prop" color, I can definitely fix that in the description.

I thought about a shard version that checks for the presence of the stone of agony, but rejected that idea because it would probably need an option to require the shard in logic for hidden grottos, similar to the Lens of Truth.

**Comment by flagrama** [comment]
You misunderstand. There are 9 Navi Targeting Prop colors, most, if not all of them are used in-game separately, and Completely Random will set each of them to a different color entirely.
https://github.com/TestRunnerSRL/OoT-Randomizer/blob/Dev/Cosmetics.py#L232-L235
```python
        ('Navi Targeting Prop',  settings.navi_color_prop_inner,    settings.navi_color_prop_outer,
            [0x00B5E174, 0x00B5E17C, 0x00B5E18C,
            0x00B5E1A4, 0x00B5E1AC, 0x00B5E1B4,
            0x00B5E1C4, 0x00B5E1CC, 0x00B5E1D4]), # Everything else
```
As for shard of agony-style, I'd literally use the shard icon probably to keep it from directly being associated with the stone of agony. I'm not sure how many people would be too upset by that idea.

**Comment by rlbond86** [comment]
This will be the same color as "checkable spot."

**Comment by rlbond86** [comment]
I really am not a fan of the shard idea because the randomizer rules require knowing the grotto locations. Another option for that could be added I suppose but it starts to become a huge change

**Comment by r0bd0g** [comment]
I guess I'll restate my opinion here, idk. I think the spirit of vanilla is to find SOA to help reveal the locations of these grottos. It'd be fairly painless I think to add a trick to not logically require it. (But SOA is already maybe logically unlocking other things as well, so I feel strange about having it logically required for those unrelated things.)

**Comment by rlbond86** [comment]
I've made a branch that only attracts Navi with the Stone of Agony. I haven't added any rules yet. https://github.com/rlbond86/OoT-Randomizer/tree/navi_grotto_agony

I'd be interested to hear @TestRunnerSRL's opinion before continuing.

**Comment by Zannick** [comment]
Just so I'm clear on the proposal and discussion so far, is this right?

* Original PR makes Navi fly toward hidden grottos. Color is unchanged (taken from existing settings).
* A few prefer to make it not an option, always enabled.
* A suggestion to make Stone act more like Shard of Agony, which adds a HUD element around grottos instead of making Navi fly toward them.

If that's right, I think I prefer always-on/no option (I think it ought to be unobtrusive enough once people are used to Navi pointing out new places), and requiring Stone, regardless of how the hint is conveyed.

(FWIW I think logically requiring Stone for hidden grottos will make this a Stone buff, since without `hints=stone` it's a dead-end item.)

**Comment by Zannick** [comment]
I consulted with TR on this, and the conclusion was:
* definitely omit the option, leave always on
* require the Stone of Agony for the behavior (TR could go either way, I lean in favor of SoA)
    * if SoA, require the Stone of Agony in logic for these grottos, and add a trick to bypass

We're both happy to have this part be more beginner-friendly, and also to give the Stone a similar use to vanilla.

**Comment by rlbond86** [comment]
> 
> 
> I consulted with TR on this, and the conclusion was:
> 
>     * definitely omit the option, leave always on
> 
>     * require the Stone of Agony for the behavior (TR could go either way, I lean in favor of SoA)
>       
>       * if SoA, require the Stone of Agony in logic for these grottos, and add a trick to bypass
> 
> 
> We're both happy to have this part be more beginner-friendly, and also to give the Stone a similar use to vanilla.

Updated to behave as described in this comment (require SoA, add trick to bypass). Glitched World never requires SoA.

**Comment by flagrama** [comment]
This behaviour is nice because you can also start with SoA so you have three options in all for how to play. On and available from start, on but require an item, and on but not required due to previous knowledge.

**Comment by r0bd0g** [comment]
Near Gerudo Valley grotto should check for SoA regardless of age.

**Comment by rlbond86** [comment]
> Near Gerudo Valley grotto should check for SoA regardless of age. (After hammering the rock, you must still hammer/bomb the ground to make the grotto appear.)

I just verified that you are correct and have updated the rule accordingly.

**Comment by LostThePirate** [comment]
Seems like a good addition, to make Scrub Shuffle and ER more palatable to newer players, assisting them to find the locations that are hidden in vanilla, as well as the Logic Trick to turn needing SoA off for experienced players.

**Comment by r0bd0g** [comment]
Alright, logic looks good to me.

Curious, what does the stone of agony pickup text say? Is there anything about it that should be updated?

**Comment by r0bd0g** [comment]
You need to update barren hints to account for stone of agony's new purpose.

Normally we don't account for trick settings b/c it gets confusion really fast, but I imagine people would generally not be happy with the change to make agony never allowed to be barren, so we might have to start making exceptions.

**Comment by rlbond86** [comment]
I've updated this PR to display a vibrating stone of agony marker on the HUD instead of attracting Navi. It was easier than anticipated.

**Comment by rlbond86** [comment]
Addressed exclusion list. Changed radius to reflect vibration region (it's actually slightly smaller, but toward the outside of the radius, the time between vibrations approaches infinity). Added fade in/out of icon.

I tried to sync the vibration to the actual stone vibration, but it was too difficult for me to implement. The vibration code is at 0x80847014 if anyone wants to attempt it in the future.

**Comment by rlbond86** [comment]
Also, due to a rebase, github appears to have completely screwed up the order of commits in the PR. It doesn't match `git log` for some reason.

**Comment by rlbond86** [comment]
Due to significant rework, I have reintroduced the changes from this PR into #966 and #967.

**Pull request closed without merging**
