### PR TITLE
Add Custom Key Models and Improve Keyring and Chu Bags

### PR DESCRIPTION
**Pull request by Maplesstar**
Big thanks to choiceoxide for the designs and all the devs who taught me how to implement this stuff.

The models for the small keys are substantially larger than the base game small keys:
image

The vanilla boss key is still in use for Ganon's boss key, but with the center color changed to match it's small key, and is sized up to match:
image

The keyring model is upgraded since I now know better where the size limitations lie, I was able to make the ring more round and add a key:
image

The chu bag change was mainly the color to better mimic the actual bombchus for the blue part. The brown was left matte since it's a bag.
image
image

For quick reference, these are the models currently in use:
image

### CODE REVIEW

**Comment by cjohnson57** [comment]
1) These models are all amazing, great work <3
2) The updated key models should probably be made optional, in a setting akin to CSMC

**Comment by r0bd0g** [comment]
There was no option to have hint texts not tell you which key is which though.

**Comment by fenhl** [comment]
Hints are allowed to give more information than item models. I agree that this should be a setting.

**Comment by r0bd0g** [comment]
Then on the other hand, there's no setting for sideways Ruto's Letter.

**Comment by GSKirox** [comment]
Sideways RL could easily be integrated into a "More accurate models" setting, since the change is done is the same file as the key changes

**Comment by fenhl** [comment]
I don't think sideways letter should be behind a setting. Letter is already a distinct model, turning it sideways just makes it easier to distinguish, so it's a pure accessibility win. This PR gives the player information they didn't have before.

**Comment by ETR-BTF** [comment]
> I don't think sideways letter should be behind a setting. Letter is already a distinct model, turning it sideways just makes it easier to distinguish, so it's a pure accessibility win. This PR gives the player information they didn't have before.

Then so should the inverted song models?

**Comment by fenhl** [comment]
The inverted song models could be behind a setting as well, yes. (I have them included in such a setting on my branch.) But there's an argument to be made that having them all distinct anyway makes it more straightforward to add colorblind-friendly symbols to distinguish them.

**Comment by mracsys** [comment]
Songs are a special case where there are no official in-game models, just unused assets. If the model pipeline we have now was available when songsanity was introduced, inverted song models probably would have been there from the beginning.

**Comment by cjohnson57** [comment]
I know Maple's currently working out the merge conflicts, once those are resolved this should be good to go

**Comment by Maplesstar** [comment]
mracsys fixed it, it's working now.

**Pull request merged**
