### PR TITLE
Change buy item names with prices

### PR DESCRIPTION
**Pull request by cjohnson57**
Change them from using brackets (ex. [30]) to ex. for 30

~~There's a weird bug with python 3.10 that seems to maybe parse these as arrays in the spoiler. I couldn't reproduce it on dev but could reproduce it on other branches, so it seems volatile, so I figured it's good to change the names to be safe.~~ Plus, I think these names are more clear anyway.

EDIT: Never mind, it was actually another issue and this solution was a red herring. However I still like the name change, so I may as well keep this PR open.

### CODE REVIEW

**Comment by Zannick** [comment]
I feel like we should have "for Rs30" or "for ₨30" or "for 🞠30" to make it a little clearer that it's a currency.

**Comment by fenhl** [comment]
probably `for Rs30` since location and item names currently avoid non-ASCII characters (e.g. `Dampe`)

**Comment by cjohnson57** [comment]
What else would "buy x for 30" mean other than currency? I think I'd find the Rs more confusing...

**Comment by Zannick** [comment]
"Buy Bombs (5) for 25": certainly a little better than "Buy Bombs (5) [25]" but still makes me go "whoa, pay 25 bombs for 5, bad deal". :p

**Comment by cjohnson57** [comment]
Fair enough, I'll update it to add Rupees to the name

**Comment by Cuphat** [comment]
Personally, I think I prefer the brackets instead of "for" but adding rupees to it makes a lot of sense. Like `Buy Bombs (5) [25 Rupees]`

**Pull request merged**
