### PR TITLE
Prevent Pausing While Item is Pending

### PR DESCRIPTION
**Pull request by Cuphat**
This is intended to prevent pausing to save warp while an item is pending (for instance, after the flag for Light Arrow Cutscene is set but before the item is given).

Testing can happen with this branch offline or additionally at [https://ootrandomizer.com/generatorDev?version=devCuphat_](https://ootrandomizer.com/generatorDev?version=devCuphat_)

### CODE REVIEW

**Comment by fenhl** [comment]
Does this function only get called when unpaused? If not, this needs to be adjusted to prevent multiworld players from getting stuck in the pause menu, since multiworld uses the same pending item queue.

**Comment by fenhl** [comment]
We also need to consider situations in gameplay where being unable to pause could result in the player getting stuck and potentially being forced to reset without saving. Being stuck on Epona in overworld ER for example.

**Comment by Cuphat** [comment]
@fenhl Thanks for all the potential gotchas. I threw this together quickly and did the most basic testing to make sure it worked. It'll definitely need to account for those things.

**Comment by r0bd0g** [comment]
Is there time to die and save the item away?

**Comment by Cuphat** [comment]
@r0bd0g I'd imagine you could get an ice trap sent via multiworld at the right time to die and save/quit, but I am not sure how else you'd be able to die quickly enough.

**Comment by r0bd0g** [comment]
I think you could also warp song while dead into it?

**Comment by fenhl** [comment]
Maybe instead of this solution we could split the incoming item queue into 2 queues: use the current one only for multiworld, and add a second queue stored in the save file for delayed items. Being stored in the save file would mean that items in it are still applied after a savewarp.

**Comment by Cuphat** [comment]
Superseded by #1695

**Pull request closed without merging**
