### PR TITLE
Rewording the Goron City Maze Left Chest hint

### PR DESCRIPTION
**Pull request by Star1468**
The current wording of the hint for this chest is "in Goron City the hammer unlocks". While hammer is one of the methods for accessing this chest by breaking the red boulders, this is not the only way to get this chest. Silver gauntlets are also in default logic, there is a trick for hover boots, and one can also access this chest with glitches or by cheesing it with CSMC. This can create confusion (and result in hints such as "in Goron City the hammer unlocks the hammer") among players newer to randomizer, who may assume based on the hint's wording that the hammer is the only way to reach this chest. To reduce confusion, this PR changes the wording of the hint to "the left chest in Goron City's maze holds", which still distinguishes the position of the chest without being misleading as to what items are required to access it. Wording chosen after considerable debate within the Discord.

### CODE REVIEW

**Comment by cjohnson57** [comment]
I missed the debate but will add on to it: "leftmost chest" could also be confusing if the player doesn't know there's a 3rd chest there. Obviously we can't expect all hints to be 100% understandable by someone without sufficient game knowledge, but I think a good way to avoid it here would be to have something like "the chest hidden by stronger rocks" or "the chest behind rocks with greater durability" (I'm sure you can come up with better wording than I can)

**Comment by r0bd0g** [comment]
I think it should reference the rocks as well but nobody could think of a good wording there were always objections to every single wording.

**Comment by Star1468** [comment]
For reference, the two discussions in the Discord about the hint's wording:

Discussion 1: https://discord.com/channels/274180765816848384/512048482677424138/923379833977860117
Discussion 2 (intermingled with discussion about other topics): https://discord.com/channels/274180765816848384/512048482677424138/942226639838933022

The current proposed wording: 1) refers to the position (the left chest), 2) refers to Goron City, and 3) is in line with the spoiler log name (GC Maze left Chest). This is one of the topics where we'll never get everyone to agree on one wording, so this is what I went with.

**Comment by cjohnson57** [comment]
After reading both I still personally think something referencing the rocks would be understandable by the highest amount of people, else would be fine with something like "the leftmost chest by itself" so that newer players will still know to look beyond the two chests.

**Comment by cjohnson57** [comment]
That's really good imo

**Comment by r0bd0g** [comment]
The three chests are not so different in terms of distance apart, so I don't think it really works. Destroy all the boulders and it's just three chests in a line back there. There is no perfect way to word this one.

**Comment by cjohnson57** [comment]
Since no good consensus could be reached on how to name it, closing this for now.

**Pull request closed without merging**
