### PR TITLE
Make Dampe 2 as child a trick

### PR DESCRIPTION
**Pull request by dombarrieau**
Dampe 2 as child is very time restrictive and should be a trick instead.

### CODE REVIEW

**Comment by Roman971** [comment]
"Dampe PoH as child" really sounds like it's about the gravedigging PoH. The trick should probably have a name that mentions the 2nd race instead.

**Comment by dombarrieau** [comment]
That's what I initially had, but changed it to be more inline with the rest of the tricks. But I also forgot about the grave digging PoH. Will submit a patch

**Comment by Roman971** [comment]
Also this is kind of minor and an edge thing but one could argue being able to do the 2nd race is needed logically even to get the chest since you could just skip it after the 1st race. I doubt we want to worry about that kind of things tho...

**Comment by dombarrieau** [comment]
You can still make it to the room with the chest in over a minute in the second race. There are the claims that the second race is harder, but it is easier to get there in over a minute in the second race than under, so I think it is ok to keep the chest always in logic

**Comment by Roman971** [comment]
Yeah if we consider the one minute limit as the reason for the trick then it's fine.

**Comment by r0bd0g** [comment]
Is this needed? I feel like doing it as child takes like 5s longer? You'd still have like 10s to spare. Could probably be hit by 3 flames and still make it.

**Comment by churnthing** [comment]
If this gets made a trick, needs to consider that the player could have bunny hood.

**Pull request merged**
