### PR TITLE
Setting to configure the multiple of tokens needed

### PR DESCRIPTION
**Pull request by KevinPal**
Allows configuring the multiple of tokens needed for rewards. For example, if set to 6, instead of needing 10/20/30/40/50, you would need 6/12/18/24/30. Also allows to randomize this value. The cursed old skull man in the center of the skulltula house will tell you how many you need. The GUI might need a reword.

### CODE REVIEW

**Comment by KevinPal** [comment]
You could make the 5th guy require 100 by setting the multiplier to 20. I'm not sure what would be the limit to start including the 6th guy.

**Comment by KevinPal** [comment]
Accidently hit close and comment instead of comment =/

**Comment by aofengen** [comment]
It's not the multiplier that's prevents 100 GS reward from being randomized - it's the fact that it's repeatable. It's certainly possible to fix, given that cows were done in this manner. Just actually have to have someone do it. But does kak really need any more checks, especially more skull checks?

**Comment by Roman971** [comment]
Shouldn't hints be corrected to account for the actual amount of tokens required for each check, instead of always saying "They say that slaying 10/20/30/40 Gold Skulltulas reveals X"?

Also it might be a good idea to change the name of the 5 token reward locations to something like "First Gold Skulltula Reward" instead of "10 Gold Skulltula Reward", for example.

**Comment by TestRunnerSRL** [comment]
I'm really not sure how much value an feature like this has. I think if the goal here is to not have to get 50 GS, then just disable the 40/50 GS spots. I also think it would potentially have problems if we wanted to change logic to expect different GS counts than what you've obtained. Like logic expecting 12 GS when you only need 10. Also This PR has nothing to do with the 100 GS reward ofc, because you don't even get an item from that reward...

**Comment by KevinPal** [comment]
At least for this PR, logic always matches how much you need. So if logic expects 12 GS, the dude will also only give you a reward for 10. Has nothing to do with 100 GS reward. As for value, well its just something commonly suggested 🤷‍♂ .

**Comment by Zannick** [comment]
It kind of makes sense as a "leeway" feature where logic expects more than you need, so that it's guaranteed possible to get 12 tokens when you need 10. But unlike triforce hunt, where the lower amount is the actual win condition, the multiplier can result in considering a reward as out of logic which could throw people off a little. I don't think there any real consequences of otherwise skipping skull pickups.

The other part of the feature, requiring less than 10, not sure if I agree with that as it messes with the balance of acquiring GS tokens.

Sorry for leaving this PR untouched for so long, but because it's so out of date I'm going to close it and ask that you reopen against latest Dev. But just the leeway ought to be fairly easy to reimplement solely in python and logic.

**Pull request closed without merging**
