### PR TITLE
Remove unused League Hint Distribution file

### PR DESCRIPTION
**Pull request by aofengen**
League hint distro is not currently used - removing to prevent confusion with league preset, which uses tournament hints.

### CODE REVIEW

**Comment by Cuphat** [comment]
This is only tangentially related, but it'd be nice to have older or other non-default hint distros collected somewhere for those who want to reference or use them (whether in a plando or on the electron version). And we should probably take a look at how we are handling the difference between default and custom hint distros in the settings string.

**Review by Cuphat — APPROVED** [review]

**Comment by aofengen** [comment]
In this particular instance I think it's easy enough to just recreate the hint distro via a plando file if someone wanted to use it, but I'd agree for the larger point of having things stored somewhere for reference

**Comment by Cuphat** [comment]
For whatever reason, the Standard Weekly preset (which, funnily enough, is itself unused at the moment as standard weeklies are using the S5 Tournament preset) still uses this hint distribution.

**Comment by aofengen** [comment]
settings_default.json has been updated to remove temporarily remove the league hint distro from the weekly settings preset

**Comment by Cuphat** [comment]
Squashed a bit and merged in f550be20673e756be35c6a397904d8e15c600d80.

**Pull request closed without merging**
