### PR TITLE
Reset frog sometimes hints

### PR DESCRIPTION
**Pull request by matthewkirby**
This is undoing PR #1605. It received racemod approval accidentally through miscommunications. I am also applying the alternate solution to #1605 and setting the frogs song of storms check as conditional with frog song rupee shuffle.

Using the tournament hint distribution I generated 100 seeds to test. When frog song rupee shuffle was on, I found 0 frogs in the rain hints. When frog song rupee shuffle was off, I found 7. This leads me to believe that this change is working as intended and will not impact the sometimes hint pool for the upcoming tournament (and will correct the pool for the RSL tournament starting this week).

### CODE REVIEW

**Comment by r0bd0g** [comment]
I don't believe this is an appropriate use of conditional sometimes, which should be reserved only for cases where a sometimes hint doesn't actually make sense anymore. (The example being a Ganon fairy hint with interior ER on where it's impossible to tell which fairy is which.) There are lots of cases where under some settings a sometimes hint becomes less powerful. I don't think any one check should be singled out like this unless you're prepared to tackle those cases as well. I was hesitant about the introduction of conditional sometimes because I feared they would be end up being arbitrarily applied in just the way that you have done here.

(On the other hand I think you could make a case for frog ocarina game becoming a conditional always, where the hint downgrades to a sometimes hint when frogs are shuffled, since the full game is not much more to add on top of other checks that you will probably want to do eventually. I don't think anybody wants that, I'm just saying, you could argue it.)

**Comment by matthewkirby** [comment]
I think the appropriate use of conditional sometimes is beyond the scope of this PR. The primary goal is to demote the 5 frog rupee shuffle hints from the sometimes pool. 

Personally, I am indifferent to whether frogs in the rain remains a sometimes or not when frog rupee shuffle is on. The change to conditional sometimes was as an attempt to achieve the goal of #1605. If a dev would prefer me to undo this portion of the PR, I would be more than willing. This is aimed at correcting the sometimes pools before the upcoming tournament.

For what its worth, I do agree with you r0b that when I wrote the conditional sometimes category it was designed to be for hints that simply did not make sense. I wrote it specifically for the Hyrule Castle and OGC Great Fairy Fountains when entrance rando is on. When ER is on, you can't tell which fairy fountain you are in so the hints would have been meaningless. But I also saw that the category is already being used in the way I am using it here. For instance, see the lines directly above my change that remove the 10-50 skull hints from the pool when their misc hint is on. This could (should?) be handled by the hint system checking if the location it is trying to hint has already been hinted (in fact, I thought it did this so I am surprised that these are necessary). But this is getting off topic and I do not want this to hold up this PR

**Comment by r0bd0g** [comment]
I didn't feel the skulltula hints were worth mentioning since them being here wasn't really necessary, and instead it's just a non-standard way of avoiding hint duplication (and I agree it's weird to see them here at all). What I object to is using conditional sometimes for cases where some settings are adding nearby checks that decrease the value of the hint.

Seeing a frogs 1 hint will give away the setting in RSL if this conditional sometimes is used (I know currently that some hints already give away the setting). I worry about expanding conditional sometimes, how confusing that could get for revealing what settings are on or off. But RSL shouldn't be taken into account for this sort of thing. RSL is some self-imposed nonsense we do to ourselves, but in theory the players know the settings of the seed before they start, and so conditional sometimes wouldn't really be spoiling anything. Unless the conditional sometimes in some cases might not make sense to be equivalent between MQ and vanilla, in which case they could end up giving away MQ/vanilla information, but only if you know a hint is conditional in one version of the dungeon but not the other. (I suspect problematic cases along those lines exist, but I'm not going to think of an example right now. You could always still get back to MQ/vanilla parity by just choosing to make both versions of the hint conditional or not even if that choice doesn't make sense for both versions.)

I don't expect many to agree with me that conditional sometimes shouldn't be used for frogs in the rain here. But I don't think this check should be singled out, and to solve that would mean diving into the larger problem of the rest of the hinted locations that could be conditional sometimes. It would be quite a task to balance everything appropriately, and I'm not convinced doing so would actually be good for the game overall.

Another way to not single the frogs in the rain hint out is to remove it from the sometimes pool entirely. It's not that great of a sometimes hint. You kind of need to find the final frogs hint also before it's even useful. But I think most people do appreciate the hint and so outright removing it would be a worse option.

**Comment by matthewkirby** [comment]
As of now, frogs in the rain will not be removed from the sometimes pool as that would impact S6. That could be revisited after the tournament if others like.

**Comment by r0bd0g** [comment]
The frogs are just straight a worse check than skull kid. I don't know if skull kid needs a hint either, but if it does it makes sense for saria's to a frog to be there too. So of course the final way to be consistent here is to keep the sometimes hints for all the frogs.

**Pull request merged**
