### PR TITLE
Revert removal of dungeon summary menu

### PR DESCRIPTION
**Pull request by mracsys**
Add the A button menu back into the game. This includes a check to remove dungeon reward icons from the summary if mixed entrance pools is a valid option and Boss type entrances are mixed.

Having one screen with all of the info is more convenient than three submenus. It is also easier in my opinion to hold the A button than a specific d-pad direction. If there is a way to shrink the font size a bit to better fit high-overscan CRTs, I can add that in.

In draft until I can test on hardware.

### CODE REVIEW

**Comment by ETR-BTF** [comment]
I've seen several people express discontent over the new, split info screen, so I think it's a good idea to revisit the idea.

**Comment by r0bd0g** [comment]
A thought I had that I think would make the split screens even more annoying, is that you still hold A but you get different info depending on which subscreen.

**Comment by Onemario1234** [comment]
I dunno, I personally like the separated submenus. Could it be relegated to a toggle in the GUI, or would that be unnnecessary?

**Comment by cjohnson57** [comment]
I like the split screens as well. They're more condensed and don't contain unnecessary rows in them. Like, in general UI or DB design, it's better to have separate tables for separate purposes than have one big table you put everything into with a bunch of empty/NULL columns.

**Comment by mracsys** [comment]
I should clarify that the d-pad menus are left untouched. This is an optional alternative. It does duplicate a lot of code, but it should be stuff that doesn't get touched often.

**Comment by cjohnson57** [comment]
But is it worth having both menus in, and having to maintain both as changes are made? I think this is just a case of people needing to get used to the change, tbh.

**Comment by mracsys** [comment]
Not a problem. I'll leave it on my branch if anyone wants to grab the changes.

**Comment by ETR-BTF** [comment]
Why not restore the old menu to, say, d-down and reserve the other two d-pad directions for future features (silver rupee shuffle & mixed pools boss shuffle) and re-add the menus when they're PRd? I do think we can't avoid multiple info screens down the line, but there's no reason to split the old menu over several screens when it works perfectly fine atm. It might be full of various information, but currently it's a single screen that gives all information for the features we currently have.

**Comment by fenhl** [comment]
The old menu _already_ doesn't fit into the safe zone anymore with total small key counts. I think the redundant summary menu is a decent compromise, but reverting the split is not the way to go.

**Pull request closed without merging**
