### PR TITLE
 Change Gerudo behavior with Gerudo's Card instead of carpenters. 

### PR DESCRIPTION
**Pull request by Cuphat**
Gerudo guards now respond to possessing the Gerudo's Card instead of freeing the carpenters. This allows you free access to all of Gerudo's Fortress and beyond with the card. Freeing the carpenters is still needed for 5 item locations (4 keys + vanilla Gerudo's Card location) and fixing the bridge.

The Gerudo's Fortress gate is automatically opened when obtaining the Gerudo's Card if the Gerudo's Card is shuffled or overworld entrance randomizer is enabled.

### CODE REVIEW

**Comment by Cuphat** [comment]
If opening the gate automagically is too controversial, it can be changed to an ER-only quirk.

**Comment by r0bd0g** [comment]
It's always a decision you have to make, after getting the card, if you can't full clear the area, whether or not to open the gerudo gate. I kind of don't like that it will just open on its own and remove that choice.

**Comment by rattus128** [comment]
This significantly changes non ER shuffled gerudo card, with an extra item obstacle to non-requiem spirit.

It would be very consistent with all the other gates (Kak, King Zora, Door of Time etc.) to just independently option "open gerudo gate". Theres no logical impact to unshuffled gerudo card, all it just does save the carpenter grind and the annoying opening of the gate to setup repeat reverse wasteland. It solves the ER problem, while hell mode can close the gate for extra memeiness.

Ill make the further case though, that any form of closed gate with the guard catch cheese is a case of a non-repeatable access which we generally try and eliminate (logic can't handle it). You can solve this problem universally by either just opening the gate unconditionally (bit like the proposal to de-feature closed forest), or you could permanently open the gate the first time link zones in to reverse fortress. Either of these solutions allow putting the reverse wasteland to fortress properly into logic as well as solving the ER problems, without any new option complexity.

**Comment by Cuphat** [comment]
I've changed things to only automatically open the gate if the Gerudo's Card is shuffled or Overworld ER is enabled, as those are the two cases where obtaining the card unexpectedly could result in a disadvantage to the player. This keeps the same Gerudo Fortress gameplay of the most popular settings, where you have to decide on your own whether it is worth taking the time to open the gate and allow reverse wasteland, without allowing the player to lock themselves out of the fortress area completely.

**Comment by rattus128** [comment]
Can I still open the gate from the front using carpenters in shuffled card?

**Comment by Cuphat** [comment]
The guards, including the one in front of the ladder and the one that lowers the gate, respond to your possession of the card, not the carpenters being freed. This means that you'll either be caught by the guard or the gate will be open if the card is shuffled.

**Comment by Cuphat** [comment]
There hasn't been any comments here, but I want to justify this PR a bit.

1) Gerudo Card making the guards friendly to you makes more logical sense than freeing the carpenters. Why would the Gerudo care about you freeing the carpenters? Only because doing so makes you a member, for which they give you a membership card.

2) There is no vanilla argument to be made. You get both at the same time in vanilla, so the flags used is inconsequential. The Gerudo Card actually having a use separate from freeing the carpenters was only actually discovered pretty recently, AFAIK.

3) This PR makes "reverse wasteland" possible in logic for overworld ER. You'd need way more hacky bullshit to open the gate when the carpenters are freed, otherwise you could lose access to a location that you'd otherwise have access to.

4) I just feel like this makes Shuffle Gerudo Card a much more palatable setting. Gerudo Card just blocking GTG and nothing else seems arbitrary and dumb, but it changing guard behavior in GF, allowing for archery as well seems to make more logical sense. The carpenters still exist as 5 item locations in total (4 keys which could be shuffled in keysanity + the vanilla card). This is subjective but I think tying the card to everything makes more sense than needing the card + 4 GF keys for GTG (and 4 keys for archery).

If nothing else, this removes what is absolutely a quirk, which is that the guards just don't give a shit that you are a Gerudo Member and toss you in jail. Anyway, I just wanted to give my thoughts on it. Looks like I'll need to rebase this again anyway.

**Comment by rattus128** [comment]
I'm just worried from a balance perspective, in that the card becomes way way more powerful gating the desert crossing after already gating a high value dungeon entrance. Its up there with the wierd egg in value terms if you enable dungeon entrance rando.

**Comment by Cuphat** [comment]
It definitely raises the value of the card a lot, but how many seeds actually require crossing wasteland as it is? I feel like Requiem comes up more often than it doesn't and doesn't dungeon ER add an additional way to get there by dropping from Spirit hands?

But yes, there are pros and cons, there's no right answer to if this is how the behavior should be. Part of why I did and and PR'd it was to see if anyone would discuss it. I feel like this is the more logical way to handle it, and I think the current behavior shouldn't be unchanged just because that's the flags that happened to get picked when they coded them.

**Comment by Hamsda** [comment]
Personally I like the changes. 
1) It doesn't affect the weekly settings at all. 
2) It makes shuffling the card much more interesting, since it is not just entry for 1 dungeon.
3) It takes a bit of focus away from the GF key(s) for keysanity (which is imo a good thing, but one could argue otherwise).

**Comment by r0bd0g** [comment]
I think I would rather the card shuffle option just be removed if it's really so much of a problem in its current form that you have to completely overhaul the way the gerudo area works in order to make sense of it.

**Comment by Cuphat** [comment]
Honestly, that just reads to me like we should remove medallion shuffle because of all the weird places medallions changed the world before it was fixed. Should Bombchu Bowling still require Dodongo's Cavern blue warp? There's some many areas in this game where the flags that they used make no sense when you randomize things, even if it worked just fine in a vanilla, casual context. Changing this one is even less egregious to me because you could drop these ASM changes into the base game and literally nothing changes for anyone playing it in any context.

**Comment by r0bd0g** [comment]
I can't get past the gate opening by itself.

**Comment by Cuphat** [comment]
The gate opening by itself is going to happen in Overworld ER regardless of this PR. The only thing this PR does is going to accomplish is also opening it if the card is shuffled, because randomly losing access to Gerudo's Fortress because you randomly happened upon the card is stupid. The gate opening isn't done in any other scenario.

Without that bit, entering GF from the back entrance could never be in logic.

**Comment by r0bd0g** [comment]
I mean, I agree that if you change guard behaviour based on the card you probably do have to have the gate open by itself.

**Comment by Roman971** [comment]
A more difficult but probably also more elegant and natural way to handle the gate opening issue would be to add a white-clothed gerudo in front of the gate so you can also open it from the other side. We could still choose to have it only in overworld ER and shuffled gerudo card. 
Not sure what the feasibility of that is though.

**Comment by r0bd0g** [comment]
Yeah, that might help some.

Cuphat have you tested the gate opening automatically thing as child (it probably shouldn't work? or should it or what?) or if you find the card outsite at gerudo fortress?

**Comment by rattus128** [comment]
Try duping the actor for the guard on top. To avoid the hassle extending
the list you could just cannibalize some irrelevant actor like one of the
crates and if it works then look at a clean solution.

**Comment by Cuphat** [comment]
I didn't test it as child but I don't see any reason why it wouldn't open automatically just like it does as adult.

I need a working L to Levitate on Bizhawk to test it as child because I am not good enough to reach that chest as child, lmao.

**Comment by r0bd0g** [comment]
I mean in theory you maybe should not be able to open the gate as child since there's not normally a guard up there to talk to?

**Comment by r0bd0g** [comment]
I kind of wish, if child fortess is going to be a thing, that we could "fix" it, and just have it look like adult fortress once you get there.

**Comment by LostThePirate** [comment]
I've got no issues with this PR (since TR asked for additional opinions). Since the gameplay impact only affects certain niche settings that would benefit from this change, and *doesn't* change default behavior for unshuffled Card/non-ER game modes, I have no problem with it. As long as vanilla behavior is maintained under more vanilla settings (having to manually open the gate by talking to the gate tower guard after freeing the carpenters and acquiring the Card), I see no issue with this to make the niche settings have more niche gameplay impacts.

**Comment by r0bd0g** [comment]
I'm giving my opinion again anyway. I don't like that shuffled card is getting lumped in with the gate opening by itself. It's not a setting that I consider any more outlandish than say, keysanity or shuffled ocarinas, so I think a more vanilla-like behaviour is appropriate for this setting. We can argue about what exactly "vanilla-like" should be here, but the gate opening by itself is definitely not that. I know the gate opening by itself is a solution to a problem, but it's not a problem that exists if the fortress behaviour is not changed.

**Comment by LostThePirate** [comment]
Would only in ER feel like an acceptable compromise, or is it a hard no-go in any form of implementation? Just curious where the line is.

**Comment by r0bd0g** [comment]
I guess to keep going from where I left off, it would be strange to have the gerudo behaviour so different just in ER. If the problem is non-repeatable access, maybe just open the gate automatically on carpenter rescue instead.

**Comment by rattus128** [comment]
+1.

My preference is the minimal change that fixes the non repeatable logic.
This would be opening the gate on rescue or opening the gate only on
reverse wasteland after a rescue.

I think we should avoid item logic changes on ER settings, as players
should be able to up their randomness by switching on ER and what they
already know stays solid.

**Comment by r0bd0g** [comment]
"maybe just open the gate automatically on carpenter rescue instead"
And to clarify in case it wasn't clear, I'm suggesting this only for ER.

**Comment by LostThePirate** [comment]
As I said, I'm not in favor of applying this change in non-Card Shuffled / non-ER situations. I don't think rescuing the guards and acquiring the Card in non-shuffled settings should open the Gate.

**Comment by Cuphat** [comment]
> As I said, I'm not in favor of applying this change in non-Card Shuffled / non-ER situations. I don't think rescuing the guards and acquiring the Card in non-shuffled settings should open the Gate.

It doesn't. This PR functionally changes absolutely nothing if the card isn't shuffled and ER isn't enabled, and is functionally identical in non-shuffled card to an alternate ER implementation that'd open the gate on carpenter rescue.

**Comment by r0bd0g** [comment]
I didn't explain what I meant properly, I think?

I don't like card shuffle having the gate open automatically. I don't see a good way to solve this aside from just leaving the gerudo behaviour alone, and keeping them responding to carpenter rescue and not gerudo card. I don't think it makes sense to just have them respond to the card instead only in ER, either. But in the case of ER only I think implementing opening the gate automatically if the carpenters have been rescued is a reasonable idea.

**Comment by Cuphat** [comment]
It just seems weird to me that you are so against the gate opening on shuffled card, even going so far as to saying you'd rather shuffled card be removed entirely, and then are fine with it in ER. ¯\_(ツ)_/¯

**Comment by r0bd0g** [comment]
Some concessions need to be made to get ER working in a reasonable way, but I don't like those changes encroaching into non-ER settings.

**Comment by TestRunnerSRL** [comment]
wasn't it suggested to put an extra guard on the other side of the gate that can open it? Wouldn't that resolve the issue?

**Comment by Hamsda** [comment]
Looking at it from a "logical" way (can't think of a better word), having the gate react to the card and the GV bridge react to the carpenter rescue would make the most sense. I don't think separating those would actually be good gameplay wise though.

**Comment by Cuphat** [comment]
If I can figure out how to actually do that, then sure. I've never messed with scenes or added actors before.

**Comment by TestRunnerSRL** [comment]
I'm going to be kinda busy with SGDQ, but feel free to ask in the dev channel for help on the room data format

**Comment by r0bd0g** [comment]
You might have to update the logic on fortress beyond gate -> fortress now to accommodate the reverse wasteland trick? I'm not totally sure how these changes affect the logic of the fortress.

**Comment by Cuphat** [comment]
Alright, I've committed Roman's guard moving patch and took out the auto-gate opening. I also fixed up the logic a bit with adding a new instance of the `Gerudo Fortress Gate Open` event to the other side of the gate when applicable. I think I did this right, but I am not 100%.

Roman said he wanted to look into tweaking the radius that the guard can catch you, but this should be closer to being ready.

**Comment by r0bd0g** [comment]
It looks like you removed the ability to get into gerudo fortress using reverse wasteland in standard settings??

**Comment by Cuphat** [comment]
Oh, that's what that was for? Fixed it back.

**Comment by r0bd0g** [comment]
I'm not sure it's correct now. If you rescue the carpenters, the guards keep capturing you until you find gerudo card? And there's a guard to open the gate if you have the card, if entrances are shuffled...

**Comment by Cuphat** [comment]
I mean, that's all correct, I am not sure what you think is the issue?

**Comment by r0bd0g** [comment]
Is there any case where you shouldn't be allowed in if overworld entrances are shuffled?

**Comment by r0bd0g** [comment]
I think it should be:
(shuffled_ow_entrances and (is_adult or gate_open)) or
(is_adult and (shuffled_card or gate_open or can_reach_valley_adult))
… but I'd like roman/rattus to take a look.

**Comment by r0bd0g** [comment]
Roman suggested is_adult or (shuffle_overworld_entrances and 'Gerudo Fortress Gate Open'), with making sure the guard appears for special interior entrance shuffle as well, and thinking about it it sounds right to me.

**Comment by Cuphat** [comment]
I've pushed the logic changes as suggested by Roman. I think this is good to go on my end.

**Comment by r0bd0g** [comment]
Could North F2 Carpenter also be reached if you have the Membership Card already?

**Comment by Cuphat** [comment]
Nice catch, I thought I got that but I only got the can_finish_GerudoFortress function and not that carpenter. Logic should be fine now, I think.

**Pull request merged**
