### PR TITLE
Add way to not repatch cosmetics when applying patch file.

### PR DESCRIPTION
**Pull request by Cuphat**
Also allows generation of cosmetics log when creating patch files. For multiworld, these cosmetic logs will be embedded in the patch file archive.

### CODE REVIEW

**Comment by Cuphat** [comment]
The use case is to simply apply the patch file with nothing else altering the output. Want to apply the cosmetics in the patch directly? Right now, you simply can't, at least not using the main program. Have an older patch file that you want to apply directly? Have a patch from someone else and you want to use the same cosmetics as they did? Found some interesting colors/random music and you want to share it? Something somehow breaks and you want to replicate the ROM used completely? You can't do that using the main randomizer program.

If nothing else, this adds feature parity with the web patcher, which can currently do this with .patch files and presumably, due to the way it works and the way it works now, will be able to do this with the .zpf formatted patches when 4.0 releases.

**Comment by TestRunnerSRL** [comment]
I'm probably going to hold on this just cause I want to avoid changing the gui until post 4.0

**Comment by Cuphat** [comment]
I'm so confused as to why I rebased this and pushed it. Re-rebased it to the right branch.

**Comment by Cuphat** [comment]
Rebased and updated for the new SFX tab.

**Comment by Cuphat** [comment]
Rebased and updated for the new multiworld patch file naming.

**Comment by Cuphat** [comment]
Rebased to fix a merge conflict.

**Comment by Cuphat** [comment]
Rebased for the SettingsList refactor/cleanup.

**Pull request merged**
