### PR TITLE
Shield and tunic objects can spawn in any room

### LINKED ISSUE #1437: MQ Fire Like Like doesn't return your shield
This Like Like in MQ Fire didn't return my shield. I'm not sure if this is vanilla behavior, but it might be programmed in MQ, because the chest you spawn contains a hylian shield in vanilla MQ. Please make the Like Like return the shield :D https://clips.twitch.tv/PeppyPleasantChamoisMoreCowbell-FZ1q1AWv8DlvTSq4

### PR DESCRIPTION
**Pull request by SlyryD**
Fixes #1437 by spawning deku shield, hylian shield, and tunic objects even if they aren't in the room's object list. This change replaces the `z64_ObjectIndex` call with `object_index_or_spawn` for each of those 3 cases.

Reverts the existing fix for MQ Fire Like Like since this solution works for that room as well.

Effects:
- Child spirit shield pot will drop a deku shield
- MQ Fire Like Like will give you back your shields (and tunics, even though it's currently not needed in rando)
- Like Likes in adult dungeons that would only give you back hylian shield (and tunics) now give you back deku shield

Comments:
- Leaving the room after spawning the deku shield from the child spirit pot will cause the shield to despawn, but you can spawn it again from the pot
- Leaving the room after a Like Like spits out your shield or tunic will cause the shield or tunic to despawn; this is consistent with vanilla Like Like behavior

### CODE REVIEW

**Comment by SlyryD** [comment]
Marked as draft since we should verify in code the object isn't loaded in the room yet and there's enough space in the object list to spawn it. Something like this:
```this->actor.objBankIndex = Object_GetIndex(&globalCtx->objectCtx, OBJECT_GI_SHIELD_1);
if (this->actor.objBankIndex == -1) {
  this->actor.objBankIndex = Object_Spawn(&globalCtx->objectCtx, OBJECT_GI_SHIELD_1);
}```

**Comment by SlyryD** [comment]
There was an additional bug with my existing code related to scene transitions. `ObjectSpawn` stores the number of spawned objects in ObjectContext `unk_09`, which I've renamed to `n_spawned_objects`. The game only uses `ObjectSpawn` to load objects like `gameplay_dangeon_keep` which remain loaded even on room transitions, so `n_spawned_objects` corresponds to the index after the last object that should remain loaded during a room transition. When a room transition happens, when processing the Object List SceneCmd, it checks ObjectContext for differences starting at `n_spawned_object` and clears out everything after the first difference, killing the corresponding actors as needed. Since my code used ObjectSpawn, it was updating `n_spawned_objects`, quickly leading to a crash during room transitions. I fixed this by restoring `n_spawned_objects` right after calling `ObjectSpawn`. Since actors are killed during the Object List SceneCmd, this does mean that shields and tunics will no longer be on the ground if you leave and re-enter the room. This could be fixed by spawning shield and tunic objects on scene init, like rob suggested. Though this might lead to problems in rooms with lots of objects loaded.

**Comment by cjohnson57** [comment]
I had no idea the shield pot was a thing. Is it repeatable? If so it should be added to logic, if not this should be good to go

**Comment by cjohnson57** [comment]
Just tested and it is repeatable, so it should be added as a logical deku shield source.

**Comment by cjohnson57** [comment]
Also as a note for anyone looking at this and wondering where it is, it's the pot in the very middle of the Anubis room.

**Comment by r0bd0g** [comment]
"Child spirit shield pot will drop a deku shield"
This isn't a thing in the actual game. It should not be changed to actually drop shields.

**Comment by cjohnson57** [comment]
If the pot is set to drop a deku shield and only doesn't because it's not in the object list, seems like kind of an oversight? Especially since it's such a convenient place for one too with all the fire around

**Comment by r0bd0g** [comment]
It doesn't matter if it's an oversight or not. It doesn't actually exist.

**Comment by SlyryD** [comment]
> Just tested and it is repeatable, so it should be added as a logical deku shield source.

If you burn that shield, you won't get a new one from the pot. So it shouldn't be in logic right?

**Comment by SlyryD** [comment]
I'm not sure I like putting it into logic. I think it's cool as something you stumble into or have as a backup if you know about it. But not as cool if you need it to beat deku. Could it maybe be a trick that you enable?

**Comment by SlyryD** [comment]
I added it to logic as a trick.

**Comment by r0bd0g** [comment]
If it exists it should just in logic. If you want it to be optional, make the whole thing optional.

**Comment by cjohnson57** [comment]
Yeah I don't really see any reason to trickify this

**Comment by SlyryD** [comment]
Hmm... if we add it to logic, I guess we can add it to the wiki. Maybe here: https://wiki.ootrandomizer.com/index.php?title=Logic#Misunderstood_Vanilla_Mechanics

**Comment by SlyryD** [comment]
I was viewing tricks as a way of informing people about it

**Comment by r0bd0g** [comment]
It doesn't make sense there, because it's a perfectly well understood vanilla mechanic that there is no shield in that pot.

**Comment by SlyryD** [comment]
Removed the trick. I'm still not sure I like it in logic vs. something cool that just happens.

**Comment by ETR-BTF** [comment]
I agree with r0bd0g on this: changing vanilla mechanics should be kept to a minimum to avoid confusion for players and this change is neither important or intuitive enough to be justifiable. If it is to be included, then I think it should neither be a trick nor be in default logic. It's a little weird to be able to go out of logic by finding this shield, but we kind of have precedents with scale/explosives in Closed Forest and Bombchus in general? Idk. I think it'd be best to just not implement this.

**Comment by SlyryD** [comment]
Removed the logic

**Comment by r0bd0g** [comment]
I want to be clear that I think like likes giving you back your deku shields where they normally wouldn't is a solid fix though.

(I'm torn on updating that mq fire like like b/c it seems intentional that it doesn't give you things back, but the rest of the like likes it's more rando's fault you can encounter them as child, which is more the kind of vanilla fix that I'm in favour of.)

**Comment by SlyryD** [comment]
@cjohnson57, can probably take Waiting for Author off of this one. Thanks!

**Comment by Roman971** [comment]
I agree with r0bd0g about the pot shield. I don't see a reason to add a shield drop to that pot if it's not in vanilla (even if it's seen as a bug). So imho that pot should be patched to not have a shield drop in its params.

**Comment by mracsys** [comment]
It feels weird to me to patch the one problem but not the other.

**Comment by SlyryD** [comment]
Alright, I removed the deku shield drop to make spirit shield pot deniers happy.

**Review by cjohnson57 — APPROVED** [review]

**Pull request merged**
