### PR TITLE
Dungeon Entrance Shuffle - With Accessible Logic Support

### PR DESCRIPTION
**Pull request by rattus128**
Co-authored between rattus128 and roman971.

Add dungeon entrance shuffle with full logic support (this is not beta quest).

For anyone interested in casual testing, playable !dev style releases here:

https://github.com/rattus128/OoT-Randomizer/releases

Randomize stone, medal, ice, well, gtg but not Ganons Castle entrances. 11 strong pool which gives it a similar feel to figuring our your song logic (for me this is the funnest part of rando). More entrances is future work.

### CODE REVIEW

**Comment by flagrama** [comment]
>Requiem taught by Shiek is logically part of the spirit temple.

What exactly does this mean? How exactly does it work?

**Comment by rattus128** [comment]
In means when you find spirit you get requiem rather than getting requiem
at the colossus. The song is moved into the dungeon for hints.

**Comment by flagrama** [comment]
So it's changed to being more of an item location like it is in songsanity? You walk into spirit, Link raises his hands and you get your new song?

**Comment by rattus128** [comment]
Currently you walk out of spirit, you get the song teach cutscene, then
leaving the cutscene you get dropped back at spirits exit location (might
not be colossus)

**Comment by flagrama** [comment]
Okay, so in Songsanity, does that mean you leave at Spirit's exit location and get the item properly too?

**Comment by mzxrules** [comment]
I don't understand why you didn't just swap the exit tables in the relevant scenes

**Comment by r0bd0g** [comment]
The bombable wall in deku tree should be hammerable. It's the same type of wall as in DC, right? The scrubs in there are hammerable as well but it's super jank to solve the 3-scrubs with it. The one to the slingshot room is reasonable but just b/c it's so glitchy with the 3 scrubs makes me wonder if just shouldn't be in logic for the one it sort of works on. I've never tried but can you shoot the web to that bombable wall through a torch? Regardless, the eye switch stays hit, and the webs stay burnt, so you could potentially open the way as child to use hookshot as adult, or open the way as adult to use boomerang as child. Or any weird combination. Slingshot the eye switch. Hammer the wall. Boomerang the token.

That's just Deku Tree. There's a lot to unpack here as far as the logic is concerned.

I'm working on a big list of tricks to add to the logic... Only a few done so far, but if I keep going and this gets merged it'd have to be completely redone. There may be a number of entrance-rando specific tricks as well that I have to figure out actually exist, even... I don't know...

**Comment by rattus128** [comment]
I found the data format for the scenes late in the development and I
haven't fully gotten into scenes and the related file-system stuff.

In short, I'll redo it using exits and see how it goes.

Are blue warps in the scene exit table? That's the trickiest bit that I can
think of right now.

Ill hit up the discord for further pointers. Thanks as always.

**Comment by rattus128** [comment]
Thanks for taking a look. The logic was always going to have corners and
I'm looking for this kind of line over line review. I will look at all of
those and add the new options.

I think the fact that eyes stay shot and webs stay burnt and the b1 block
stays pushed, deku b1 can be best handled by defining all the little
regions to factor out all the common sub expressions. I have in other
places kept those possibilities where one age can open the age for the
other.

I already know one trick level (I think) thing which is adult can do a
precise shoot of the last floor cricle web in deku standing on the chest in
b1 lower shooting through torch with regular arrows. Csmc has a difficulty
impact here but works with both sizes.

V2 will have a reworked deku b1.

**Comment by rattus128** [comment]
@flagrama , yes I tested it just then and it works in songsanity by looting over links head stepping out of spiri.

**Comment by rattus128** [comment]
@r0bd0g I have done some experiments in Deku Tree based on your suggestions. The scrubs are hammerable. The slingshot room one is easy but the 3 by Gohma are definately jank. I like the consistency argument of just letting it go.

It is a very easy shoot to the web on the wall near bombable through the torch. The more interesting shoots are these two:
https://www.twitch.tv/videos/380936935
https://www.twitch.tv/videos/380937846
The harder feels like trick level to me. The easier one doesn't leave a lot of space to stand either so i'm wondering if it should have the same consistency argument applied and both shoots are the same trick?
Leaving those two out of logic for them moment I ended up with this for that skull:
```
            "GS Deku Tree Basement Back Room": "
                (has_fire_source_with_torch(Adult_Deku_Tree, Child_Deku_Tree) and
                 ((can_use(Slingshot) and Child_Deku_Tree) or
                  (can_use(Bow) and Adult_Deku_Tree)) and
                 can_blast_or_smash(Adult_Deku_Tree) and
                 ((can_use(Hookshot) and Adult_Deku_Tree) or
                  (can_use(Boomerang) and Child_Deku_Tree))) or
                (Adult_Deku_Tree and Child_Deku_Tree and has_explosives and
                 can_use(Boomerang) and (has_sticks or can_use(Dins_Fire)))"
```
Which is not as scary as it reads. Basically just and-or logic of the child and adult splitting the various requirements for eye, bomb-wall and range-looting between then as you suggested. The last or expression covers child using adult B1 skip (block push) to reverse crawlspace.

I'm wondering if the notation needs to just hide all the "and Adult_Foo" by just building that into can_use() implictly.

Regarding your trick work, do you have a branch I can to diff to see where its at? The implicit can_use approach, will cut my diff by a lot.

As for the other dungeons, I think they not quite as complicated, as Deku is the only one where a wrong-age full completion comes into play. Going dungeon by dungeon:

DC: already have most of it due to closed DoT
Jabu: Logically small and revolves around child-only boom
Forest: Child dip stops at the push blocks
Fire: Child dip stops at the push block (or tunic)
Water: Child cant do much
Shadow: Child can do nothing
Spirit: Already have the conditions due to requiem (child) and silvers
well: Adult can do nothing (crawlspace)
Ice: Child height limited cant get to blue fire at all
GTG: non-trivial child dip but largely hookshot locked

**Comment by r0bd0g** [comment]
I don't have a branch for it since I haven't made a lot of progress yet. About 5 tricks in of like 80.
That first shot through the torch in deku doesn't really look worse than, say, spirit trial? But I haven't tried it recently so it's hard to tell from the video. Second one looks probably too hard for default logic.
I wonder if somebody has a way of fixing the 3 scrubs to work with hammer? Sounds like it'd be difficult for not much benefit...

**Comment by r0bd0g** [comment]
Gohma you need a way of stunning her now. Nuts or sling. It's not possible to get to her without possibly having nuts though... You can also bring her off the ceiling with any projectile but I mean, I dunno if this really matters at all.

Nothing in Fire Temple should be accessible as child if fewer tunic requirements is off.
For consistency I don't think using the entrance into the temple should require tunic, just based on how very little else in the crater requires it even with fewer tunic requirements off. Some of the movements there can actually be a little tight with only 3 hearts so I dunno how I feel about the way it currently is, actually.

Explosives should be able to get the GS in the first room of Forest? I never bothered to fix this logic since you needed hookshot to get here anyway.
Forest Temple NE Outdoors Chest Platform already has a different name in MQ, but I forget what it's called right now. Can't you get this GS here without Hookshot if you fall down to it from above?

What all damages Dinolfos?
What all damages Freezards?

It should be possible to progress in Ice Cavern as child-only if you have Blue Fire from somewhere else. So I think that means you can get Compass Chest, Freestanding PoH, Iron Boots Chest, and the other two GS's just as child. Use has_blue_fire. It's time I think that a Blue Fire event location be placed in Ice Cavern.

The Deku Scrub in Jabu can be reached as adult using a scale. Actually jumping down from the top works too but it probably shouldn't be in logic like that.

I see a lower-case "true" in the overworld. I'm not sure if it matters.

So in Spirit Temple, you're not supposed to check if you have child or adult access for the shared child+adult routes, since it doesn't matter how you got into the room, only that you can do it regardless of how you got there. The calls to has_projectile in here never pass it a child or adult requirement, which I guess is fine? The defaults are None and I have no idea what has(None) actually returns, though...

I'm not sure but I don't believe the 2 keys + chus_in_logic spirit temple routes are actually safe anymore. The idea was that, it was not possible to be out of logic and waste your keys as child in the spirit temple, since if bombchus were in logic you could always buy more and blow up the sun again that way. But now since we have no idea how you actually got to the spirit temple as child, it's possible that you've done some other non-repeatable thing to get here. What that non-repeatable thing might be is anybody's guess, and I have no idea if it even exists.

Why did you change spirit compass chest from hookshot to longshot?

So the Water Temple entrance requiring tunic (fewer tunics off) I guess is fine? If the lake is filled then it is something of a lengthy dive. Though this will create something of a mismatch I think between how much time passes before the zora tunic is required compared to the goron tunic.

You need to add Zora Tunic requirements throughout Water Temple.

You shouldn't remove the Iron Boots from things inside the Water Temple that don't strictly require Iron Boots. You'd have to check for Iron Boots or shuffled entrances. The non-shuffled logic still needs Iron Boots there for entering the temple after the lake is filled. Actually the fact that you don't necessarily have to get locked out of Water Temple without the Iron Boots makes me wonder if longshotting the torches at the bottom could be in logic. Maybe it's a touch too obscure, but it having a trick option would be possible I guess. Anyway I brought all this up in reference to how you removed the Irons as required for the Compass chest, but that still requires Irons, either to lower the water or to be able to use the hookshot underwater. However, there are things which don't strictly require Irons that you did not remove the Iron Boots for. Morpha Heart, Dark Link region, for examples.

I can't remember if the torches to the torch room stay lit if you leave the dungeon or not. What all weapons actually kill shell blades?

For the Central GS, what's Slingshot for, and Boomerang actually reaches?

**Comment by rattus128** [comment]
@r0bd0g, Thanks for that detailed logic review. That really moved progress a long way. I've made nearly all changes and have some answers to your questions below. I have a few more questions, mostly around grey area logic decisions. I have just finished all the code changes, I'll push V3 probably in a few hours.

With Gohma I'm relying on that child-only still has to eye-shoot which guarantees a sling. If adult is in play then nuts can be freely farmed with MS. The multi-phase gohma kill is ok with no projectile weapon as if you kill the babies she jumps down on her own. Im guessing this a thing if the B1 skip trick is defined? Its a case of pre-condition assumption which will mess with further dev - including boss rando. Fix it now for the future?

Those goron tunic requirements are inconsistent currently. For the overworld entry to fire-temple I have left it as-is for the moment. I saw your discord comment about fixing the crater and I think that makes sense and will improve consistency. Happy to remove it if that turns out to not be the a solution. My refactor is pushing the tunic reqs into the dungeon, so this will make it easy to remove that condition in the overworld.

Inside fire, I'm going with tunic req for everything if the trick is off so child will be completely useless with the trick off. This also fixes adult behaviour when fire not on fire (this branch was wrongly assuming fewer tunic).

For the first skull in forest, with a good position and well timed throw you can bomb the skull. Explosives added to logic. Demo here:

https://www.twitch.tv/videos/381276176

For the NE platform skull in forest there are a fair few more options falling down from above. Any of bow/dins/hook/explosives can be used. Added all of that. Demo here:

https://www.twitch.tv/videos/381247708

Dinolfos as child are hard work. They have 12 health for 24 damage needed total. Slingshot can hit for 1 each but the dinos have an evade and a block that can burn extra ammo so getting the kill with only 30 seeds is awkward. The jumping around makes bombs hard too and you need 12 hits but you can AoE them both at once. I feel like both of these are trick level. You will need 12 hits with sticks without JS. Getting 6 JS hits with sticks is more reasonable but you lose sticks if you slash and they evade by jumping. Ive left it KS only for the moment, but happy to change.

Frezzards are weird. The logic I have there is wrong, because they are actually completely immune to KS somehow. Sticks kill them but its 8 sticks to kill all 4 which is feeling a lot like deadhand. Bombs work nicely and the moving one will explode a bomb as it runs over so no need for fancy timing. Dins wrecks them. So I have put Dins and bombs in and left sticks out.

I have made all those changes to Ice location logic and the has_blue_fire State.py. Child cannot do the serenade check which maybe should be fixed.

Added adult jabu scrub dive with scale to logic.

Lower case true fixed.

The semantics of has_projectile with those new argument defaulted to None are the same as before the code changes. So None/None will perform no extra qualification. I think i did the code change around some of those has_projectile's in a confusing way, as the extra Adult_Spirit_Temple conditions are really piggy-backing on the silvers one in the same and. Ive reordered some of the 3-way ands. New Child_Spirit_Temple checks are a straight up replacement for Requiem.

To preserve that chus in-logic, I am relying on the fact that there are no non-repeatable child dungeon entrances but Im not 100% on that either. Ive added the extra condition to avoid it.

The spirit compass longshot change is a hangover from the old CSMC bug that I fixed locally. Reverted.

Torches do not stay lit in water.

The clams in water as child are hard work. Boom and sling do nothing. The sword mechanics are differnt such that child cannot just stab them the way adult can with MS. I did however get an easy clean kill using the double charged magic spin attack:

https://www.twitch.tv/videos/381359063

Ive added magic to the condition next to the Kokiri sword but part of me thinks this is pretty obscure and maybe just say this check is not a thing for child?

The boomerang does reach the central pillar skull. The slingshot was there to ride up the water however I found that you can reach the cut-switch with the boomerang if you stand at the front of the water spout. So ive dumped the sling condition. I was actually missing the FW condition for the child or - fixed that. Heres a demo, the boomerang standing position for the cut switch the most interesting bit:

https://www.twitch.tv/videos/381292052

Ive added the missing conditions for tunic and non-ER Irons.

I added an extra region for the Water Temple highest water level vs the dive as this factors out both the tunic and the irons that would otherwise end up in almost every condition. This is also a single point to define the trick for longshotting the torch which definately is a thing in ER as you suggest. So ive prepared for that by organizing the code to explictly add Irons to the checks past the dive that still need irons in their own right. The Iron_Boots or shuffle condition is also implemented as a catch-all to avoid this going viral through the logic.

For the overworld Zora tunic requirement going down to water temple when filled has about 6 seconds spare when you have to take into account the gate might not be open yet and you need to hook it. Ive left the tunic in for the mo but I agree whatever happens for tunics in general should be followed. Ill try and catch you on Discord for what we can do with tunics in general.

**Comment by r0bd0g** [comment]
Still for the Forest GS when you come into the room from above to get it, the logic has to confirm that you actually came from above. If you just hookshot up to the chest from below, you can't fall down to the GS.

For consistency, Ice Map should has blue fire.

You missed some instances of bombchus in logic in spirit.

The intention of logic_water_bk_chest is that you will use iron boots to weigh down the switch. There is a precise jump you can do which is quite a bit more precise, though. But it wasn't logically relevant as you needed Irons to be here anyway. The precise jump is relevant in MQ water and a trick option is coming eventually. tm

It's possible to get river gs without irons. Might be too hard. But if you stand on the very edge of the ground there you can just reach the token. It's easier with bow b/c the token has a larger hitbox I guess than the skulltula.

**Comment by rattus128** [comment]
For the forest skull I was relying on that if you got to the platform with the hook from below you had hook implictly which mean you can take the skull. Its obscure though and the kind of pre-condition im trying to remove elsewhere in the code, so I have dropped that extra region and just change it to use can_reach() as you suggested earlier. It looks much cleaner and self documents nicely.

Ice map fixed. With Ice I need to look into this events concept at some stage.

Spirit 2 key chu fixed with the missed conditions.

logic_water_bk fixed by associating the irons with the trick itself and no other condition.

I think that river skull kill is too hard.

For next steps, I think I have more work to do in forest. Killing the map chest guard will need weapon conditions, and I think I go some of the cross age region sharing wrong. Tomorrow.

Thanks as always.

**Comment by rattus128** [comment]
Unrelated to logic review, I have also made an update to Fill algo that greatly imporves rando with no all-locations-reachable. Some good spoilers with things like GTG on Deku being generated at reasonably high frequency now.

**Comment by r0bd0g** [comment]
Something just occurred to me. Nut and Stick access from the babas could be affected here. The way the is_adult part of getting these items works is, you can get the sticks/nuts from Kokiri Forest, until you beat Forest Temple, but then if you can beat Forest Temple, then you can go back to Forest Temple and get more sticks there. You might have to backflip over Mido again if that's how you got there the first time, but if you did that without know how you did it and can't do it again I dunno, that's on you. I'm not sure the assumption that you will be able to go back into Forest Temple as adult and get more and holds anymore. You might have to consider how you would get sticks/nuts from Forest Temple, and cut is_adult access to the Kokiri Babas if entrances are shuffled.

But there's a wider problem potentially? When putting in all of the stick/nut drops from pots or whatever, I only put in the ones that were logically relevant. Now that entrances are shuffled I actually have no idea if there are more stick/nut locations that need to be added that didn't matter before. I probably should have kept my notes file on that around.

**Comment by rattus128** [comment]
The obvious manifestation of that would be scale diving into forest on
water, finishing forest, then finishing water.

Other solutions include leaving the forest monstered, or stopping the lake
fill. Stopping the lake fill also makes sense given that morhpa might now
be at the other end of the world. Add in the bonus of scale fully in logic
on water entrance.

Easiest solution is cutting that adult baba access as you suggested. I'll
make that change, conditional on shuffle.

Thanks

**Comment by r0bd0g** [comment]
You should add a nut drop to dampe's grave. But I think there are other important ones, like, maybe there's a nut pot in jabu? But it didn't matter b/c you had to pass through domain? I forget man. You might have to go on a hunt for sticks and nuts idk lol.

**Comment by r0bd0g** [comment]
"I probably should have kept my notes file on that around."
Then it occurred to me that maybe I did. So I found my list of drop locations, anyway.

- Buy Sticks, Buy Nuts
- Kokiri Forest Babas (but not as adult in entrance shuffle)
- Forest Temple Babas - You'll have to add this drop location and check that you can get nuts and get sticks from them.
- Goron City Stick Pot - The logic on this might not be complete, I would have to check and I'm not going to I guess. I may have only put the minimal requirements logic required to make it work after considering all other stick locations.
- Bottom of the Well Stick Pot
- Zora's Domain Stick Pot
- Zora's Domain Nut Pot
- Dampe's Grave Nut Pot
- Hyrule Field Grotto Nut Pot
- Hyrule Castle Grotto Nut Pot
- Spirit Temple Nut Crate
- Jabu MQ Nut Pots

I'm not sure if I trust past me still not to have left anything logically irrelevant off the list. But that's what I've got.

**Comment by rattus128** [comment]
Thanks,

Some comments inline below. This stuff is all a huge help.

Currently all the non repeatable accesses I can think of are high enough
sphere to guarantee nuts and sticks implicitly (e.g. strength to finish
forest can open goron city to child which gives sticks which gives nuts)
but ill make these changes because those are fragile assumptions.

On Wed, 20 Feb. 2019, 09:31 r0bd0g <notifications@github.com wrote:

> "I probably should have kept my notes file on that around."
> Then it occurred to me that maybe I did. So I found my list of drop
> locations, anyway.
>
>    - Buy Sticks, Buy Nuts
>    - Kokiri Forest Babas (but not as adult in entrance shuffle)
>
>
No-ER condition added


>    - Forest Temple Babas - You'll have to add this drop location and
>    check that you can get nuts and get sticks from them.
>
>
The giant ones drop both sticks and nuts under usual weapons. Added. I've
simplified to just logic for adult as the closed forest or s0 forest covers
child.


>    - Goron City Stick Pot - The logic on this might not be complete, I
>    would have to check and I'm not going to I guess. I may have only put the
>    minimal requirements logic required to make it work after considering all
>    other stick locations.
>
> Added hammer bow or adult strength.



>    - Bottom of the Well Stick Pot
>    - Zora's Domain Stick Pot
>    - Zora's Domain Nut Pot
>    - Dampe's Grave Nut Pot
>
> Dampes nut is the catchall for adult nuts. Added.


>    - Hyrule Field Grotto Nut Pot
>    - Hyrule Castle Grotto Nut Pot
>    - Spirit Temple Nut Crate
>    - Jabu MQ Nut Pots
>
>
ER MQ on the to do list.

**Comment by r0bd0g** [comment]
Is strength upgrade not a valid way of reaching the goron city stick pot?

**Comment by rattus128** [comment]
Yes,

I had this diff and lost it somehow. Fixed. Adults only, as it only works
for adult opening it for child from the inside.

Thanks

**Comment by rattus128** [comment]
@r0bd0g , Here are the logic updates in the force push since your last reading:

```
$ git diff -w f6a7c51..3313db8 data
diff --git a/data/World/Forest Temple.json b/data/World/Forest Temple.json
index 888e401..dc064de 100644
--- a/data/World/Forest Temple.json     
+++ b/data/World/Forest Temple.json     
@@ -4,10 +4,10 @@
         "dungeon": "Forest Temple",
         "locations": {
             "Forest Temple First Chest": "True",
+            "Forest Temple Chest Behind Lobby": "Adult_Forest_Temple or Kokiri_Sword",
             "GS Forest Temple First Room": "
                 can_use(Dins_Fire) or 
                 has_projectile(either, Adult_Forest_Temple, Child_Forest_Temple)",
-            "Forest Temple Chest Behind Lobby": "Adult_Forest_Temple or Kokiri_Sword",
             "GS Forest Temple Lobby": "
                 (Adult_Forest_Temple and can_use(Hookshot)) or
                 (Child_Forest_Temple and can_use(Boomerang))"
diff --git a/data/World/Overworld.json b/data/World/Overworld.json
index 50ba0fe..8ad6bdb 100644
--- a/data/World/Overworld.json
+++ b/data/World/Overworld.json
@@ -46,7 +46,7 @@
             "Deku Tree Gossip Stone (Left)": "True",
             "Deku Tree Gossip Stone (Right)": "True",
             "Child Deku Tree": "True",
-            "Adult Deku Tree": "is_adult"
+            "Adult Deku Tree": "is_adult and shuffle_dungeon_entrances"
         },
         "exits": {
             "Kokiri Forest" : "True"
@@ -590,7 +590,7 @@
             "GS Kakariko Watchtower": "(has_slingshot or has_bombchus) and nighttime",
             "GS Kakariko Above Impa's House": "can_use(Hookshot) and nighttime",
             "Child Bottom of the Well": "can_play(Song_of_Storms)",
-            "Adult Bottom of the Well": "is_adult"
+            "Adult Bottom of the Well": "is_adult and shuffle_dungeon_entrances"
         },
         "exits": {
             "Hyrule Field": "True",
@@ -913,9 +913,14 @@
             "Sheik in Crater": "is_adult",
             "GS Mountain Crater Bean Patch": "
                 can_play(Bolero_of_Fire) and has_bottle and can_child_attack",
+            # This logic sucks, but I really want child Fire Temple in ER for with no tunic
+            # as its a super easy dash coming from the bolero warp. Make it consistent with
+            # adult with child by removing tunic if adule has bolero, but only on shuffled
+            # entrances
             "Adult Fire Temple": "
-                is_adult and (logic_fewer_tunic_requirements or has_GoronTunic or can_play(Bolero_of_Fire))",
-            "Child Fire Temple": "can_play(Bolero_of_Fire)"
+                is_adult and (logic_fewer_tunic_requirements or has_GoronTunic or 
+                              (shuffle_dungeon_entrances and can_play(Bolero_of_Fire)))",
+            "Child Fire Temple": "can_play(Bolero_of_Fire) and shuffle_dungeon_entrances"
         },
         "exits": {
             "Death Mountain Crater Lower": "

```

**Comment by r0bd0g** [comment]
You don't actually need to check is_adult on that strength upgrade use. If you're goron city as child you can just get the pot.

**Comment by rattus128** [comment]
Removing RFC label. This has moved a long way recently with most of the prep work already merged.

**Pull request merged**
