### PR TITLE
Hint Distribution Option

### PR DESCRIPTION
**Pull request by Cuphat**
The Hint Distribution option allows you to configure what types of hints are used. Possible options are Normal for the default style, Powerful for the weekly/tournament style, or Jokes if you need some comedy in your life.

This also adds the location of the gossip stone each hint was placed on to the spoiler log and cleans out the formatting characters.

Here's 100 spoiler logs for each of the 3 options: http://runs.live/hint_distribution_logs_2.7z

Let me know what you think. I thought it'd be nice to have the tournament hints included, and this option could always be expanded if desired.

### CODE REVIEW

**Comment by flagrama** [comment]
I don't think that Tournament is a great name to use as it requires outside knowledge to understand it, and might confuse some people into thinking it is an option only to be used in tournaments. Is there maybe some other name to use for it? Something like "Easier" or "Stronger" or probably something much, much better because I'm not good at naming things.

Now if we could add more junk hints in to make the Jokes option more dynamic 👀

**Comment by Cuphat** [comment]
You're right. I changed Tournament to Powerful, as that is at least more descriptive. I am also bad at names so if anyone has a better name, go for it.

**Comment by Cuphat** [comment]
Way of the Hero.

**Comment by phixtyseven** [comment]
Ah, thank you

**Comment by r0bd0g** [comment]
Removing lens of truth from woth is not something that really works correctly as implemented.

Imagine lens is at frog songs, and one of the songs is behind OoT. That's going to add a billion requirements, all of it will go on woth, but mysteriously only the frog songs for lens at the end of it all will be removed.

Another idea might be to turn all of the logic options on between the spoiler and generating the hints.
The removal of the stone of agony has similar problems... I guess "hints need nothing" sort-of simulates it. At least if you figure out that stone is woth, you know one of the always hint locations is required.

Also, Master Sword does not need to be manually removed anymore.

**Comment by Cuphat** [comment]
Thanks for the feedback, r0bd0g. At that point I was just duplicating how the tournament fork removed those from the WotH pool, but you are right, it's incredibly hacky in a bad way. Thanks for the tip on how to improve it. I believe this new implementation should work better.

I re-generated the spoiler logs and updated the link to them. Required items that are excluded from Way of the Hero are split into the "Other Logically Required" section of the spoiler log.

**Comment by r0bd0g** [comment]
I don't like how it has to run can_beat_game twice on all the required items. But I mean I guess this is probably about how it would have to work. One thing though is that whatever items you collect from turning off those logic options will have to be recollected every time you call can_beat_game, but I doubt that has that much of an impact on run time.

**Comment by TestRunnerSRL** [comment]
So I've been doing a pretty major revision on how the hint system works, so this kind of distribution isn't really applicable. I did heavily use your idea with structuring the distribution with some kind of modular distribution object, and took it to the next level where the actual hint selection process is more modular and random. This does kinda kill the tourney build style hints, but I think we can make it so that it works in a pretty similar way.

I'm not really a fan of the hints system logic not following the main placement logic. I understand that players who are doing those tricks won't want those hints, but you can just as easily argue that players who are not doing those trick will want them. You really can't please both sides, and I don't like the inconsistency. If a vast majority of the runners want to play with those glitches in logic, then they should add them to logic.

**Comment by Cuphat** [comment]
I'll keep this branch hanging around for my own reference at least, but this particular pull request is obviously not getting merged now, so I guess I'll close it. I appreciate you guys taking a look at it and implementing something similar, as I think it's a good idea overall.

**Pull request closed without merging**
