### PR TITLE
Fix broken drops and add magic jars to the junk pool

### PR DESCRIPTION
**Pull request by SlyryD**
- fix_broken_drops setting
  - allows the deku shield to spawn from the child spirit pot and puts it in logic
  - ensures you can pick up the magic jar wonder item on top of the GTG eye statue

image

- add magic jars to the junk item pool
  - ensure freestanding magic jars look different from freestanding magic meters by making the magic jars look like the shop green potion refill
  - turn into 5 rupees if plando'd as a starting item without magic meter

image

- add setting to GUI (misc section)

image

### CODE REVIEW

**Comment by r0bd0g** [comment]
The magic jars are something that should be implemented into the random junk pool. Precedent is that they go into the pool even if the pool doesn't normally have any of those items in it (ex: sticks and seed drops). So it's important I think that there's no possible confusion between a magic drop and a magic upgrade.

**Comment by SlyryD** [comment]
They are marked as junk with weight 0, meaning there will always be 5. I test it out with the same weight as purple rupees as well, and was getting 9 on average (with balanced item pool, normal ice traps). Is that what you mean by random item pool?

**Comment by r0bd0g** [comment]
I mean the pool of items that randomly get added to fill out the item pool. Gets used when you remove map/compasses or whatever.

**Comment by fenhl** [comment]
I think that's based on the vanilla junk items now with #1513, so no magic jars would be added without the setting.

**Comment by r0bd0g** [comment]
That change sounds like a regression to me?

**Comment by fenhl** [comment]
I was mistaken, the behavior hasn't changed. I also wasn't aware that this was intended; I thought the item pool was supposed to match the vanilla items from shuffled locations.

**Comment by r0bd0g** [comment]
It is supposed to match when the pool isn't altered. The junk pool is for when items need to be added after the pool is altered when things are removed from it.

**Comment by cjohnson57** [comment]
Large magic jars are added to the junk pool, not sure if it was like that before or if Sly fixed it in his most recent force-push.

**Comment by cjohnson57** [comment]
Actually, it seems to be adding them to the junk pool even if the setting is disabled, @SlyryD If that's fixed this PR should be good to go!

**Comment by r0bd0g** [comment]
Yeah the setting impacts only default item pool. I don't imagine most players really think about the item pool all that much. Since they're bluepees in the original game (magic jar denier), it shouldn't be default on. I mean you could maybe just add magic drops to the junk pool and just cut the 'magic jars from shadow temple' aspect. (Maybe it could be good to have this for if pot shuffle wants to shuffle magic jars from the default contents? Not sure how pot shuffle is handling default contents at this time.)

**Comment by ETR-BTF** [comment]
How about the Deku Shield on top of Mido's House that appears in the opening cutscene when Navi flies from the Deku Tree to Link's House?

**Comment by SlyryD** [comment]
> How about the Deku Shield on top of Mido's House that appears in the opening cutscene when Navi flies from the Deku Tree to Link's House?

That's a cool idea but I should probably stick to scene setups that are playable in vanilla :D There are other scene setups that appear in cutscenes, like graveyard while learning suns song, which has a chest on top of the graveyard ledge.

**Pull request closed without merging**
