### PR TITLE
Add setting to shuffle reward for catching the hyrule loach

### PR DESCRIPTION
**Pull request by kr3z**
In the vanilla game, each time you catch the hyrule loach at the fishing pond you're given a purple rupee as a prize. This PR adds a setting to shuffle that prize into the item pool. When enabled, the first time the loach is caught you receive a random item as the prize. Subsequent loach catches will then give the normal purple rupee prize.

An unused bit in the HIGH_SCORE(HS_FISHING) word in the save context is used for the flag to indicate whether the loach prize has been given or not. The vanilla game uses the following bits in HIGH_SCORE(HS_FISHING):
- 0x7F and 0x7F000000 are used to store the size of the current record fish as child and adult respectively
- 0x80 and 0x80000000 are used as flags to indicate if the current record fish was caught using the sinking lure
- 0xFF0000 keeps a count of the number of times the player has paid to play the fishing minigame
- 0x100 and 0x200 are flags that are set the first time the player plays the fishing minigame as child and adult respectively
- 0x400 and 0x800 are flags to indicate whether the child/adult fishing prizes have been given
- 0x1000 is a flag that gets set if the player catches the hat off of the fishing pond owner's head
- 0x2000, 0x4000, and 0x8000 are all unused. This setting uses the 0x8000 bit as a flag for the loach prize.

The loach can be caught using the default lure while it is in its spawn location. If the player gets too close to the loach, then it will move to the bottom of the pond and largely ignore all lures. The loach's threshold for detecting player proximity is larger than for other fish and so will scare out of its spawn position more easily than other fish. Once it has moved to the bottom of the pond, it can be difficult to catch. To make this less painful, enabling this setting will also modify some vanilla fishing pond behavior in order to make it easier to catch the loach. 

Normally, the loach will only spawn on every fourth play of the fishing minigame. But with this setting enabled, the loach will always spawn. This is done by overwriting the branch instruction that checks if play count & 3 == 3 during pond initialization. Rather than just overwriting the branch with a nop instruction, it's replaced with an sb instruction to store a non-zero value to an unused byte in memory. The byte occurs immediately after the variable D_80B7E0B6 and is unused due to byte alignment. Storing a non-zero value here acts as a flag that can be checked to see if the setting is enabled.

In the vanilla game, the sinking lure becomes available once the player has received the fishing prize for their current age. There are four positions in the pond that the sinking lure can be found at. During initialization of the fishing pond, the game will randomly choose one of those positions and make the sinking lure obtainable in that one position. With this setting enabled, the sinking lure will be available immediately without having to first do the normal fishing check, and will also be obtainable at any of the four positions rather than at just one of them. To do this, we hook into the Fishing_UpdateOwner function where it checks if the player is in the right position to obtain the sinking lure. The added code increments the array index of the sinking lure position, and then if the index is greater than four it sets the index back to 1. This causes the sinking lure's position to constantly rotate between all available positions, and the player visiting any of the four positions will result in obtaining the sinking lure.

Since the sinking lure is considered 'illegal' according to the fishing pond rules, the game will normally not give you the child/adult fishing prize if you catch the fish with the sinking lure. Because this setting makes the sinking lure available immediately, and because there's no way to switch back to the default lure once you have the sinking lure, this setting also allows the player to receive the child/adult fishing prize even if they use the sinking lure.

With the sinking lure, you can get the lure to the bottom of the pond where the loach hangs out. But when the loach is sitting at the bottom of the pond its code doesn't actually check for the lure. To make it easier to catch, this setting modifies two specific loach states to get it to actually pay attention to the lure. This modification is done to case -1 and case -2 in Fishing_UpdateFish. Case -1 is the state of the loach when it is sitting at the bottom of the pond. Case -2 is the state of the loach when it periodically rises to the surface. Neither of these states normally check for the lure, and both cases end with the line:
`this->actor.flags &= ~ACTOR_FLAG_0;`

These lines are replaced with calls to make_loach_follow_lure, which has the effect of running the following code. This checks if the sinking lure is equipped and if so, calls the function that checks lure position. If not, it unsets the actor flag as normal. This is the same code executed by non-loach fish once they've been scared from their spawn positions into the center of the pond:
```
if (D_80B7E0B6 == 2) {
    func_80B70ED4(this, input);
} else {
    this->actor.flags &= ~ACTOR_FLAG_0;
}
```

With these changes, the loach is significantly easier to catch.
[Video of catching the loach both in its spawn position and from the bottom of the pond](https://youtu.be/ZCaVufAjYek)

### CODE REVIEW

**Comment by cjohnson57** [comment]
The changes you made for this setting are awesome, especially spawning the loach and lure immediately. With all of this work I think we can definitely accept this.

**Comment by r0bd0g** [comment]
What is the weight of the loach? I'm just wondering if it gets set to the same weight as the other fish since we have hacks that set all the fish to particular weights.

Wasn't the point of the loach is that it's hard to catch? I don't know that I understand the point of adding a check for it if you're going to make it so easy to do. Is there normally even a prize for catching it? It's so many hoops you've had to jump through to make this playable, that I'd say you've basically added in an entirely new sidequest that only vaguely existed in the vanilla game before this, on par with adding a check for beating the running man, or something. To just, create a new check out of the air like this, it'd be a first, if accepted.

**Comment by cjohnson57** [comment]
I mean, without these modifications, I don't think I'd even accept this PR as it would be absolutely terrible to do this all for 1 check lol.

Although maybe for the masochists (which I call them that with love) it could be a dropdown:
* Unshuffled
* Shuffled (Modified to be easier)
* Shuffled (Unmodified)

**Comment by ETR-BTF** [comment]
Can the loach be isolated from other fish? In the video when you tried to catch the loach the first time, two smaller fish bit first. If this happens every seed, this can get frustrating pretty fast. Isolating the loach will also make this setting more in line with the isolation of the fish that satisfy the child/adult fishing checks.

> I mean, without these modifications, I don't think I'd even accept this PR as it would be absolutely terrible to do this all for 1 check lol.
> 
> Although maybe for the masochists (which I call them that with love) it could be a dropdown:
> 
> * Unshuffled
> * Shuffled (Modified to be easier)
> * Shuffled (Unmodified)

Hell mode is surprisingly popular, so I'm sure there are also people out there who want to torture themself with an unmodified version of this feature. :P

**Comment by r0bd0g** [comment]
Even "unmodified" would not be unmodified b/c there's no way to revert to vanilla fishing mechanics.
(Honestly I would appreciate a setting for that. Not to play myself but because I think people should be able to experience that horror. The people need this to be able to appreciate how good they have it. You'd probably have to add fishing to conditional always.)

But what I was saying was with all of these hoops jumped through to make the loach playable, if it doesn't really feel like catching the loach anymore, should it actually be playable?

I think the change to make the sinking lure available right away and usable for the main prize might be unnecessary. What reason would a player have to prioritize the loach over the main fishing check? (Having a hint would be the only reason, but that's more of a hint problem.) So why not just get the main prize, and then come back for the loach with the lures enabled? Maybe even go so far as to not have the loach spawn on the first visit to retain at least some of its seeming elusiveness. Does the sinking lure really need to be at all four spots? Is it that arduous to just check all four? I guess you could seed the RNG if differences in RNG between players is that much of a concern, but maybe that'd be overkill.

**Comment by kr3z** [comment]
To answer some of the questions:
The size of the loach is affected by the existing fishing hacks, but weight is calculated from the size value differently for the loach than it is for the other fish, so the loach still ends up with a similar weight as in vanilla. The way the size hack works is that it iterates over the entries in the sFishInits array. Every fish with an even array index is set to as size of 46 as child and 52 as adult. Each odd array index fish is set to 36 as child and 44 as adult. In terms of weight, the loach that spawns as both child and adult has an odd array index and the weights come out to be 19lb for child and 28lb for adult. The loach that only spawns as child has an even array index, and comes out to 30lb.

As for vanilla sizes, each fish is given a base size in the sFishInits array. There is then a random factor added to that base size, and then if the player is child the size is scaled by 0.73 to make the fish smaller as child. For the loaches, the size for the odd array index loach falls roughly in the range 33 - 36.5 as child and 45-50 as adult. The child only even index loach falls in the range 31-35. So the odd index loaches are about the same between vanilla and hacked sizes. The even index loach has a larger hacked size than it is in vanilla, but its the same size as the adult loach in vanilla.

As for whether there is normally a prize for catching the loach, yes the vanilla game rewards you with a purple rupee for catching the loach. This setting modifies the existing getItemId for the loach prize, it does not add a new item that doesn't exist in the vanilla game.

Regarding isolating the loach from other fish, this is theoretically possible. The sFishInits array holds the spawn coordinates for each fish, so it's possible to change the spawn location of the loach. Though I don't find it too frustrating to catch the loach in its current spawn position. When you cast, all fish in the area will try to bite the lure. Sometimes the loach will bite first and sometimes it might take a couple of casts before hooking the loach. The other alternative is scaring the loach to the bottom of the pond and then using the sinking lure to catch it. The loach scares more easily than other fish so its easy to move just the loach while keeping all other fish in their spawn positions. The loach will pick a random position to move to on the bottom of the pond, but if its the only fish that has moved out of its spawn position then it should be isolated from the other fish.

As for the sinking lure modifications, my though was that since there are dual hints that can hint the fishing checks it would be better to not lock that behind another check that the player may already know is dead. And the sinking lure being available at all four positions I just find more convenient than having to check each position until I find it.

**Comment by cjohnson57** [comment]
Yeah I think if an option to leave it (relatively) unmodified is added this'd be good to go in my eyes after code review

**Comment by r0bd0g** [comment]
We already have fishing, and fishing again. Do we need fishing again again? After all these changes, what still differentiates the loach from the existing checks?

**Comment by kr3z** [comment]
I changed the setting to a drop down with three options, 'Off' 'Vanilla Behavior' and 'Easier Behavior'

**Review by cjohnson57 — APPROVED** [review]

**Review by cjohnson57 — CHANGES_REQUESTED** [review]
Sorry just realized 1 more thing, you didn't add hints for the new item location

**Comment by r0bd0g** [comment]
Should it be an always hint if it's not on easy mode?

**Comment by cjohnson57** [comment]
> Should it be an always hint if it's not on easy mode?

Definitely

**Comment by kr3z** [comment]
I added a hint for the location and set to as conditional always when using the vanilla behavior setting

**Review by cjohnson57 — APPROVED** [review]

**Pull request merged**
