### PR TITLE
Remove Wastelands gate cutscene

### PR DESCRIPTION
**Pull request by GSKirox**
Remove the Wastelands gate opening cutscene when you talk to the Gerudo guard after getting the Gerudo Card Membership.
Also sped up the actual opening movement by increasing the speed of the gate, and removing an internal timer which only purpose was to time the cutscene properly.
The gate flag is set before the cutscene, so you can save quit or warp before the gate is actually all the way up, and it'll be opened fully the next time you come.

https://user-images.githubusercontent.com/65768236/223843535-fb4c6bff-a3df-4b83-baee-362fc6d3adff.mp4

https://user-images.githubusercontent.com/65768236/223843541-fbe3716f-e12c-4e5f-8ca3-92cd319b3d47.mp4

### CODE REVIEW

**Comment by r0bd0g** [comment]
What happens to the guard actor? Is she just stuck like that?

**Comment by GSKirox** [comment]
Oh wow i didn't even notice that lol. Her animation changes back after a few seconds, i'm guessing it's tied to the time the cutscene lasts normally.
Could probably adjust it but it's really minor.

**Comment by r0bd0g** [comment]
What happens if you try to talk to her in that time?

**Comment by GSKirox** [comment]
There's no Speak option on A until she changes her animation back, so you can't.

**Comment by r0bd0g** [comment]
In hideout shuffle, can this type of guard throw you into the jail? If so you'd probably want to be able to talk again right away just in case you wanted to do that.

**Comment by fenhl** [comment]
No, the only guard you can ask to be thrown into jail is the one standing at the bottom of the path to HBA.

**Comment by Cuphat** [comment]
TIL you can ask a guard to be tossed into jail.

**Comment by fenhl** [comment]
Only once #1616 is merged.

**Pull request merged**
