### PR TITLE
Control shopsanity prices

### PR DESCRIPTION
**Pull request by Lego6245**
This PR adds an option to give users finer control over shopsanity's prices without having to rely on the plandomizer. The shopsanity_prices option allows users to default to the current pricing structure, with the following choices:

Random, which preserves the existing behavior involving a 300 rupee cap and a beta distribution to bias the random prices towards the lower half of the range.

X Wallet, where X is each type of wallet. These randomize prices in 5 rupee increments up to caps determined by the maximum carriable rupees for each wallet, for instance, 200 for the Adult's Wallet, or 999 for the Tycoon's Wallet.

Affordable, where the shopsanity item's prices are capped at 10 rupees. This is similar to scrubsanity's affordable setting.

### CODE REVIEW

**Comment by ETR-BTF** [comment]
I'm not seeing the option in the gui.

**Comment by Lego6245** [comment]
> I'm not seeing the option in the gui.

I was able to see it when running Gui.py out of the project root. Did you enable a shopsanity option first?

**Comment by ETR-BTF** [comment]
My bad, it seems I downloaded the wrong branch.

**Comment by aofengen** [comment]
Would it be possible to post some example images? Won't be able to download the branch for a whole, and I'm curious how it looks

**Comment by Lego6245** [comment]
Screen Shot 2021-09-24 at 2 53 29 PM
>

**Comment by aofengen** [comment]
@Lego6245 so does that set all randomized shop items to the same price?

**Comment by Lego6245** [comment]
> @Lego6245 so does that set all randomized shop items to the same price? Or is it a min/max kind of thing?

Currently, the setting is for a set, fixed price. I hadn't considered a desire to make it a range.

**Comment by aofengen** [comment]
Hmm.. I kinda like either way, to be honest. Some finer, more granular control for shops provides less required rupee grinding (or I guess more if you really want that ha). This is cool. Well done

**Comment by ETR-BTF** [comment]
How about a double slider to indicate min/max values, where they overlap if you want a fixed price?

**Comment by Lego6245** [comment]
> How about a double slider to indicate min/max values, where they overlap if you want a fixed price?

Sounds kinda complicated to get it to work right. If that's a strong want, I can investigate further and see if I can get it to work, but to my knowledge there's no existing pair of co-dependent sliders so it may require additional work to get it to behave correctly.

**Comment by Hamsda** [comment]
Yeah a double slider for indicating min and max values has been wanted for various other settings already, so I don't think we have that option right now.

**Comment by r0bd0g** [comment]
I don't think we need this feature. I don't feel that setting all prices to a static price is really what people want, and to give people finer control over how prices are distributed would be too complicated to do properly. I could see having a set of fixed price distributions to choose between or something (kind of similar to what is currently done with scrub shuffle), but even that I'm not sure how it would go...

**Comment by Lego6245** [comment]
> I could see having a set of fixed price distributions to choose between or something (kind of similar to what is currently done with scrub shuffle), but even that I'm not sure how it would go...

If it wasn't clear, the PR includes multiple pricing options including randomization capped at each wallet band (99, 200, 500, and 999), as well as an "Affordable" option a la scrub shuffle where prices are fixed to 10 rupees. The custom fixed price option is only one option that's part of the PR.

**Comment by Lego6245** [comment]
I've updated the PR description to make the above clearer.

**Comment by r0bd0g** [comment]
I don't understand what the "X or Fewer" option is doing.

I think the current behaviour might have a bug where 300 is not actually possible? Remember hearing something about that a while back.

**Comment by Lego6245** [comment]
> I don't understand what the "X or Fewer" option is doing.

X or Fewer is generating a random price for each item in a shop, with an upper bound of either 99, 200, 500, or 999 depending on the option chosen. For instance, 200 or fewer would guarantee that all items are obtainable after receiving the adult's wallet, with prices ranging from 0 to 200, in increments of 5.

>I think the current behaviour might have a bug where 300 is not actually possible? Remember hearing something about that a while back.

It's probably because the `int` cast will floor any float instead of rounding it, so you'll never get the maximum of 60 * 5. Could either `round` the float prior to the cast, or multiply it by 61 instead of 60.

**Comment by Hamsda** [comment]
I think the idea sounds interesting, but it is taking up a lot of UI space for very little relevant gameplay change, I feel?

As r0bd0g pointed out, I don't think the option for setting all prizes to something expensive would be very popular. And that should be the only option that requires the slider, right? Maybe could just scrap that part, and just offer a few options in the dropdown to reduce the required space and still offer most of the changes?

**Comment by Lego6245** [comment]
> Maybe could just scrap that part, and just offer a few options in the dropdown to reduce the required space and still offer most of the changes?

I can definitely do that, but I will say that the slider is hidden behind selecting the custom option, so it's not always visible. Neither is the price options drop down, it's only shown if you select a shopsanity option that's not "off", similar to how the Medalions/Skulls/etc sliders work for stuff like Ganon's boss key.

I agree that out of all the options, the custom one would probably be the least used, if ever, so I'll remove it in the next iteration.

**Comment by Hamsda** [comment]
Yeah I assumed they were hidden, but you also have to consider a sort of "worst case" in terms of UI space used.

I do like the idea of a sort of "shopping spree" mode with shopsanity 4 and all of the items set to 10 rupees though :)

**Comment by Lego6245** [comment]
> I do like the idea of a sort of "shopping spree" mode with shopsanity 4 and all of the items set to 10 rupees though :)

I saw a number of requests in the discord about a affordable shopsanity mode, so I figured there was some demand for a setting like this, similar to how scrubs can be set up.

**Comment by Lego6245** [comment]
Gentle nudge now that the 6.1 push it out of the way. Open to any feedback!

**Comment by Zannick** [comment]
I think the shop shuffle quantity is still useful to have separately. This seems good to me. I'm pondering whether the nondefault options should also be betavariate-biased but I guess that's part of the charm being copied from scrub shuffle? I guess we can try it out and see.

**Review by Zannick — APPROVED** [review]

**Pull request merged**
