### PR TITLE
Rearrange the order of settings in the spoiler log based on importance and similarity

### PR DESCRIPTION
**Pull request by DuskTheUmbreon**
These are arguably two of the most important settings the spoiler log can display, so it makes more sense to push them to the top, above almost everything else, rather than being buried in the middle, between TH and bombchus in logic.

This puts these two settings on the fourth and fifth lines of the settings list in the spoiler log, between random settings and closed forest. It *shouldn't* affect anything else.

### CODE REVIEW

**Comment by ETR-BTF** [comment]
Would it make sense to reorder the other settings to reflect the order in which they appear in the GUI? For example, a lot of the options on the "other" tab (e.g. cucco count) appear before the various ER and sanity options. The starting age option also isn't with the other ER options and I could go on for a while. :P

**Comment by DuskTheUmbreon** [comment]
It might be a good idea to spend a bit more time sorting things around to more logical spots in the spoiler...It'd also be a lot of extra work to do, though.

There's also a couple other settings (like MQ or GBK) that might be better closer to the top? There might be some debate there as to what order some things should go in or if it'd be better to just make everything else match the order they appear in the GUI. I could also see an argument for forcing the big lists (such as starting items and tricks) closer to the bottom...

**Comment by ETR-BTF** [comment]
If we can get a consensus on the ideal ordering, then I wouldn't mind doing the extra work.

**Comment by ETR-BTF** [comment]
I whipped something up to get a discussion going. It's in txt format because github doesn't accept json. 

It's basically the order in which they appear in the gui. Some comments:
- Can json files have empty lines? Because I think they add readability in this case.
- Starting items mistakenly(?) appear twice in the log. 
- I put the detailed "logic tab" and "starting items" tab at the end so that the big lists would not obstruct readability. That kind of puts "night skulls require suns" in an awkward position though.
- Arguably it makes more sense to put the gbk setting/condition with that of the rainbow bridge. Maybe "triforce hunt" also.

[settings_order.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/6489872/settings_order.txt)

**Comment by Zannick** [comment]
jsons can have whitespace, yes. blank lines should be fine. I think it looks good. I would probably reorder and group things together based on function (eg. move lacs_condition+gbk to structure/win conditions near the top, group hints together, move ocarina_songs to be in a cosmetic-like section toward the end), but that could also be a separate PR. Basing on the GUI is fine enough for me for a first stage.

The starting item redundancy is being taken care of by #1352.

**Comment by ETR-BTF** [comment]
I've reordered+grouped some things based on function, as Zannick suggested and I've also added some of the new additions to the log since the last batch of merges.

There is one line that seems redundant to me: the name is "hint_dist" and it always has "custom" as its value, even when selecting one of the built-in hint distributions.

[settings_order_v2.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/7009222/settings_order_v2.txt)

**Comment by DuskTheUmbreon** [comment]
I've updated it (mostly) per ETR's file. I made some changes to the order to sort things in a way that made more sense to me.

[settings_order_v3.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/7110911/settings_order_v3.txt)

**Comment by cjohnson57** [comment]
If this is updated to work on latest, I'll review it. That being said, getting our community to agree on "importance" seems a difficult task. And those who are used to the current ordering may not be a fan.

**Comment by ETR-BTF** [comment]
> If this is updated to work on latest, I'll review it. That being said, getting our community to agree on "importance" seems a difficult task. And those who are used to the current ordering may not be a fan.

The current ordering is about as chaotic as it can be lol. I think the ordering that we came up with is very intuitive and also a massive aid to the Support team. It's moreso in the order in which they appear in the gui than in order of importance, with the exception of settings like win condition and logic setting, which I'm sure people would agree are the most relevant ones.

**Comment by cjohnson57** [comment]
Ok yeah, if it's mainly based on ordering in the GUI then I think that's an objective enough measure that there's not too much room for arguing.

**Comment by cjohnson57** [comment]
Since Dusk hasn't expressed any interest in updating this to latest I'll close it for now.

**Comment by ETR-BTF** [comment]
Would it be wise to plan with the devs when to develop and PR this feature since it seems to cause conflicts with every other PR?

**Pull request closed without merging**
