### PR TITLE
MQ Fire Like Like returns your shield

### LINKED ISSUE #1437: MQ Fire Like Like doesn't return your shield
This Like Like in MQ Fire didn't return my shield. I'm not sure if this is vanilla behavior, but it might be programmed in MQ, because the chest you spawn contains a hylian shield in vanilla MQ. Please make the Like Like return the shield :D https://clips.twitch.tv/PeppyPleasantChamoisMoreCowbell-FZ1q1AWv8DlvTSq4

### PR DESCRIPTION
**Pull request by SlyryD**
Fixes #1437 by adding deku shield and hylian shield to the list of objects for the room in MQ Fire.

### CODE REVIEW

**Comment by SlyryD** [comment]
Works as adult and child with deku shield and hylian shield. 
image

**Review by cjohnson57 — APPROVED** [review]
Nice and easy fix

**Comment by r0bd0g** [comment]
Would there be any point in 'fixing' it to also return the tunics? In theory a fix to vanilla mq would include that even though you wouldn't ever see it in rando.

**Comment by cjohnson57** [comment]
Hm, I guess no reason not to.

**Comment by r0bd0g** [comment]
Perhaps there should at least be a comment about the state of tunic drops from this like like.

**Pull request merged**
