### PR TITLE
Move Troublesome MQ Floor Switches Down 1 Unit

### PR DESCRIPTION
**Pull request by engineer124**
This PR addresses this issue: https://github.com/TestRunnerSRL/OoT-Randomizer/issues/1288

To quote: "The floor switches that were annoying to press (I guess because they were placed too high) in vanilla were long ago fixed to be easier to step on, but there are many such switches in MQ that have not been touched."

The 5 floor switches that were lowered by 1 unit are:
1. Top of MQ Deku main room (particularly when pressed as adult?)
2. Fire temple MQ flame wall maze
3. Fire temple MQ... uhhh whatever the hammer chest room from vanilla is called
4. Fire Temple MQ, the blue switch where the map chest is in vanilla
5. I've bonked on the switch in the first room of MQ Forest a few times

I tested all 5 of these switches as adult and they are much easier to press down now.

However, the Fire Temple MQ blue switch (where the map chest is in vanilla) had issues as a result of this change. I found that by moving it down 1 unit, that while it was easier to step on, it became too sensitive and constantly switched on and off, triggering the cutscene over and over again. So I'm not sure if this particular switch should be moved down 1 unit. But I'd like someone else to test it if possible to see what they think.

A secondary minor (and imo insignificant but worth noting to devs in case it is important) is that for all 5 switches, while pressed down, very slightly blends in with the floor since it was lowered 1 unit. This is purely aesthetics and does not impact how the switch is pressed.

### CODE REVIEW

**Comment by r0bd0g** [comment]
Is that blue switch the first problematic one that's blue?

**Comment by engineer124** [comment]
In what sense? Could you elaborate? 

That blue switch was the only problematic switch I came across, and it was the only blue one that I tested. I didn't go too much outside of those five (my memory recalled the mq basement forest switch being picky, but testing it without mods and it was just fine, so I have poor memory and I left it alone).

Any other blue switches I could test?

**Comment by r0bd0g** [comment]
I just mean, have all of the other switches we've adjusted have not been blue switches that stop being pressed if you get off of them.

**Comment by engineer124** [comment]
I see. Yes, the other 4 switches adjusted are not blue. They do not toggle on and off when stepped off of.

The remaining switches are either permanent (Forest Switch to spawn the first chest), Temporarily permanent (Deku to spawn flames in the central room, resets when scene is reloaded), and timer based (Fire x2, stays held for many seconds so Link can race to beat the flames).

**Comment by r0bd0g** [comment]
I mean I was wondering also if any of the vanilla dungeons had blue problematic blue switches. I'm assuming the reason we're only encountering problems with lowered switches now is b/c this is the first time a blue one had to be moved. This blue switch in mq fire was one of the more annoying ones, b/c you're carrying a box you can't roll or jumpslash, and b/c the room is heated you don't always have time to dilly-dally, but if the multiple press thing is remotely common it probably can't be changed, or at least it can't be changed like this.

**Comment by SlyryD** [comment]
It probably makes sense to leave the MQ blue switch where it is, if it's causing problems.

**Comment by Zannick** [comment]
Let's remove the Fire Temple MQ blue switch from this PR, then.

**Comment by r0bd0g** [comment]
The awkward thing is that blue switch in fire is one of the more annoying ones.
You have to carry the box onto it, so the usual methods of getting onto annoying switches can't be used.
In vanilla there was a problematic switch in the basement of forest. If you played before the fixes, you know the one.
It was fixed in vanilla 1.2 (not sure about 1.1) by rotating it 45. 
I wonder if something else ought to be done for it...

**Comment by cjohnson57** [comment]
Hey engineer are you planning to remove that one switch?

**Comment by r0bd0g** [comment]
While editing mqu.json is the more sane way to make this change, I kind of feel like it should be done in the same way that the vanilla switches were moved down. It's weird that we would like, change all the actors, and THEN move the switches again, but it might be better to leave the .json as a more accurate representation of MQ. And this way the average person can look and see the changes being applied.

**Comment by SlyryD** [comment]
After testing the blue switch in fire temple with and without engi's change, I think engi's change is actually fine. That's definitely the hardest switch to get onto out of all of these. I had to try hard to replicate the extra sensitivity engi was talking about.

**Comment by SlyryD** [comment]
If you all are still against it. There's my other pull request mentioned here, but I closed it for now.

**Comment by SlyryD** [comment]
We would need a custom JSON parser to handle comments in the JSON file. Looking at the file history also isn't that bad: https://github.com/TestRunnerSRL/OoT-Randomizer/commits/Dev/data/mqu.json

**Review by cjohnson57 — APPROVED** [review]
Approving this but will undo the specified switch myself upon merging

**Comment by cjohnson57** [comment]
After consulting with Sly this'll be merged as-is on a trial bases but the one that potentially causes issues may be undone if complaints about it come in.

**Pull request merged**
