### PR TITLE
Add Tricks (rebased on behalf of r0bd0g)

### PR DESCRIPTION
**Pull request by rattus128**

### CODE REVIEW

**Comment by r0bd0g** [comment]
Thanks :) 


- I reworded the description on the Water Temple Boss Key Chest trick to just say it requires Iron Boots rather than "No Additional Items".
- I removed "this is very difficult" from the hover boots waterfall trick. Since we're passing that trick in difficulty now it seemed weird to call that one out.
- Added a short bit to the tooltip about what the Fire Temple Flame Wall Maze Skip allows you to skip.

- Corrected three wholly unimportant instances of "Bow" to "has_bow".
- Backspaced an unnecessary is_adult check in the Fire Temple Middle logic.
- Added lens requirements to both vanilla and mq light trials.

Added Tricks:
1. Forest Temple NE Outdoors Ledge with Hover Boots
- You can get from the balconies up top down to the ledge where you normally have to hookshot up to a chest or fall down from the door above.
- This one is mostly relevant in MQ, but also in vanilla with ER.
2. Water Temple Boss Key Region with Hover Boots
- This is the trick where you backwalk with the Hover Boots and then backflip over the spikes.
- It's only relevant in vanilla because you need the Longshot to even get to this room in MQ.
- In ER it's possible you might not even have the hookshot, so I had to modify the logic on the GS as well as the BK chest, since you can use the Hover Boots to kill and obtain the GS as well.
3. Water Temple Falling Platform Room GS with Hookshot
- Normally in logic with the Longshot, precise positioning can obtain the GS with only Hookshot.
4. Death Mountain Crater Upper to Lower with Hammer
- This is the move where you jumpslash the rock twice in the same jump in order to destroy it from the upper crater side.
- Relevant if you do not have the means to stop the Link the Goron and in ER.
5. Shadow Temple River Statue with Bombchu
6. Stop Link the Goron with Din's Fire
- Link the Goron, adult Goron City->Darunia's Chamber, and can_finish_adult_trades were affected by this.
7. Fire Temple Song of Time GS without Song of Time
- Precise jump.
8. Climb Fire Temple without Strength
- Precise jump.
9. Fire Temple MQ Flame Wall Maze Skip
10. Fire Temple MQ Big Lava Room Bombable Chest without Hookshot
- Precise jump.
11. Light Trial MQ without Hookshot
- This one is another flame wall skip.
12. Ice Cavern MQ Scarecrow GS with No Additional Items
- Precise jump.

**Comment by r0bd0g** [comment]
Is there a can_live_dmg method now or something? The Ganon's Castle MQ trick could probably use it...

**Comment by Roman971** [comment]
Shouldn't Goron Shop access as adult take "Stop Link the Goron with Din's Fire" (n° 6) into account?

**Comment by r0bd0g** [comment]
This guy affects so many places :NotLikeThis:

            "Goron Shop": "
                has_explosives or Progressive_Strength_Upgrade or can_use(Bow) or 
                (can_use(Dins_Fire) and (is_child or logic_link_goron_dins)) or
                (is_child and can_reach(Darunias_Chamber) and has_sticks)",

Is this how it should be?

**Comment by Roman971** [comment]
I think so yeah.

**Comment by rattus128** [comment]
> This guy affects so many places :NotLikeThis:
> 
> ```
>         "Goron Shop": "
>             has_explosives or Progressive_Strength_Upgrade or can_use(Bow) or 
>             (can_use(Dins_Fire) and (is_child or logic_link_goron_dins)) or
>             (is_child and can_reach(Darunias_Chamber) and has_sticks)",
> ```
> 
> Is this how it should be?

Added. Thx

**Comment by rattus128** [comment]
> Is there a can_live_dmg method now or something? The Ganon's Castle MQ trick could probably use it... The Fire Temple MQ one I intentionally left off Fairy but maybe if there were a set-up for the jump that worked every time then to use a Fairy would be fair...

The interesting thing about can_live_dmg is you specify how much. But as this is a flame fall with afterburn, its impacted by the goron tunic IIUC. So do we have to write some freeform involving the tunic to get this fully right? I believe the conservative damage number would be 1.25 ruling out quad, but with a tunic quad would survive. Let me know what I should do and I can push it tonight.

**Comment by TestRunnerSRL** [comment]
this is merged

**Pull request closed without merging**
