### PR TITLE
Changed in-game tunic icon colours to match worn tunic

### PR DESCRIPTION
**Pull request by ThomasJRyan**
Added a cosmetic option to change in-game tunic icon colours to match their overworld counterparts.

Implements an algorithm for adding a hue to RGBA values found in IconManip.py
Adds in a folder under data to hold greyscale tiff images so as to require less processing time.

Adds a Checkbutton into the GUI under UI Colors for toggling whether it should be used or not.

image

### CODE REVIEW

**Comment by aofengen** [comment]
does this change the color that the item model appears as in the world? I.e. If I see a tunic somewhere, would I know before grabbing it which one it is?

**Comment by ThomasJRyan** [comment]
> does this change the color that the item model appears as in the world? I.e. If I see a tunic somewhere, would I know before grabbing it which one it is?

It does not. It only affects the icons. Might be fun to look into changing the model colour, but I currently have no plans to do so.

**Comment by flagrama** [comment]
I'm pretty sure no racers want the model changed, and the devs don't really want to add more options to the GUI. This might be better always on as well so there isn't an extra option to do something so simple.

I think you should also generate a few patch files and try to get people to test them (they should be able to apply patches using just about any version of the rando including the website).

I'd test a patch on the website yourself first too. Make sure this doesn't end up doing something like rainbow sword trails ended up doing where it overwrote something and caused Forest Temple to generate as completely Vanilla in a race before among testing other bugs.

**Comment by ThomasJRyan** [comment]
Would it be better to make it always on? Feels like cosmetics aren't something that should be necessarily forced...

I can get some tests going. Shouldn't be difficult. With the nature of what it's doing I'd be shocked if it caused any issues gameplay wise. Will take a look and get back to this.

**Comment by flagrama** [comment]
I'd say that it is a cosmetic that goes along with choosing your tunic color in the first place. That's just my opinion though, it's up to the devs what they want.

As the guy who broke 5.0, I'm just saying testing with patches are a good idea :laughing:

**Comment by Cuphat** [comment]
I like the idea of changing the menu icon, good job.

> does this change the color that the item model appears as in the world? I.e. If I see a tunic somewhere, would I know before grabbing it which one it is?

Changing the icon in the menu is fine, but the models shouldn't change as the color of the tunic models carry specific meaning. Someone is way more likely to expend the energy to get the Goron Tunic if they see it than the Zora Tunic in a race setting, for example.

> Make sure this doesn't end up doing something like rainbow sword trails ended up doing where it overwrote something and caused Forest Temple to generate as completely Vanilla in a race before among testing other bugs.

That was because it modified one of the ASM symbols that rando added, and that symbol moved depending on version. Since cosmetics weren't versioned, it just changed the byte where that symbol would have been on that version.

This won't have that issue, and can be ran on any rando version or even the vanilla ROM itself. It changes icons where they just statically are on any 1.0 NTSC OoT ROM.

> Would it be better to make it always on? Feels like cosmetics aren't something that should be necessarily forced...

It should probably just be on, maybe only run it if the color of that tunic isn't default? I agree with flagrama that the cosmetic option for this is essentially the same as the tunic color cosmetic,

**Comment by ThomasJRyan** [comment]
Changed it so the tunic icon colour will automatically change if the tunic colour isn't vanilla

**Comment by flagrama** [comment]
This method is weird to me because if I set `Kokiri, Goron, Zora` tunics as `Zora, Kokiri, Goron` I'll end up with vanilla tunic colors even though I shifted them, right? Which is probably only a problem for people who choose "Random Choice" instead of "Completely Random" or selecting their own colors, so wouldn't actually affect me, but still would seem odd.

**Comment by ThomasJRyan** [comment]
You are very much correct and I've fixed it up so it won't have that issue.

**Comment by Syloh11** [comment]
Is this also possible to do for gauntlets?

**Comment by ThomasJRyan** [comment]
> Is this also possible to do for gauntlets?

Yes, and if there's an interest I can do it as well

**Comment by Syloh11** [comment]
> > Is this also possible to do for gauntlets?
> 
> Yes, and if there's an interest I can do it as well

Yeah that'd be dope. I just figure since gauntlet color can be changed it'd be cool to see this there as well.

**Comment by Roman971** [comment]
I would argue doing this for the inventory gauntlet color could be confusing since you wouldn't be able to tell which upgrade you have, if you forgot for whatever reason.

**Comment by flagrama** [comment]
On one hand, you can hover over the item in the menu to see what it is called. On the other, it gives people not using cosmetics an advantage in races and such.

**Comment by Roman971** [comment]
I wasn't aware you could tell them apart by hovering the item. I guess it would be alright then.

**Comment by Syloh11** [comment]
I'd be surprised if someone forgot what gauntlets they have in a race.

**Comment by Nicholas-Steel** [comment]
The text description changes Roman, that's how you tell the difference by hovering over it  ;)

**Pull request closed without merging**
