### PR TITLE
Add new electron based GUI

### PR DESCRIPTION
**Pull request by dragonbane0**
Almost ready...things left to do before this can be PRed:

~~-Add some switches to make this GUI work on the website outside of the electron context~~ Done
~~-A "boot" node module which can be launched from python or via console which checks if the GUI needs a re-compile if used in release mode. Should also perform the one-time environment setup if needed~~ Done
~~-Minor cleanup~~ Done

~~Should only take another day or so~~

### CODE REVIEW

**Comment by dragonbane0** [comment]
Alright this is pretty much ready to go. Just the integration work left and the boot helper module which I'm currently working on

**Comment by dragonbane0** [comment]
Should be all in good shape now. A few people from ootr support have tested the GUI with success. I also tried a macOS virtual machine and there were no issues.

**Usage for end users and dev unrelated to the GUI:**
Node and NPM need to be installed (Node ships with NPM). Any Node version > 9 and < 12 should work fine. Just launch the Gui.py how you are used to and it will take care of the rest. I made a brief mockup that gets the job done, but this is missing checks like if Node is installed and can be used: 

`#!/usr/bin/env python3
import os
import sys
import subprocess
 
def guiMain():
    args = ["node", "run.js", "release", "python", sys.executable]
    subprocess.Popen(args,shell=False,cwd="GUI")
 
if __name__ == '__main__':
    guiMain()`

In short it will trigger "node run.js release python pythonPath" in the GUI folder as the working directory. The run.js takes care of setting up the node environment, compiling Angular and Electron as well as maintaining an index that gets used to quickly decide whether to re-compile or straight boot on future launches.

I leave the design of the Gui.py to you TR, since you need to rip out Tkinter here.

**Usage for GUI dev:**
Open a cmd window in the GUI folder and run "node run.js python pythonPath". Without the release switch, the run.js will start the Angular dev server instead.

That's about it for usage. 

**Things left to do**
The settings_list.json under GUI/electron/src/utils is mostly up-to-date with current Dev, but the list of locations is incomplete for the disabled_locations setting, as that got changed a lot and is a pain to edit by hand. A json output of that list in the name, text format would be appreciated for that. 

It would probably be wise to go through the entire GUI and check everything again for missing/wrong settings before this is published widely.

**Notes**
The settings_list.json and settings_mapping.json are quite customized now to also allow the inclusion of the needs of the website. While adding new settings is easy through that, it needs to stay in sync with the python source somehow. So it might be required to switch the python SettingsList to a similar json format, so both can draw from the same input file and PRs don't need to adjust both things constantly, which seems like it will lead to issues fast of things not staying in sync properly and the GUI breaking.

**Comment by dragonbane0** [comment]
Trez made some improvements to the design after some more feedback. I also fixed a few bugs Lost caught while testing the GUI.

**Comment by dragonbane0** [comment]
Another round of QoL improvements have been added after feedback from the Discord. Everyone seems to be happy now as far as I can tell.

It should be noted for users with data caps that on the very first ever installation of the GUI on their system npm will download around 180 MB - 220 MB in package data depending on the OS. Every later install will pull all the needed files from a cache npm creates on the system, so every install after the first one will only waste around 1.3 MB of network traffic, even if the installation is performed in a different folder with a different dev build.

**Comment by dragonbane0** [comment]
Some additional information for dev:

**Electron**
The Electron source is contained within GUI/electron/src and written in TypeScript. Main.ts is managing the Electron process (the main side which has full access to the host system) and is used as the entry point. The preload.ts gets injected into any given browser window created by the main process and managed by the renderer process. 

The renderer process (the "client") acts mostly as a normal browser environment and is thus isolated from the host system. The preload.ts has restricted access to the main process and the renderer process and thus sits in the middle as an mediator of sorts. It gets loaded as part of a browser window before the first webpage does, in a separate JavaScript execution context. The webpage is thus only able to communicate with the preload.ts via a process called postMessage. 

If the webpage loaded in electron were to be high-jacked in some way or electron tricked into loading a remote webpage instead of a local one stored on the computer, the page then does not have full access to the host computer which would be catastrophic, but can only communicate with the preload.ts and the preload.ts gets the desired information from the main process / the host computer limiting access (the preload.ts should thus not implement a generic file IO API for example).

electron/src/modules/generator.js is the low level module which handles all communication with the ootr python source.

The settingsParser.js is used at boot time to combine the 3 json files in electron/src/utils together at runtime into a single object the main electron process shares with the browser app to initialize the GUI settings view. The settingsParser can be launched with a flag to indicate electron mode or web mode. In web mode certain electron only sections are not included within the output object, but different web sections are included instead. This gets used by the ootrandomizer.com server.

**The settings_list.json structure**
settings_list.json contains every single setting of the GUI as an array of objects. The following keys per setting entry are supported:

- default ---> The default value in the GUI
- name ---> Internal name of the setting
- text ---> Name of the setting as shown to the user
- tooltip --> The tooltip shown to the user when he hovers/clicks on the setting. Line breaks are inserted by adding a HTML `<br>` tag into the string
- type ---> Type of the GUI element to use to control the setting. Available types are: 
  1. Checkbutton: A boolean on/off toggle
  2. Radiobutton: A radio in-line list of buttons you can select one option of
  3. Combobox: A dropdown box that offers multiple options you can select one of
  4. Scale: A numerical scale that goes from a minimum to a maximum value and is accompanied by a number input box for manual input
  5. Textinput: An input box designed for text
  6. Numberinput: An input box designed for numbers (no scale)
  7. Fileinput: An input box designed for file paths accompanied by a browse button that opens a system file dialog
  8. Directoryinput: An input box designed for directory paths accompanied by a browse button that opens a system directory dialog
  9. SearchBox: A dual list of options that the user can select multiple options of and move them between active and not active. Also allows to text search for an option or select all at once. Drag and drop is also supported
  10. Presetinput: Designed for the main tab only. Adds a combobox and 3 buttons for the preset handling
presets.json is structured in the exact same way as the presets_default.json and thus redundant.
  11. Outputdirbutton: Designed for the main tab only. The button to open the currently set output dir

- options --> An array of options the setting can have. This is used for the settings type Checkbutton (redundant), Radiobutton, Combobox and SearchBox. Each option entry can have the following keys:
  1. name: Internal name of the option value
  2. text: Name of the option as shown to the user
  3. tooltip: The tooltip shown to the user when he hovers over the option. This is only supported by SearchBox at the moment. Line breaks are again added by a `<br>` tag
  4. controls-visibility-tab: What tab(s) to disable when this option is selected. Multiple tabs can be separated by comma and are addressed by their internal name (see mapping.json structure)
  5. controls-visibility-section: What section(s) to disable when this option is selected
  6. controls-visibility-setting: What specific setting(s) to disable when this option is selected


**The settings_mapping.json structure**
Follows shortly

**presets.json**
The presets.json is structurally identical with the presets_default.json and thus redundant.

**Comment by TestRunnerSRL** [comment]
Added the suggested Gui.py file. I also needed to rework how the `SettingList.py` file was structured so that I was able to include all the relevant info for the `setting_list.json`. Some notable changes is how the `dependency` is handled. Now it instead is list of settings/sections/tabs that the setting option disables when it is set. On load, the python code will then generate the old lambda to use runtime. This is a bit more limiting than the previous system and it used to be a function pointer, but this new method matches when the webpatcher uses, and it should cover the general use cases that have been done so far. I did notice that there `setting_list.json` doesn't seem to be able to handle having things disable when a `Checkbox` is unchecked. Nothing currently uses it, but it's something that we should probably add because I'm sure it'll come up in the future.

Currently, when you run `python Gui.py`, it'll first regenerate the `setting_list.json` in electron mode. if you add the cli arg `--web`, it'll instead generate with the web version of the options. The arg `--skip-settingslist` will skip regenerating the `setting_list.json`. Setting properties can be overwritten based on the electron/web build by prepending the setting in the `gui_params` with `web:` or `electron:` respectively. Otherwise the options will be the same for both. As such, the `settings_mapping.json` no longer lists all the setting parameters, only the settings' name.

The `ootrandomizer.py` still has the original behaviors, so CLI generation is still preserved, as well as all the original webside commands for generation. These commands can be changed pretty easily, and the location for the `settings_list.json` needs to updated; I'm not sure where it's supposed to go.

The generated `settings_list.json` is actually just the combined json that is generated from the `settingsParser.js`, so there's no need for that module anymore. I'm not sure how to change the GUI side to appropriately reflect this change. Let me know if there's something missing or incorrect in the file.

A feature that I noticed that is missing is the filter search for the location list. In the main dev build, there's a drop down to filter the search list further by the options' tags. It doesn't need to be the exact same implementation, but being able to filter/search by their tags is really helpful because of the shear number of locations. I've added the tags to the options in the `settings_list.json`

I noticed a few oddities in the `settings_mapping.json`, like the fact that the webpatcher hides some option when disabled (like the number sliders when they are randomized), but they don't on the electron side. Not sure why there are a bunch of dependencies in the properties between web/electron outside of the WAD stuff.

I made some other feedback in the Discord, so I'm also waiting for some of those to be added to the PR as well.

**Comment by dragonbane0** [comment]
Many improvements were made according to feedback posted here and on the Discord

**Pull request merged**
