### PR TITLE
Multiworld docs improvements

### PR DESCRIPTION
**Pull request by fenhl**
* Improves the subheader of the multiworld settings section, giving a better explanation of what multiworld does and adding links to [the wiki article on multiworld](https://wiki.ootrandomizer.com/index.php?title=Multiworld) as well as [Mido's House Multiworld](https://midos.house/mw) and [Bizhawk Shuffler 2](https://github.com/authorblues/bizhawk-shuffler-2).
* Fixes a typo in the description of the `PLAYER_NAME_ID` field in the co-op context docs.

### CODE REVIEW

**Comment by LostThePirate** [comment]
Isn't BizHawk Shuffler just Archipelago?

**Comment by fenhl** [comment]
I'm not aware of any connection between the two projects.

**Comment by ETR-BTF** [comment]
> Isn't BizHawk Shuffler just Archipelago?

I think Bizhawk Shuffler is just the project that automatically changes the game you're playing every x seconds. Archipelago is an entirely different project that allows for cross-game Multiworlds.

**Comment by Cuphat** [comment]
I think this is a bit too long of a description. Ideally it shouldn't be too much larger in size to the presets next to it. I think the lines between the wiki link and the generation time warning are probably best to be moved into the wiki page it links to instead.

image

**Comment by cjohnson57** [comment]
Agree with Cuphat, although I would probably just remove the sentence about Bizhawk Shuffler

**Comment by fenhl** [comment]
CI failure seems to be on Dev.

**Comment by cjohnson57** [comment]
Yeah my bad

**Review by cjohnson57 — APPROVED** [review]

**Pull request merged**
