### PR TITLE
Fix Equip Swap Crashes

### PR DESCRIPTION
**Pull request by Sirius902**
This PR fixes crashing when using Deku Sticks and masks as adult by replacing the display lists with an empty one if Link is adult. This is for convenience, allowing people who wish to equip swap on N64 to do so just as in VC.

### CODE REVIEW

**Comment by fig02** [comment]
just to avoid confusion id say "avoid crashes when using deku stick as adult", equip swap donesnt have anything to do with it FeelsOkayMan

**Comment by Zannick** [comment]
If we want a short name for the asm stuff, I guess "Equip Swap" is okay though.

Has someone tested this? I'm not a big equip-swapper.

**Comment by Sirius902** [comment]
@Zannick I know it's already been merged, but I'd just like to let you know that I've tested this both as adult and child with the items in question.

**Comment by ETR-BTF** [comment]
Does this include hook as child?

**Comment by Sirius902** [comment]
@ETR-BTF No, it does not. It only fixes equip swaps that would work on VC and hookshot softlocks on all consoles.

**Pull request merged**
