### PR TITLE
Option to Match Item Models with Cosmetic Colors

### PR DESCRIPTION
**Pull request by Roman971**
This adds an option in the top section of the Cosmetics tab which makes all ingame model colors and drop sprites match your corresponding cosmetic colors (for hearts, magic and gauntlets).
This includes all "Get Item" models such as the Piece of Heart and Magic Meter models, as well as both heart and magic drop sprites that can drop on the ground throughout the game.

Tunics and potions are purposefully excluded from this to avoid issues with not being able to distinguish them from each other if they matched randomized colors.

**Credit to @ThomasJRyan** for the drop icon patching implementation and showcase images found below.

Here is an overview of how having this option enabled looks like ingame:

image

image

image

image

image

### CODE REVIEW

**Comment by r0bd0g** [comment]
Does it need to be an option?

**Comment by Syloh11** [comment]
Would it be possible to add a separate option for potions and tunics to also have this for those who want it?

**Comment by ThomasJRyan** [comment]
Tunics have been discussed a couple times now. Most say it creates unfair gameplay and I guess wouldn't be used because of it (common argument is you'd be much more likely to detour to get goron tunic than you would Zora tunic, but with the colours being different you wouldn't know what's what).

With potions it just seems more like a hindrance than anything. Sure you can just read the descriptions but that's just added complexity

**Comment by Zannick** [comment]
We might have to narrow what's considered acceptable cosmetic colors for certain things so that the pickups remain visible.

I think I might also start confusing Heart Containers with the new Double Defense, but that's really minor.

**Comment by Zannick** [comment]
Sorry for the long wait. Is this ready for review/merge?

**Comment by Roman971** [comment]
I believe there aren't any known issues with it. I think icons sometimes end up a bit too dark when the base colors are already dark, but that's pretty minor and I don't know if we want to worry about it.

**Pull request merged**
