### PR TITLE
Display Triforce Pieces current count and Triforce Pieces goal on file select

### PR DESCRIPTION
**Pull request by GSKirox**
This PR re-organizes the Stones/Meds part of file select screen when Triforce Hunt mode is enabled, in order to always show both the current pieces in inventory and the total needed to the goal, instead of only showing the current pieces when at least one have been found.
Big thanks to Choiceoxide for the redesign !
fileselectTH1
fileselectTH300
The meds layout follow the song order on the same screen, to have a visual harmony => Spirit before Shadow.
If Triforce Hunt is not on, the file select screen reverts back to the current design.

### CODE REVIEW

**Comment by ETR-BTF** [comment]
This reminds me that we should check what happens if we have over 999 Triforce Pieces in the pool, because we can now have well over 1000 locations. I think you said that that exceeds the hardcoded maximum of Triforce Pieces?

**Comment by GSKirox** [comment]
Yeah this would need a fix, all the file select numbers are hardcoded for 3 digits max

**Comment by cjohnson57** [comment]
VERY nitpicky request: Would it be possible to make the left number gold when it's at (or above) the winning number?
image

**Comment by GSKirox** [comment]
Sure can !
triforce_yellow

**Review by cjohnson57 — APPROVED** [review]

**Pull request merged**
