### PR TITLE
Disallow excluding the Bombchu Bowling refill locations

### PR DESCRIPTION
**Pull request by fenhl**
These locations (“Market Bombchu Bowling Bombchus” and “Market Bombchu Bowling Bomb”) are never shuffled, so excluding them doesn't really make sense. (As far as I can tell, it will either do nothing or cause an error, depending on other settings.) This PR removes the tags from these locations, which removes them from the list of options for the “Excluded Locations” setting.

### CODE REVIEW

**Comment by r0bd0g** [comment]
You're supposed to be able to exclude these types of locations, which prevents them from being used as your logical source of refills, iirc. But maybe that's changed I dunno. (If you got an error, it could be because you disabled too many bombchu drop locations?)

**Comment by ETR-BTF** [comment]
> You're supposed to be able to exclude these types of locations, which prevents them from being used as your logical source of refills, iirc. But maybe that's changed I dunno. (If you got an error, it could be because you disabled too many bombchu drop locations?)

If this is the reason for why they are excludable, then I think it's a weird/confusing implementation of the feature.

**Comment by r0bd0g** [comment]
I'm not sure if it was ever changed or if it's supposed to still work that way or not.

**Comment by cjohnson57** [comment]
> You're supposed to be able to exclude these types of locations, which prevents them from being used as your logical source of refills, iirc. But maybe that's changed I dunno. (If you got an error, it could be because you disabled too many bombchu drop locations?)

I don't see any code for this anywhere in the project

**Review by cjohnson57 — APPROVED** [review]

**Pull request merged**
