### PR TITLE
Custom sorting the locations in the spoiler log

### PR DESCRIPTION
**Pull request by ETR-BTF**
Originally the order of locations in the log was based on the order they appeared in the logic files. Since this was not a sensible ordering I decided to reorder them in a manner I consider practical. They are ordered as follows:

1) Dungeon rewards and songs first.
2) Next, all locations are grouped by location (first overworld, then dungeons).
3) The overworld checks follow a route that is close to the intended vanilla route. Dungeons ditto, but with the mini-dungeons at the end.
4) Within a region the order is gift/freestanding/chest -> scrubs -> cows -> GS -> shops.
5) Within dungeons the order follows what I believe is considered the most common/optimal routing in glitchless settings.
6) In the overworld child checks come before adult checks, and they also follow "optimal" routing (e.g. for night kak skulls you don't go from the watchtower to the skull house to the skull near the DMT entrance).

This sorting is achieved by comparing the list of locations in Spoiler.py with a large list that has been custom sorted. There are undoubtedly more efficient and elegant ways of implementing this, which is why I am submitting this as a draft initially. My idea was to add a "sorting index" to the locations in LocationList.py, but this has the disadvantage of making reordering the locations later (e.g. if more locations are added) a drag. I would love to receive suggestions on how to proceed.

### CODE REVIEW

**Comment by ETR-BTF** [comment]
I also happily take suggestions on the order of the MQ checks. :) 
@r0bd0g

**Comment by ETR-BTF** [comment]
I also don't know if Spirit should come before or after Shadow and I'm too afraid to start that conversation. :P

**Comment by r0bd0g** [comment]
You know it's Shadow before Spirit don't act like you didn't try to pull a fast one. :p

**Comment by ETR-BTF** [comment]
The implementation is not exactly elegant yet but I'd like to see this become a feature before the next major release. A similar thing could be done for entrances.

**Comment by Zannick** [comment]
Yeah, this is not bad. Sorry I didn't look at this before--I see a quick optimization we could do to create a dictionary based on those values so `key` isn't calling `index`. I can take care of that after merge.

**Comment by Roman971** [comment]
Having a duplicated list of locations seems really unfortunate. Any chance we could figure out a solution that doesn't involve doing that?

**Comment by ETR-BTF** [comment]
I had the idea of adding a "sorting index" to every location in LocationList.py but I wanted to wait for feedback before implementing that, because the downside is it makes reordering checks later a drag.

**Comment by Zannick** [comment]
We could program the rules ETR-BTF used here to generate the list... to generate the list once at startup. Unfortunately we'd lose some of the routing info without being able to write an index in. Or we turn the LocationList dict into a list of tuples (with a dict generated from it), so that the ordering there corresponds to the ordering in the spoiler, but that would be a different kind of mess.

**Comment by Zannick** [comment]
Actually, I think that would be the best option. Something like:

```
_location_list = [
   ("Links Pocket",     "Boss", None, None, None, None),
   ("Queen Gohma", ...)
...
]
location_table = {
   t[0]: t[1:]
   for t in enumerate(_location_list)
}
# just the sort index
location_sort_order = {
    t[0]: i
    for i, t in enumerate(_location_list)
}
```

**Comment by Roman971** [comment]
I _think_ we could use an OrderedDict in that case.

**Comment by Zannick** [comment]
Yes, we can construct location_table directly as an OrderedDict, then iterate over that to create the cached location_sort_order. We can't extract the index directly from the OrderedDict, hence the extra step.

**Comment by Zannick** [comment]
I'll work on this unless @ETR-BTF is interested?

**Comment by ETR-BTF** [comment]
Go for it. I wouldn't be able to finish this any time soon anyway. Sorry I couldn't do more.

**Comment by Zannick** [comment]
Thanks for initiating this change! This'll be a lot easier to manage in the future if anyone wants to reorder locations.

**Pull request closed without merging**
