### PR TITLE
Thieves' Hideout entrance shuffle, take 2

### PR DESCRIPTION
**Pull request by fenhl**
Based on #1108 but updated for latest Dev and with logic cleaned up a bit.

Must resolve before merging:

- [x] @r0bd0g said they may want to further rework the logic and it would make sense to do that here.
- [x] Being caught inside the hideout should place you at the most recently used entrance of the part of the hideout you're currently in. (fenhl#3)
- [x] Jail access probably needs to be made repeatable. Maybe add a dialog option to the Gerudo guards to throw you in jail even though you have the card? (fenhl#6)
    - [x] Logic needs to be updated to account for this.
- [x] There is a bug on this branch where if overworld ER is on but hideout ER is _off_, getting caught in the hideout without hookshot places you at GV rather than GF. (fenhl#5)
- [x] A decision needs to be reached on whether fenhl#7 should be merged.

Maybe/nice to have:

- [ ] The heart piece should probably either be removed or added into logic. (#1971)
- [x] The chest on the roof is still not reachable as child, but its contents should probably be made consistent across ages anyway, if they aren't already.
    * Already consistent according to shiroaeli.
- [ ] Interiors and grottos reachable from hideout interiors should have their savewarps changed to the hideout savewarp, to match the behavior of shuffled boss rooms. An exception should be made for the entrance near the savewarp to make it easier to build valid world layouts. Alternatively, the Beta Quest feature of holding a button while saving to set spawn to overworld spawn could be ported.

### CODE REVIEW

**Comment by r0bd0g** [comment]
I've only read through it. I still need to go in and take a look around. First impressions:
- I'm not convinced the two ledge jumps at fortress need to be separate tricks. The difficulty and knowledge requirements are quite similar? Maybe it should be a single trick for climbing the fortress from outside. The lower one is only going to be relevant when fortress ER is on anyway.
- It might be worth expanding on the tooltip for Thieves' Hideout "Kitchen" with No Additional Items. I think I forgot this a bit when going through pot shuffle. Certainly 'hover boots' aren't going to help you get to the crates in the room. 'Allows passing through the kitchen by avoiding being seen by the guards. Logically normally guarantees Bow or Hookshot to stun them from a distance, or Hover Boots to cross the room without needing to deal with the guards.' I dunno.
- Should we do something about that heartpiece? In theory it should be in logic for heart wincons. So that's why I feel like we ought to address it somehow but I dunno how. I think it should be removed actually. Can child get onto the rooftop from up here to get the Odd Mushroom?
- "GF Hall to Balcony Entrance": "can_use(Longshot)", # via jail ceiling -- I wasn't aware this was possible without clipping through the ceiling? Is there actually some line of sight to get up there, longshot a crate through a hole or something?
- "Hideout Kitchen Front": "Gerudo_Membership_Card or can_use(Bow) or logic_gerudo_kitchen" -- I'm definitely going to have to go in and take a look around though, and it'll still be a week or two before I get to that. I would have assumed though that stunning them with Hookshot would be okay. And some of these treks have maybe not been tested under the trick.
- Don't forget to update the tricks in hellmode preset.

**Comment by puddydoo** [comment]
Sorry i didn't notice this before making #1628...
This seems probably better, though I moved GF Storm Grotto to the normal Gerudo Fortress region since there was no need to distinguish it. I also renamed some of the regions and cut out the Southeast Roof region. These are all minor differences though and not really needed

**Comment by mracsys** [comment]
There is a bug in this with open fortress preventing access to Fortress locations and the GTG entrance. The card is placed at its vanilla location, which worked fine before as Hideout and Fortress were always connected, and the logic helper `can_finish_GerudoFortress` permitted the location to be reached with open fortress. The new logic for the Hideout Gerudo Membership Card check requires either Normal or Fast Fortress. To keep access open for checks locked by the card, it should be collected during item pool creation if Fortress is open.

For testing, the key rings unit tests for open fortress work well.

**Comment by fenhl** [comment]
I'll have to take a look at #1628 and what it does differently. The savewarp exits should probably stay since mixed pools boss rooms will need them as well, though they should probably be generated dynamically so that interiors connected to the hideout use its savewarp too.

**Comment by puddydoo** [comment]
True, the fact that it could be used for mixed pools boss rooms were part of the reason why i originally thought to put a savewarp field in the first place.

**Comment by fenhl** [comment]
> I'm not convinced the two ledge jumps at fortress need to be separate tricks.

Agreed. Merged the two tricks.

> It might be worth expanding on the tooltip for Thieves' Hideout "Kitchen" with No Additional Items.

Done.

> Should we do something about that heartpiece? […] I worry about the odd mushroom chest.

There's a chest with an odd mushroom in it? If that's reachable now, it definitely needs to be removed to avoid softlocks via trade item reverts. And if we're removing that, it might make sense to just remove the heart piece as well.

> I worry also about non-repeatable access to the ledge to the break room.

Any suggestions on what to do here? For the Water temple entrance, a way to go back to the previous state was added in form of the water level gossip stone. Maybe we could add a way to ask the Gerudo to throw you in jail?

> Don't forget to update the tricks in hellmode preset.

Done, thanks for the reminder. We should really get CI set up for stuff like this.

**Comment by r0bd0g** [comment]
As child the GF chest has a mushroom. I'm not sure if it still has a mushroom in rando. Honestly might be time to make that chest have the same contents as both ages regardless of whether or not it's reachable as child.

Yeah honestly maybe the guards at fortress should be like "hey you want to be thrown in jail for old times sake? no, yes." lol. Maybe that would be less intrusive than, idk, adding a hookshot target so you can just hookshot up there directly.

**Comment by r0bd0g** [comment]
"Interiors and grottos reachable from hideout interiors should have their savewarps changed to the hideout savewarp, to match the behavior of shuffled boss rooms. An exception should be made for the entrance near the savewarp to make it easier to build valid world layouts."
Could this lead to a problem where there's no way to escape fortress? Logic assumes a respawn back to default spawn is always possible. Actually you might have that problem already if you savewarp to hideout 1, and then both exits of that go to another area that you can't savewarp to spawn from. So you have to ensure one side of hideout 1 exits to OW, or you have to add some way to savewarp back to main spawn on any savewarp (this is already a feature in BQ I think).

**Comment by r0bd0g** [comment]
Exits from the Gerudo Fortress balcony are not complete. These are the only actual bugs that I noticed.
- You can go back into the hall to balcony upper, yes, but your access to hall to balcony entrance is "True" but actually it requires you to backflip over a railing and take fall damage. So you would need a way to survive the damage with Nayru's or Fairy, or you could avoid damage if you have the Hookshot, by falling down into the jail, hookshotting up, and jumping over from there. You can also do a precise jumpslash recoil to get onto the ledge that you would hookshot up to inside the jail. But this would be a trick just to avoid damage in OHKO, which we normally don't add.
- This means you will need a new access from Balcony into Gerudo Fortress proper, True, as the normal ground down there has a property to not take fall damage when landed on from height.
- And lastly you can easily Longshot directly to the chest, so you'll need to add an exit for that. (This longshot use can be done from the ledge inside the jail as well but it's too precise not to be a trick. And if you have longshot then it will be easily obsoleted by the trick to jump up the fortress from outside.)

You may be able to cut the distinction between GF Kitchen Roof Access and GF Southeast Roof. There's a jump child can use to get up there, and while it would need to be a trick, it doesn't matter because child can't actually do anything up there. And everything up on the roof is already confirming that you're adult. So maybe it's easier just to 'let child do the trick jump by default' and then confirm you're an adult for everything you can do up there (which we already do).

There's a trick you can do to get from the ledge below the skulltula (rooftop region) over to the hall to balcony, with nothing. Target the wall to the left up of the skulltula near the edge while holding ESS left. Buffer one frame full left and then roll next frame to jump. At some point in the jump you gotta switch a bit forward to grab ledge. Adult only. Up to you if you want to add this now or not.

After playing it I guess I can agree that hookshot is a bit too much from going hallway to upper kitchen. It's not that bad honestly to just do this room with nothing at all as adult. You can usually sneak up behind and slash. But we're being nice I guess; there are a lot of guards in here pretty close together. And hookshot requires you to get pretty close to use. But I think longshot should actually be safe. The extra distance allows you to get them while they're standing still from far enough away that there's no risk of being spotted. Longshot was WotH for passing gerudo cards, clearly. You can use longshot to do a completely safe upper kitchen down to the hallway as well, but it makes asks for a little too much strategy idk? I would stun the two guards in the kitchen and then take out the one near the rear, then return to safety. Then get the one closer to the front while she's not in sight of the hallway. Then the one in the hallway you can stun looking down the hallway from the other side of the room.

It wasn't pretty but I confirmed the rest of the treks that I hadn't done before under logic gerudo kitchen. The hardest was rear to hallway as child with nothing since you have to run past all three of them at once while their backs are turned.

I guess that's all I have to say about the logic.

**Comment by fenhl** [comment]
> Could this lead to a problem where there's no way to escape fortress?

That is why I think there should be an exception for the front entrance of the 1 torch jail. Planning ahead for mixed pools bosses and true mixed pools, we want it to be possible for dungeons to be inside other dungeons, but we also want overworld savewarp to be accessible without items from all other savewarps. Allowing transitive overworld savewarp access would fulfill both criteria. For example, if the Deku to Gohma is the Fire temple entrance, and exiting Deku is a house, savewarping in the house should put you at overworld spawn, and the randomizer should recognize that since exiting Fire and savewarping puts you near the Deku exit, Fire has overworld savewarp access.

> Whether or not you want to add that now is up to you.

I'm not the right person to ask about tricks. Will defer to what others think.

Your logic comments all make sense to me. Do you want to send a PR fixing the logic or should I make the changes?

**Comment by r0bd0g** [comment]
I think the BQ overworld savewarp failsafe was something like "hold L+R while you save to save to initial spawn instead" but I don't remember exactly. Such a feature could absolve us of having to make sure there's always OW spawn access, and maybe players would like being able to quickly get out of Ganon's Tower or whatever. I prefer having to think about exiting dungeons to savewarp, but if it gets in the way of certain OW configurations... Or maybe it could be optional.

The logic changes are all pretty straight-forward, so I'll leave it to you. But I think more complicated changed going forward I'm gonna start PRing them b/c it can sometimes be hard to communicate exactly what you want. And you still have some decisions to make regarding longshotting guards and such.

**Comment by cjohnson57** [comment]
> The heart piece should probably either be removed or added into logic.

This could be something on there with @SlyryD's setting

**Comment by r0bd0g** [comment]
I don't know that that really fits since the poh is there and works just fine currently.

**Comment by SlyryD** [comment]
> > The heart piece should probably either be removed or added into logic.
> 
> This could be something on there with @SlyryD's setting

The heart piece is there in vanilla, seems fine to me. Note that you can't pick it up until the Gerudo Fortress text is gone.

**Comment by r0bd0g** [comment]
Not being able to pick something up until the text is gone goes for everything. For example the magic jar refills in the entrance of MQ Fire are annoying b/c you always have to wait.

**Comment by fenhl** [comment]
From @Hamsda:

> to clarify this bug once and for all:
> \- mracsys Dev-M
> \- no hookshot
> \- overworld ER is on
> \- hideout shuffle is off
>
> the exterior GF guards will correctly put you at the GF from GV entrance
> but the interior guards will revert back to non overworld ER behavior and throw you into GV near tent

So that's something that needs to be fixed too. @mracsys could you take a look? I wasn't able to spot the issue from a quick glance at the asm changes.

**Comment by fenhl** [comment]
@mracsys has opened fenhl#7 which changes savewarping in shuffled hideout to use the overworld spawn. I'm not convinced this is a good idea. Please discuss on that PR's thread.

**Comment by r0bd0g** [comment]
You can stun first break room guard with stick or sword? Child link is too short to be seen by the guard staring at the table, so you can freely go for the crates.

**Comment by Roman971** [comment]
I think shuffling hideout entrances should be part of the shuffle interior setting, probably as a new level with all interiors + hideout, since that would be simpler UX-wise and more consistent with how we currently handle special interiors and ganon's castle.

**Comment by r0bd0g** [comment]
After thinking about it some more I think hookshot is probably fine for stunning the guards for all treks through the kitchen. I copied most of the logic here and pasted it in for pots since breaking those checks up by the interiors they're in seemed like a good idea. I fixed the remaining logic bugs there that I mentioned here.

**Comment by r0bd0g** [comment]
I glanced over and have no real reason to expect the logic to have any issues.

The only real things I still have questions about are unchecked up in the main description.
I think something probably has to be figured out with 37th PoH though? I don't agree that it's only 'nice to have'. I suggest just removing it if hideout ER is on.

**Comment by cjohnson57** [comment]
After considering it I agree with Fenhl regarding not changing the savewarp behavior. It is some obscure and unintuitive behavior, but it's mentioned in the setting description and the benefits it gives are worth it imo

**Review by cjohnson57 — APPROVED** [review]

**Pull request merged**
