### PR TITLE
Split pause menu dungeon info into 3 menus and include total small key count

### PR DESCRIPTION
**Pull request by fenhl**
The total number of small keys collected for a dungeon is included in the dungeon info the randomizer displays on the inventory screen of the pause menu. Unlike the existing “current small keys” count, this new number does not decrease when a key is used on a door. The counts are displayed as `current(total)`, e.g. `2(3)` means you've found 3 keys for this dungeon but have already used one of them so you have 2 remaining.

The number of collected small keys is stored in the unused field of the dungeon's scene flags. If this PR is merged at the same time as #1535, those docs should be updated to reflect this.

~~This number is also displayed in the get item text boxes for small keys. Since I don't know how to add a new dynamic text component similar to the vanilla one that displays skull count, I had to add 61 different textboxes for these messages. This implementation may have to be revisited in the future, since it seems we're almost out of text boxes. I also had to change small keys to be capped at their maximum number, which can spoil whether a dungeon is MQ in plentiful if you find all its keys including the spare key.~~ This change was reverted for now due to #1572.

To reduce clutter and avoid potential issues with overscan mentioned in #1508, the dungeon info screen is split into 3 screens, activated using the D-pad instead of A:

* D-down displays dungeon rewards (now including the free one)
* D-right displays current and total small keys, boss keys, and the Gerudo card
* D-left displays maps, compasses, the skulltulas clear indicator, and MQ status

Splitting dungeon rewards from the remaining info also prepares for potential future features that would require this, namely mixed pools boss shuffle and dungeon reward shuffle.

The existing feature to equip or unequip boots using the D-pad is disabled on the inventory screen. It can still be used on the other 3 screens, while moving between screens, or while the animations of the pause menu opening or closing play.

The D-pad icon on the HUD has been fixed to not disappear when paused, and a minor inconsistency with the fade-in and fade-out animations has been fixed. On the inventory screen, it displays icons indicating the different dungeon info displays: The Zora sapphire on D-down, a small key on D-right, and a map on D-left. This makes these menus more discoverable.

# Screenshots
image

D-down:
image

D-right:
image

D-left:
image

### CODE REVIEW

**Comment by ETR-BTF** [comment]
How important the key/mq information is depends on which dungeons are required. So I think it'd be nicer to have the dungeon rewards info on all screens. The first screen would then also no longer be necessary (for now). If the first screen is kept, then it might be informative to add the free dungeon reward to that screen as well.

**Comment by fenhl** [comment]
I can see how that could be useful, but leaving it out has the benefits of being less redundant, working better with features I think are likely to be added in the future, and keeping more horizontal space on D-right available for silver rupee shuffle. Adding the free dungeon reward makes sense though.

**Comment by fenhl** [comment]
I managed to get key counts in item get text boxes to work by simply adding a separate text box for each one.

**Comment by ETR-BTF** [comment]
I quite like how you fixed the order of the dungeon rewards. It speeds up marking them on your tracker because you just have to remember the order of dungeons (words) and not the order of dungeon rewards (images). For _my_ brain that's easier and faster at least.

**Comment by fenhl** [comment]
The patch to change the get item text box based on the number of keys collected currently doesn't apply to keys collected from gold skulltulas, because they use a separate code path. Need to figure out how to apply the patch there as well.

**Comment by fenhl** [comment]
Looks like the amount of extra text already causes gen failures in some situations. Marking as draft until that's resolved.

**Comment by fenhl** [comment]
Reverted the addition of extra text boxes. They can be added separately after #1572 is fixed.

**Comment by r0bd0g** [comment]
I don't like something about the way the dpad icons flash between icons while paused.

**Comment by mracsys** [comment]
Was overscan a problem with keeping the key counts and other info on one screen? I liked having it all in one place. I also preferred the dungeon order staying fixed instead of the dungeon rewards since the tracker I use cycles through rewards for a dungeon instead of the reverse.

**Comment by fenhl** [comment]
Yes, there are already minor issues with overscan without this PR.

The order being changed is one of those things that will have to be done anyway once mixed pools boss shuffle (or medallion shuffle) happens, so I figured it would be better to make the change now rather than potentially having the layout change in 2 successive versions.

**Review by cjohnson57 — APPROVED** [review]

**Pull request merged**
