### PR TITLE
Remove assumptions about Links Age and Locality from Dungeons

### PR DESCRIPTION
**Pull request by rattus128**
Remove assumptions about what age Link is when in a dungeon. This puts all wrong age dips into logic, preparing for entrance rando.

Spirit has new exit for the hands to handle non-colossus placement.

The DC patch is not strictly needed, just a minor refactor. Individual commit messages have more information.

Vanilla only, MQ is a TBD.

Regression tested with 5000 all sanity seeds

### CODE REVIEW

**Comment by r0bd0g** [comment]
I talked with rattus128 and the exit from spirit hands needs a bit of a fix.

**Comment by r0bd0g** [comment]
So the exit from the Spirit Hands isn't quite right. You can leave on 3 keys+explosives, or 5 keys. You don't need to check if you're child or adult or not. But once you leave like that you won't necessarily know what age you are, so you can only apply it to reaching goals that can be done as either age, which right now is only the nayru fairy, but that might extend out to the wasteland soon.

The Forest Temple Babas say "Kokiri Forest", not that it matters. Should the logic on these really be true? It's true if you're an adult, but as child? And isn't there one in both NE and NW?

I don't see here where you've changed Buy Hylian Shield to a progression item? It may have been done before somewhere I didn't look at it yet.

Is jumpslashing the vines GS in Deku easier as adult? If it's quite a lot easier then maybe it could be in default logic. The jumpslash with sticks currently as child was already right on the bubble.

Really, din's can't kill a bubble in the forest temple? Why not man, this game is weird.

**Comment by rattus128** [comment]
All fixed.

Added that colossus fairy case.

Fixed the babas region def.

Progressioned Hylian shield.

The JS is a similar level of difficulty to child stick from experiments.

Bubbles are completely immune to Dins in both flaming and hopping states.

**Comment by r0bd0g** [comment]
Thinking about it more, I think the babas in forest should be moved into the first room. If you can beat forest, then you can reach the babas no matter where they are, but this way they're logically the same as the babas in kokiri forest, just need to make sure you can reach forest.

**Comment by rattus128** [comment]
Yes that makes  a lot of sense for consistency. I use NE cause NW is
covered by true on adult,  and MQ has the two eye shoots for symmetry. But
first room with a comment probably cleaner than all that.

**Comment by r0bd0g** [comment]
The logic on those babas can't be true though. It should probably be full logic to kill them I guess.

**Comment by rattus128** [comment]
I went for the simpler "is_adult". Child will always have the KF babas, and
this is really about the KF babas for adult rather than the actual Forest
temple babas.

Thanks as always

**Comment by r0bd0g** [comment]
The only weird thing about that is that it could show adult getting sticks from forest temple in the playthrough when the courtyards aren't actually reachable. It should function correctly, but idk, minor detail in the spoiler. It's fine I mean it works like this...

**Pull request merged**
