### PR TITLE
Add Tricks, "Final" Batch

### PR DESCRIPTION
**Pull request by r0bd0g**
Changes:
1. In the invisible blades room of Shadow Temple, you can backflip or jumpslash off of the chest to collect the token.
- I considered making a trick, but decided that this was easy and obvious enough for default logic.
2. I needed to move the path to crater GS into the summit region, so I decided to move the cow grotto into that region as well.
- Pretty unnecessary change, I guess. >_>
3. Modified guarantee_trade_path to include the Bolero of Fire route.
- While adding that a trade path could be guaranteed with reverse wasteland, I noticed the bolero route was not included.
4. I backspaced the word "very" from the tooltip for the new Dampe 2 as child trick.
- I reserve the word very only for the veryest of verys. >_>

Added Tricks:
1. Shadow Trial MQ Torch with Bow
2. Death Mountain Trail Upper Red Rock GS without Hammer
3. Death Mountain Trail Lower Red Rock GS without Hammer
4. Spirit Temple Lower Adult Switch with Bombs
5. Goron City Spinning Pot PoH with Bombchu
6. Fire Temple East Tower without Scarecrow's Song
7. Bottom of the Well Cage GS without Boomerang
8. Forest Temple MQ Twisted Hallway Switch with Hookshot
9. Dodongo's Cavern Child Slingshot Skips
10. Reverse Wasteland
11. Forest Temple Outside Backdoor without Hover Boots
12. Dodongo's Cavern MQ Early Bomb Bag Area as Child
13. Water Temple Central Bow Target without Longshot or Hover Boots

### CODE REVIEW

**Comment by dragonbane0** [comment]
Some of these tooltips seem very long, which won't look nice without manually inserted <br> line breaks. Please test whether they look okay on a small GUI window size first and add line breaks where necessary. Otherwise you risk the tooltip bleeding over the window edge and get cut off

**Comment by r0bd0g** [comment]
Except Reverse Wasteland, most of the longest ones are from before the new GUI. What's the difference between <br> line breaks and the line breaks that are there now? I tried to shrink the size of the window down, but the resulting size still seemed quite large? All of the tooltips seemed fine to me at that size, but is there a way to make the window even smaller so I can test that?

**Comment by dragonbane0** [comment]
@r0bd0g Nevermind lol. I didn't know TR transforms the traditional /n line breaks to HTML <br> tags during parsing to JSON. You are all good then!

**Comment by r0bd0g** [comment]
Ah, yeah, that makes sense. :)

**Pull request merged**
