### PR TITLE
Make various shuffle X settings consistent with plentiful item pool

### PR DESCRIPTION
**Pull request by matthewkirby**
Currently, plentiful item pool adds the following extra items to the item pool.
```
easy_items = ([
    'Biggoron Sword',
    'Kokiri Sword',
    'Boomerang',
    'Lens of Truth',
    'Hammer',
    'Iron Boots',
    'Goron Tunic',
    'Zora Tunic',
    'Hover Boots',
    'Mirror Shield',
    'Fire Arrows',
    'Light Arrows',
    'Dins Fire',
    'Progressive Hookshot',
    'Progressive Strength Upgrade',
    'Progressive Scale',
    'Progressive Wallet',
    'Magic Meter',
    'Deku Stick Capacity', 
    'Deku Nut Capacity', 
    'Bow', 
    'Slingshot', 
    'Bomb Bag',
    'Double Defense']
```
It also adds an extra Ruto's Letter, changes the heart pieces to heart containers, and gives extra triforce pieces.

However, plentiful item pool is inconsistent with major items in other shuffled settings.

- [x] Songsanity
- [x] Shuffled Ocarina
- [x] Shuffled Gerudo Card
- [x] Shuffled Magic Beans
- [x] Small Keysanity (Dungeons)
- [x] Small Keysanity (Gerudo Fortress)
- [x] Boss Keysanity
- [x] Ganon Boss Keysanity

Future Work
- ~~Shuffled Weird Egg~~
- Adult Trade Item
- Gold Skulltula Tokens with GST Bridge and Skullsanity

In this PR, plentiful item pool now accounts for the above items when the respective settings are enabled. 
- Each singleton item has a single extra copy added to the item pool. 
- Small keys have one extra key added to the item pool

### CODE REVIEW

**Comment by Cuphat** [comment]
Most of these should be straightforward. Just note that Weird Egg will need some light work in the C code, somewhat similar to what I did for Ruto's Letter but a bit simpler. Basically just make sure it doesn't actually overwrite the child trade slot if something is already there.

**Comment by r0bd0g** [comment]
Do you have enough space to fit all these extra items? Try shuffling everything and turning on 1 major item per dungeon.

**Comment by matthewkirby** [comment]
I can tell you right away that that answer is no. Just do the same with the current master branch and triforce hunt can break one major item.

**Comment by r0bd0g** [comment]
Maybe the tooltip then of 1 major should mention that it can be incompatible with some settings idk.

**Comment by flagrama** [comment]
Request that you remove the code in plando that expects Weird Egg to be a unique item as well after latest commit. Just so I don't have to change it myself later :sweat_smile:

**Comment by flagrama** [comment]
This too https://github.com/TestRunnerSRL/OoT-Randomizer/blob/9846b9fd4b313196c8f0d9357fc44b63549e5f05/Plandomizer.py#L591

**Comment by matthewkirby** [comment]
Oh, whoops. I thought you were just watching for the exception. I also just realized that I didn't include the adult trade item.

**Comment by flagrama** [comment]
> Oh, whoops. I thought you were just watching for the exception. I also just realized that I didn't include the adult trade item.

I removed that comment because I forgot what that code was doing was making sure that those items weren't duplicated outside of user control, so that line is still fine. But do remove the exception for adult trade quest too if you throw that into the plentiful item pool.

**Comment by matthewkirby** [comment]
dotzo pointed out in discord that this Weird Egg change can result in a softlock if a player obtains Zelda's Letter before the Weird Egg. I still think that a duplicate weird egg should be available (songs seemed to be the biggest offender with plentiful) but will need another way of handling this. I am going to remove it from this PR and open another one once I have a way around this.

**Comment by matthewkirby** [comment]
It took me a little longer than I would have liked to get back to this. But it should be ready. I pulled out the Weird Egg code due to concerns raised in discord. My solution was that when you picked up the Weird Egg, check to see if there is an item in the child trade slot. If the slot is empty, award the Weird Egg, otherwise don't do anything. Unfortunately, this could result in a soft lock if a player obtained Zelda's Letter before the Weird Egg.

**Pull request merged**
