### PR TITLE
Bingo hint bug fixes

### PR DESCRIPTION
**Pull request by DobbyDigital**
This PR fixes some minor bugs  with bingo hint generation. 

In the previous iteration, even while specifying that no always hints should appear, the conditional always hints would still be included. The fix here changes the number of copies in the hint distribution for always and trial hints to 0, which ensures that no always hints (conditional or otherwise) are place. **Warning: This PR relies on the fix that mracsys put in his PR (#1163). Without that, some combinations of settings, item placement, and goals result in the seed generation failing.**

In addition, the set of hint distributions which prevent the bingosync_URL field from appearing in the GUI was hardcoded, so any user-added distributions would cause the field to appear. The fix for this is very much gross to read, and I think dragonbane was working on a more intuitive system for disable that would simplify this significantly.

### CODE REVIEW

**Comment by Cuphat** [comment]
You should probably merge Dev into this branch now and let the changes from Dev overwrite your Bingosync URL disable hack as #1154 has been merged to take care of that.

**Comment by Zannick** [comment]
At this point, I've already taken care of the Dev merge.

**Comment by DobbyDigital** [comment]
I appreciate it; Github Desktop was being weird on my end and not letting me do it

**Comment by DobbyDigital** [comment]
Okay, fixed all the merge conflicts. I just need to do testing then it should be good to go

**Comment by Zannick** [comment]
Ah, sorry, I meant I already merged the changes from this PR locally into Dev and taken care of the merge conflicts. Just going to do more PR merging before I push to Dev to actually close the PR.

**Comment by DobbyDigital** [comment]
Oh cool, that works too!

**Pull request closed without merging**
