### PR TITLE
Remove frustrating RNG elements from Fishing

### PR DESCRIPTION
**Pull request by Roman971**
Fishing can be very frustrating if you are unlucky so I think it would be a good idea to make it a bit more player-friendly with the following changes:
- Prevent fishes from randomly getting off the hook in any way. With this, the only ways left for a fish to get away is if you deliberately want to lose it by either not setting the hook or by stopping to reel for a few seconds.
- Change fish behavior to make it bite the hook quickly once you stop moving and the hook is stable. Fishes can still bite randomly as soon as they are in range, just like before, but this should ensure the player doesn't have to wait for a very long time if he is unlucky.

Both changes are independent so we can also decide to keep only one of them depending on what people feel about this. I personally think the first change is the most important one and should be at least be considered.

### CODE REVIEW

**Comment by r0bd0g** [comment]
Wasn't fishing nerfed already?
I still kind of wish all the changes to fishing were a speedup option, so that who like pain can disable it.

**Comment by TestRunnerSRL** [comment]
Dunno about the second part, but the first seems ok? I usually just disable fishing so I kinda would like some second input on how much of a problem this actually fixes

**Comment by Nicholas-Steel** [comment]
The first option would also resolve the long standing issue of fish detaching from the hook right away when using Bizhawk for a long period of time without any hard resets.

**Comment by Roman971** [comment]
Fishing can make you lose up to multiple minutes if you are unlucky. This is often seen during races and usually results in a very unfair time loss for some players.

The main reasons this can happen is if the fish doesn't bite for a very long time or if the fish keeps getting away before you can reel him all the way in. Both those problems are entirely dependent on RNG and they can easily add up to multiple minutes with no way for even the best players to prevent it.

Just take a look at what happened to Marco during the recent Marco vs WTHH race in the Accessible Tournament Winner's Final: https://www.twitch.tv/videos/424860041?t=01h03m27s

**Comment by Roman971** [comment]
Rebased and split the changes in 2 separate commits so the first one can be picked separately if needed.

**Comment by flagrama** [comment]
I was against this at first because it seems to be removing gameplay for no real reason, though I also know random elements that cause immediate failure are annoying. At the same time I never have significant issue with catching fish.

I would like to know what exactly the conditions for losing a fish are normally though. Is it actually random, or are there certain actions a player has to do that causes some of them?

> The first option would also resolve the long standing issue of fish detaching from the hook right away when using Bizhawk for a long period of time without any hard resets.

Have you actually tested this? It could fix it, but it may also just be an emulator bug that could supersede this fix.

**Comment by Roman971** [comment]
There are quite a few ways to lose a fish. One of them is completely random based on a small RNG roll over time. The other ways are based on inputs and what the fish is doing compared to the line, which partially depends on RNG since the fish movement and behavior is mostly random. All those fish loss cases are removed in my changes.

The only cases left are based solely on inputs: if you don't set the hook within the first few frames after the fish bites, or if you completely stop reeling for a while. Those could be removed as well but I chose to keep them in so players can still lose the fish if they want to, for example if the wrong fish ended up biting.

I'm not sure if the BizHawk issue is one of the cases I left in or not, but chances are it might be prevented as well, although that was never part of my intentions.

**Comment by r0bd0g** [comment]
"The other ways are based on inputs and what the fish is doing compared to the line"
Not really related to this PR but it would be helpful if you could explain the mechanics of this b/c everything everybody has ever said has sounded like placebo to me.

**Comment by Roman971** [comment]
Okay so I investigated all the fish loss cases extensively and it looks like the 5 non-RNG cases are as followed:
- Failing to set the hook within the first few frames (couldn't find the exact number in code).
- Stopping to reel for over 5 seconds (100 frames).
- Having the fish hooked for over 5 minutes (6000 frames, yes).
- This one is weird and I couldn't test it, but theoretically: having some dmadata address not set to a certain value and having the fish hooked for over ~2.5 seconds (51 frames). Not really sure what's going on there but I think this might just be the cause of the BizHawk issue.
- Another weird case which is probably irrelevant from what I can tell, and seems to be there as a failsafe: having a wrong "fishing state" value (so not being in the "hooked" state). That case should normally not be encountered since it can only happen when the fish loss routine is run, which should only be the case when you are in the "hooked" fishing state.

The only other case is the RNG roll I mentioned previously, so it looks like there is indeed no situation where fish behavior and inputs can make you lose a fish, I misinterpreted some of the cases in my original investigation since I didn't look into the exact conditions.

For reference, my changes in this PR keep the first 2 cases and remove all the other ones, but it looks like only skipping the RNG case should actually matter, except maybe that one other case which seems related to the BizHawk issue.

**Comment by mzxrules** [comment]
what address is the code relevant to the "dmadata" check?

**Comment by TestRunnerSRL** [comment]
Can we get a confirmation if this indeed fixes Bizhawk's behavior? As for RNG, I actually how LTTP does it, which is probably kinda hard to implement here. The way they handle RNG for these kinds of things is that they RNG is the "same" for everyone in that seed. But with the fishing being pretty complex and not just some coin flips, I'm not sure how to best imcorporate that without basically writing a totally new randomness for this, which would be pretty awkward (like fixed total distances/time that the fish drops). So I would kinda assume that removing RNG is something the racing community would approve of, but it would be nice to get some confirmation from some of the racers on that opinion.

**Comment by LostThePirate** [comment]
As far as I know, this has *nothing* to do with the "Bizhawk fishing bug" which is entirely caused by Bizhawk failing to properly emulate a Soft Reset. If players only Hard Reset (which has *exactly the same end-user effect besides this bug*), they will never encounter the fishing bug.

As for removing RNG, I was unaware that there even was any RNG involved in fishing, so this feels to me like solving a problem that doesn't exist. I'm probably mistaken about the RNG, since you've found a way to influence it, but as a player, I've never felt like there was any RNG involved in the fishing minigame, so this feels really unnecessary to me.

**Comment by r0bd0g** [comment]
For me, whether the fish bites and whether the fish lets go has always felt like pure rng. Whenever someone would tell me, "oh you just gotta _______" it always sounded like placebo.

**Comment by Hamsda** [comment]
Yeah fishing is very much RNG and I don't think even the 100% runners fully understand fishing, seeing as there are many runs lost to it.

Imo the fish immediately biting when you hold the lure still is not needed. In 90%+ of cases, you can get a fish to bite while he is close to you.
The fish randomly letting go while you pull him in (and in the worst case completely swimming away so you have to go to another fish), is very frustrating and can cost minutes.

**Comment by Roman971** [comment]
@mzxrules The "dmadata" address in question is 0x800088A0, but I don't even know what part of the memory that's supposed to be. I thought it was dmadata but apparently it's not? May be a boot address, I'm not sure, but you would probably know.
As far as I can tell, it's looked up by the fishing actor during initialization at 0x80A3514C which sets the 0x80A47EE4 byte differently depending on its value. The fish loss routine then looks up that byte at 0x80A3EC84 and skips the relevant fish loss case (fish hooked since 51 frames) if that byte is equal to 0.

**Comment by Hyxost** [comment]
You guys are not understanding this. THIS is what the community wants. It doesn’t matter if you disable fishing, don’t know that fishing has RNG, don’t like removing rng elements (?). This is the right thing to do for the sake of the game and it’s community. Thank you for reading and I hope to see this implemented soon.

**Comment by LostThePirate** [comment]
No, we're *debating* this to determine *if* this is what the community wants. You and all your friends wanting this is still only a drop in the bucket when talking about the playerbase for this game.

**Comment by Hyxost** [comment]
I’m sorry, but « debating to determine what the community wants » in github conversation is not the right way, let’s make a poll in the discord, where the whole community will be able to vote. Why not do that?

**Comment by Nicholas-Steel** [comment]
That's... what has already been determined on the discord afaik (at least TestRunner has told staff there to run a bunch of ideas by the community via discord)

**Pull request merged**
