### PR TITLE
Option for harder scrub shuffle added

### PR DESCRIPTION
**Pull request by BladefangFT**
Added an option to not reduce the prices for deku salescrubs, requiring more overall rupee farming

### CODE REVIEW

**Comment by Hamsda** [comment]
I added another option to make the prices for each of the scrubs random (10-99 rupees) and put all of the options into a combo box similar to shopsanity.

**Comment by TestRunnerSRL** [comment]
I'm thinking about this option still. There's some changes I'm making to it currently. The main problem is that the amount of money needed is kind of ridiculous, it's why it was reduced to 10 in the first place. currently you'll have random expecting to cost about 2000 rupees, and about 1290 for vanilla and 360 for low. I'm making sure that it's not phrased such that vanilla is the preferred option. I also am changing the random distribution to try to hit more around 1000, maybe lower.

Another thing, don't use rom.last_address, it's supposed to used only internally. Instead I'm going to change it to rom.read_int16(None)

**Comment by TestRunnerSRL** [comment]
Still not sold on it, but it's ok for now I guess

**Comment by Hamsda** [comment]
Yeah I realized when I looked at the blame that you added it in the same commit.
Is there like a convention for python to mark variables as private? I'm very much not a python programmer, so I wasn't sure if I could just use `last_address` outside of `rom.py`.

**Comment by TestRunnerSRL** [comment]
You could, but I was trying to use it like private. Python doesn't really have private. You can hide variables by doing some stuff with wrapping the calls that put the variable in a closure. But yeah, it's really just convention basically. Actually accessing `last_address` is actually ok, but I just wanted convention to be consistent in other places rom access is.

**Comment by flagrama** [comment]
python convention is `_this_is_a_protected_variable` and `__this_is_a_private_variable` but all using that protected/private variable convention will do is throw up linting warnings when you try to use them outside of that context. You can still use them without causing errors in the program.

**Comment by Hamsda** [comment]
Ah, yeah that would've been helpful, my linter would probably have some mean words for me then.

**Comment by TestRunnerSRL** [comment]
Ah ok, I wasn't aware of that. I'll keep that in mind in the future. I'm not really a python developer so I'm running with scissors.

**Pull request merged**
