### PR TITLE
 Add inventory/equipment/status icons to file menu, rev 2

### PR DESCRIPTION
**Pull request by rlbond86**
This PR adds inventory icons to the file menu. This is a rework of PR #985 and disables the file tab to create more space for icons. The icons show Link's inventory items, equipment, songs, status items, and counts of rupees, skulltula tokens, and Triforce pieces (if applicable). If Triforce hunt is not used, the icon instead shows whether Link has obtained the key to Ganon's Tower. The Master Sword icon is lit if Link is currently holding it.

### CODE REVIEW

**Comment by rlbond86** [comment]
Note: The "deaths" icon is hidden if the player hasn't died (visible in image #2). Two hearts are shown if the player has double defense (image #1).

[Patch file for testing](https://github.com/TestRunnerSRL/OoT-Randomizer/files/5475650/patch.zip)

**Comment by aofengen** [comment]
@rlbond86 github seems to have auto-linked to issues 1 and 2 in the previous comment - not sure if it matters, but may cause confusion latet

**Comment by aofengen** [comment]
As for the images themselves, they look great. I really like what you've done here.

**Comment by fig02** [comment]
huge fan of this, looks alot better than the last iteration.
Small nitpick, do you think its possible to resize the left side icons here and scooch them over to keep it in line with the buttons?
image

**Comment by fig02** [comment]
Im actually currently decompiling the whole overlay for file select, and I think its feasible to put a blue plate behind all of the icons so its not hanging out in the open, but I dont know if I could make that happen before we want to do a release

**Comment by rlbond86** [comment]
I can adjustment alignment tonight.

**Comment by fig02** [comment]
imo death count can also just be straight up omitted for the sake of a cleaner layout. Its a pretty useless piece of information, and it can go into credits stats whenever that becomes a thing.

Is the rutos letter icon intended to show open fountain? 
In my opinion, (and a few other rando dev's opinion fwiw) think that this should purely be an inventory display and nothing more. So if thats the case I think it should probably be removed. Even though its unfortunate, cause it would make that section of the display uneven lol.
But yea curious on your thoughts about that

**Comment by fig02** [comment]
The bottle icon in the top right can possibly be exclusively for the rutos letter item? Its really the only bottle that is important to track. Then remove the bigger one in the middle so that the display is solely for inventory and not about settings, Id say

**Comment by rlbond86** [comment]
The ruto letter shows that the fountain has been opened, either by showing the letter or by the Open Fountain setting. I think I added it for symmetry.

**Comment by fig02** [comment]
Gotcha. Yeah I think having a slightly uneven layout is better than adding an icon for something seemingly arbitrary and out of place from the purpose of everything else, which is just to show your current inventory.

We can maybe do like magic and strength on top (the most important of these 5) and the other 3 below?
image

**Comment by fig02** [comment]
or maybe move the triforce piece count over there? gives more room to align stuff on the left as well 
sdf

**Comment by ETR-BTF** [comment]
I would say move the skull count (or maybe even the rupee count) instead of the ganon boss key/triforce count. The icon for the win condition deserves to be big and not tucked away with the Stone of Agony. :P

**Comment by rlbond86** [comment]
Count icons won't fit, they need extra room for the numbers

**Comment by matthewkirby** [comment]
We super love this ui change over in rando rando. One of the things that would make it perfect for us is if all of the settings information was removed. It was mentioned above but it would also be fantastic if we could have the triforce piece removed from the menu as well (until you have your first piece).

**Comment by ETR-BTF** [comment]
I guess you could do wallets if you removed the rupee counter. I don't know if that's color-blind friendly tho.

**Comment by fig02** [comment]
yeah stone of agony isnt too important so it could possibly go.

On another topic, I mentioned earlier that the death count is useless, but cuphat made a good point that people who use OHKO might still like to keep it. I think its the kind of thing that fits more in credits stats, but we havent implemented that yet.

Im not a huge fan of its placement in the original image, but i dont have any better ideas at the moment :(

**Comment by rlbond86** [comment]
Glide64_THE_LEGEND_OF_ZELDA_06

I've updated the item positioning.

Since there's not really a consensus on which indicators to add/remove, I am leaving them as they are right now. The positions are pretty easy to modify by examining the code should changes need to be made.

**Comment by ETR-BTF** [comment]
I'm assuming the icons with counts cannot be shrunk because the counts have to remain legible?

I don't know how feasible (or desirable) this would be but since fig's currently decompiling the file select screen would it be possible to expand the window to create more space to work with?

**Comment by rlbond86** [comment]
Stuff could be moved to the right but it looked weird since the window is very dark there.

I'd prefer to get this in as is and then change positions when the decompile is finished

**Comment by fig02** [comment]
the decomp will be a long while. and the positioning of things/what gets shown is a deal breaker for a few of us.
we can continue the discussion in discord if its easier there, but yea I dont think we want to bring it in as is without ironing out a few changes

**Comment by fig02** [comment]
new alignment looks great though, thanks for that. 

The few things that are deal breakers at the moment are:
-triforce count should only be shown if count is > 0
-probably should not bother showing ganons key for when triforce hunt is off, it gives too much information about settings and isnt too important 
-rutos letter indicating fountain should be removed and that section of icons rearranged

the death count stuff isnt a big deal, so its really those 3 i think.

**Comment by fig02** [comment]
I have some ideas so I may checkout your branch and mess with it today. Ill post about it if so

**Comment by fig02** [comment]
@rlbond86 Made my changes, Ill pr them to your branch if we're all cool with them

changes made:
-open fountain icon removed
-stone of agony removed
-ganons boss key removed
-triforce pieces only show with 1 or more obtained
-death counter brought down next to quest status
-always show deaths
-magic/strength/scale/card reordered and moved right
-bottle icon only shows for rutos letter
-skulltula count is always on even if its 0
-medallions in line with the buttons

empty
full

**Comment by Hamsda** [comment]
Looks very nice and I don't think gives away any settings information for RSL (besides starting items obviously).
Hopefully this makes it in for 6.0, just gives it a lot more polished feel.
Credit stats in 7.0? Pog

**Comment by fig02** [comment]
submitted a pr

**Comment by ETR-BTF** [comment]
What happens to the letter icon if it's open fountain and the letter isn't in the item pool?

**Comment by fig02** [comment]
this display is purely about your inventory, nothing about settings. if you have open fountain you are aware that you wont be getting letter and can ignore the icon

**Comment by rlbond86** [comment]
I've updated to take some of @fig02's suggestions.

File with 0 deaths and 0 triforce pieces (either triforce hunt is disabled or no pieces are found yet):
Glide64_THE_LEGEND_OF_ZELDA_07

File with deaths and triforce pieces:
Glide64_THE_LEGEND_OF_ZELDA_08

The bottle with letter icon is completely removed now, as is Ganon's boss key.

The arrangement of icons is hopefully more aesthetically pleasing.

I rejected a few changes like the positioning of the death count.

**Comment by fig02** [comment]
medallion placement is very cool.
the death count off to the side is very out of place to me, I dont think theres much of an issue with what i had personally. and stone of agony is pretty useless overall and offers more symmetry by being removed, imo

**Comment by rlbond86** [comment]
I actually don't think removing the SoA increases symmetry, the three upgrade items (magic, strength, scale) really go together IMO. It's weird to split them up for one to join the Gerudo's Card.

The death placement is not my favorite, but it's not really an "item" so it doesn't feel like it belongs over next to your equipment to me. I'm open to suggestions though

**Comment by fig02** [comment]
its just as much a part of your quest status even if it doesnt go into your pause menu, i dunno i think its fine to group them together.

And I see your point about grouping the upgrades together, but I dont think you can really say that the 2 items on top of 3 has the same symmetry as 4 items in a square. The placement I chose in my rendition has magic and strength on top, which is the most relevant and important, with scale and card below which have some uses but are less important overall. And stone of agony is just kind of there

**Comment by fig02** [comment]
those differences aside, in my pr i spread out the equipment a bit to line up with the thing next to it and shifted the songs a bit to the right, I think itd be cool to include those here
fgdsfg

**Comment by fig02** [comment]
Im thinking we could maybe get things to be a bit more in line by putting a bit more space between the items above, but I havent tried it out yet

**Comment by rlbond86** [comment]
Perhaps this is more agreeable. Still hidden when deaths = 0.

Glide64_THE_LEGEND_OF_ZELDA_13

**Comment by rlbond86** [comment]
Your screenshot looks _less_ aligned to me. so I'm a bit confused.

**Comment by fig02** [comment]
We're looking at it from different perspectives I guess. I wasnt looking at it being in line with the items above it, just the grouping of the different squares of icons relative to each other.

I do like the new death count positioning. Do you think hiding when you dont have any is necessary? It fits pretty well down there and feels like thered be a hole there when you dont have any deaths

**Comment by fig02** [comment]
my intention of moving the songs to the right was to try to push these more in line. but maybe we can go the other way and spread the items out a bit more to stretch to be in line? I can do the experimenting to see what it looks like 
fgdsfg

**Comment by fig02** [comment]
Additionally if we leave the count always on, we can stretch the equipment to spread all the way down in line with it. the boots are a bit close to the tunics anyway imo and can benefit from a bit more space. just a thought 
lfgddf

**Comment by rlbond86** [comment]
I think it looks weird if the icons do not have the same amount of space between themselves. I at least aligned at half-tile increments in my version. To stretch some blocks by inserting additional empty vertical or horizontal pixels between tiles looks awful IMO

**Comment by rlbond86** [comment]
Regardless, I believe this discussion has gotten to the point of [bikeshedding](https://en.wiktionary.org/wiki/bikeshedding) so I'd prefer to stick to more substantive issues. Hopefully, all problems with RSL have now been resolved.

**Comment by fig02** [comment]
I mean, for a feature that is very visual based I think agreeing on alignment is a substantial issue. So i dont agree with you there.
I think the issues with rsl and alot of others has been resolved, which is great.

I do still think the death count should just stay on. It makes sense to hide triforce pieces because of the expressed concerns, but it seems more intuitive to see that you have 0 deaths instead of a missing icon

**Comment by rlbond86** [comment]
Perhaps other devs have an opinion?

**Comment by TreZc0** [comment]
Based on the latest revision, I am blasted by the functionality, but have a few suggestions for the layouting.
In general, the outer quader should be respected in my opinion (No 1 in the image). The items on the outer edge, be it at the top, the bottom, left, and right, should line up with end. I think the outer items should be directly on this line. Right now, with the padding, it adds a lot of unnatural jumps left and right. 

Same goes for the padding between the blocks of items, magic etc,, songs, and the death counter. (No 2 in the image)
Them not starting at the same point creates a lot of noise that doesn't warrant having the blocks more centered.

I think they should all start at the same point, right were the block of songs starts now. 
The focus on the right side and the end of the entire overview doesn't add nearly enough visual fidelity to make up for the noise created in the center I fear, which is the main focus of the player when opening the file.

Slide sidenote: Padding between swords, shields (especially noticable), tunics and boots is really low. This might work a little better with more padding, just like the 3 rows of items on top (both horizontally and vertically).
Given that we win a lot more space if we finish the items up with the imagined end line in my image (1).

layout

**Comment by Zannick** [comment]
I'm really happy you picked this back up, and I'm definitely a fan of the improved layout on the left-hand side. I'm a bit less comfortable with the spacing between groups of items on the right side, and being strictly right-aligned makes it look not-great on the left (as Trez said). Part of the trouble is that the song icons are an inconvenient fraction of the size of the other items. But also, without the guidelines from the pause screen, the padding to the left of the Kokiri Sword makes the padding above it stand out even more because KS doesn't use the full height of the icon space.

Since we have 49 items here we ought to be able to make a 7x7 arrangement with no new padding. Here's my crude paint suggestion: put swords and shields in one row, tunics and boots in one row, move magic, gauntlets, scale, and card to the side, and make song icons the same size as everything else (either by stretching or spacing them out--the pause screen has lots of space between them).
layout2
Also let's move the whole block back to the left as I think there's too much horizontal space between the medallions at the Deku Stick. Or increase the size or in-between spacing if you want to avoid having too much space left on the right.

Finally, some icons have some very slight cut-offs on the right or bottom side: medallions on the right, light arrows, beans, scales on the bottom. Is that from the original icon, or because we aren't drawing the whole thing? We should try to draw the whole icon, even if there's minor overlap in grid spacing.

It may be nitpicking, to spend so much time talking about alignment, but it's not bikeshedding to discuss that on a UI feature once we're happy with the major features and decisions (like what to show when).

**Comment by fig02** [comment]
I personally would prefer if we could make it work with the equipment in the same 3x4 rectangle as it shows in the pause menu, but def do see the benefits in putting them in rows as well

**Comment by Zannick** [comment]
Yeah, the trouble is finding a way to fit the other things into the space left by the 6x3 and the 3x4 rectangles taken straight from the pause screens. We could probably squeeze the songs into a 4x2 block as evidenced in prior updates, so that leaves... a 1x3 block (starting where the bottle is now) and a 4x2 block (starting below the hammer) to form a 7x7, but we only have 7 items to fit that space of 11, and that's too many for a 6x7. Well, we could add 3 more bottles and the Stone of Agony, I suppose. (But then we're still not putting the bottles and quest items in the same relative space as the pause screen either...)

Another alternative is to swap the shields and the tunics in my paint, so the swords are still above the shields and the tunics are still above the boots.

**Comment by rlbond86** [comment]
I'll have to look over this, but the right-side of the icons being cut off is not intentional but seems to be unavoidable when reducing their size. The same thing happens with the boots on the d-pad display thingy.

**Comment by ETR-BTF** [comment]
If magic/strength/scale/card are gonna be a column it might be nice to have the scale at the bottom and strength above it, as that's where they're positioned on the left column of the equipment screen.

**Comment by fig02** [comment]
This would be my ideal layout. I dont care too much for the hanging space on the right side that trez posted about, but I do like having all icons aligned on the left and that it starts right under the name.
This would be a compromise to keep things in line, but still keep the equipment layout out like we are used to seeing. I would also like to keep the death counter on all the time like I mentioned above, and in my layout it is in line with the bottom row of boots.
jdfsd

**Comment by fig02** [comment]
maybe the song icons could be scaled down a tiny bit in my layout to give it a little bit of breathing room, but yea

**Comment by fig02** [comment]
like this 
sdfg

**Comment by rlbond86** [comment]
> 
> 
> like this
> sdfg

That actually looks pretty good to me, other than a few slight pixel adjustments

**Comment by rlbond86** [comment]
Here's a different option... Add three bottles (not shown) and do a 6x4 box that matches the inventory screen. Then on the bottom do a 2x6 equipment, a 2x4 songs, and 2x2 misc.

It's a bit sparse on the right side compared to previous entries though. 
Glide64_THE_LEGEND_OF_ZELDA_01

**Comment by fig02** [comment]
second option is not bad at all.
I do heavily prefer keeping the equip section in the normal 3x4 if we can. And I think the first option gives the death count a more fitting and permanent place to live

**Comment by rlbond86** [comment]
Yeah i think your option with small notes is better. Let me tinker to try to get it 100% aligned

**Comment by fig02** [comment]
i can pr what I have currently. 
One subtle thing that I think helps alot is spacing the boots one extra unit down because the icon itself is much taller than the others. So even tho the tile spacing is technically not even, it puts an even amount of spacing between them.

**Comment by fig02** [comment]
Complete side note, but what are thoughts on hiding the rando hash when the select file screen is open? Now that we have all of the items on screen it can look pretty busy to have the hash there as well. It might be nice to have it only show on the other screens

**Comment by fig02** [comment]
eh nvm its pretty far removed from the rest of it

**Comment by Zannick** [comment]
> I'll have to look over this, but the right-side of the icons being cut off is not intentional but seems to be unavoidable when reducing their size. The same thing happens with the boots on the d-pad display thingy.

If it's an existing issue we can look into it another time. Thanks.

**Comment by rlbond86** [comment]
I've made some slight adjustments to position but overall I like this layout a lot.

Glide64_THE_LEGEND_OF_ZELDA_04

**Comment by fig02** [comment]
Ah yea the new dimming is a nice touch :D 

do you think the songs could come over a few units to the right? with them smaller notes I think it has a perfect little box to sit just under the 4 items above.
Huge fan of how this is turning out tho, very clean
kdjfsd

**Comment by rlbond86** [comment]
I thought people wanted it lined up on the left side 😳😳😳

**Comment by fig02** [comment]
I mean yea, but the way the notes sit in its tile it sticks out to the left a bit, and with the new note size theres alot of space on the right between the notes and the equipment :D

this is 2 units shifted, what do you think
kjhdfgdf

**Comment by Zannick** [comment]
Well, not left-aligned purely so. Centered or justified (aligned both left and right) is usually better here, and fig's is a bit more centered.

**Comment by fig02** [comment]
yeah, the left alignment was specifically about the left side of the different chunks of items as they were a bit staggered before. And with the new size I think it looks a bit mroe in place when its shifted just under the stuff thats above it.

After that tho this is perfect imo and ready to go

**Comment by rlbond86** [comment]
Ok, open another PR and I can approve remotely

**Comment by fig02** [comment]
done

**Comment by rlbond86** [comment]
Merged

**Comment by fig02** [comment]
Looks beautiful :') Thanks for working with us on this. Im sure people will love it.

**Review by fig02 — APPROVED** [review]

**Comment by Cuphat** [comment]
Yeah, looks really good to me. 👍

**Comment by r0bd0g** [comment]
Why was stone of agony removed? It's actually a very important item particularly with stone of agony hints, but also the hidden grotto trick disabled.

**Comment by fig02** [comment]
best item is a bit of a stretch imo. for the sake of a better layout it was worth dropping. the information is still available in the pause menu for the few that still want that information

**Comment by r0bd0g** [comment]
Its spot on the menu is actually pretty hard to notice. You're probably more likely to realize you have it by the icon showing up when you walk near a secret.

Maybe you could put SoA around where magic currently is and squeeze magic in somewhere near heart count? I dunno.
Currently the kokiri boots are useless information but I'm not sure how you could remove those while still having a balanced-looking layout.

**Comment by rlbond86** [comment]
I'll keep tweaking this, I do think SoA would be nice to have.

**Pull request merged**
