### PR TITLE
Closed Deku

### PR DESCRIPTION
**Pull request by Cuphat**
Allows a hybrid of Open Forest where leaving the forest is open but Deku Tree access still requires Kokiri Sword and Deku Shield.

### CODE REVIEW

**Comment by r0bd0g** [comment]
How does this interact with learning Zelda's Lullaby?
In vanilla, learning ZL moves Mido.

**Comment by Cuphat** [comment]
Why does this game suck shit

**Comment by Cuphat** [comment]
TR taught me how to git gud so I changed the flag Mido uses to fuck off to his house to showing him sword and shield instead of getting Zelda's Letter.

**Comment by r0bd0g** [comment]
The change to the Mido flag might be worth having regardless of settings? If you use normal closed forest, and you escape, it'd be weird for him to just disappear.

Did you affect the cutscene with mido that plays after beating deku? That cutscene also goes away after getting ZL. Can you do me a favour and just get rid of it regardless?

**Comment by Nicholas-Steel** [comment]
Yes, ditching Mido questioning your killing of the Great Deku Tree would be great! Or do you mean something else?

**Comment by Cuphat** [comment]
Mido now abandons his guard duty and chills in his house only is both "Showed Mido Sword & Shield" and one of "Obtained Zelda's Letter" and "Obtained Kokiri Emerald & Deku Tree Dead" are set.

As a result of the above, he now will fuck off and not bother you when leaving Deku.

**Comment by Cuphat** [comment]
This is not compatible with Dungeon Entrance Randomizer quite yet, it's otherwise complete.

**Comment by Cuphat** [comment]
Alright, this should be fully functional in all cases, AFAIK.

**Pull request merged**
