### PR TITLE
Option to generate all files for multi world at once

### PR DESCRIPTION
**Pull request by Hamsda**
This PR adds a `Generate All` button next to the player id and generates all seeds (1 to world count) at once.

I think there was talk about this before, but I was recently trying to look at a few multi world spoilers, and generating those was a giant pain. So I decided to add this :)

I wanted the player id field to be greyed out, but didn't get it to work. So that could/should be improved I guess.

### CODE REVIEW

**Comment by TestRunnerSRL** [comment]
So I kinda didn't have this option by design. The problem is that one person will generate all the seeds and then distribute them around. I realize that distributing seeds is on the fault of the user, not the developers, but I really don't want to encourage it. The correct usage is everyone generates their own seed.

I realize this is annoying for debug testing, but I don't want this something people use on a regular basis.

**Comment by Hamsda** [comment]
Hmm interesting but annoying :/

**Comment by r0bd0g** [comment]
That the item placement, spoiler, and hints must be regenerated each time is kind of a problem. Especially if you generate for a large number of players it could take a very long time to generate.

Maybe if you included all the information for all players in the spoiler log, and then we could somehow parse the log and generate the ROM from a spoiler log instead??? A feature along those lines could also be used for Plando, Vanillamizer...

**Comment by Hamsda** [comment]
Hmm... I'll have to think about that for a bit, but seems like the best middle ground.

**Comment by TestRunnerSRL** [comment]
I added locations of every world as well as the way of the hero hints into the spoiler. It only has the gossip stones for the one player with how it's currently implemented, but I figured that wasn't important. If gossip stones is something you really thing should be generated, I'll include it too. As far as parsing the spoiler to create roms, that sounds like a potential feature, but I probably won't do that until after 3.0 is released

**Comment by r0bd0g** [comment]
The gossip stone hints would need to match regardless of how you generated the seed, if this is a feature we're really going with.

**Comment by TestRunnerSRL** [comment]
There's a lot more info I think that needs to be added to the spoiler to be able to generate a seed from it.

**Comment by r0bd0g** [comment]
Things like, what trials are chosen, how many big poes you need, price of items in shops... Yeah, there's stuff, isn't there.

**Comment by TestRunnerSRL** [comment]
I think if we are going to have a way to convert spoilers into a rom, it'll need to be a different PR, so I'm going to close this.

**Pull request closed without merging**
