### PR TITLE
Key Rings

### PR DESCRIPTION
**Pull request by cjohnson57**
Adds a multiselect setting, per dungeon with keys, which allows you to choose for that dungeon to have key rings instead of individual keys. A key ring gives you all the keys for a dungeon at once. For example, when you pick up the Forest Temple key ring, you're given 5 forest temple keys (unless Forest Temple is MQ, in which case you're given 6).

If keysy or vanilla keys are selected, key rings have no affect. Thieves Hideout key ring also has no affect if fortress is open or fast (since fast fortress only has 1 key anyway).

I added items to the item table which are basically the same as the normal small keys, except they use new message IDs which add "Ring" onto the item get message, and they use a new function `give_small_key_ring`. Since knowing the correct amount of keys to give required knowing whether each dungeon is MQ, CFG_DUNGEON_IS_MQ was moved to the header file of dungeon_info.c. Similarly, the dungeon enum was convenient to have, so it was moved from item_table.c to item_effects.h (the latter of which is included in the former, so it works).

An addition was made to the `collect` and `uncollect` functions in State.py to ensure that collecting a single key ring would be logically equivalent to collecting all necessary small keys, by adding 10 small keys of whatever type key ring was found. (To be technically correct I could add whatever number of keys present in the given dungeon depending on MQ or not, but it would work out to the same thing). This prevents adding noise to the logic files by checking for key rings everywhere keys are checked for, and prevents breaking any open or in progress PRs which modify key logic.

DungeonList.py was modified to add an id for each dungeon and also to set its `small_keys` variable equal to a key ring if that id is found in the `key_rings` setting (unless keys are vanilla, in which case the normal small keys are kept). These id's match ones used in `dungeon_shortcuts` as well, so by standardizing them they could potentially be used for other purposes in the future.

Also modified the code for `#MajorItem` in plando to correctly use either small keys or a key ring depending on the settings.

enchanted_sword and Maple helped with the hints for them!

Unit tests were added, which can be divided into two groups. One group is just run to ensure no exceptions arise, the other group are run in their own unit test function to ensure the item pool is set correctly when combining different keysanity, key ring, item pool, and gerudo's fortress settings. All unit tests passed.

### CODE REVIEW

**Review by Cuphat — APPROVED** [review]

**Comment by r0bd0g** [comment]
How does this interact with plentiful? I would assume the seed would have two key rings and so you end up with 2x the normal number of keys?

**Comment by cjohnson57** [comment]
> How does this interact with plentiful? I would assume the seed would have two key rings and so you end up with 2x the normal number of keys?

Yep, a lot of the unit tests I added were to ensure the item pool is set correctly in different situations

> What type of chest does it go in? (Not even sure how chests types work at the moment.) Not sure what you could do differently, but I kind of feel differently about key rings to where somehow a small chest doesn't feel right.

They're set to go into a silver chest, same as small keys, but that's not a bad idea. That being said in textures only we don't want the size to change, and in classic mode Jay is adding they would be confused with boss keys, meaning they would only be in big chests if "Size and Textures" was chosen, which might be confusing

**Comment by Cuphat** [comment]
I pushed a few code changes that functionally change nothing but make the code cleaner/more reusable.

**Comment by Zannick** [comment]
More of a nitpick than a code review comment, but why do we need a new `snake_case` id for dungeons with small keys? ...maybe this is just true of Settings subkeys.

**Pull request merged**
