### PR TITLE
Narrow conditions for priority one-way handling

### PR DESCRIPTION
**Pull request by fenhl**
This optimization is intended for ALR to guarantee access to certain regions via one-ways earlier in the seed generation. It should only apply to AGR if there are necessarily goals locked behind these regions. It already does not apply to RO.

### CODE REVIEW

**Review by Zannick — APPROVED** [review]

**Comment by Zannick** [comment]
I want to ponder this more deeply, actually. If AGR *can* require all dungeons, then we'd need this to avoid having repeated failures due to not placing a warp to Graveyard/Shadow.

**Comment by fenhl** [comment]
I suppose the Nocturne warp could be enabled if there's a dungeon reward goal.

**Comment by Zannick** [comment]
And if there's a dungeon reward goal but no dungeon ER, we'd also need Requiem. But not Bolero.

How often do we expect it to be the case that we'd need this in AGR? I can think of: bridge=dungeons, GBK=dungeons, maybe lacs? And then Bingo is random enough that I'd want to leave it enabled.

**Comment by fenhl** [comment]
Also bridge = meds and Gbk = stones or vice versa. Not sure what you're referring to with the Bingo comment.

**Comment by Zannick** [comment]
Bingo can have a lot of different types of goals. My point is that there's a lot of cases to cover and it could be more work to maintain an accurate list than to just have it always on for AGR. What's the motivation for this? Just to let AGR sometimes not have warp access to Shadow?

**Review by Zannick — CHANGES_REQUESTED** [review]
Unapproving for now, since I'd still like this in AGR for a few cases but we should allow it to narrow further (like Bolero can be excluded) as mentioned.

**Comment by fenhl** [comment]
Narrowed things down a bit:

* Bolero is prioritized under one of the following conditions:
    * ALR
    * Token wincon and overworld tokens not shuffled
* Nocturne is prioritized under one of the following conditions:
    * ALR
    * Dungeon reward wincon
    * Stone wincon _and_ medallion wincon
    * Token wincon and dungeon tokens not shuffled
* Requiem is prioritized if no ER options that can make Colossus reachable as child are on (which now includes special interiors in addition to dungeon and overworld ER, since some special interiors can give access) and one of the following conditions is true:
    * ALR
    * Dungeon reward wincon
    * Stone wincon _and_ medallion wincon
    * Token wincon and either type of token not shuffled

**Comment by cjohnson57** [comment]
I don't really understand the reasoning behind the token conditions, can you explain them?

**Comment by fenhl** [comment]
Bolero locks access to a bean patch skull so it locks a goal item if overworld skulls aren't shuffled. Nocturne locks access to a dungeon so it locks a goal item if dungeon skulls aren't shuffled (unless GTG or Ganon's are in there but I feel like forcing that is even less variety than priority one-ways). Requiem locks access to both a bean patch skull and a dungeon.

**Comment by cjohnson57** [comment]
Gotcha, I was thinking about it backwards since normally you'd check if those locations *are* shuffled to see if you care about doing stuff to them or not

**Review by cjohnson57 — APPROVED** [review]

**Pull request merged**
