### PR TITLE
Add setting to enable casting farore in every overworld area

### PR DESCRIPTION
**Pull request by kenokeefe91**
Hello,

This is a new Misc setting proposition, to perform it I got the restriction flag for each overworld area from this documentation https://wiki.cloudmodding.com/oot/Scenes, using it I've calculated each area and restriction addresses (thanks Roman for your help, result is at the end), and by editing the restriction flag I was able to enable Farore for the related area.

I've voluntary deactivated it for Market's areas (tot entry, market, back alley, market entrance) due to some bug related to Farore forcing the player to spawn in 3rd person camera, the market areas really don't like it because they are using fix camera (and to be honest fixing this is way above my programming skills).

I've made a video to show what happens when you try too https://www.youtube.com/watch?v=3me8zyH_rhU

I've tried to be the more explicit in the description but I'm no native english speaker so don't hesitate to tell me if you see any spelling mistake 

Addresses and restriction flag for each area

```json
[
  {
    "name": "Hyrule Field",
    "address": "0xb6d2b0",
    "value": "0x51000010"
  },
  {
    "name": "Kakariko Village",
    "address": "0xb6d2b4",
    "value": "0x52000010"
  },
  {
    "name": "Graveyard",
    "address": "0xb6d2b8",
    "value": "0x53000010"
  },
  {
    "name": "Zora's River",
    "address": "0xb6d2bc",
    "value": "0x54000010"
  },
  {
    "name": "Kokiri Forest",
    "address": "0xb6d2c0",
    "value": "0x55000010"
  },
  {
    "name": "Sacred Forest Meadow",
    "address": "0xb6d2c4",
    "value": "0x56000010"
  },
  {
    "name": "Lake Hylia",
    "address": "0xb6d2c8",
    "value": "0x57000010"
  },
  {
    "name": "Zora's Domain",
    "address": "0xb6d2cc",
    "value": "0x58000010"
  },
  {
    "name": "Zora's Fountain",
    "address": "0xb6d2d0",
    "value": "0x59000010"
  },
  {
    "name": "Gerudo Valley",
    "address": "0xb6d2d4",
    "value": "0x5a000010"
  },
  {
    "name": "Lost Woods",
    "address": "0xb6d2d8",
    "value": "0x5b000010"
  },
  {
    "name": "Desert Colossus",
    "address": "0xb6d2dc",
    "value": "0x5c000010"
  },
  {
    "name": "Gerudo's Fortress",
    "address": "0xb6d2e0",
    "value": "0x5d000010"
  },
  {
    "name": "Haunted Wasteland",
    "address": "0xb6d2e4",
    "value": "0x5e000010"
  },
  {
    "name": "Hyrule Castle",
    "address": "0xb6d2e8",
    "value": "0x5f000010"
  },
  {
    "name": "Ganon's Castle Exterior",
    "address": "0xb6d2ec",
    "value": "0x64000010"
  },
  {
    "name": "Death Mountain Trail",
    "address": "0xb6d2f0",
    "value": "0x60000010"
  },
  {
    "name": "Death Mountain Crater",
    "address": "0xb6d2f4",
    "value": "0x61000010"
  },
  {
    "name": "Goron City",
    "address": "0xb6d2f8",
    "value": "0x62000010"
  },
  {
    "name": "Lon Lon Ranch",
    "address": "0xb6d2fc",
    "value": "0x63000010"
  },
  {
    "name": "Temple of Time",
    "address": "0xb6d300",
    "value": "0x43001015"
  },
  {
    "name": "Chamber of the Sages",
    "address": "0xb6d304",
    "value": "0x44a2aaaa"
  },
  {
    "name": "Shooting Gallery",
    "address": "0xb6d308",
    "value": "0x42115555"
  },
  {
    "name": "Castle Hedge Maze (Day)",
    "address": "0xb6d30c",
    "value": "0x45115555"
  },
  {
    "name": "Castle Hedge Maze (Night)",
    "address": "0xb6d310",
    "value": "0x46115555"
  },
  {
    "name": "Grave (Redead)",
    "address": "0xb6d314",
    "value": "0x3f0000d0"
  },
  {
    "name": "Grave (Fairy's Fountain)",
    "address": "0xb6d318",
    "value": "0x400000d0"
  },
  {
    "name": "Royal Family's Tomb",
    "address": "0xb6d31c",
    "value": "0x410000d0"
  },
  {
    "name": "Great Fairy's Fountain (Upgrades)",
    "address": "0xb6d320",
    "value": "0x3b000010"
  },
  {
    "name": "Fairy's Fountain",
    "address": "0xb6d324",
    "value": "0x3c0000d0"
  },
  {
    "name": "Great Fairy's Fountain (Spells)",
    "address": "0xb6d328",
    "value": "0x3d000010"
  },
  {
    "name": "Tower Collapse Exterior [?]",
    "address": "0xb6d32c",
    "value": "0x1a000550"
  },
  {
    "name": "Castle Courtyard",
    "address": "0xb6d330",
    "value": "0x4a000554"
  },
  {
    "name": "Fishing Pond",
    "address": "0xb6d334",
    "value": "0x49115555"
  },
  {
    "name": "Bombchu Bowling Alley",
    "address": "0xb6d338",
    "value": "0x4b115555"
  },
  {
    "name": "Ranch House & Silo",
    "address": "0xb6d33c",
    "value": "0x4c001015"
  },
  {
    "name": "Guard House",
    "address": "0xb6d340",
    "value": "0x4d001014"
  },
  {
    "name": "Granny's Potion Shop",
    "address": "0xb6d344",
    "value": "0x4e101555"
  },
  {
    "name": "Treasure Box Shop",
    "address": "0xb6d348",
    "value": "0x10101555"
  },
  {
    "name": "House of Skulltula",
    "address": "0xb6d34c",
    "value": "0x50001015"
  },
  {
    "name": "Market Entrance (Child - Day)",
    "address": "0xb6d350",
    "value": "0x1b001015"
  },
  {
    "name": "Market Entrance (Child - Night)",
    "address": "0xb6d354",
    "value": "0x1c001015"
  },
  {
    "name": "Market Entrance (Ruins)",
    "address": "0xb6d358",
    "value": "0x1d0010d5"
  },
  {
    "name": "Market (Child - Day)",
    "address": "0xb6d35c",
    "value": "0x20001015"
  },
  {
    "name": "Market (Child - Night)",
    "address": "0xb6d360",
    "value": "0x21001015"
  },
  {
    "name": "Market (Ruins)",
    "address": "0xb6d364",
    "value": "0x220010d5"
  },
  {
    "name": "Back Alley (Child - Day)",
    "address": "0xb6d368",
    "value": "0x1e001015"
  },
  {
    "name": "Back Alley (Child - Night)",
    "address": "0xb6d36c",
    "value": "0x1f001015"
  },
  {
    "name": "Temple of Time Exterior (Child - Day)",
    "address": "0xb6d370",
    "value": "0x23001015"
  },
  {
    "name": "Temple of Time Exterior (Child - Night)",
    "address": "0xb6d374",
    "value": "0x24001015"
  },
  {
    "name": "Temple of Time Exterior (Ruins)",
    "address": "0xb6d378",
    "value": "0x250010d5"
  },
  {
    "name": "Link's House",
    "address": "0xb6d37c",
    "value": "0x34101015"
  },
  {
    "name": "Carpenter Boss's House",
    "address": "0xb6d380",
    "value": "0x2a101015"
  },
  {
    "name": "Back Alley House (Man in Green)",
    "address": "0xb6d384",
    "value": "0x2b101015"
  },
  {
    "name": "Know-It-All Brothers' House",
    "address": "0xb6d388",
    "value": "0x26101015"
  },
  {
    "name": "House of Twins",
    "address": "0xb6d38c",
    "value": "0x27101015"
  },
  {
    "name": "Mido's House",
    "address": "0xb6d390",
    "value": "0x28101015"
  },
  {
    "name": "Saria's House",
    "address": "0xb6d394",
    "value": "0x29101015"
  },
  {
    "name": "Stable",
    "address": "0xb6d398",
    "value": "0x36101015"
  },
  {
    "name": "Gravekeeper's Hut",
    "address": "0xb6d39c",
    "value": "0x3a101015"
  },
  {
    "name": "Back Alley House (Dog Lady)",
    "address": "0xb6d3a0",
    "value": "0x35101015"
  },
  {
    "name": "Impa's House",
    "address": "0xb6d3a4",
    "value": "0x37101015"
  },
  {
    "name": "Lakeside Laboratory",
    "address": "0xb6d3a8",
    "value": "0x38001015"
  },
  {
    "name": "Carpenters' Tent",
    "address": "0xb6d3ac",
    "value": "0x39101015"
  },
  {
    "name": "Bazaar",
    "address": "0xb6d3b0",
    "value": "0x2c101015"
  },
  {
    "name": "Kokiri Shop",
    "address": "0xb6d3b4",
    "value": "0x2d101015"
  },
  {
    "name": "Goron Shop",
    "address": "0xb6d3b8",
    "value": "0x2e101015"
  },
  {
    "name": "Zora Shop",
    "address": "0xb6d3bc",
    "value": "0x2f101015"
  },
  {
    "name": "Kakariko Potion Shop",
    "address": "0xb6d3c0",
    "value": "0x30101015"
  },
  {
    "name": "Market Potion Shop",
    "address": "0xb6d3c4",
    "value": "0x31101015"
  },
  {
    "name": "Bombchu Shop",
    "address": "0xb6d3c8",
    "value": "0x32101015"
  },
  {
    "name": "Happy Mask Shop ",
    "address": "0xb6d3cc",
    "value": "0x33101015"
  }
]
```

### CODE REVIEW

**Comment by fenhl** [comment]
I sent kenokeefe91#1 with changes to the setting display name and description.

**Comment by mracsys** [comment]
Instead of hardcoding the restriction flags, I think it would be better to read each region's flags from the rom and remove (add?) the FW flag. That way we can also control other item restrictions such as Nayru's Love.

**Comment by kenokeefe91** [comment]
@mracsys Nayru is already allowed in the area where I activate Farore here so I don't think this may actually change something, except if you want to deactivate it in some areas but I don't know why you would do that ?

**Comment by kenokeefe91** [comment]
@mracsys also I may be mistaken but I think Nayru restriction works with Dins one, so if you disable one you'll disable the other too :/ same for activation, If you look at the doc link I've sent in the PR description you'll see that they are linked together

dins_nayru

**Comment by r0bd0g** [comment]
This has possible logical implications. I have plans to -maybe- add FW between dungeons as a logical way to affect ToD. But I'm not sure how/if this setting would be supported if I were to do that.

**Comment by kenokeefe91** [comment]
@r0bd0g what do you mean by "adding FW between dungeons" and how can it affect time of day ?

**Comment by r0bd0g** [comment]
Imagine you can only access an area at one time of day. You could set FW and then return to it at a different time of day.

**Comment by kenokeefe91** [comment]
Ok, so to summarize our discussion on discord, this is basically the same issue as manipulating tod with Farore using dungeons (with ER or not) you can easily go "out of logic" doing it because today this is not a behavior taken in account for tod manipulation.

So the logical consequences of this setting is not an issue yet as long as tod manipulation with Farore is not planned to be added in the logic algorithm.

If it is, issue will be that every areas where you could use Farore must be taken in account for tod manipulation.

So I don't know, if you don't want to add this setting for this reason I understand, final decision about this PR is in your hands :)

**Comment by r0bd0g** [comment]
Nah some obscure logic thing that might not end up implemented anyway, it doesn't matter. I just wanted to make note of it.

**Comment by kenokeefe91** [comment]
Ok, so maybe this new setting can be accepted for a future version ? 👀 👉👈

**Comment by r0bd0g** [comment]
(I suspect there may yet be concerns though)

**Comment by kenokeefe91** [comment]
As I said validation is now in the hands of the maintainers ^^ and I stay open to question

Personnaly as long as there is an explanation I'm fine if the setting is being refused

**Comment by cjohnson57** [comment]
Great job on this, I like this setting. Based on the discussion in the discord looks like we're waiting to split it into a multiselect, and then it'd be good to merge imo.

**Comment by kenokeefe91** [comment]
Hey @cjohnson57 not really, we've found a way to crash the game with @r0bd0g  when using it with er grotto.

If a grotto from graveyard is on a "casual grotto entrance" when you leave it and cast Farore the téléportation point will be in the grotto.

No problem at first glance but if you teleport with a song, came back to the grotto using Farore and leave the grotto the game crash…

I haven't tested on VC and @r0bd0g and I have other scenarii to test in order to find a way to solve this.

**Comment by r0bd0g** [comment]
I believe the exit point of the grave is being overwritten by using a warp song since warp songs reuse that address (it could also be overwritten by exiting a different grotto in the interim), and the resulting wrong warp failing for whatever reason is the likely cause of the crash.

(This same bug is the reason that warp songs are not allowed to spawn you in graves.)

**Comment by kenokeefe91** [comment]
Scenarii to test

```
after you warp to colossus, but before returning fw, go in and out of the grotto there

then see where leaving the grave takes you

I think that's what it is tho, it's trying to exit you out of the last grotto you exited

and warp songs use the same addresses, so those count

We might be able to get weird behaviour on main branch
```


```
Here's an idea: 
Go in and out of the tomb at the top of DMC, 
go in and out of the lower grotto in DMC, 
jump into the lava and presumably respawn inside the tomb?, 
leave the grotto, 
and probably respawn coming out of the lower grotto?
```

**Comment by kenokeefe91** [comment]
Testing the scenario with ER grotto, as stated by r0bd0g 

Question now is how do we fix that ? :D 

https://www.youtube.com/watch?v=xl3hVmikaiI

**Comment by kenokeefe91** [comment]
So I currently have no real ideas about how to prevent the game from crashing when using this settings with ER grotto, if someone want to try something you can use my repo as a base but for now the best is to close this PR.

Anyway thanks a lot to the people who helped me investigate on it, I've learnt a lot on the game doing it :)

**Pull request closed without merging**
