### PR TITLE
Add in options for cutscenes which are useful for tricks

### PR DESCRIPTION
**Pull request by dotzo**
Make skipping the Poe Cutscene in Forest Temple an option to allow noIM/WW Rules to get into the basement using the bottle trick.  In the GUI it appears under "Skip Epona Race" in the "Other" tab in the big box of "Timesavers".

### CODE REVIEW

**Comment by rattus128** [comment]
Should there be an accompanying logic change?

**Comment by dotzo** [comment]
It's not repeatable on a single save so it won't be considered by logic.

**Comment by rattus128** [comment]
Is playing under no IM/WW with accessible logic a thing now that glitched logic exists? Otherwise, since there's no logical impact and its just restoring an opportunistic skip, maybe just make it conditional on glitched logic.

**Comment by dotzo** [comment]
It can't be in glitched logic either.  I follow the same rules of repeatability as glitchless.  And yes, noim/ww races will still be on glitchless logic.

**Comment by TestRunnerSRL** [comment]
I don't really like the idea of an option being added so that people can do a glitch that's not even in logic. I'd probably only take this is this covered more of a collection of things. like "skip all cutscenes" or something, not just this singular instance.

**Comment by dotzo** [comment]
Seems odd to not want a way to make something back to vanilla just because it doesn't affect the randomizer itself.  Adding back more cutscenes doesn't really do anything since this is the only one that's useful in any meaningful way.

**Comment by TestRunnerSRL** [comment]
I don't really care about things behaving as vanilla, and we don't really have options to make things vanilla, so this would be setting a potentially bad precedent. Afaict this basically adds an option that has fairly minor effect, so I dunno, especially since it's out of logic. It's basically just promoting people to do things out of logic, which is very odd since I kinda felt that the whole point of glitched logic was so that people could do glitches and remain in logic.

**Comment by dotzo** [comment]
It's a glitched equivalent of fast epona. it doesn't affect logic but allows you to get checks more quickly. no longer having to do the poe fights to check the basement.

**Comment by dotzo** [comment]
Added Darunia in fire and twinrova to the list.  The former allows a unique bk skip, the latter makes the fight not suck by insta-starting.  Neither affect logic as cutscenes are 1 time events.

**Pull request merged**
