### PR TITLE
Bingo preset added

### PR DESCRIPTION
**Pull request by DobbyDigital**
Adds a default set of settings to use when playing bingo on OoTR. Most of the settings are not super consequential (such as child stealth being on or off), but some settings can have impacts from a goal perspective. Notably, removing maps and compasses from the game, skullsanity, and closed bridge. 
This preset also defaults to using the bingo hints, making it more apparent that the option is available for default and board-specific hints.

### CODE REVIEW

**Comment by LostThePirate** [comment]
The Disabled locations here confuses me. Turning off Frogs 1 but leaving Frogs 2?

**Comment by Zannick** [comment]
Seems fine as a starting point; I'm guessing that's how people will be using this mostly? Load some settings on the web, flip some settings for added convenience like child stealth, and save a personal preset?

**Comment by DobbyDigital** [comment]
Probably? Ultimately it's basically entirely up to personal preference, so that's my guess is to what people will do. It's mostly as a starting point for completely new players who don't know much about bingo so they don't accidentally screw themselves with settings LUL 
 My hope is to eventually have a Wiki page for bingo that will mention the settings that you shouldn't really touch and the ones that don't really matter.

**Comment by DobbyDigital** [comment]
Wait, did I disable Frogs 1 but not Frogs 2? That's a miss-click on the disabled locations, I will fix that. Thanks Lost!

**Comment by LostThePirate** [comment]
If you want Wiki access, just ask TreZ. Not a big deal, he just doesn't leave it open to public edits because too many random NSFW pages kept getting added by bots, lol.

**Pull request merged**
