### PR TITLE
Extend space available for message data

### PR DESCRIPTION
**Pull request by mracsys**
Use both the Japanese and English message files for storing messages. The JP file is written to first, followed by the EN file, for a total space of 0x74000 bytes (up from 0x39000 bytes). Which file to load is determined by the segment number for a given text ID in the message table. 0x08 will load JP, 0x07 will load EN. More info on the message table format is at https://wiki.cloudmodding.com/oot/Text_Format.

Message 0xFFFC in the JP table is used by the title and file select screens with hard-coded offsets based on the vanilla JP file. This is accounted for at patch time by updating the hard-coded values to the new location in whichever file the message is placed.

Text shuffle appears to still work based on a quick test.

Testing the file split needs to either artificially decrease the JP text file size or add a lot more text to the game. Message relocation to the JP file works fine, so this should be OK but is untested as of submission. I'll take a look when I have more time to hunt for specific text in-game.

### CODE REVIEW

**Comment by fenhl** [comment]
This should fix #1572.

**Comment by mracsys** [comment]
Overflow to the EN file works now. PJ64, N64, and Wii VC were tested with the JP file restricted to 0x3A00 bytes.

**Comment by cjohnson57** [comment]
Will merging this preclude #1397? Or could it be adjusted to work the other way around if such a setting were enabled?

**Comment by mracsys** [comment]
Other languages should be fine. The language bit isn't touched in this PR outside of telling the game what text file to load. Fonts are untouched. However, looking at how the other PR is writing to the ROM I don't think these are compatible as-is. They can be made compatible.

**Pull request merged**
