### PR TITLE
Logic and Trick Update

### PR DESCRIPTION
**Pull request by r0bd0g**
Changes/Fixes:

Also includes the emergency fix for bombchu salesman and market night crates.

I added logic for using FW to travel between dungeon entrances.
- I can make this a trick, if you'd prefer. Comparing to the trick to use FW in Water Temple, I felt that that required a bit too much understanding of the game, knowing how the water level would interact with FW and that room that you can never normally visit at highest level. To be honest, FW between dungeons, if it ever comes up, would probably stump somebody just as hard, but at the same time there's nothing really tricky happening here. You just use FW. Beyond that we're asking players to understand their world layout in order to accomplish something, which can sometimes be really difficult, but it's also sometimes kind of the point of ER.
- It's not relevant on main branch, but b/c some branches have mixed pools bosses as an option, I had to also add returning FW to boss doors. Even though it's not relevant in Shadow or Spirit in the current mixed pools bosses implementation, I added it to those anyway for completeness, and in case anybody decides to try for a different implementation. The FW Warp access is only on the dungeon entrance since you can use the savewarp to reach it. Also, you might not be able to cast FW in the before boss room if you don't come in through the boss door?, but that's not a problem because you can always just use FW earlier and walk to the boss door again.
- I implemented this with logic, using a series of at()s. If the day comes where FW anywhere becomes an option, we will need to more general implementation. I thought that something more detailed was not worth adding at this time.

I decided to add using the Spirit Temple hands to pass time of day, and then returning out of the Spirit Temple entrance. I can make this a trick if you'd prefer. I put the region in the OW file since it's kind of an OW region and it's shared between the two Spirits, and used a savewarp to return to the Spirit entrance since that's probably how you would actually get there. I can use a savewarp like this, right? If the day comes that it's possible to enter the dungeon from the boss door, we should remember that we need to add logic to return through the dungeon to the boss door, since that might not always be possible after savewarping to the entrance. I didn't implement that now b/c I didn't want to have to even think about whether or not it'd be more complicated to handle than it first appears (would probably I have to move the hands region back into the Spirit file or something due to region naming differences). (I felt that ToD passed too slowly in the Fishing Pond to consider putting that into logic. It actually takes forever.)

I fixed a could bugs involving Kak Gate Open on Zelda. It was expecting you to visit Kak as child to deliver the letter, even though that's not necessary, since the gate automatically opens. This fix is only safe to include now thanks to #1949. This now allows Open on Zelda seeds to borrow Masks (and also enter child Kak proper from DMT while the visible one-way trick is off) without having to visit child Kak proper first. To accomplish this I added an event for opening the Gate to the root, and this also allowed me to simplify the Kak Gate logic itself a bit. With Kak Gate logic fixed I was able to remove the duplicate event for opening the Mask Shop. Arbitrary changes beyond this point. I added a region for the storefront to avoid repeating 'Kakariko Village Gate Open' on every check. I switched off of using "Mask of Truth Access" in cases where I believed complete_mask_quest would do. I moved the mask checks inside the at()'s to save on parens, but also it was weird that Saria's Song was inside the at(), but the Masks weren't.

Removed a check that prevented child from entering Fortress from Wasteland unless it was OW ER. I should probably explain why that was there, but it's pretty dumb. I think back when I wrote that ages ago, being in child Fortress at all might have been considered a glitch in some ruleset, I dunno? So I wanted to keep child logically out, even if you couldn't actually do anything relevant there, unless it was a setting with ER on where child access to Fortress couldn't really be avoided. Doesn't make sense. Pretty dumb. None of this affected anything since adult had to open the gate, and what could child do that adult couldn't? It wasn't until Fortress ER was added and I saw the Reverse Wasteland tooltip updated that I realized that whoever rewrote it didn't understand what that line in the tooltip was supposed to mean, and then checking the logic I realized this piece was still there and still not really making sense. So now you can access Fortress as child with the Reverse Wasteland and Quicksand with Nothing tricks enabled (or if you spawn at the Fortress/Wasteland entrance), if adult opens the gate first. Only relevant now in hideout ER.

I feel like this is often requested, so I figured to just do it. I split the Lens trick for Ganon's Castle MQ into two, with a separate one just for Shadow Trial. I considered making the trick just for the platform and reverting to the regular lens trick for the invisible path, but thought that would be too confusing. I could also have had the Shadow Trial trick remove the lens requirement the rest of Ganon's as well, but I felt that there was no real reason to force that.

The web blocking the invisible enemies GS in Jabu can be burned, which opens up some more methods of obtaining the GS involving the Fire Arrows. After burning the web, you can either Longshot the skulltula from afar or use the Iron Boots to get close enough to get it with Hookshot.

Reworked "Hammer Rusted Switches Through Walls" to include an instance of hitting a boulder through a wall in MQ Spirit Temple. This can allow child to climb Spirit without Bombchus, if adult can reach this boulder to Hammer it, which would require shortcuts on (or, maybe some day, access from one of the other entrances), and all 7 keys. Note that this trick is usually enabled in standard settings.

Removed the three tricks for obtaining the lower red rock GS in DMT and replaced with a single method involving a jumpslash.

Added a trick tag for dungeon shortcuts. I just ctrl+f'd the word shortcut, so let me know if I missed any.

---

New Tricks (aka Hell Mode Improvements):

"Boulder Freestandings with Boomerang" - General trick for whenever a boulder has a freestanding inside and you can Boomerang it out. Ice is basically a water boulder, right? I didn't want to make a separate trick for that water trial use, so I folded red ice in as basically just another boulder, which I think is pretty fair. But then I felt I had to include an instance in Ice Cavern that doesn't make as much sense to include, since there's a much easier way that doesn't need any Boomerang.

"Adult Kokiri Forest GS with Nothing" - ESS shuffle jump to reach the skulltula. Renamed the Hovers variant a bit.

"Gerudo's Fortress Break Room Entrance with Precise Jump" - ESS shuffle jump from below the skulltula to get over to the break room.

"Dodongo's Cavern Bombchu the Eyes from Below" - This is obsoleted as adult by the spike trap room jump. It's mostly obsoleted as child by the slingshot skip; this new trick only allows you to skip additionally needing a weapon to kill the Lizalfos (and keep in mind that Bombchus were considered logical for fighting Lizalfos back when I first decided not to add this trick). Both tricks you kind of need to know a setup, but I think slingshot skips have become lesser-known since randomizer rarely sees the dungeon completed as child.

"Forest Temple West Courtyard Hearts with Boomerang" - Boomerang these freestandings from below. Somebody looking to be helpful ought to make a setup video to get all 5 of these, two in Vanilla and three in Master Quest.

"Fire Temple MQ Entrance Flame Wall Skip as Child" - Child is to short to go around this flame wall, so a flame wall skip would have to be used. It can be used to reach two crates in the event that only child is able to reach the dungeon.

"Ice Cavern Frozen Rupee with Nothing" - Just kind of press yourself against the ice for a bit and you can get this rupee without Blue Fire. Something similar can be done for the MQ Water Trial Heart, but you have to get basically fully inside the ice in order to collect that one.

"Ice Cavern Frozen Pot with No Additional Items" - About a million things can easily break this pot through the ice, but the most generic way is to stand next to it and do a quick spin.

"Water Temple Morpha without Hookshot" - Using a sword. Sticks are not really viable, so child would have to use Kokiri Sword, which does take kind of a long time. It took me a solid hour of trying to pull this off without taking any damage.

"Water Temple MQ Reach Dark Link without Longshot" - Requires Hover Boots and Hookshot. The hard part is timing when to go with the Hover Boots. Not having Longshot makes the Boss Key Region trick with Hover Boots relevant in MQ, so that trick also had to be reworked.

"Shadow Temple MQ After Boat GS without Hookshot" - Use any projectile or Din's to kill the Skulltula, and then fall into the chasm to collect it. You can also throw a pot, but if the statue is down (this trick is currently only relevant with shortcuts on, so the statue is actually guaranteed to be down), there is no trajectory that works. Except you can jump off the statue above the Skulltula and shield-drop a pot onto it.

"Shadow Temple Triple Spinning Pots with Bombchus" - 3x and moving version of the bombchu trick for the pot earlier in the dungeon. Relevant if freestandings are shuffled.

"Spirit Temple Climb to Adult Side with Hover Boots" - Dungeon shortcuts trick to climb up to adult size without Hookshot, by using the Hover Boots off of the Armos.

"Spirit Temple MQ Water Jet Silver Rupee without Hammer" - Longshot through the jet to a chest on the other side. The only chest that works is the one that spawns from collecting this rupee, so it's only relevant when silver rupees are shuffled.

### CODE REVIEW

**Comment by r0bd0g** [comment]
There was a missing can_use() in Ice Cavern. I fixed it but I dunno why it's not showing up here. This whole place is an enigma. "Add more commits by pushing to the patch-2 branch on r0bd0g/OoT-Randomizer" Is that not what I did?!?!!

I think the unitest is failing because it's looking for a trick that doesn't exist anymore. If so, I dunno if makes sense to pass tests by editing the tests, so I'm not convinced that's my problem.

I was a bit lazy with trick names and descriptions, feel free to improve those if you want.

Some of these changes might be controversial, in particular I think FW and Spirit Hands?, and honestly maybe even renaming rusted switches since it's in such common use.

As usual, go over the changes carefully to make sure there are no errors.

**Comment by ETR-BTF** [comment]
> I added logic for using FW to travel between dungeon entrances.

I think this is fair. I think this is comparable to going thru spirit for colossus access.

> I decided to add using the Spirit Temple hands to pass time of day, and then returning out of the Spirit Temple entrance.

I think this is also fair. We already have this for colossus access so why not also for access to different times of day?

> "Water Temple Morpha without Hookshot"

Thoughts on an intermediate trick that's sword + magic for spin attacks? I find it's considerably easier than with just a sword, and iirc we have other tricks where there's a separate trick for a significantly easier version even tho it has slightly higher item requirements than the much harder trick.

> renaming rusted switches since it's in such common use.

I hard agree with changing the name on the user-side, but I don't think I agree with changing the internal name. It's going to break plandos and presets for no good reason.

I should mention that I did not look at the changes themselves. I just read r0bd0g's github messages.

**Comment by jdunn596** [comment]
> I think the unitest is failing because it's looking for a trick that doesn't exist anymore. If so, I dunno if makes sense to pass tests by editing the tests, so I'm not convinced that's my problem.

It is indeed failing because of the name and yeah we should typically be updating the tests as well when making these changes or creating new ones as applicable with feature updates.

Also your patch-2 branch has an error in `Ice Cavern.json` where "Ice Cavern Frozen Blue Rupee" is duplicated and pretty much causes the generator to shit itself lol. Idk why it's not showing up in the PR though which is weird...

**Comment by r0bd0g** [comment]
I made the Ice Cavern fix fix and now it shows up right away. When I first edited it, the web gui errorred out a couple times?? It was really weird. That copy-paste error might have been my fault or maybe the error did something weird.

---
I don't actually know how to run the tests locally, so it's a bit annoying for me to fix because the only way I know how is to make the PR and then guess and check until the errors are gone. Do you want me to change the tests? It would kind of take me a long time to check them all and see if they're setting that trick. I see which ones the unitests are failing on, but I'm not convinced that's an exhaustive list. Or would you rather something else...

"It's going to break plandos and presets for no good reason."
I agree that that's a short-term annoyance. I think long-term it would be better to have the two names match in a reasonable way. If changing the internal name is a deal-breaker, I think just separating it out as a separate trick would be preferred (or maybe even just put it in default logic, since you're definitely supposed to figure out that boulder is in there), but it's kind of strange that the way this trick works is so enshrined, because it sees use in standard. But the truth is, in terms of actually affecting seeds, this change is pretty minor. It'll probably be a long time before any seed requires it even if everybody plays settings where it could be required. It's a small thing but maybe it is causing a major disturbance. It would have been combined together like this though, from the start, had shortcuts existed and I'd thought of this case back when the trick was made. Maybe it was short-sighted of me back then to give the trick name such a narrow focus.

**Comment by r0bd0g** [comment]
"Thoughts on an intermediate trick that's sword + magic for spin attacks?"
When I learned how to do this I opted not to use spin attacks because I felt, while unreliable, the jump attack was just better when you don't have magic. Having magic would probably make hitting more reliable, and if you can get up to a full charge you can still get the double damage. This is still a pretty difficult trick either way, so I'm not convinced having magic makes so much of a difference that a 2nd trick is warranted. It would also be the first time that we'd have multiple tricks only for combat difficulty reasons. From that perspective, is magic really that important here? I feel like I'd rather have BGS than magic. I kind of feel like having is_adult, or maybe not ohko and ohko quad, or maybe DD and/or a bunch of hearts, could also help about as much as magic would, as far as helping players actually succeed at defeating the boss eventually.

**Comment by jdunn596** [comment]
I changed the tests already I PRd the changes to this branch on your fork. Once you merge them, it'll automatically update in here

**Comment by r0bd0g** [comment]
I would have expected to get a notification for that? Don't see any setting where I could change that, either.

**Comment by fenhl** [comment]
You can go to <https://github.com/r0bd0g/OoT-Randomizer> and select “Watch” in the top right. It's disabled by default for forks for whatever reason.

**Comment by ETR-BTF** [comment]
> "It's going to break plandos and presets for no good reason."
> I agree that that's a short-term annoyance. I think long-term it would be better to have the two names match in a reasonable way. If changing the internal name is a deal-breaker, I think just separating it out as a separate trick would be preferred (or maybe even just put it in default logic, since you're definitely supposed to figure out that boulder is in there), but it's kind of strange that the way this trick works is so enshrined, because it sees use in standard. But the truth is, in terms of actually affecting seeds, this change is pretty minor. It'll probably be a long time before any seed requires it even if everybody plays settings where it could be required. It's a small thing but maybe it is causing a major disturbance. It would have been combined together like this though, from the start, had shortcuts existed and I'd thought of this case back when the trick was made. Maybe it was short-sighted of me back then to give the trick name such a narrow focus.

I think having an extra trick for this reason would be worse than breaking plandos. Maybe these kinds of changes should be made right before major releases so that plandos don't break multiple times per dev cycle. So putting that part in a separate PR so the rest can get merged earlier. Or something like #1839 but for tricks as well?

**Comment by cjohnson57** [comment]
Great work on this!

>I added logic for using FW to travel between dungeon entrances. I can make this a trick, if you'd prefer.

I think I'm okay with having FW not be a trick, ER already expects you to use things like savewarps and this doesn't feel too different.

> I decided to add using the Spirit Temple hands to pass time of day, and then returning out of the Spirit Temple entrance. I can make this a trick if you'd prefer.

That also doesn't seem too trick-y to me.

> I think long-term it would be better to have the two names match in a reasonable way.

Eh, we have several settings whose internal names don't exactly match the external names. I agree I'd rather not break plandos (again), and keep the internal name the same.

This PR will also unfortunately have to be updated to move all the trick setting changes into the new SettingsListTricks.py

**Comment by r0bd0g** [comment]
As far as I know, this is what's needed to finish this up. Honestly I have no idea how to actually do this.

- Find all instances of logic_hammer_through_walls and replace back to logic_rusted_switches. Most of the instances are in plando files. You've got the trick list, the default presents, and the logic files where the trick is used.
- Rename trick from "Hammer Objects Through Walls" to "Hammer Rusted Switches and Boulders Through Walls" (and lets hope nothing else ever needs to be hammered through a wall). The trick name becomes a bit long but I think this is the best compromise.
- Change one weirdly worded tooltip for chu the eyes (because it's bothering me for some reason) from "Uses" to "You can use", I guess, and adjust line breaks.
- Don't actually changing the SettingsList file. Copy-paste the trick list from this PR over top of the new trick list file instead.

**Comment by r0bd0g** [comment]
Made the change to the trick internal name.

No idea how to do the other thing you asked. It ought to be a pretty simple copy paste if you actually know how to work this place.

**Comment by cjohnson57** [comment]
You'll have to merge latest dev into your branch and resolve whatever merge conflicts arise, and move your changes into SettingsListTricks.py, also changing the format slightly (As now the name is on the left side of an assignment rather than a property)

**Comment by r0bd0g** [comment]
I noticed an extra space in settingslist line 191 that I have no idea how it got through.

I'm gonna rely on somebody hopefully merging this and copy-pasting that tricklist over. I gotta move on with my day.

**Pull request merged**
