### PR TITLE
Scrub Shuffle: Update scrub messages with correct price.

### PR DESCRIPTION
**Pull request by Cuphat**
Also changes the spoken item name to "mysterious item".

### CODE REVIEW

**Comment by r0bd0g** [comment]
Does it play with text shuffle?

**Comment by Cuphat** [comment]
Text shuffle? lmao

**Comment by Roman971** [comment]
Along with this change, the tooltip for scrub shuffle option should probably be updated to remove the now incorrect text saying "The texts of the Scrubs are not updated."

**Comment by flagrama** [comment]
Are randomized item prices not considered hints?

**Comment by Cuphat** [comment]
I fixed the tooltip, thanks @Roman971.

I've also made a change so that scrub prices can now show in the spoiler log when using No Output. This'll allow those message IDs to be more easily exempted from text shuffle, but I haven't done that yet.

**Comment by flagrama** [comment]
Oh, I guess this is the part where I start yelling at people to put it in the Changelog too

**Comment by Cuphat** [comment]
I didn't think to do that because I wasn't completely sure this was getting merged for 4.0, but I realize it makes no sense not to update it so consider it done.

**Pull request merged**
