### PR TITLE
Fix progressive item models in shops

### PR DESCRIPTION
**Pull request by mracsys**
Prerequisite for #1972 to make the custom key setting toggle function. Without this PR, keys in shops will have vanilla models.

Shop scenes currently use hard-coded model and display function IDs assigned at patch time. This PR hooks into the shelf slot initialization function and the shopkeeper purchase function to dynamically change models and display functions to match the current progressive tier for that item. If an item is not progressive, there are no changes.

Ice traps use the current progressive tiers of their cloaked items.

Multiworld item receipt while in a shop is not handled. This retains the existing behavior while still in the shop, but all items will upgrade to their new models when re-entering the shop. I'm open to contributions if anyone wants to tackle this.

Tested on PJ64, N64, and Wii VC.

Current behavior:
https://github-production-user-asset-6210df.s3.amazonaws.com/19615534/243195692-0d6e1046-247a-40b5-98d6-c30be3ddfa88.mp4

Proposed behavior:
https://github-production-user-asset-6210df.s3.amazonaws.com/19615534/243195705-0e7106c1-6254-4171-ba72-0afb41155a31.mp4

### CODE REVIEW

**Comment by mracsys** [comment]
The change to upgrade functions to accept an override instead of an item ID in #1871 conflicts with this PR. I'm making a note on both PRs in case they end up in the same merge batch.

**Comment by r0bd0g** [comment]
"Multiworld item receipt while in a shop is not handled."
What about if a shop has two copies of the same progressive, are you saying the other doesn't update if you buy one?

**Comment by mracsys** [comment]
That is handled and demonstrated in the video.

**Comment by r0bd0g** [comment]
Let's say you get a strength from MW inside a shop, then you buy a strength in the shop, what happens to the model of the third strength also in that shop? If it updates, could you buy anything to get it to update, or do you have to buy the strength.

There's also the Kokiri Shop which could have an item around the side of the counter. Anything happen with that?

**Comment by mracsys** [comment]
Buying a second strength after getting the first from another world would immediately update all remaining strength upgrade models in that room to gold gauntlets. Likewise, buying any non-progressive item from the shop, including refills, will trigger refreshing the other items. This would upgrade strength models to silver gauntlets in your example.

The Kokiri shop item will always update like other freestanding items.

**Comment by r0bd0g** [comment]
I was gonna ask next if I had to buy a strength, or if only buying anything would work to update it, which seems to have been answered.

I meant if the Kokiri shop item is picked up, would the shop update from that. I assume it's like the MW case, but the description implies it could only come up in MW.

**Comment by mracsys** [comment]
I misunderstood, sorry!

Picking up the item in Kokiri shop will not update shop item models for the same reason MW item receipt doesn’t update them.

**Pull request merged**
