### PR TITLE
Closed Forest ER

### PR DESCRIPTION
**Pull request by puddydoo**
Closed Forest now works with ER and adult start. Although without ER, it only works with adult start if Open Door of Time is enabled. Closed door of time would require being able to guarantee child can get items to leave the forest completely independently of the actual playthrough starting as adult.
Closed Forest is also changed so that it is logically allowed to use shortcuts, warps, etc. to get out of the forest, but the prior behavior is restored with a detailed logic setting next to the night skulltula setting.

### CODE REVIEW

**Comment by DuskTheUmbreon** [comment]
I would suggest handling forest escapes as a trick, rather than as a setting, since it's not an actual mechanics change and it's just a logic change.

It'd also probably help for people using the RSL script, since that doesn't randomize tricks, it'd remove confusion on if you're expected to escape or not.

**Comment by puddydoo** [comment]
I don't think it can be a trick. Certain ER settings force disable Require Deku because that's the only way it can work.

**Comment by puddydoo** [comment]
There's an error that keeps this from generating and I don't understand it at all.

**Comment by puddydoo** [comment]
> required field "lineno" missing from expr
Traceback (most recent call last):
  File "OoT-Randomizer\OoTRandomizer.py", line 62, in start
    main(settings)
  File "OoT-Randomizer\Main.py", line 56, in main
    spoiler = generate(settings, window=window)
  File "OoT-Randomizer\Main.py", line 121, in generate
    worlds = build_world_graphs(settings, window=window)
  File "OoT-Randomizer\Main.py", line 145, in build_world_graphs
    world.load_regions_from_json(overworld_data)
  File "OoT-Randomizer\World.py", line 334, in load_regions_from_json
    self.parser.parse_spot_rule(new_exit)
  File "OoT-Randomizer\RuleParser.py", line 460, in parse_spot_rule
    access_rule = self.parse_rule(rule, spot)
  File "OoT-Randomizer\RuleParser.py", line 455, in parse_rule
    return self.make_access_rule(self.visit(ast.parse(rule_string, mode='eval').body))
  File "Python38\lib\ast.py", line 363, in visit
    return visitor(node)
  File "OoT-Randomizer\RuleParser.py", line 285, in visit_BoolOp
    elt = self.visit(elt)
  File "Python38\lib\ast.py", line 363, in visit
    return visitor(node)
  File "OoT-Randomizer\RuleParser.py", line 285, in visit_BoolOp
    elt = self.visit(elt)
  File "Python38\lib\ast.py", line 363, in visit
    return visitor(node)
  File "OoT-Randomizer\RuleParser.py", line 254, in visit_UnaryOp
    res = eval(compile(ast.Expression(node), '<string>', 'eval'))
TypeError: required field "lineno" missing from expr

**Comment by puddydoo** [comment]
The way I tried to make it so time of day can be logically checked under Closed Forest makes generation fail when I enable Closed Forest (unless ER is enabled)

> required field "lineno" missing from expr
Traceback (most recent call last):
  File "OoT-Randomizer\OoTRandomizer.py", line 62, in start
    main(settings)
  File "OoT-Randomizer\Main.py", line 56, in main
    spoiler = generate(settings, window=window)
  File "OoT-Randomizer\Main.py", line 121, in generate
    worlds = build_world_graphs(settings, window=window)
  File "OoT-Randomizer\Main.py", line 145, in build_world_graphs
    world.load_regions_from_json(overworld_data)
  File "OoT-Randomizer\World.py", line 334, in load_regions_from_json
    self.parser.parse_spot_rule(new_exit)
  File "OoT-Randomizer\RuleParser.py", line 460, in parse_spot_rule
    access_rule = self.parse_rule(rule, spot)
  File "OoT-Randomizer\RuleParser.py", line 455, in parse_rule
    return self.make_access_rule(self.visit(ast.parse(rule_string, mode='eval').body))
  File "Python38\lib\ast.py", line 363, in visit
    return visitor(node)
  File "OoT-Randomizer\RuleParser.py", line 285, in visit_BoolOp
    elt = self.visit(elt)
  File "Python38\lib\ast.py", line 363, in visit
    return visitor(node)
  File "OoT-Randomizer\RuleParser.py", line 285, in visit_BoolOp
    elt = self.visit(elt)
  File "Python38\lib\ast.py", line 363, in visit
    return visitor(node)
  File "OoT-Randomizer\RuleParser.py", line 254, in visit_UnaryOp
    res = eval(compile(ast.Expression(node), '<string>', 'eval'))
TypeError: required field "lineno" missing from expr

**Pull request closed without merging**
