### PR TITLE
Seeded Shadow Temple Truthspinner RNG

### PR DESCRIPTION
**Pull request by mracsys**
Creates duplicates of the game's pseudo-RNG functions referencing a separate seed value set at patch time. The correct truthspinner skull will be random on first load and each time the room is entered, but the sequence of correct skulls on room loads will be consistent for every player. The idea is to remove RNG from areas of races where it can lead to time losses of a few seconds or more.

There was a lot of discussion in mid October on this in the discord. Other ideas included making the correct skull always the same or precompleting the puzzle in race settings (subset of the shortcut). The feature could also be expanded to other significant RNG areas such as Treasure Chest Minigame. I'm opening this as a draft for any followup discussion.

Credit to @cjohnson57 for the initial work.

### CODE REVIEW

**Comment by r0bd0g** [comment]
"the sequence of correct skulls on room loads will be consistent for every player"
I'm not convinced that this will actually be true except when the room is loaded from the main entrance. I suspect, needs to be confirmed, that the way you load objects as you traverse between rooms will affect the order that the skulls are initialized.

(My evidence for this so far is that somebody ran tests on using the door coming back from Dead Hand and found approximately even odds of each skull being correct, rather than the skewed odds you would expect when coming from main entrance. In Mzx's blog post about the skull not being chosen completely fairly he mentions that his findings might only apply from main entrance due to the skulls potentially not loading the same way when other entrances are used.)

**Comment by ETR-BTF** [comment]
> The feature could also be expanded to other significant RNG areas such as Treasure Chest Minigame.

Or the Hylian Shield discount.

Has this been tested with FW, savewarps and deathwarps?

**Comment by r0bd0g** [comment]
I haven't tested anything, but I would expect save (unless the changes in RNG caused by loading the room are not saved), death, and FW (at least when cast in the same room as the spinner?) to all work as expected? It's just when going through doors and coming back into the room that I worry it won't be consistent. And that's kind of a problem b/c coming back from dead hand is usually when you want to pull the spinner. It doesn't really make sense to go out of your way to pull it the first time you're in the dungeon, just to guarantee you get the same RNG as everybody else who decided to do that, when you don't even know if that RNG is good or bad. So I think this PR kind of has to guarantee the same torch even after going through doors for this feature to make sense to have, and I'm not sure it does at the moment. (Though if you were to fix that, there's no way to do so without inadvertently affecting the odds of each torch being correct. I assume right now this PR is using the biased odds that vanilla uses, but if you come in through the door and not the main entrance, if it's not actually consistent which torch is correct, then practically now those torches should all have even odds, so fixing the torch to always be the same no matter how the room is entered will cause the odds when coming in through a door to not be practically even anymore.)

**Comment by Cuphat** [comment]
Coming from the entrance (40 times, 1 = left, 2 = center, 3 = right):
1122313333313311323113313321222213133331

Coming from Deadhand side (FW from another dungeon after save warping):
1122313333313311323113313321222213133331

Those are the same. Save warping resets the RNG. Obviously you'll have a different random number the first time you come through the room (i.e. from the entrance) than you will the second time (i.e. after Deadhand). There's no way to be perfect with this, any potential solution has its own issues.

**Review by Cuphat — APPROVED** [review]

**Comment by r0bd0g** [comment]
I don't know how you tested that but it doesn't seem like a good test to just FW in the same way every time. If you want to see the correct torch vary you need to try loading rooms in awkward orders as you go through the dungeon. In particular I'd like to see some varied movement through the dead hand area and back out to the spinner, to see if the things you do along the way can change which torch is correct. I'm not confident that this PR is adequately tested at this time.

You mean savewarping resets it to the first torch in the sequence? I'd prefer if it didn't do that. Can we save your RNG position into the save?

**Comment by Cuphat** [comment]
If anyone wants to do more extensive testing than I did, be my guest, but honestly the worst case scenario I see for this PR is that it doesn't accomplish its goal and I haven't really seen any evidence that that would be the case.

**Comment by r0bd0g** [comment]
I've seen some possible evidence. The mzx blog said that traveling through doors could affect the order that the torches initialize, changing the odds of which torch is correct. Somebody did tests repeatedly coming in from the door from dead hand so see if the odds were correct (rather than coming in from the main entrance like the blog post said to do), and got even odds of the torches being correct, rather than the skewed odds that you would expect, however their sample size was not particularly large. But even odds is what you would expect if each load was changing the order the torches initialized.

**Comment by cjohnson57** [comment]
In terms of the purpose of this PR (being to keep racing even), don't racers typically do truth spinner first thing either way?

**Comment by r0bd0g** [comment]
Should be faster to do it on the way back from dead hand? (It doesn't really make sense to change up your habits just to get the same RNG as everybody else who does that, when you don't even know if that RNG is good or not.)

**Review by cjohnson57 — APPROVED** [review]

**Pull request merged**
