### PR TITLE
Add ability to exclude sequences from being used when shuffled

### PR DESCRIPTION
**Pull request by flagrama**
Use cases:
> I don't like having Learn Song shuffled into fanfares since it kills the bgm track.

Add "Learn Song" to the exclude file.

> I still think the Fire Temple Music in OoT 1.0 is offensive even though it isn't (#557)

Add "Fire Temple" to the exclude file and include either a Fire Temple 1.2 or Shadow Temple sequence in the folder.

> I have way too many custom sequences and would like to exclude some of them occasionally without having to move the files all over the place

Add your custom song's **file** name, each on a new line, to the exclude file.

### CODE REVIEW

**Comment by flagrama** [comment]
Should be a little better now that it isn't "I need to get this written 10 minutes before I generate a seed to stream" code. In theory you should be able to remove all vanilla sequences to force only custom ones now where with the old code you'd likely run into the "too many attempts" error.

**Comment by flagrama** [comment]
SearchBox added to GUI to allow excluding vanilla sequences outside of the excluded.txt file
- Allows excluding certain sounds to be available on the website as well
- I'm sorry I broke the nice three column layout for the SFX and don't know how to fix it, please help.

If creating a patch file and all vanilla sequences are excluded it will simply replace all music with No Music and mention in the Cosmetics Log that all music sequences were disabled

If creating a ROM excluding all sequences will raise an error to remove some exclusions or to add custom tracks.
- I assume this is not an issue for the website as I believe it should always be using the Patch methods, but perhaps an edge case where someone tries to exclude all sequences when applying the patch file? If this is an issue I can make some further changes to correct this to something more website friendly.

**Comment by flagrama** [comment]
Removed the exclusion file as it is no longer relevant so long as custom tracks can be managed in the GUI

Removed references to exclusion file in README

SearchBox now says "Exclude Music Sequences" instead of "Exclude Vanilla Music Sequences"

Use data_path from Utils for music path

Use No Music path instead of throwing error when all sequences are excluded while generating a ROM

**Comment by TestRunnerSRL** [comment]
I'm worried about adding a lot to the gui for a level of control that is likely beyond 99% of users. Also this option's wording and tooltip still confuse me about the functionality of this. It's ambiguous if the song is removed from the pool and a different one get's duplicated, or if that song is fixed and not randomized.

**Comment by flagrama** [comment]
Yeah, I tend to not be so good at wording. The song is removed from the pool and a different one gets duplicated.

I just thought having it added to the GUI would be nice for people who use the website to exclude annoying ones like Shooting Gallery, Mini-Game, and Horse Race. Otherwise I'd be fine keeping it as an extra file in the Music folder to make it possible to ensure custom tracks will appear more often.

**Pull request closed without merging**
