### PR TITLE
Random trials were not taken as a random subset but number of trials was uniformly distributed.

### PR DESCRIPTION
**Pull request by akshatchugh**
This is quite uneven and chances of needing all 6 trials were as high as 1 in 7 whereas now they are 1 in 64.

### CODE REVIEW

**Comment by TestRunnerSRL** [comment]
I think the old method was done by design. The idea is just that you choose a random option 0-6, then choose the trials. I'm not exactly convinced this change to the distribution is an improvement.

**Comment by akshatchugh** [comment]
I wasn't very convinced either at first honestly (I'm still not a 100% sure this is better). But after some calculations, I found out that the probabilities of trials being chosen are actually not independent in the current implementation. This might not matter of course, but intuitively it feels like it's wrong for the probabilities to not be independent.

**Comment by Taylor-Bryan** [comment]
Curious.

So, the likelihood of getting only one trial is about 10% with this change, and then a ~17% of getting a specific trial. Over the course of say three seeds - I may get one trial each time, but the likelihood of getting the same one is fairly low.

This does put the ability to get all 6 trials fairly low though. I would be curious to see the spread of generated seeds with random trails selected with this change in place. I think the idea itself is good - more randomness in a setting like this is probably a step in the right direction. I may implement this in my local build as well and see how it feels. I can see the intent in both of these decisions, however I do believe @akshatchugh is right in his assessment that is 

> feels like it's wrong for the probabilities to not be independent.

If we can get a good set of sample data, I'm sure the folks on the Discord would be open to the potential implications of the change or a few folks would be willing to try it out.

**Comment by TestRunnerSRL** [comment]
I think there's some confusion here. The current method should also be independent. Whether a trial is in or not does not affect the odds of other trials being in, and you can't make any predictions based on knowledge of which trials you know. The only thing being suggested here is just a different probability distribution which makes doing 3 trials likely and 0 or 6 unlikely.

If you want such a thing, you might as well just choose 3, as it will have a similar result. The purpose of random option is to choose a random option. The settings already have which trials to be chosen to be randomized. Also since you often do not even know which trials you need to do until you enter Ganon's Castle, the only relevant thing is really how many trials you need to do, so again, having a uniform distribution on the count is less predictable.

@Taylor-Bryan I'm not sure why you need to take any data on this. This is a pretty simple probability problem that you can solve analytically.

**Pull request closed without merging**
