### PR TITLE
Add Quick Boot Equips

### PR DESCRIPTION
**Pull request by krimtonz**
Use D-Pad Left to equip iron boots if they're in the inventory, or D-Pad Right to equip Hover Boots if they're in the inventory.  Press the button again to equip Kokiri boots

### CODE REVIEW

**Comment by TestRunnerSRL** [comment]
So iirc, the main reason this wasn't implemented before was because this doesn't work for VC, as it doesn't have a mapping for the D-Pad. This is kind of a problem if people on VC in a race have a disadvantage.

**Comment by krimtonz** [comment]
I recently made a change to gzinject that will allow for this.  gzinjectgui still needs to be updated to use the new options though.

**Comment by TestRunnerSRL** [comment]
Hmm, we should probably make it clear somewhere that people will need to update their gzinject to use this feature. I think I'll hold on this merge until gzinjectgui is also updated since I figure that is what most people use.

**Comment by krimtonz** [comment]
gzinjectgui has been updated.

**Comment by phixtyseven** [comment]
This is amazing, thank you

**Pull request merged**
