### PR TITLE
Allow Multiple 'Bottle with Letter'

### PR DESCRIPTION
**Pull request by Cuphat**
If King Zora has been moved or if you have a bottled letter in any of the 4 bottle slots, you are given an empty bottle instead, with letter bottle icon/model and changed text explaining that the bottle is emptied.

Plentiful item pool updated to add a duplicate 'Bottle with Letter'.

### CODE REVIEW

**Comment by r0bd0g** [comment]
Does this interact correct with barren hints? There's a special case for bottles.

**Comment by Cuphat** [comment]
I didn't change barren hints, but I /think/ it should work mostly as expected. It's not counted as a duplicate "Bottle" but it still checks for duplicate "Bottle with Letter" by itself.

**Comment by r0bd0g** [comment]
If that's the case then is there a bug with bottled big poe? It's possible you could have up to three of them on woth.

**Comment by r0bd0g** [comment]
TR can you check Big Poes and Barren hints work correctly if more than one Big Poe is on WotH?

**Comment by TestRunnerSRL** [comment]
i mean this is actually pretty commented in the code. From World.py
```
        for location in woth_loc:
            if not location.item.special.get('progressive', False):
                # Progressive items may need multiple copies to make progression
                # so we can't make this culling for those kinds of items.
                duplicate_item_woth[location.item.world.id][location.item.name] = location
            if 'Bottle' in location.item.name and \
                location.item.name not in ['Bottle with Letter', 'Bottle with Big Poe']:
                    # Bottles can have many names but they are all generally the same in logic
                    # The problem is that Ruto's Letter and Big Poe might not be usuable as a 
                    # Bottle immediately, so they might need to use a regular bottle in
                    # addition to that one. Conversely finding a bottle might mean you still
                    # need ruto's letter or big poe. So to work with this, we ignore those
                    # two special bottles as being bottles
                    duplicate_item_woth[location.item.world.id]['Bottle'] = location
```
Basically, those two bottles are not considered bottles.

**Pull request merged**
