### PR TITLE
Add new junk hints

### PR DESCRIPTION
**Pull request by Zannick**
Some are useful information, like other junk hints.  
Others are useless but fun... like *other* junk hints.

### CODE REVIEW

**Comment by flagrama** [comment]
I like the random numbers one.
The falling in holes resetting chickens one is false. Grottos are the one thing that doesn't reset the ones in the pen.

**Comment by Zannick** [comment]
Wait, really? When did that change?

**Comment by flagrama** [comment]
You reset the cuccos you haven't put in the pen, but not the ones in the pen. Entrance Rando with mixed pools on Roman's fork may work differently though.

**Comment by r0bd0g** [comment]
As far as I know, the cuccos never leave the pen. You can go anywhere.

**Comment by Zannick** [comment]
I'll just remove it for now.

**Pull request merged**
