### PR TITLE
Fix Suns Song + Random Melodies interaction - The Very Final

### LINKED ISSUE #1792: Sun's Song random notes softlock
I think we got a report of this happening even after our fix for long songs. I might have dreamed it though. I can't find any solid documentation of this happening. Edit: Okay I found it.

### PR DESCRIPTION
**Pull request by GSKirox**
Hopefully. 
Should fix #1792 for good according to mzxrules' research : https://github.com/OoTRandomizer/OoT-Randomizer/issues/1792#issuecomment-1464084023

This PR implements the safest solution described, which was to fix Suns Song duration to its default vanilla value : 208 frames.
It keeps the random melody rolled, and just adjusts the duration accordingly.
I tested it as much as i could and it seems to work in all problematic cases, including the MQ Spirit Symphony puzzle.

### CODE REVIEW

**Comment by ETR-BTF** [comment]
Thanks for the fix!

Should all songs have their duration fixed for safety? We've never received reports for bugs like this other than for Sun's Song.

**Comment by fenhl** [comment]
I think the variety in duration is nice to have, so I'd say no unless we get any reports.

**Comment by GSKirox** [comment]
Yeah i agree with Fenhl, rather not touch anything else until it's proven broken.

Of course it's not a real proof, but this change made me test a lot of different Epona's song and Song of Time random rolls to test the MQ Spirit Symphony room puzzle, and they all worked.

**Review by cjohnson57 — APPROVED** [review]
Thank you so much for the fix and thanks so much to @mzxrules for digging into it and finding the issue!

**Pull request merged**
