### PR TITLE
HUD: Button Color Options

### PR DESCRIPTION
**Pull request by Cuphat**
Allows customization of the A, B, C, and Start button HUD colors.

### CODE REVIEW

**Comment by r0bd0g** [comment]
I'm gonna recommend, if you haven't done it already, that you update the button colours in all places that that they were updated in the GC version, including on the staff both in-game and on quest status, but also the "more text" triangle/square (to match the A button colour). I don't know if there are other places where colours were changed that I haven't thought of.

**Comment by TestRunnerSRL** [comment]
As I've commented on earlier, I'm uncertain about this feature mainly because it adds a lot of new options that have relatively minor effects.

**Comment by r0bd0g** [comment]
I'd probably use it if I could get the full GC experience going.

**Comment by Cuphat** [comment]
It is a fair amount of new options, but it honestly balances out the Cosmetics tab.

image

I'd look into replacing the button colors elsewhere if I knew where to find them. ¯\_(ツ)_/¯

**Comment by TestRunnerSRL** [comment]
I think i'd be more willing to accept this if we instead combined the 4 options into a single set of presets. like `N64`, `GC`, etc. And also a random one ofc. I just can't see having 4 options for such minor things being worth adding to the option overload, but having just is probably fine. Also I still think the start button color is pretty silly, but if it's part of the single presets then wtv.

**Comment by Cuphat** [comment]
Condensed it into one option. You lose the capability to set custom colors that way. Ideally the GUI would let you set all 4 colors custom even with one option, but that's not how it was done for Navi so I am not sure how feasible that is. If someone wants to set custom colors, they can use a branch that has the options split to patch with assuming this is merged.

**Comment by GhostlyDark** [comment]
If I may add to this: I'd really hate to lose the ability to customize the HUD buttons and it seems silly to me how the settings can't exist as seperate options, even though Navi settings take up so much.

Here are some presets I'd like to see though (as used by the Majora's Mask ROMs):

**MM N64 HUD Colors:**
A button: #64C8FF
B button: #64FF78
C button: #FFF000
Start: #FF823C

**MM GCN HUD Colors:**
A button: #64FF78
B button: #FF6464
C button: #FFF000
Start: #787878

**Comment by Zannick** [comment]
Presets would likely be customizable on a local install, much like Settings presets are. That won't help for any seeds made online, though.

What's the status here? Did we find the remaining places that button colors appear or still looking?

**Comment by LostThePirate** [comment]
The Public is generally big fans of more cosmetic options.
With the condensed preset list to avoid UI bloat, this seems like a good addition to me.

**Comment by Roman971** [comment]
All places where button colors appear are handled with the exception of textbox button icons, which actually use normal yellow/green text colors, so a lot of work would be needed to make them use separate colors that can match the randomized ones.

I mentioned this a long time ago but there is still one small issue with the current state of those changes which is that some uncommon colors can cause the shop cursor to use wrong colors for a few frames when it does the pulse effect, but that's not easy to fix at all if we want to do it properly.
Simple solutions include disabling the pulse effect when button colors aren't vanilla, or just not matching the shop cursor to the A button color.

**Comment by Zannick** [comment]
> textbox button icons, which actually use normal yellow/green text colors, so a lot of work would be needed to make them use separate colors that can match the randomized ones.

Where does this apply (outside of text rando)? Do we want to consider it a blocker?

> I mentioned this a long time ago but there is still one small issue with the current state of those changes which is that some uncommon colors can cause the shop cursor to use wrong colors for a few frames when it does the pulse effect, but that's not easy to fix at all if we want to do it properly.
Simple solutions include disabling the pulse effect when button colors aren't vanilla, or just not matching the shop cursor to the A button color.

Either of those simple solutions seems good. I would prefer not matching the shop cursor to the button color.

**Comment by Roman971** [comment]
> Where does this apply (outside of text rando)? Do we want to consider it a blocker?

This applies wherever C and A button icons are used in text messages, mostly in NPC instructions and item usage explanations. I wouldn't consider it a blocker but more like a possible improvement in the future.

**Comment by Zannick** [comment]
Ok, so I'll merge this tomorrow, if there are no further objections, since Dev is widely acknowledged as unstable 😜. Next work would be:

* possible improvement for icons in text messages
* the shop cursor color should be independent

**Pull request merged**
