### PR TITLE
Adding "Random" as a possible selection for "Rainbow Bridge Requirement"

### PR DESCRIPTION
**Pull request by Blueteeth0711**
You can select "Random" as an option for "Rainbow Bridge Requirement".  Doing so will randomize Rainbow Bridge Requirement the same way "Randomize Main Rule Settings" does.  This means "tokens" is not a possible option.

### CODE REVIEW

**Comment by bpanosh** [comment]
Tested by looking at spoiler log and making sure random_settings was updated appropriately.  Also created a seed and checked the alter to make sure it correctly displayed the bridge conditions.

**Comment by LostThePirate** [comment]
Why would Tokens not be on the table for this setting? If you're gonna make it random, then actually make it random, don't put hidden limits on it.

**Comment by Blueteeth0711** [comment]
> Why would Tokens not be on the table for this setting? If you're gonna make a Random setting, then actually make it random, don't put hidden limits on it.

Honestly I agree with you, however I am trying to keep this logic consistent with what "Randomize Main Rule Settings" produces.  According to the discord chat it was a design decision to leave skulls out of "Randomize Main Rule Settings" so I figured we should apply the same rules here.  If people want me to add in skulls (which honestly I would prefer as well), I can go back and do this.

**Comment by LostThePirate** [comment]
I was honestly unaware that Randomize Main Rules left that out; I was under the impression the only thing it didn't randomize was Master Quest.

**Comment by Blueteeth0711** [comment]
> I was honestly unaware that Randomize Main Rules left that out; I was under the impression the only thing it didn't randomize was Master Quest.

Yeah I was too until I started working on this.  I was wondering why I never got a skull seed when I played Randomize Main Rule Settings haha.  Personally I agree with you and think it should be part of the pool as well.  It does feel a bit weird to put hidden limits on it as you said.

**Comment by ETR-BTF** [comment]
> I was honestly unaware that Randomize Main Rules left that out; I was under the impression the only thing it didn't randomize was Master Quest.

The tooltip now tells the user what is randomized. Also - and I only kind of skimmed thru the conversation in discord - but iirc the author was explicitly asked to follow "Randomize Main Rule Settings".

random_settings

**Review by Zannick — APPROVED** [review]
We could always add separate Random options if folks really want to be surprised with 100-token seeds (given that we're always choosing the full amount for the others): Random, Random (No Tokens).

Potentially we should name it "Random (No Tokens)" anyway.

**Pull request merged**
