### PR TITLE
Navi Hints [WIP]

### PR DESCRIPTION
**Pull request by accept8605**
20-03-11: I was kind of busy and didn't get to work on it. Sorry. Haven't given up though... I'll get back to work on it in a few months I think. Like early summer or so.

19-08-23: I'll start working on it again now. Hope there will be an update soon.

More stuff to improve, this will take a bit longer

The general Idea is that you set a delay of 30min or an hour or whatever, and if you dont get ANY required Item in that time, the first Item from the rando spoiler data that you havent got yet, I mean its location will be told by navi. The "general area" normally.

You don´t want hints? Even when stuck and you would be ready to look at the spoiler file and catching more than you wanted?
Its deactivated by default and you can set the delay to like 10 hours so you will never get a hint
I mean you just have to find a delay time that's suitable for you
and if that suitable time runs out, you probably want to know which area to look at

To be done:
-Testing and some bugfixing - done
-Clean up the code more - done
-Manipulate the OOT Navi timer - done
-React right to progressable items - done
-Navi should pop up in dungeons, too - done
-Multitexts for bottles(only if multiple bottles in spoiler) - done
-Make the hint logic more sophisticated - not sure if its neccessary to make it dynamicly react to your current location ingame, on hold now

For the Implementation I have 2 areas in the ROM, the lookuptable and the texts itself. The lookuptable is also dma loaded in the RAM. The lookuptable for Navi texts (8 Bytes each per text 
         2 Bytes SaveDataOffset, 1 Byte SaveDataBitoffset, 1 Byte to handle by software,
         2 Bytes SavedataMask, 1 Byte ItemID, 1 Byte Sphere - for each required Item). All those are generated in Python from the spoiler data. I hand the spoiler data item to savedata context to get address and bitmask. 
Thats it for the python part

For the asm part
I have 2 new hooks, textloadlogic and cycliclogic.
The textloadlogic is called whenever any text is loaded.
I check the text rom address and if its a navi text rom address, I manipulate it to my own rom address.
The cycliclogic generates the target rom address for the text.
The cycliclogic works like: Check all the lookuptable entrys and check the savedata for each lookuptable entry, if you got the item check if you got it before, if not reset the my navi timer. if my navi timer runs out get the first lookuptable entry you dont have the item in the savedata => Set rom address for textloadlogic

### CODE REVIEW

**Comment by flagrama** [comment]
[Saria's Song and Navi Provide Known Hints](https://trello.com/c/ADgr96h0/13-sarias-song-and-navi-provide-known-hints)

**Comment by Zannick** [comment]
Any updates on progress here / #659? These are heavily out of date versus current Dev and should probably be closed and reopened, or carefully rebased.

**Comment by accept8605** [comment]
> Any updates on progress here / #659? These are heavily out of date versus current Dev and should probably be closed and reopened, or carefully rebased.

Hi, I've been busy with other stuff, and it would take to much time to get back into this. Feel free to reuse the code how you like.

I'll try to talk to you on discord

**Comment by TreZc0** [comment]
See #659

**Pull request closed without merging**
