### PR TITLE
Hint tweaks

### PR DESCRIPTION
**Pull request by Hamsda**
I've been fiddling with the wording for hints:
- Mainly tried to improve the color highlighted bits (the stuff between the `#`) so you only ever need to read that and it will be unique, e.g. the 2 different hints for composer grave now include the redead/darkness part.
- Another small thing was removing things like `gilded chest` or `apparent key` since we have CSMC and accurate freestanding models since those were written.
- Since I'm not a native English speaker, I'm not certain why some things got capitalized by the original author(s), when it is only parts of a name, e.g. `Crater` vs. `valley`. I just stuck with what has been done previously.

This doesn't add/remove any hints for standard weekly (just tweaks wording), only for variety settings.

Also I just rebased again to get the latest commits from db0, but that duplicated my commits? I'm bad at git <.<

### CODE REVIEW

**Comment by r0bd0g** [comment]
I definitely would not say "on a meadow"? I didn't notice too much else as far as wording that seemed off.

What all locations did you add/remove hints for?
(In particular I'm confused by the removal of Shadow MQ's invisible maze.)

**Comment by Hamsda** [comment]
> I definitely would not say "on a meadow"?

Yeah I actually have never heard someone use meadow casually, so wasn't sure how to phrase this. Just wanted to get away from `forest` since that is used for the non clear hints Forest Temple.

For additions/removal, I took a look at the item and time requirements and how easily checks can get isolated. With that in mind, I hope these lists make sense.

Added:
- GV cow
- HF Grotto Cow 
	- thinking about it, this might need the same exclusion as the skull in the same grotto for ER?
- GS DMC crate
- GS deku back room
- GS DC MQ SoT blocks
- GS Jabu MQ rang room
- Jabu MQ cow
- Forest MQ island
- GS Water south basement
- GS Water MQ south basement
- GS Shadow near ship
- Shadow MQ beamos silvers
- GV storms grotto
- BotW entrance

Removed:
- 1st chu bowling
	- not for standard anyways, but this one was kinda dumb of me to add in the first place
- Fire MQ West Tower Top 
	- with the freestanding key and potentially a skull even further in tokensanity, this one did not seem worth the hint
- Water MQ BK chest 
	- this one could arguably stay in, but with the linear nature of MQ water, there is a 1/3 chance you need to do this one for the BK anyways, and once you put in tokens it goes even higher
- Shadow MQ bomb flower
	- with the freestanding key in MQ this one also seemed much less of a timesave (I would remove the one for regular shadow as well, but i did not want to add/remove the ones for standard weeklies)
- DMC fairy entrance
- Forest entrance

**Comment by flagrama** [comment]
It would probably be "in a meadow"

As for 
> Since I'm not a native English speaker, I'm not certain why some things got capitalized by the original author(s), when it is only parts of a name, e.g. Crater vs. valley. I just stuck with what has been done previously.

That's just nobody following english rules properly, as per usual on the internet :laughing: 
Those should probably be something like: Gerudo should always be capital. Valley should be capital if after Gerudo as "Gerudo Valley" is the proper noun of the location, but valley should be lowercase any other time it's just being used as a normal noun. Similarly; Death Mountain Crater, Death Mountain, mountain, mountain crater, crater.

**Comment by Hamsda** [comment]
Ok, let me clean up a little then!

**Comment by Zannick** [comment]
So, I would suggest:
* in the belly of a deity -> "swallowed by a deity" or "in the stomach of a deity" or "in a deity's stomach", not necessarily all the same one for variety's sake, e.g. "stingers swallowed..." and "stone in the stomach"
* "fractured #wall in the desert#" -> "#fractured wall in the desert#" or "#fractured desert wall#"?
* "the well of a village" -> "a village well"
* "a particular #wall in Zora's Fountain# hides" -> "a #fountain wall#"
* the Colossus should always be capitalized
* "in #a frozen fountain#, an opening" -> "an opening in #a frozen fountain#"
* "in Spirit Temple" vs "in the Fire Temple" etc. This is inconsistent. I would prefer "in the __ Temple" everywhere.

Rebasing rewrites your commits, so when you push to your github repo, it says that head doesn't match. You must have then pulled and merged, which is why you have multiple copies of the commits now. You have to force-push when you rebase if the original commits are already on github. (You could squash the commits if you like. Or maybe I'll do it when I merge.)

**Comment by Hamsda** [comment]
> the Colossus should always be capitalized

Hmm based on flags comment I un-capitalized that one, since it wasn't the full name `Desert Colossus` but rather just `colossus`. Why is English so derp...

> "in #a frozen fountain#, an opening" -> "an opening in #a frozen fountain#"

Good catch, I changed almost all of these around and missed that one!

> "in Spirit Temple" vs "in the Fire Temple" etc. This is inconsistent. I would prefer "in the __ Temple" everywhere.

I thought I converted all of these to `in __ Temple`, just for brevity's sake, but adding the `the` sounds better in my head, yeah.

And yeah, I'm not too familiar with rebasing. I fetched the upstream changes and merged them into my forks Dev branch and then rebased this branch onto that. Then it told me to pull before I pushed, so I did that lol. Hope I'll remember the force push for next time.

**Comment by Zannick** [comment]
Colossus as it's used here isn't a generic term like valley or crater imo. English is silly. :)

**Comment by flagrama** [comment]
A colossus is a object, not a place, so a bit different than I explained. Desert Colossus is a specific place and is named after the Colossus within it, but the Colossus is a specific object when being referred to. The game's text dump seems to capitalize The Colossus too, implying it is in fact a proper noun here.

**Comment by Hamsda** [comment]
Changes are in. I also changed `paying a fee #within Gerudo's Fortress# grants access to` to `paying a #fee to the Gerudos# grants access to`.

**Comment by r0bd0g** [comment]
(Added)
I'm cool with all of these:
GV cow, GS DMC crate, GS deku back room, GS DC MQ SoT blocks, GS Jabu MQ rang room, Jabu MQ cow, GS Water south basement, GS Water MQ south basement, Shadow MQ beamos silvers, GV storms grotto, BotW entrance.

HF Grotto Cow
I didn't realize exclusions for locations like these in ER was a thing?

Forest MQ island
I don't see why this one needs a hint. Logically speaking, the falling ceiling chest is strictly worse as you might need song of time to reach that. Only in the case where you don't have the longshot (or hovers out of logic with the trick off) to get it from the courtyard, the hint saves a very short backtrack from killing the green poe to the courtyard side door. Additionally, I dislike that there is a chest at this same position in vanilla that is not hinted. I would prefer if, where possible, equivalent locations all have the same hints so that the sometimes hints don't give away MQ/Vanilla dungeon information, except when necessary. It's particularly awkward when the text provided could apply to the location in both MQ or vanilla, and only by having secret knowledge of what locations can be hinted at by the randomizer can you discern whether you've got MQ or Vanilla from the hint.

GS Shadow near ship
It's pretty rare that you will come through here without at least bow to be able to peak it and see what it is. The hint is only really good in that case. I'm pretty on the fence with this one, but I feel like there are probably a lot of unhinted locations worse than this.


(Removed)
1st chu bowling
I don't even see why 2nd chu bowling is hinted. You can see what it is for 60r. That's not a big deal. If you struggle with minigames it's not going to help you to have this hint b/c you could always see whether you needed it or not anyway. I think it was only added b/c of the minigame category of hint needing some more locations to be worth having? Personally I would remove this hint, the 2nd bowling hint, and the whole minigame hint category as well, but I think if one or both do end up removed, perhaps the frequency of minigame hints in the distributions need to be reduced so that the other minigame locations don't get hinted even more often than they already do.

Fire MQ West Tower Top
I really disagree with removing this one. Again it does have a sometimes hint for the same spot in vanilla and as I said with the outside hookshot chest hint, it would be better if the hints don't give away whether you have MQ or Vanilla, especially if the provided text could apply to either version. But regardless of that I would argue that this one should stay. With skullsanity off I don't think the difference between compass chest to hammer chest in vanilla, vs the freestanding key to the topmost chest in MQ, is really all that much different. You have to walk a bit farther to reach the key in MQ (though to avoid fighting the Flaredancer, you have to know how to peak the key through the wall), but then to actually open the topmost chest takes longer because of where the switch is positioned, so it about evens out. Also, is there a possibility of getting locked by Volvagia between the freestanding and the final chest, if you have already used a key on the opening loop? And even with skullsanity on, with a little bit of janky know-how and the longshot, you can get the skulltula early, leaving the topmost chest as the final check of the dungeon.

Water MQ BK chest
Removing this one is fair, I guess. Especially since the hint is no longer mentioning the "gilded chest" specifically, and then the MQ variant of the room that has the BK chest has no boulders and is a freestanding key rather than a chest. Can you think of some way to hint the vanilla BK chest and the freestanding MQ key with the same hint text? You probably could but it would be quite a bit of a stretch. So probably best left as-is.

Shadow MQ bomb flower
I really think this one needs to stay as well. You say it's not much of a timesave, but it's a full-blown more-difficult than normal Dead Hand fight in an area that has a ton of requirements to visit. It's a really long check, and since it has an equivalent for vanilla, again I think both should be hinted and with the same text. It's a bit of a problem now that the hint is specifically mentioning the floormaster -- I think in this case it is worth it to think of some way to use the same text for both locations to keep the vanilla/mq information hidden a bit longer.

**Comment by Hamsda** [comment]
- HF Grotto Cow
Ye, see https://github.com/Hamsda/OoT-Randomizer/blob/hint_changes/HintList.py#L38
Presumably because these get hinted because of a combination of being remote + requirements for the grotto + requirements in the grotto. So in ER they aren't that terrible. Also because the hint descriptions reference where the grotto is.

- Forest MQ island
I just personally found this one annoying every time I played MQ forest. Fairly rare to have longshot early. Time wise it is in a similar fashion to the Floormaster hint for vanilla forest, though I have no idea why that one gets a hint anyways.

- GS Shadow near ship
Fair point, mainly added this one because it is the only hard longshot locked check in vanilla shadow, so getting a hint that it is the 5th small key or boss key can be nice.

- 1st chu bowling
Yeah I decidedly wanted a few more checks for the minigame category back when I added it. Getting a hint for the 2nd one is just a tiny time save. I am personally happy with strong/very strong 🤷‍♂ 

- the other 3
All of these seem to boil down to wanting to hint similar locations. I highly disagree with the notion that hints should try and hint equivalent locations to not give away MQ/vanilla. Especially if it forces us to write not great hints. Like you said yourself, Water would be a real stretch. And I think the shadows hint for MQ was terrible as well, since the shadows for Forest/Shadow vanilla refer to the Floormaster i thought (though the one in Forest isn't even invis, again, terrible hint), whereas this one has a 2nd Dead Hand. If the Shadow one is supposed to refer to the Floormasters outside, then how is that hinting at that room specifically. I agree the fight isn't super quick, but the requirements are the same for all the checks back there. All this made the hint really bad imo, so I removed it.

I'm not very attached to any of the added ones. I do think that removing the 3 MQ dungeon ones is the right choice though.

**Comment by Zannick** [comment]
How strong is gaining the knowledge that a dungeon is MQ/vanilla ahead of simply entering the dungeon? Knowing that a dungeon is MQ/vanilla means you know what items are requiring to beat/clear it. Usually you find out upon entering which it is, and prior you that you need the compass (if shuffled into the world or started with), or to go to the dungeon entrance. (Or to know how many MQs you have and count...)

I like the idea but if we can't do it for this Water BK chest then I'd argue it'd be better to go for consistency, and either not try to maintain equivalence or remove hints we can't reasonably equalize in order to maintain equivalence. And if it's not really that strong, then it's not as concerning that the hint can convey extra information to experienced players.

I don't play MQ enough to be familiar with these locations, so I'll have to ask the two of you to come to an agreement on this before I merge these in.

**Comment by Hamsda** [comment]
There are already a ton of hints that only exist for one version of the dungeon or the other, like Forest Floormaster or Fire Scarecrow. Once you add tokens it becomes even more.

So I don't get why we should try and force two chests, that just happen to be in the same spot but have very different requirement levels compared to the rest around them, to have the same hint.

**Comment by r0bd0g** [comment]
Some of those locations have hints just so that some check in the dungeon can be hinted. I think forest floormaster, the end of shadow, even dead hand in botw, all kind of exist b/c AA wanted to try and have a least one check per dungeon able to be sometimes hinted. So those checks were chosen as the "worst" check for those dungeons. If you remember back to early versions of the randomizer, chest above king dodongo used to be a sometimes hint, just b/c if DC was a stone then that was the worst check in dungeon, at least before hearts were shuffled. But it wasn't a hard rule since Jabu didn't used to have one. I guess just trying to explain where those sometimes hints came from.

I wanted to keep the hint texts the same for equivalent locations, where reasonable, so as to not devalue the maps with m&c info on. Regardless, having hint text that could read as being for either MQ or Vanilla is a problem, b/c I don't think it's fair to expect players to know that only the MQ or Vanilla version of the check is available to be hinted. So at the very least I'm opposed to having only one or the other hinted in cases where you can't tell which it is from only reading the text.

**Comment by Hamsda** [comment]
I mean that's something to bring up with the CoS in the future then. Like I don't want some last minute changes to influence standard weekly settings. I do fully agree that some hints for dungeons should just be gone entirely, because we basically only have them for legacy reasons.

**Comment by Zannick** [comment]
> Regardless, having hint text that could read as being for either MQ or Vanilla is a problem, b/c I don't think it's fair to expect players to know that only the MQ or Vanilla version of the check is available to be hinted.

You're saying that players shouldn't need to know when only one version of a location is hinted. I agree, but why? Because it gives away the MQ/V info in an opaque way? Players aren't guaranteed these hints; if they don't see a hint for Forest MQ Island they won't be able to infer the dungeon is V. I'm confused how you get to
> I'm opposed to having only one or the other hinted in cases where you can't tell which it is from only reading the text.

which is arguing for making it explicitly obvious whether the hint is MQ/V, and seems to me exactly the opposite of the other stance.

I agree with "players shouldn't need to know when only one version of a location is hinted" because my main concern is more that the player should easily understand where the hint is referring them, regardless of MQ/V.

I also agree with consulting the Council, in which case I'd prefer to take only the wording changes and leave the additions/removals for later.

**Comment by r0bd0g** [comment]
MQ/Vanilla information being useful definitely depends on a lot of factors. It's helpful if the dungeon is in an out of the way place and has high requirements to be able to get anything done. Of the dungeons with checks that we're debating, Fire Temple requires a fire source to get much of anything done, so you might prefer to not go out of your way to visit that dungeon until you have one. Shadow Temple has higher requirements with numerous checks locked by Longshot and Song of Time, as well as the early area checks being logically locked by all the keys, so you need Hovers or Fire Arrows to even get started. Water Temple hard requires Irons and quite a few of the checks require fire source as well, but I think we're mostly in agreement with Water Temple. It could also be helpful if the MQ information affects the value of the dungeon. Most of the MQ dungeons we're talking about do on average take a bit longer to clear. BotW and Jabu are the main two dungeons that change a lot in value, but I don't think there are any chests in those dungeons that we currently disagree about.

So it's very situational whether or not the MQ info is helpful. If I were to rate the typical helpfulness of the information I'd say it's like a 3/10. Regardless of whether the information is good or not, I think it's a bad design choice for the mere existence of a hint that doesn't actually contain any MQ or vanilla information in the text, to reveal the MQ/vanilla information only to players intimately familiar with the hint list. So I really think we should avoid this kind of scenario, and I don't think we have to sacrifice much at all to make it happen. There are three main ways to do it:
One, for when the locations are substantially similar, we use the same hint text to describe them.
Two is to ensure that the text is not ambiguous at all as to what dungeon the hint is for.
And three is to not hint either version.

**Comment by r0bd0g** [comment]
Going over again my thoughts on the 4 main points of contention:

Water Temple: I think both BK chests and the freestanding key are different enough checks that it doesn't make much sense to combine any of them them anymore. So this is a case where the hints would all be clear as to which version of the dungeon is being described.

Forest Temple Outside Hookshot Chest: I don't think there's any way to differentiate these chests with the text. The vanilla version of this chest definitely does not deserve a hint, but I think neither does the MQ version, so this would be a case where I would hint neither location. The slight backtrack from the green poe in the route the doesn't require the longshot isn't really worth talking about. So while it does sometimes require the longshot to get, the falling ceiling room chest is just way worse as it requires playing the Song of Time (multiple times, if you don't know the strat) and going through an additional room. It doesn't make sense to hint this location over falling ceiling. Regardless I don't think falling ceiling deserves one either. They're all just checks you will do in the process of clearing a relatively linear the dungeon.

Shadow Temple MQ Bomb Flower Room: This fight actually really sucks; super annoying. Especially if you are playing with lens logic not on all, you might have to get this guy out of the ground without even being able to see where he is. Sometimes he just doesn't even spawn or something so you might waste all of your bombs or something and he just never pops out. This fight is dumb and the location deserves a hint. We seem to also be stuck with a hint for the same location in vanilla. The checks are similar in that you go through an invisible maze and you fight a dumb enemy to spawn a chest. But they're different enough that I wouldn't be opposed to having the hint text clearly specify which version of the dungeon you've got, perhaps by always specifically mentioning the floormaster and the dead hand.

Fire Temple Final Chest: I don't think the vanilla version of this chest is so much worse that it deserves a hint while the MQ version doesn't. The distance from the previous check to the final chest is not all that much different, and in MQ you need an additional key to make the trek. There's also not a good way to differentiate the two chests in the text. So in this case I would hint both locations with the same text.

**Comment by Roman971** [comment]
HF Grotto Cow needs to be excluded if grotto entrances are shuffled, just like any location hint whose wording is based on the grotto location.

I'm not sure I agree with the addition/removal of entrance hints because it unbalances the amount of grotto vs interior vs dungeon hints.

**Comment by Zannick** [comment]
I think it's too close to the 5.2 release to have a thorough consideration of these and have them make it in. Can you split this PR into 2: one with the rewording of existing hints, which will make it in; and one with the additions and removals?

**Comment by Hamsda** [comment]
I honestly have no clue how I would do that, github noob :(

**Comment by Zannick** [comment]
Manually. :p Make a new branch and copy the rewordings only over.

**Comment by Hamsda** [comment]
Ah, sure thing, will do in a few.

**Comment by Mast3rGenius** [comment]
Don't agree with this change at all.

**Comment by Hamsda** [comment]
@r0bd0g 
I pretty much agree with all of what you wrote.

The 2nd Dead Hand fight in MQ shadow isn't that bad, usually just casting Dins is good enough, but you are probably right that he deserves a hint, even with there being an additional check back there in MQ. I just think the wording of the vanilla hint doesn't really fit, so yeah, I'll see if I can come up with some decent wording.

For Fire I personally think its a good bit worse, because like half the time coming from highest Goron or compass chest is spent before and with the Flare Dancer. So having the Key + chest (+ potentially skull) after is very different from just having the chest up there.
Though the better solution to what I did would probably be to hint both the chests up there with the same hint and have an extra hint for MQ skull?
I feel the wording we currently have for the vanilla chest doesn't really fit though, since talking about the Flare Dancer hiding something describes the freestanding key much better when talking about MQ. I'll see if I can come up with a description that fits them both without it being ambigious towards the scarecrow chest in vanilla (was thinking "chest in flame ring" initially).

I think we should rethink some of the hints that are currently in weeklies. I didn't wanna touch those on such short notice with 5.2 around the corner, but with this not being included, I feel there's room for debate.
E.g. Forest Floormaster, which has a key like 50% of the time anyways or so and doesn't cost that much time even if you have to get it. Like even a bow chest hint is sometimes more useful if you dip Forest without bow lol.

And I'll include the cow in the exclusion unless I can think of ways to describe the 3 excluded checks without referring to their non entrance shuffled locations.

**Comment by r0bd0g** [comment]
One thing I want to add I guess is that you can do the c-up trick on MQ to see what is inside the elevator, so you can potentially skip fighting the flare dancer, if that wasn't clear, but it does require some knowhow to take full advantage of a hint for that final chest.

Perhaps the hint could say "Flare dancers guard a -chest containing-" rather than just saying they guard it?

**Comment by Hamsda** [comment]
No duplicate commits this time, but the old ones are shown down here again? <.<

Anyways, I tinkered some more with it:

- I removed the minigame category: 
Added it like a year ago, but it never really worked well, and people who dislike any of the minigames will just disable them anyways.
- Links House Cow now is an always hint:
This one is really time consuming, so if you run into cow shuffle in mystery and have hints, they should really give you this one.
- New wording for the hints that were based on their location:
I think this wording works quite well. The highlighted part should be clear enough, but I added `in a grotto` just to make sure people realize its those.
- Removed Forest Temple hints:
r0b made a good case for why the MQ Forest one shouldn't have one. 
And since this is not last minute before 5.2 now, I wanna include changes that should really happen, but would have affected weekly settings on too short notice. Forest Floormaster being a hint that I think nobody feels really great about, half the time you need to get it anyways, and many other times you can get it decently fast with hovers/recoil/from BK.
- New wording for Fire Temple west tower:
Took what r0b suggested, but I think this might be too long? I'll have to test this in game first.
- Shadow MQ Dead Hand 2 hint is back:
Still not sure if I like the wording, but `shadows` is a pretty good description for invisible enemies, which is pretty certainly the Floormaster and Dead Hand respectively.
I wonder if the vanilla Floormaster one deserves a hint even?
Similarly not sure if the Beamos one for MQ deserves a hint. My thinking here was mostly that you might not have longshot, so you might leave this one behind and open the shortcut, since you only hard require longshot in the back of MQ Shadow. But if you have longshot, it is really not a slow check.

As usual, feedback needed for this one. I may work on these some more in the next few days.

**Comment by r0bd0g** [comment]
I read through this again and have some assorted thoughts, idk. Really only this first one in Deku do I really care about, the rest of it is pretty pointless. I kind of want to go through and make a list of every crappy location and discuss whether it could have a hint but I don't want to take the time to do that right now lol.

GS Deku Tree Basement Back Room: Looking this over a realized this check has an MQ equivalent that the current text could apply to. The main difference between the two checks is that vanilla requires explosives, so maybe that could be worked into the text somehow. There are already so many checks back there on MQ that have sometimes hints, I don't know if it needs another, especially when the ceiling is strictly worse, but hinting both locations with the same text wouldn't be the end of the world either.

GS Dodongo's Cavern MQ Song of Time Block Room: I guess I just wanted to ask why you chose this check to hint? I'm not saying it's the wrong choice, I guess I'm just wondering if you considered Gohma larvae room? I think those are worst checks of the dungeon since you'd rather clear DC as adult but those two checks could be child-only if you don't have a fire source. I guess if you get owned by the larvae room it's more your fault b/c you could have done it as child, whereas the song of time GS you might not have had the requirements.

GS Jabu Jabu MQ Boomerang Room: I wanted to point out that this check is very easy to peak without song of time, and pretty easy to get without it as well if you have Boomerang. But you do have to know a couple of tricks. If you're intending this hint for racers, it's not really needed, but more casual players would appreciate it.

a spider under a #crate in the crater# holds
a #spider under a block in the volcano# holds
I worry that these two hints are worded so similarly? Not sure what could be done about it. I guess I also just noticed the highlighting is a bit inconsistent there.

Shadow Temple MQ Beamos Silver Rupees Chest: I'm torn on this one as well. On the one hand it's a really quick check, but on the other hand I've last-locationed my go mode there multiple times. It's made worse b/c I know how to skip longshot for the back rooms of the dungeon. For most players, there will be more longshot requirements than just this, so I feel like it's more likely for them to want/need to dip the dungeon again after finding longshot. A routing option you can try here when double-dipping after longshot is to void out after the beamos chest (not as great on ohko), which brings you back very close to the block shortcut.

**Comment by Hamsda** [comment]
Thanks for the feedback!

- GS Deku Tree Basement Back Room:
Hmm yeah, I hadn't thought of the fact that the MQ one is the same basically, since as you said the 2 SoT ones there are pretty much worse.
- GS Dodongo's Cavern MQ Song of Time Block Room:
Yeah I considered the larvae checks... tbh i'm not sure which is worse. The SoT one just feels annoying to do and outside of ER you probably have access to larvae room as kid usually.
- GS Jabu Jabu MQ Boomerang Room:
Wasn't quite sure about this one either. It's probably fair to get rid of this one, the invisible enemies one is by far worse (especially with lens not set to everywhere and people being unfamiliar with this room).
- Shadow Temple MQ Beamos Silver Rupees Chest:
That void out is a neat idea for going up to boat w/o LS!
As I already said, really not sure if this is worth the hint in the end since it's basically "on the way" if you have everything to clear shadow.
- spider wording:
`in the volcano` in clear hints will read as `in the Fire Temple`, though this is a fair point. Maybe being cryptic about the Fire Temple is not the right choice here...

I'll probably make more changes to some of the highlighting, since that's one of the key points why I started working on these again.

**Comment by r0bd0g** [comment]
Not sure if my routing option in shadow got across correctly? The idea is, if you've cleared the dungeon without longshot and pull the block, and then later come back with longshot to finish the dungeon, you get beamos rupees chest and then void out back to the start of the long hallway.

**Comment by Hamsda** [comment]
Yeah I got the shadow idea. :)

Tbh I'm not sure who the hints are intended for... optimally they are sorta useful for both audiences?

**Comment by Zannick** [comment]
Are these ready for review?

**Comment by Hamsda** [comment]
Okay, for now these should be good for review @Zannick 
Probably could still use some work until 6.0, but overall I think the hints are in better shape than previously, especially for just scanning the highlighted parts (if you know the hints of course).

**Comment by r0bd0g** [comment]
Wait did you get rid of Deku back room? I've been owned by that check so many times lol.

I actually thought "darkness hides" in the composer grave was a pretty clever way of putting it.

**Comment by matthewkirby** [comment]
1. While this has just been pending review for awhile, I noticed this hint yesterday
`'Deku Tree MQ After Spinning Log Chest':                    ("a #temporal stone within a tree# contains", None, ['dungeon', 'sometimes']),`.

Why do some dungeons have `clearer_hints` options and other don't. It isn't super clear to me why we swap between `a volcano` and `Fire Temple` but not between `a tree`, `a cavern', and `a diety`?

2. While I am looking at the hints as well:
`    'Spirit Temple MQ Child Center Chest':                      ("a #temporal paradox in the Colossus# yields", "a #temporal paradox in the Spirit Temple# yields", ['dungeon', 'sometimes']),` 
This could also be problematic if dungeon ER is on (the non-clear hint). With dungeon ER, Colossus is not necessarily Spirit Temple.

3. For song of storms grottos, why are some explicit on the region but others are not?
```
    'Zoras Domain -> Zoras Domain Storms Grotto':               ("a #storm within Zora's Domain# reveals", None, 'entrance'),
    'Hyrule Castle Grounds -> Castle Storms Grotto':            ("a #storm near the castle# reveals", None, 'entrance'),
```

**Comment by r0bd0g** [comment]
The use of "the colossus" there is based on the sheik text that refers to Spirit Temple as the colossus of the sand or something to that effect. In the non-clear hints, Spirit Temple is generally referred to by this name.

**Comment by Zannick** [comment]
I'll review this today, should be in this weekend if it's good. Followups after will be welcome.

**Pull request merged**
