### PR TITLE
Dungeon ER: Adult Deku Entrance Requires Showing Mido Sword & Shield.

### PR DESCRIPTION
**Pull request by Cuphat**
This follows the precedent set from the Bottom of the Well entrance or the Ice Cavern entrance. If both Closed Deku and Dungeon ER are enabled, this requires showing Mido the sword & shield as a child to open Deku Tree's mouth. This won't effect Open Forest or ER off.

### CODE REVIEW

**Comment by rattus128** [comment]
Upvote from me, this is a nice balance fix that has been on my wish list for a while.

Can we make a note on the closed-deku tooltip?

I am a little worried the behavior is slightly non-intuitive, in that with an adult start between the two settings will not give any indication of what you need to do to open the door (people dont read tooltips). Looking for in-game ideas.

A gossip might do it or maybe navi could say something?

I'm also open to the idea of child having to visit the meadow to open adult deku regardless of closed forest settings, which makes ER more self consistent across the closed deku settings toggle. In child start open forest, this costs almost nothing to route in. In adult start (closed door) adult loses a free dungeon but in very ok with that (bordering on much in favour of) as those settings are asking for a more closed starting world.

To implement it this way, you would want to probably restore the few seconds of cutscene where the jaw opens so the player can see what happened.

But if we cant do any of that, i'd much prefer this behavior over the current for 5.0

**Comment by flagrama** [comment]
What is the thought process behind 
> I'm also open to the idea of child having to visit the meadow to open adult deku regardless of closed forest settings,

That makes no sense to me. Closed Forest/Deku should probably both do it if Closed Forest ever finds itself no longer impossible with Adult Start, but Open Forest is Open Forest IMO.

As for fixing the problem with not knowing how to open it, perhaps there is some way to create a Z-targetable area on the tree's mouth while it is closed? Either making the mouth itself actually targetable, or something similar to the "???" text box that several of the Great Fairy Fountain entrances have? (Speaking of, I'll have a suggestion for those in the Discord in a second too)

**Comment by Roman971** [comment]
I mentioned this before when it came up but I personally really don't like that we are adding cross-age restrictions like that where they don't exist in the original game. In my opinion, it's already an issue that you have to play the SoS in the Windmill as child in order to open it for adult.

I get that leaving Deku Tree completely open for adult goes against the point of Closed Deku, but I find this particular solution inelegant and forcing child to come and open it for adult seems like a bad design decision to me. 
There is a reason a lot of people hate the whole Ice Cavern situation so much that there is now an option to have it open from the start. And of course the game developers never intended it to be played that way since you were supposed to complete Jabu before ever becoming adult.

I think we need a solution for Closed Deku as adult in ER but I don't think it should include having to do something as child.

**Comment by flagrama** [comment]
The restrictions do exist in the original game though? You literally can't access bottom of the well or deku tree at all as adult. ER is the thing changing the original game. I don't want it to do it quite as strongly which is why I want to play closed deku and have it not open until I open it as child.

I understand it is done because it would restrict the randomization so I accept that you do it to allow them to be mixed. I don't like that their access restrictions are changed which is why I'm happy with the bottom of the well and deku tree being like this.

**Comment by r0bd0g** [comment]
I don't know if it matters but I think deku baba sticks/nuts as adult in kokiri forest should be moved to the other side of mido for this PR.

**Comment by TestRunnerSRL** [comment]
I do kinda wish there was a way for adult to get past mido as well with the proper item requirements. It's one of the annoying behaviors of botw currently

**Comment by Hamsda** [comment]
I don't think it is bad if we have some cross age interactions like this tbh, as long as you don't have to do it all the time.

The ones I can think of at the moment:
- using hammer/bow to open parts of Death Mountain or Goron City for kid
- storms to open BotW for adult
- handing in rutos letter to access beyond KZ as adult
- planting beans

The chances for any of these happening depend on settings obviously, but most seem rare enough or fall into the "you signed up for this" category, I feel. So I wouldn't mind adding opening the mouth based on showing Mido your kid equipment for both ages?

One other thing I would find interesting is iron boots to access a filled well as an alternative to storms (dungeon ER ofc). When it was always open as adult with the boulder removed, that resulted in almost always going in as adult and storms became way less useful. But if it were filled as both ages (and no boulder as adult), you'd have two ways into the dungeon. This also wouldn't affect non-ER at all, since adult can't do anything in BotW anyways.

**Comment by rattus128** [comment]
I agree, especially considering this is explicitly behind an option that
closes off the world. When combined with closed door adult start, letting
adult open is not just a timesaver but a fundamental logic change.

I just dont think that you can cater to a closed world and avoid double
dipping. They asked for a harder to route seed so we should give it to them.

Regarding the well, part of rando is routing strategy, and you quickly find
yourself just routing well opening in with dampe digging and chickens.
Allowing adult would again be a fundamental logic change for closed door
play, opening the world up more after opting in to a close setting.

**Comment by Cuphat** [comment]
Literally adding Mido to adult Kokiri would take editing the scene which is again something I have no actual clue how to do but I've already nearly rewritten most of Mido's spawn ASM already so it is not like it'd be hard to get him to spawn there at this point probably.

**Pull request merged**
