### PR TITLE
Move pending item queue to save data

### PR DESCRIPTION
**Pull request by fenhl**
This is intended as an alternative to #1693. Instead of preventing pausing which could have negative side effects as discussed on that PR, this PR ensures that pending items don't get lost on savewarps by storing them in the save data.

I originally suggested using separate item queues and only persisting delayed items, not incoming multiworld items, but the behavior would be the same and not splitting the queues leads to simpler code.

Not tested yet.

### CODE REVIEW

**Comment by fenhl** [comment]
I have tested to confirm that this does fix the bug in question, i.e. if you savewarp out of ToT before checking LACS, you receive the item after respawning.

**Comment by fenhl** [comment]
We just completed a 14-person multiworld on my branch and there didn't seem to be any issues related to this PR.

**Review by Cuphat — APPROVED** [review]

**Comment by ETR-BTF** [comment]
Does this fix #1703 also?

**Comment by fenhl** [comment]
Unsure. You can test on <https://github.com/fenhl/OoT-Randomizer> (GitHub, not web).

**Comment by ETR-BTF** [comment]
Sadly, it does not fix it :(

**Pull request merged**
