### PR TITLE
Added 'No Ocarina of Time Reward' and 'No Frog Ocarina Game' Settings

### PR DESCRIPTION
**Pull request by Cuphat**

### CODE REVIEW

**Comment by Hamsda** [comment]
Was trying to get the same thing working last night.
Does this generate for you without song shuffle on but with the no oot required? It could never place the songs because of how the fill treats songs for me 🤔

**Comment by Cuphat** [comment]
@Hamsda The rule logic has to be `(not (logic_no_ocarina_of_time and shuffle_song_items))` to allow that spot to get a song placed, then in can_play it checks to see if the song is from the Song from Ocarina location and returns false to make the song not required.

**Comment by Hamsda** [comment]
oh its the can_play change I missed, I see
welp time to delete my branch :D

**Comment by Cuphat** [comment]
This thing is finicky as fuck, I swear it was working perfectly last night but I might have to take a harder look at it. It seems to have a rare seed where shit goes bonkers.

**Comment by Cuphat** [comment]
It already affects the hint exclusion because if it is off, that location is always Ocarina of Time. It affects the rules so that fill_songs can actually still place a song there. I am just a moron for not actually checking if the game is still beatable after songs are placed.

**Comment by Cuphat** [comment]
This should actually work as intended now, I think.

**Comment by Cuphat** [comment]
I believe I have figured this out for real this time. Going to do more testing, then I'll re-open and push everything.

**Pull request merged**
