### PR TITLE
Easter egg hunt setting

### PR DESCRIPTION
**Pull request by fenhl**
This adds a setting that replaces all Triforce pieces in the item pool with Easter eggs. Easter eggs come in four colors and otherwise behave like Triforce pieces, so this is purely a visual change.

This setting has been used twice for Freaky Friday races around Easter, so having it on main Dev would be convenient if they wanted to repeat this in the future. The changes made to get things working (including in multiworld) could also be useful for anyone implementing their own variant of Triforce Hunt, such as Triforce Blitz. Since it's somewhat of a niche setting, I decided not to include it in the GUI, though this can of course be changed if desired.

Credit to @KevinPal for [the original implementation](https://github.com/KevinPal/OoT-Randomizer/tree/triforce_easteregg) this PR is based on. The main change compared to that branch is that instead of editing the egg item model from the base game to be pink, this PR adds edited copies as new files. This means that the Weird Egg and the Pocket Egg retain their vanilla appearance.

The feature is ready to play in its current state, but there are some nice-to-have things currently missing:

- [x] Easter eggs are missing cryptic hint text, so they're currently hinted as “an Easter Egg” even without the Clearer Hints setting. Suggestions welcome.
- [ ] The HUD still displays a rotating Triforce piece. If anyone knows how to edit it, it would be cool to have it display as an Easter egg with some sort of pattern painted on it so the rotating animation is visible.

### CODE REVIEW

**Comment by r0bd0g** [comment]
I suggest removing references to "Easter" and just calling it an Egg hunt or something along those lines.

**Comment by fenhl** [comment]
Why?

**Comment by r0bd0g** [comment]
I don't think the religious reference is appropriate.
Honestly the whole setting leaves a bad taste.
(Next up, replace all hints with Bible verses.)

**Comment by fenhl** [comment]
I was under the mistaken assumption that Easter egg hunts weren't an exclusively Christian thing. Still, I think the religious reference is fine given that it's in a hidden and completely optional setting, and not comparable to the most recent edit of your comment, which would be forcing something on everyone. Including the word Easter in the name helps quickly explain what the setting does, and I don't think leaving it out would make much of a difference since the reference would be easily identifiable regardless. That said, if there are others who share this concern, I'd be willing to reconsider, so please speak up. In the meantime, I'll be rethinking how to handle this setting on my personal branch where it does appear on the GUI.

**Comment by r0bd0g** [comment]
(I meant it like, the egg hunt setting would be the one with the bible verses everywhere. Like, just fully embrace the Message.)
Did you remember the altar wincon text?

**Comment by Cuphat** [comment]
I do find it funny that by making it a hidden setting that can't be enabled on the GUI, it turns the setting into... an easter egg.

**Comment by cjohnson57** [comment]
Yeah I mean, sure the Easter holiday has religious connotations but so does Christmas and it feels a bit much to restrict usage of the word. Especially when Easter Egg has become such a ubiquitous term in game culture.

That being said, I'm not sure if I feel this should really be something for the main branch. Maple and I wanted to make a Golden Banana TH at some point and I never considered bringing it to main, lol

**Comment by fenhl** [comment]
Marking as draft since a gen failure was discovered that happens when the randomizer attempts to cloak an ice trap as an Easter egg (since Easter eggs have get item IDs greater than 255).

**Comment by cjohnson57** [comment]
Sorry, don't think we'll be merging this

**Pull request closed without merging**
