### PR TITLE
Merge Explosive logics into one.

### PR DESCRIPTION
**Pull request by dotzo**
Made Bombchus in Logic a default option.  Bowling will require a bomb bag, as will the rolling goron.  Chus are progressive by default.  Refills will still appear in the bombchu shop, bazaar, and kokiri shop, and will only be purchase-able once you have possession of chus.  Removed references to bombchus_in_logic everywhere in the code, defaulting to True, this includes logic.  bombchus are now permanently a major item

### CODE REVIEW

**Comment by r0bd0g** [comment]
Regardless of whether this is a good idea, you forgot to remove the rolling goron with strength trick option.

**Comment by TestRunnerSRL** [comment]
Buhhh, as much as I'd like to force bombchu in logic on, this sounds like something that the community would be really against. Also bombchu bowling requires bombchus normally because you can just get bomchus from the game, so if it can use bombbag, then you can always use bombbag to get bombchus anyways. I don't get why the change the rolling goron either

**Comment by dotzo** [comment]
The flag changes for bowling/goron were to go back more toward vanilla / pull in parts of chus not in logic.   The goal is a hybrid "explosives in logic" rather than changing it to be exclusively chus for everything.  If it were possible to do EITHER bag/chus for bowling that'd be fine, but idk how to do that in ASM.

**Comment by TestRunnerSRL** [comment]
I mean that's the same problem either way. I also feel that trying to compromise over this is basically taking the worst of both worlds. Bombchu in logic makes various changes that if you don't take will break the entire logic around the option. As for being "like vanilla", besides the fact that I couldn't care less about vanilla, vanilla would be beating DC. Normally, after beating DC, you also gain access to Bombchus Shop and Bombchu Bowling, while bombbag is before beating DC. So bowling is unlocked by having the bombchus, not the bomb bag in vanilla.

**Comment by dotzo** [comment]
Yea, i'm aware of that. obviously going all the way with vanilla flags is stupid. bag is objectively closer, though.  idk, shit at work broke so i got bored. do with it what you will.

**Comment by Cuphat** [comment]
Honestly? This doesn't sound like an awful idea to have as a middle-ground option for bombchus logic. Forcing this as the default and only option seems bad though.

**Pull request closed without merging**
