### PR TITLE
Ignore title file for real for Ganon BK conditions.

### LINKED ISSUE #1414: Not saving and not continuing gives Ganon BK
1. Set Ganon BK to be awarded on 6 medallions.
2. Create new file.
3. Die to the first enemy you find.  Wow, you suck at this game.
4. Select No for both "Do you want to save" and "Do you want to continue" (Gotta save those nuts).
5. Start the same file again.
6. Get the Ganon BK?

I've reproed this on both dev and devR; here's the dev seed.
https://ootrandomizer.com/seed/get?id=904544
Platform used: RetroArch ParaLLEl N64 on Windows

### PR DESCRIPTION
**Pull request by Cuphat**
The file index is apparently not set back to 255 when dying and selecting "Don't Continue". Check for the title file's Deku Stick count instead (which is helpfully 50, which is not possible without ACE level shenanigans).

Fixes #1414.

### CODE REVIEW

**Comment by Zannick** [comment]
I've not seen anyone suggest how to detect being on the title screen or in attract mode, nor whether or not that would work. A compromise could involve testing the checksum and then the 50 sticks.

**Comment by r0bd0g** [comment]
There's a byte that's set to 0 normally, 1 title screen, 2 file select, though I forget what values higher than that get interpreted as, so you might have to check. I don't have the address on hand, nor do I know how to find it aside from loading up the game and searching for it with mhs, though I'm sure there's a place where it's documented.

**Comment by Cuphat** [comment]
Literally the only thing wrong with checking the checksum is the 1/65536 chance that you'd effectively randomly (though there is nothing random about it) end up with a 0 checksum. I personally have no problems saying if you want to title file SRM a rando you better break a damn stick to make the Ganon BK condition work. If anyone has a more precise byte to determine this shit or even an ASM hack to set the file index to 255 when dying/not continuing, I am all ears. This might not be the most ideal fix on the planet but you have to actively try to fuck it up (like, who has SRM'd in rando? especially since we break most of those setups already.) and it fixes the much more important bug.

**Comment by Cuphat** [comment]
Now fixed to check game_mode instead. See commit message:

`Rename z64_file_t.interface_flag to game_mode (based on decomp) and check that it is 0 to give Ganon BK. It is seemingly 1 on the title cutscene, 2 on file select, and 0 during normal gameplay. This has already been used for CAN_USE_DPAD and CAN_DRAW_TRIFORCE in the past.`

**Review by Zannick — APPROVED** [review]

**Pull request merged**
