### PR TITLE
Revert removal of dungeon summary menu Take #2

### PR DESCRIPTION
**Pull request by mracsys**
Re-opened after consensus on the ootr discord.

Add the A button menu back into the game. Overall size is shrunk to better fit on screens with overscan. This includes a check to remove dungeon reward icons from the summary if mixed entrance pools is a valid option and Boss type entrances are mixed.

Having one screen with all of the info is more convenient than three submenus. It is also easier in my opinion to hold the A button than a specific d-pad direction.

Tested on PJ64, N64, and Wii VC.

This also includes a minor fix to prevent the d-pad icons from flashing between the boots and dungeon icons when equipping items on C buttons. D-pad boots/ocarina inputs on pause/unpause are preserved.

Menu with at least one entry in every slot:
image

Text legibility on N64:
image

### CODE REVIEW

**Comment by r0bd0g** [comment]
N64 res is a little rough. Can you show me all of the numbers?

**Comment by ETR-BTF** [comment]
> N64 res is a little rough. Can you show me what all of the numbers look like?

In particular I'm curious about how the 3 looks next to an 8.

**Comment by cjohnson57** [comment]
D-Pad menu is untouched.

**Comment by mracsys** [comment]
As-is, 0's and 8's are hard to tell apart:

image

Changing the 0's to capital O's, it's clearer and doesn't look odd:

image

For comparison, the d-pad key menu (unchanged):

image

Also note that my capture card is darker than the TV image. On my TV the 5, 7, F, T, and I all have clear top lines instead of looking like they are chopped off.

**Comment by cjohnson57** [comment]
Yeah, the O is thin enough that it still looks like a 0, It'd make sense to change it to that (although if you do then you should change it for the other menu too for consistency)

**Comment by cjohnson57** [comment]
One last thing I just noticed, when I go to the key menu there are what look like backslashes on the right of the screen for some reason, they're only there on that menu and only on this branch as far as I can tell.
image

**Pull request merged**
