### PR TITLE
Add new bombchu options

### PR DESCRIPTION
**Pull request by rlbond86**
Change the "Include Bombchus in Logic" checkbox to a dropdown with four options:

* "Included in Logic": Bombchus are included in logic (equivalent to the old checkbox being selected)
* "Included in Logic (Discounted)": Bombchus are included in logic, but their price is reduced.
* "Excluded from Logic": Bombchus are not factored in logic, but are still included in the random pool and can be bought from the Bombchu Salesman.
* "Removed from Item Pool": Bombchus are removed from the pool entirely and the Haunted Desert Bombchu Salesman is removed. The Spirit Trial door in Ganon's Tower is unlocked. A few boulders in Spirit Temple MQ are removed. Logic assumes Link never has Bombchus. (Bombchus can still be won at Bombchu Bowling or purchased in the Back Alley after obtaining bombs).

The reason this change was introduced is to try to address some issues with the current two bombchu options.

* "Included in Logic": This mode properly accounts for bombchus in the logic, but sometimes the player has to go through large sections of the game with no access to regular bombs. This can be annoying, as bombchus are expensive and not dropped by enemies. Additionally, under the default settings some sort of explosives are easy to find, considering 3 levels of bomb bags and several bombchu items in the pool.

* "Excluded in Logic": This mode does not force the player to buy large numbers of bombchus to get through the game, however finding bombchus allows the player to sequence break in unpredictable ways. Using the found bombchus can be a gamble and players can be encouraged to save before using one and then restart if nothing is revealed.

* "Included in Logic (Discounted)": This mode attempts to reduce player frustration by reducing the price of Bombchus. The price of Bombchus is reduced to 30/55/90. 

* "Removed from Item Pool": This new mode removes bombchus from logic and from the item pool. Players will never find bombchus, and all logic assumes that the player never obtains them. A small number of changes to the game are made to make it beatable (in Vanilla, a door in Ganon's Tower is unlocked; in MQ, three boulders are additionally removed). However, bombchu are sometimes useful and some players may like to have them in the game or dislike making changes to the game by unlocking doors or removing boulders.

### CODE REVIEW

**Comment by r0bd0g** [comment]
MQ Spirit is impossible without bombchus.

**Comment by TestRunnerSRL** [comment]
Hmm, I dunno, this feels weird.

I don't think the discounted option is really needed. The first bombchu is always a 20 pack, and the bombchus are already fairly affordable. You typically shouldn't ever need to by more than one 10-pack even if you aren't being careful with the counts. Like if you really are having money problems here, you probably have it with everything else, like sticks and tunics. Might as well just use the start with rupee option at that point. If this is supposed to be like the deku scrubs, the deku scrubs have the option cause using vanilla prices ends up being thousands of rupees, which is pretty ridiculous.

I don't get the point of the "remove bombchus from itempool".

The other options I assume are basically the current behaviors. The whole point of the "bombchus in logic" option was basically that logic was unable to consider a bombchus from chests because they could run out. The solution was to make minor changes to the shops/minigames such that the bombchus could be properly considered in logic, which allows for a lot more route variety and more even pacing. (It also made some other minor changes to allow them to be more accessible so you wouldn't run into the rupee grind problem).

**Comment by rlbond86** [comment]
I'm not sure about only needing one 10-pack. The fire temple and dodongo alone probably need 30 bombs between them. If you only have the 99 rupee wallet it's easy to get into a very annoying grind for more bombchus. That doesn't happen with the tunics where you are guaranteed to be able to get a bigger wallet. 

The "remove from pool" option exists because bombchu are weird. You basically never need them to beat the game except for a single spot. And it makes all these issues. There are something like 6 bombchu items and 3 bomb bags so the player is more likely to find bombchu first.

Really I think "included in logic" is the better option than "excluded in logic" though. I consider removing bombchus outright to be better than having bombchus in a weird state of being outside logic altogether.

Anyway there's at least some useful code in there to modify and delete actors so maybe give that a look

**Comment by TestRunnerSRL** [comment]
I might have my counts off, but
DC is 13 bombs
Fire is 5 Bombs
OW checks are ~10 bombs
Goron City is 4 bombs
Water is 1 bomb
BotW is 3 bombs
Shadow is 2 bombs
Spirit is 2 bombs

So worst case this is roughly 40 bombs. However having any of the 3 strength upgrades or hammer drops this to less than 30, which means you could use any of 9 items. So it's extremely likely to not ever need more than 30 even if you aren't being careful. Even if you still need bombchus for DC, you're also banking that you don't find any of these 9 items to reduce your bombchu reqs or just finding more bombchus in the 100+ available checks. Having done quite a few seeds, I've never needed to buy more than a single 99 rupee 10-pack in a run. In fact, I can usually get away with not buying any bombchus at all, since I generally always just find more packs in the field or a bombbag before I ever get close to running out.

**Pull request closed without merging**
