### PR TITLE
Added 'Start With' option to Shuffle Maps/Compasses

### PR DESCRIPTION
**Pull request by Cuphat**
This option works with Enhanced Maps/Compasses and gives the player all the maps and compasses from the start.

### CODE REVIEW

**Comment by Cuphat** [comment]
I won't lie, the main reason I want this is so I know where the dang chests are in Master Quest.

That said, I think it fits. It's equivalent to remove in what it does to the item pool, but it still gives you the maps/compasses. Maps and compasses are cool and have at least some use, even if you shouldn't need them once you are familiar with the game.

**Comment by r0bd0g** [comment]
I guess I'll give an opinion here. Feel free to ignore me.

I'm not sure if this setting needs to work together with enhance map/compass. If enhance maps is off, you'll see the mq/vanilla data at all times anyway. And with enhance compasses off, the information about the pedestal is just there to read to get that information. It'll take 2 seconds to read it as you pass by. I think I'd prefer if it functioned identically to 'remove'. Actually I'm not sure if remove shouldn't just behave like this.

I feel like a better solution would be to have a checkbox that makes the map/compass data visible inside the dungeons regardless of whether you have the maps or compasses, but of course that would be harder to implement, for so little benefit.

**Comment by Cuphat** [comment]
I've updated the naming of it to 'Start With'.

I can see the argument that it's not really a game changer to allow Enhance Maps/Compasses, but it seems a bit arbitrary to disallow it and it does change things in a minor way since you can check it immediately.

**Comment by phixtyseven** [comment]
I agree that it is very similar to the remove option, we could probably just replace the old option altogether. I can't easily imagine someone complaining about not having an option to permanently hide all the dungeon info, including chest locations.

On the other hand, the remove option is already there, and it works. It's just a question of whether the distinction preserved by keeping the two options is substantial enough to be worth the time a user spends figuring out which options they want to play with.

As far as labels go, maybe consider free

**Comment by TestRunnerSRL** [comment]
I decided that the restriction on when enhanced map and compass should be valid was not necessary. You can now use it for any option. It might seem like some of the option combinations are somewhat silly since the information is being removed, but some people may like to play with such a configuration. I think this is cleaner in the end. Also added a note about the ToT Altar, since that's pretty relevant. I kinda want the name of the option to include the ToT in it, but it's already so long.

**Pull request merged**
