### PR TITLE
Fix door of time collision not being deleted.

### PR DESCRIPTION
**Pull request by louist103**
Same as #1295 but I am re doing the PR cause something went horribly wrong on my local branches.  I'll close that one after creating this.

### CODE REVIEW

**Comment by Zannick** [comment]
@Roman971 mind reviewing this one?

**Comment by Roman971** [comment]
I think there is still something wrong with this branch, since it looks it was based on master instead of Dev according to the commit history. And I don't think we typically squash commits when merging, so I think this will have to be fixed on your side.

I suggest making a completely new branch for this and cherry-picking only the changes involved in the fix. I believe you should even be able to do this without creating a new PR, if you force push the new branch to replace the old branch.

**Review by Roman971 — COMMENTED** [review]
Here are my comments when it comes to the actual review:

**Comment by Zannick** [comment]
Much appreciated if you do the rebase/cherry-pick, and watch out for this in the future. What Roman is suggesting is:

```
git checkout -b dotfix2 Dev
git cherry-pick e40ad7c b180a5d
# (resolve merge conflicts and git add and git cherry-pick --continue)
# (test that it looks right to you)
git push -f dotfix2 origin/dotfix
# git checkout -B dotfix dotfix2 # to change your old branch to the cleaned-up version
```

I may be able to do this for you, but note if you tried to then pull the branch you'd get your local, 6.0-release-based branch merging back in unless you do some further trickery.

**Comment by Zannick** [comment]
Rebased and squashed into a single commit. This should still be the same content, please let me know if it's not.

At this point, we shouldn't need to merge Dev anymore, even if it updates.

**Review by Zannick — APPROVED** [review]

**Pull request merged**
