### PR TITLE
Remove scarecrow spawn cutscene

### PR DESCRIPTION
**Pull request by GSKirox**
Pretty straightforward, just remove the small cutscene of Pierre spawning.
Also works with free Scarecrow setting.

https://user-images.githubusercontent.com/65768236/223808795-55e75ffb-e3d3-408f-9b07-43ab164596f8.mp4

### CODE REVIEW

**Comment by ETR-BTF** [comment]
The sound in the clip doesn't work for me. Is there still a little fanfare when the scarecrow spawns? I think it's important to keep at least some indication that the scarecrow spawned successfully.

**Comment by GSKirox** [comment]
Oh yeah i'm recording without sound *facepalm* Great job me.
Yeah the fanfare still plays.

**Comment by r0bd0g** [comment]
Did you test with free scarecrow?

**Comment by fenhl** [comment]
> Also works with free Scarecrow setting.

**Pull request merged**
