### PR TITLE
Allow Impas House to straddle hint regions in ER, while only using the back entrance for hints

### LINKED ISSUE #1047: Impa's House Cow uses Front exit of Impa's House for its hint region
... rather than the back of the house as was intended.
I don't believe you can actually experience the consequences of this bug on the official builds, though.
This also means the "False" exit out of Impa's Cow region is doing nothing. Actually apparently it gets pruned as useless anyway?

### PR DESCRIPTION
**Pull request by Zannick**
based on a conversation yesterday with @r0bd0g, and fixes #1047.

This is done with a "hint_region" annotation, that allows us to specify when a region should be given hints as though its another. Namely, locations in the region where the cow is (`Kak Impas House Near Cow`) will find their hint area by searching for a hint area from `Kak Impas House Back`.

Without this annotation, the hint area for the `Kak Impas House Near Cow` region would be dependent on the ordering of its entrances...

Includes a minor refactor of `main()` to set up a unittest that has access to the World object.

### CODE REVIEW

**Comment by Roman971** [comment]
I don't understand what's the point of this change. We already ensure both entrances are in the same hint area, so it doesn't matter which entrance is used for the hint. And doing it any other way would be inconsistent with how we handle hints for indoors with multiple entrances here.

**Comment by Zannick** [comment]
This would allow us to not have both entrances in the same area, which I thought was the case in your fork somewhere? r0b was experiencing a bug related to this, and I want to demonstrate that this is a way to do it that I might extend to Windmill, which we solved by introducing an event item `Dampes Windmill Access`--instead we could turn it into a dead-end region `Kak Windmill Upper` that has the same hint region as `Kak Windmill` and remove the event item. So I'm envisioning it being a way to improve consistency for hints for indoors with multiple entrances. (Also, with different hint area entrances, having the hint area change if you reorder the regions entering the House Near Cow area is uncomfortably inconsistent imo.)

The potion shop is the weird special case where its locations are all in the front half already, and the back half is empty, and the player can go freely between the two. But if, say, Kak Potion Shop Front connected to another indoor region with two exits, then the hint area search might find a hint area through the back door instead of the front.

...if Kak Potion Shop Front connected to Impas House Back, then the potion shop items would be hinted from the back entrance while the cow would be hinted from Impas House front (without this change) or the potion shop back entrance (with).

**Comment by Roman971** [comment]
Well I don't think we want to allow multiple entrance indoors to be in separate hint areas in this fork. The reason I allowed it in my fork is because, with mixed pools and/or decoupled entrances, there is basically no way to keep it fully restricted, so I went ahead and removed every restriction to stay "consistent". It does mean some hints will use the "wrong" or "less accurate" entrance unfortunately, but it happens so rarely that I decided to take the loss.

And if it's just to "simplify" the process a bit, I don't think we really need to introduce this method on this fork, but I guess it's probably fine. Tho I think the name `hint_region` is confusing, or at least not explicit enough. And adding a new attribute to regions in general is pretty unfortunate imo.

**Comment by Zannick** [comment]
If we don't want to allow indoor areas to connect different hint areas in this fork, then this isn't very important here. I do like enabling the option, however. I could offer it up for the decoupling fork instead, since it should help with those rare occasions where the hints confuse players. I'll try to think of better names while I consider the options.

**Pull request closed without merging**
