### PR TITLE
Remove decompressor size check

### PR DESCRIPTION
**Pull request by CMuncey**
Remove the size check to allow for decompressing decompressed roms. I think there is also a check in the python to make sure the input rom has the correct CRC. The decompressed rom's CRC (0x93522E7B) would need to be added to that. Also the web version's decompressor is custom, so this doesn't help with that.

### CODE REVIEW

**Review by Zannick — APPROVED** [review]

**Comment by Zannick** [comment]
btw, do we need to update the decompressor binaries to match?

**Comment by CMuncey** [comment]
Still needs an M1 mac binary (I only have an x86 one) and an arm Linux binary. Both of which _should_ be handled by the makefile (the one makefile works for Windows/Mac/Linux, but probably not on more obscure OSs like freeBSD).

I had to use MinGW32-make for the windows versions, so I think both of them might be 32 bit versions, but that shouldn't be an issue performance-wise.

**Review by Zannick — APPROVED** [review]

**Comment by Zannick** [comment]
We haven't gotten an M1 mac binary yet and I don't think I can build one. Shall we merge anyway or find someone to build it?

**Comment by CMuncey** [comment]
It should work without it on M1 macs, they have a dynamic recompiler that should make it work. If we can get one, that would be nice, but it's not the end of the world if we don't. I would say go ahead and merge

**Pull request merged**
