### PR TITLE
Starting ice traps

### PR DESCRIPTION
**Pull request by fenhl**
This allows an ice trap to be placed on Song from Impa as an effective starting item or given as an explicit starting item via plando. Behaves correctly regarding saving and loading.

Since the number of pending ice traps is now stored in the save context, it is no longer possible to completely avoid an ice trap by savewarping before it's applied. (Savewarping while frozen still works.)

The number of pending ice traps is stored in the unused field of the scene flags for scene 0x49. If this PR is merged at the same time as #1535, those docs should be updated to reflect this.

### CODE REVIEW

**Comment by ETR-BTF** [comment]
What's the limit of pending Ice Traps and what happens if you go over it? Could be relevant when going afk in a MW with Ice Trap Onslaught?

**Comment by ETR-BTF** [comment]
What's the limit of pending Ice Traps and what happens if you go over it? Will that be a problem in MW or OoT Online if people return from afk with a lot of pending Ice Traps?

**Comment by fenhl** [comment]
The limit is 4294967295 and I have not tested what happens if you go over but presumably it would overflow to 0 and skip 4294967296 ice traps.

**Comment by ETR-BTF** [comment]
> The limit is 4294967295 and I have not tested what happens if you go over but presumably it would overflow to 0 and skip 4294967296 ice traps.

I think we're safe lol

**Comment by fenhl** [comment]
Changed the location the count is stored from scene 0x00 to scene 0x49, since upcoming features like total small key count display may want to use dungeons' own unused field.

**Review by cjohnson57 — APPROVED** [review]
Awesome work, lol

**Pull request merged**
