### PR TITLE
Fix dungeon entrance marker on minimap

### PR DESCRIPTION
**Pull request by rlbond86**
This PR fixes the dungeon entrance marker on the minimap. When in an area with no dungeon entrance, the marker would appear on the top left of the screen.

https://imgur.com/xjf0rSX shows an example.

### CODE REVIEW

**Comment by flagrama** [comment]
Does it always show a dungeon marker where a dungeon is, or only when it has actually been opened? DC is a good example of one that should exist but I guess doesn't if you haven't opened it as child, but I don't think unopened dungeons should be shown as open on the map.

**Comment by rlbond86** [comment]
There is no additional logic to determine whether the marker should be shown or not. (Vanilla also does not appear to perform this kind of check based on my experimentation.)

**Comment by rlbond86** [comment]
The inserted NOP in hacks.asm can be removed to only fix issue 1 if that is more desirable.

**Comment by flagrama** [comment]
I know that the Deku Tree entrance doesn't appear until you enter Deku Tree and the Dodongo's Cavern one as child doesn't appear until you enter DC as well. They might all be based on having entered once?

**Comment by rlbond86** [comment]
That's possible, I will have to check.

**Comment by flagrama** [comment]
Just tested on gz. DC and Forest Temple both appeared after entering the dungeon and exiting. I believe that is how it works, and I'm not sure it should be changed IMO.

**Comment by rlbond86** [comment]
Reverted that particular change.

**Pull request merged**
