### PR TITLE
New Setting : Remove Ice Block In Adult Lake

### PR DESCRIPTION
**Pull request by GSKirox**
This new setting removes the ice block in adult Lake, enabling Link to go to Zora's Domain (or whatever entrance is there if Overworld entrances are shuffled) with no extra requirement than a Lake access.
In my opinion it's mostly interesting if Overworld entrances are shuffled, since this is an annoying "one way" entrance.
image

### CODE REVIEW

**Comment by r0bd0g** [comment]
Getting one-way'd kind of comes with the territory. If your goal is to remove getting one-way'd you kind of have a long way to go. Are you gonna remove the ice in Domain next? Are you gonna remove the block behind Darunia for child? Remove the guy blocking the potion shop back? Open the drawbridge at nighttime?, you'd probably have to redraw the background image for that scene. What would you do, for example, about this same entrance if you come in as child without a scale? On other branches, mixed pools, every time you come out of a grotto you don't have the requirements to open?

It's not gonna be feasible to change all of that. If you really want to stop getting one-way'd you'd need like an undo button that sends you back to the entrance before last, or something, which would be super overpowered. Maybe that "FW anywhere" idea could semi-fill in for it if you could fix all that bugs with that, if players are willing to start with FW and magic, and be willing to cast it just about every new loading zone that doesn't one-way them.

Both sides of this entrance are the only two child-only OW entrances in the game. I think it's good for variety if we have a couple of those. This would make it more accessible as adult, which I think would be a shame. Adult might have to go over and hit the gossip to lower the water in order to go through it in some cases, I dunno, bit of an off-beat thing you might have to do there I guess.

There's no toggle for whether or not to open the BotW or Deku entrances as adult after opening them as child (or to remove the boulders blocking Fire Temple), it just happens if you turn dungeon ER on. Besides opening for the other age once opened as the proper age, we could have had them open all the time, closed all the time, or had a setting (or maybe multiple settings, for each possible entrance) for any of those three possible implementations. Instead we made a choice about what would result in a better game balance and we went with it. It seems harmless enough to just add any one toggle but if you do this every time a setting comes through you're going to be drowning in toggles pretty quickly. While I would completely disagree with permanently opening up this entrance for adult, I also disagree with adding a toggle for such a small thing. If you want this entrance to be open for adult, I think you decide which circumstances you think would play better with it open, and just open it.

**Comment by GSKirox** [comment]
I certainly don't intend to go through each entrance, but this one has interesting implications even in the most "usual" settings, so i thought maybe an individual toggle would make sense so that everyone can decide if they want to try or not.

But I don't mind making it conditional with some settings and remove the toggle, if we can find a good balance.

**Comment by r0bd0g** [comment]
One idea is, can you make it so that the block only isn't there if you just came in from that entrance? Is that a reasonable idea? Like, giving players one chance to decide they don't want to go in that direction yet. This would be a change much more targeted at addressing the one-way issue. But, tricky caveat, it should only remove itself when you come in from this entrance using the normal 'other side' of the loading zone (so, never removed on spawns or warp songs, and never in decoupled where no entrances have 'other sides' even though it may sometimes randomly happen). This would have still a small logical impact of allowing an immediate return to where you just were with a potentially refreshed environmental timer and an adjusted time of day.

It still seems weird to single out only this entrance for a fix when there are so many more one ways though. And again I kind of feel like getting one-way'd is just one of the things you should have to deal with in these kinds of settings, so I would want it toggle-able. I feel like we gotta give such a toggle a bit more substance, so I wonder what other entrances it could be worth including? The block behind Darunia seems like the most obvious one since I think that's the only other double-sided OW entrance that has no hope at all of being returned through.

**Comment by GSKirox** [comment]
Hmm I don't see a way to remove the block conditionally with coming from the entrance, but it's an interesting idea.

Honestly, fixing the one way entrance wasn't the motivation. I just thought it could be interesting in some scenarios, removing the one way was just a nice bonus incentive.

I think the Darunia block and the Kak Potion Shop guy shouldnt be too hard to do, but obviously that only solves the "no item" entrances. Can't do much about the Lost Woods => River entrance, or the multiple grottos in mixed pools.

**Comment by ETR-BTF** [comment]
I don't think this should be merged. The changes made to dungeon entrances can be justified because otherwise there are very few permutations for dungeon ER. This change seems, to me at least, to be about the frustrations involving one-way entrances, in which case the player should just not shuffle them. I might feel different about this if _every_ one-way entrance was patched to be both-ways, because then you can justify it as "I don't want to shuffle one-way entrances, but I also don't want them to remain vanilla".

**Comment by cjohnson57** [comment]
Sorry, I think I agree with the others on this one. Dungeon entrances have obstacles removed but dungeon entrances are much more restrictive than OW

**Pull request closed without merging**
