### PR TITLE
Settings to change the game language to Japanese (for JP users)

### PR DESCRIPTION
**Pull request by JackTriton**
Recently, I've noticed that there are some Japanese players playing this.
and I thought making Japanese version of this would be great for them.
As Japanese-player, I want to contribute on the text part.

For Example:
Translate "You got ~ !" to "~を　みつけた！"

### CODE REVIEW

**Comment by aofengen** [comment]
The change you made doesn't allow for a choice of what language to use. It only changes the patch forcing english text to now force Japanese text - meaning that will be the default for anyone playing rando

**Review by TreZc0 — CHANGES_REQUESTED** [review]
Like that, this cannot be accepted.
This would change the language to JP for all players.

Instead, this needs to be extended by a GUI option (which should be cosmetic).
The default should still, but the gui could feature an optional switch to JP.

Then, the patches.py should apply the value from the gui, just like with cosmetics.

On top, the comment in the patches.py should be changed to reflect on the option.

**Comment by JackTriton** [comment]
Added Language Option section on Cosmetics tab.

**Comment by aofengen** [comment]
@JackTriton in settings_maping.json, you seem to have inadvertently deleted lacs_condition from the object at L.213

**Comment by TreZc0** [comment]
Yea no, you definitely need to create a fresh branch from dev first, or merge all dev commits since your fork first. I suggest you make a new PR then, as this would be quite too complicated to do with this current outdated fork.

**Comment by r0bd0g** [comment]
Due to differences in text speed, I don't think a language option is able to be cosmetic at this time.

**Pull request closed without merging**
