### PR TITLE
Move item restrictions to a table.

### PR DESCRIPTION
**Pull request by louist103**
Add the table and move PY patches to it. The foundation for fixing the bunny hood problems.

### CODE REVIEW

**Comment by GSKirox** [comment]
There's another restriction change that has been merged two months ago : https://github.com/OoTRandomizer/OoT-Randomizer/pull/1845
Not sure why it doesn't show up in your commit's Patches.py ?

**Comment by fenhl** [comment]
This branch is older than that PR and should probably be rebased.

**Comment by ETR-BTF** [comment]
Relevant issue: #1844

**Review by cjohnson57 — APPROVED** [review]

**Review by cjohnson57 — CHANGES_REQUESTED** [review]
Sorry just realized what the others meant,

These restriction changes should be added to the table as well:

```python
    # Allow Ocarina in some places
    rom.write_byte(0xB6D346, 0x11) # Granny's Potion Shop
    rom.write_byte(0xB6D30A, 0x51) # Archery
```

**Comment by louist103** [comment]
#1975

**Pull request closed without merging**
