### PR TITLE
HintList.py

### PR DESCRIPTION
**Pull request by dotzo**
Changed some wording in HintList.py to aid in reading the hints after many complaints.  All the words are Google-able for those for whom english is not their first langauge, as well as others.

### CODE REVIEW

**Comment by Nicholas-Steel** [comment]
These changes are significant improvements, though although I think Bomb Bag and Fire Arrows could be further improved I can't think of anything off the top of my head that wouldn't blatantly spell it out for the end-user.

**Comment by Zeimyth** [comment]
This will result in merge conflicts if my PR https://github.com/TestRunnerSRL/OoT-Randomizer/pull/93 is merged as it is now. It should be pretty simple to correct, though some hints will be less unique with the new names given here.

**Comment by dotzo** [comment]
Closing with Zeimyth's update being better.

**Comment by Zeimyth** [comment]
@dotzo PR #93 has been merged now.

**Pull request closed without merging**
