### PR TITLE
DMC Logic rework, take 2

### PR DESCRIPTION
**Pull request by OriginalPiMan**
This PR would replace the old Upper/Lower/Central and Nearby/Local logic in DMC with full entrance to entrance logic.

I think I accidentally closed my previous pull request [https://github.com/TestRunnerSRL/OoT-Randomizer/pull/1231](https://github.com/TestRunnerSRL/OoT-Randomizer/pull/1231) when I renamed my main fork from Dev to Dev-Pi.

See the previous PR for old comments. Updates since then include renaming exit handler regions and adding a preamble to the whole thing.

### CODE REVIEW

**Comment by r0bd0g** [comment]
In logic helpers, "Plant Crater Bean" should be "Plant DMC Bean". I first pointed this out in January lol.

**Comment by r0bd0g** [comment]
Alright I looked over this PR and I once again have some thoughts on some of the specifics.


- Goron City to Upper Crater as Child -

Let's start by talking about going from Lower to Upper Crater as child, coming from Goron City (I didn't bother running any tests for coming from lower grotto). I don't necessarily agree going to upper Grotto is easier than going for Trail. I'll explain that more in a bit, but for timing the various methods of avoiding the scrub I'm going to use going for DMT rather than the grotto, because reaching the loading zone is a more consistent movement to execute than entering the grotto. After climbing the ladder I recommend doing 3 sidehops right plus a couple frames of rightward slowwalk before backwalking into the loading zone.

Let's talk about the various ways of dodging the scrub. If you just attempt to jump across, grab the ledge, and climb up, you will get blasted into the lava. I know it's possible to clear the gap with no ledge-grab or jumpslash, but for our purposes let's consider that impossible since it's difficult to do consistently. So let's try stunning the scrub by throwing a deku nut across the gap before jumping. With good movement, this will leave you with about 1s to spare (more like 0.5 to 1.5s to spare, depending on how well-executed the movement was), as you exit to DMT. Now let's try it again but actually just whiff the deku nut so it doesn't even stun the scrub and realize the time it took you to throw the nut was enough of a delay that the scrub probably won't hit you anyway. So probably easier than throwing a nut is to jump across immediately, but don't climb up right away. Wait for the nut to just pass overhead, and then climb. This also leaves you with about 1s of time to spare upon reaching DMT. So if Deku Nut is logical, using no items is maybe actually easier and takes about the same amount of time. Alternatively you can jumpslash across the gap. This saves maybe 0.75s over stunning the scrub with a nut or just waiting out its attack. You probably expect it necessary to take damage from the scrub after doing this, but it's not too difficult to avoid this. If using a Deku Stick, if you jumpslash directly at the scrub, the deku stick will actually break on the nut and destroy it before it can hit you. Unfortunately, the Kokiri Sword hitbox is too short to do this so easily, but if you stop moving for just like 1 frame after alerting the scrub but before jumping over (costing only a few frames), that will line it up so that the Kokiri Sword jumpslash can destroy the nut as well. You can also permanently despawn the scrub, in scrubsanity, and then reload the area and make the trek with the scrub not there. It was annoying to test this on the practice ROM, so I didn't, but one imagines the speed is faster than using a Deku Nut, but probably slower than using a Deku Stick. So with good movement, depending on the method and the execution you can expect to have somewhere from 0.5 to 2.25s time remaining on the trek through Crater from City to DMT as child.

Now let me explain a little more about why I don't feel reaching the grotto is significantly easier than reaching DMT. It's true that if the boulder has already been destroyed, then the grotto is closer by about 1s (though it is a much smaller target, which makes it less consistent to actually enter). But destroying the boulder and going through a new entrance is probably one of the main use-cases for logic like this, and particularly when the boulder needs to be destroyed with a bomb, it can be a problem to execute. The most time-efficient way is to pull the bomb early and throw it, but boulder hitboxes are so jank that it's actually a little difficult to do this consistently. If you instead want to place the bomb next to the boulder with time to get out of the way of the explosion, the boulder explodes with only 1s to spare (when using a no item method for the scrub), and then there's not really enough time to make it into the grotto after. You will probably have to die and make the trek again, which is pretty annoying and can sometimes come with an unavoidable loss of a shield. You could tank the damage from the bomb if you're not on OHKO, but that's going to make any following treks through Crater more difficult for you unless you spend the time trying to get a heal. If I were doing this in a real seed I wouldn't want to have to deal with using explosives safely on such a short timer, and would rather go for DMT, hopefully not get one-wayed, and then come back for the grotto. Technically the grotto is about 1s closer, but going for trail overall is the easier play.

(An aside, you could go from City to the wall PoH. Your movement actually has to be really good to make it at all, even with Deku Sticks to help you. It's only just barely possible at all with the ledge grab before the scrub and no items at all to help you. So this trek is definitely too precise for logic. Also, with Deku Sticks, the crate GS can be done fairly consistently with 0.5s left, but that's still pretty tight and only the Deku Stick method is really viable.)

So if any trek here as child is to be in logic, I don't think the treks to Upper Grotto and DMT are different enough in difficultly to warrant a difference in logic. While I could see requiring a jumpslash to cross the gap, I don't think the amount of time saved by using one (maybe 0.75s) is worth splitting hairs over. I would rather allow all methods of dealing with the scrub than allow only some of them. I don't think any consideration for OHKO is needed here as all methods can avoid the scrub's attack without losing significant time, so the heat timer remains the primary factor. And after examining the strictness of the timers of some of the other treks in this PR, I think that all of the treks as child from city to upper crater are too difficult to be in logic.


- Fairy Fountain to Upper Crater -

Exiting DMC Fairy as child, the treks to DMT, the Crate GS, the Grotto, and the Wall PoH all seem reasonable under FTR as you've prescribed. (Even bottling a Gossip Stone fairy isn't all that crazy, but definitely would go a step too far.) Actually, for DMT and the Grotto (particularly when you can jumpslash), it's debable whether or not FTR should even be required, but child is a little clumsy I guess, so maybe it's fine. But whether or not FTR should even apply as child is a different question... Fewer Tunic Requirements is already a pretty weird and arbitrary trick in how it applies, so... fine... fine. My thought has always been that child cannot wear a tunic, so there is no tunic to be fewer than... If it is to be used as child, I would prefer the trick to be renamed to something like "Stricter Environmental Timers" or something to that effect, but some of the ways FTR is used, particularly in the Water and Fire Temples, are not really all that much about the strictness of the timer anyway, and by now people are used to the FTR name, so renaming it would not accomplish very much. So... fine.

As adult, the treks from Fairy to DMT and Upper Grotto seems easy enough to not require FTR. The Wall PoH is a bit more debatable but even that I don't think should need FTR as adult. (Hookshotting the ladder could come into play here, which would give you even more time, but maybe hookshotting the ladder and saving time with it is too difficult for players with FTR off. But... more on hookshotting that ladder in a bit.)

As well, as adult, I was able to bottle a Fairy from the Gossip before dying and without rolling at all, so the trek from the Fairy to the Gossip might be safe under FTR.


- From DMT / Upper Grotto -

As both child and adult, the trek from DMT to the Gossip Stone (even with the wall still there and even to bottle the fairy) seems fine with no tunic.

The trek from DMT to Lower Grotto (Hover Boots or Boulder Smashed routes), seems fine with no tunic. From Upper Grotto to Lower Grotto takes maybe 3s longer, but even that is kind of borderline. I'd kind of prefer the two to have equivalent tunic logic to and from most places, but the difference in the distance here may actually be relevant enough to matter.


- Hookshotting the Ladder -

Even factoring in my suggested changes until now, your timings are still a more lenient than mine. The treks that you have as requiring Hookshot are City to Wall PoH, Lower Grotto to Upper Grotto, and Lower Grotto to DMT. The only one of these that I wasn't able to make in time with no Hookshot and no rolling was Lower Grotto to DMT. It was still doable enough that I would have put it under FTR (previously this was even no tunic at all), but... you're probably right that it is a bit much? Anyway, Hookshotting this ladder can save maybe 5s if done right, but it's actually pretty difficult to set it up in a short period of time in order to get such a significant time save. So even when it's done okay it might only save a second or two. Really, I just don't want to be requiring a Hookshot for such a minuscule thing. I don't want to see a Hookshot on WotH for this ladder... I would remove Hookshot for City to Wall PoH and Lower Grotto to Upper Grotto since those I was able to make with just the control stick and one instance of pressing A to let go. For the one trek that I wasn't able to do without pretty good movement or Hookshot, I would rather just require Goron Tunic for this trek. (Lower Grotto to Wall PoH is already in a similar spot, where you have it requiring Tunic always, but Hookshot could actually make it doable.)


- From Lower Grotto to Wall PoH -

However I think bean route here likely is safe under FTR. But it might not be a significant enough of a thing to be worth requiring the bean plant for, similar to how I feel the hookshot shouldn't be required for that ladder. But... this would probably never going to be logically required anyway. So even though it's reasonable it's probably not worth increasing the logic's complexity over...


- DMC Boulder Skip -

I used a pretty simple itemless setup and had at best 5.5s left on destroying the boulder coming from DMT and 2s left on destroying the boulder coming from the upper grotto. There's plenty of time to do the double jumpslash so you can just do that instead if the boulder skip is too hard. I mean technically you didn't enable a trick that said you know how to do that jumpslash... Destroying the boulder with the boulder skip would definitely be in FTR at least, whereas the double jumpslash is easily in under no tunic, so there's a bit of a disparity there... But I think it might be better to keep things simpler by just having the boulder skip cleanly obsolete the double jumpslash (make sure to note that in the tooltip).

As far as whether ever using the boulder skip should be available under FTR to reach any checks... You have to be coming from DMT to even consider it, and the most reasonable place to get to is DMC Fairy, which won't logically relevant since you have to have the hammer, so... 2s left at best into Goron City is not great for such a finicky trick. It might be best if everything there is always tunic. (Child can perform this trick as well, and I don't want to have to deal with that, so if it always requires tunic then I won't have to.)

Also, we may need to consider renaming "logic_crater_upper_to_lower" in the logic since I don't feel that that name really makes sense anymore, and also don't like how different it is from "logic_dmc_boulder_skip" when the tricks are so related. Maybe something like "logic_dmc_boulder_jumpslash"? I dunno. The name "without Hammer" doesn't really feel correct either since Hover Boots or the boulder already being destroyed is also without Hammer. Maybe "with Boulder Skip" or something?

The boulder skip route from upper grotto to sheik seems bugged. It should probably always be requiring tunic.


- DMC Fairy with Hovers -

There's a possible trick coming down the pipe that I wanted to investigate at some point but TBH it doesn't really need to be done right now. If it were added, all entrances to the fairy fountain would need to add a line for trick+bean+hovers plus the appropriate tunic logic for that spawn point. I didn't investigate so I don't know what the appropriate tunic logic might be.


- MQ Fire Big Lava Bombable - 

I reevaluated the timing on going to the bombable side room both with hookshot and with the trick jump. The hookshot method is cleanly in FTR. The trick jump is pretty tough still but you do have at least a little leeway, and you have to enable ohko and two tricks to get yourself into this position, so... maybe it's good as-is.

---

- Summary -

- Tunic Logic that should be reconsidered:
-- DMT to Gossip (no tunic as either age)
-- DMT to Lower Grotto (no tunic)
-- Fairy Fountain to DMT (no tunic)
-- Fairy Fountain to Upper Grotto (no tunic)
-- Fairy Fountain to Wall PoH (no tunic)
-- Fairy Fountain to Gossip (FTR)
-- City to Upper Grotto (no child access)
-- City to Wall PoH (FTR without hookshot)
-- Lower Grotto to Upper Grotto (FTR without hookshot)
- Some treks I looked into that I wasn't sure about:
-- Upper Grotto to Lower Grotto (no tunic?)
-- Lower Grotto to Wall PoH (FTR with bean?)
-- Lower Grotto to DMT (always tunic?)
- Other:
-- Upper Grotto to Sheik boulder skip route seems bugged
-- Consider renaming the two crater upper to lower tricks
-- An instance of 'anticlockwise' in the comments should be changed to 'counterclockwise'

---

But should we do this at all? I think... probably? But I want to sleep on it one more time and then I'll try to explain...

**Comment by r0bd0g** [comment]
Does anybody else find the current DMC logic difficult to follow? To understand what is the effective logic from A to B you have to trace through the various local and nearby regions, often multiple times. And too often the final resulting tunic logic does not mesh well with the true difficulty of the trek. You might want to make modifications to fix the larger problems, but the confusing nature of it makes it difficult to make significant changes, particularly if you would need to add regions. Personally I don't find it to be some beacon of maintainability.

Compared to this PR though it does get some points for brevity. The problem with the logic in this PR is that it's huge. And whenever you want to make changes, you have to make the change 7 times, once for each entrance. But writing it out each time does force you to consider the tunic logic at each step to make sure the timings are reasonable. I know it's a lot of code but I think there's something to be said for just being able to see the full connections at a glance. Logic is not easy to test for correctness. The best you can really do is look at it and try to reason whether it works or not. Hiding the true logic in a tangle of regions makes it more difficult to verify. And for the same reason I don't feel adding helper methods to this PR would actually help with maintaining it, since you would have to refer to the helper methods every time you want to check what the logic is actually calling for.

One thing I would suggest is that the tabbing could probably be improved. Everything being tabbed in the same amount makes it difficult to tell where one route ends and another begins. I suggest only the start of each distinct route should get top-level tabbing.

As well, you should double-check that equivalent logic is worded the same way each time. The logic bug with the boulder skip route for Upper Grotto to Sheik was one instance where it differed, and that turned out to be a bug. I don't know if there are other differences out there, but it'd be better to minimize the number of them so it doesn't create confusion along the lines of "Why is this worded this way but this one worded that way? Is this a bug?" When there's a difference it should be deliberate because there's an actual difference in logic between the routes.

Honestly, I think DMC is always going to be a mess no matter how you do it. I doubt the average player is really noticing the logic all that much as they're running through the game, but I think at least this implementation should be fairer to players since it more accurately reflects how long the treks through crater actually take.

**Comment by Zannick** [comment]
Honestly how we handle DMC logic is going to involve some tradeoffs between readability and maintainability, and that's best figured-out if we make clear what our main goal is.

**Understandability** (readability): where one can look at the file and easily understand what they would have access to or what they would need to gain access or just straight up what the possible options are.

**Maintainability**: where it's hard to make inconsistencies arise, i.e. route fragments are deduplicated where possible so we don't have to write the same changes 7 times.

The current DMC logic is my and Roman's work trying to balance these by breaking Crater into its major sub-areas and each of those into 2 smaller regions: one where you could be considered to have enough time to go to another sub-area, and the other consisting of checks you could make even if you came from another sub-area. Granted, the names "Local" and "Nearby" could have been better chosen and that's probably on me for suggesting them.

I'm not particularly attached either way. Are these remaining items from r0bd0g's summary requested changes?

**Comment by OriginalPiMan** [comment]
I've taken the summary as requests for changes which I've reviewed one by one.
For half of them, I have made the requested change.
For half the remainder, I have restated my case and will seek a second opinion.
And for the rest, I have yet to complete my review. Once I've done these, I'll post my response in full and merge the changes I have made.

**Comment by OriginalPiMan** [comment]
Most recommendations by r0bd0g have been adopted. The following have not and I would like a second opinion:
**DMT or Upper Grotto to Hammer grotto as adult** - Not changed, you would remove FTR/Tunic. I think the timing is just barely too tight to justify removing FTR.
**Fairy Fountain to Wall** - Not changed, you would consider removing FTR/Tunic. I think the timing is just barely too tight to justify removing FTR.
**Lower Grotto to Upper Grotto or DMT as adult** - Not changed, you would remove hookshot requirement. I want a second opinion on hookshot things. I think it's worth keeping.

**Comment by r0bd0g** [comment]
One of the comments has been changed from saying "DMC" to just saying "DM".

You changed the internal name for the upper to lower jumpslash trick in settings list, but didn't actually make that change anywhere in the logic file.

The Plant DMC Bean you added to Lower Grotto to Wall PoH is missing an opening quote.

A couple of the tabbing changes I'm not really sure about. In many cases they're separating the various routes a little more cleanly, but in at least one spot it had me questioning whether the brackets were right since the tabbing and brackets were not really matching at that spot. There were also some equivalent sections that were tabbed differently. At this point I don't think it's really worth calling out any exact specifics; tabbing's too subjective.

My notes above suggest it was kind of close for Upper Grotto to Lower Grotto on whether it should ever require tunic or not, and also say that DMT to Lower Grotto is 3s closer, so I doubt that DMT to Lower Grotto is really needing tunic. You can do it in two treks if really necessary, since the first trek you could theoretically get the boulder destroyed and then die, though I doubt many will actually be needing the extra time that gives you. So a difference in logic for from DMT and from Upper Grotto might be better here.

You can pretty easily make the treks through crater where you've required Hookshot, without Hookshot. As well, actually saving time with the Hookshot is not entirely simple -- I have died with what should have been ample time in actual races from failing to get hookshotted onto this ladder multiple times in a row. For both of these reasons I would like to avoid the possibility of seeing Hookshot on WotH just for this purpose. I'm surprised to see you've removed Hookshot on City to Wall PoH, but not Lower Grotto to Upper Grotto, since those two treks seemed of roughly equivalent difficulty when I tested it. Lower grotto to DMT I can understand wanting to keep Hookshot for, and that one's a niche enough case I'd be willing to just cross my fingers and hope nobody ever runs into it. (Lower Grotto to Wall PoH can also be reasonable with good hookshotting, but I really don't want to see this trek dragged into the mix too.)

**Comment by Hamsda** [comment]
> The current DMC logic is my and Roman's work trying to balance these by breaking Crater into its major sub-areas and each of those into 2 smaller regions: one where you could be considered to have enough time to go to another sub-area, and the other consisting of checks you could make even if you came from another sub-area. Granted, the names "Local" and "Nearby" could have been better chosen and that's probably on me for suggesting them.

Honestly I'd personally rather keep the current DMC logic over this PR. Once you wrap your head around the `local` and `nearby` concept, it really is not bad at all. These changes on the other hand seem like a maintainability nightmare, with missed changes waiting to happen.

**Comment by r0bd0g** [comment]
The current tunic logic is both too lax in some places and too harsh in others. Changes are needed. I don't know that I believe the current implementation can capture all the necessary nuance without being mucked up so much so as to be unrecognizable. Other the other hand I think this PR is actually capturing too many nuances.

**Comment by Hamsda** [comment]
I'm not saying the logic is perfect, don't get me wrong. On the other hand, as Zannick has put it in a different discussion before, we don't need to perfectly model every single interaction. Just needs to be a good enough approximation that allows casual players to complete the game even in the worst cases, and hopefully is still interesting for advanced players.

**Comment by cjohnson57** [comment]
Sorry Piman, cleaning up old PRs and this one's been sitting abandoned for quite some time. If you resume work on it and update it to work on latest, feel free to reopen!

**Comment by r0bd0g** [comment]
Even if you never reopen it, please don't delete this branch -- I may need to refer to it later.

**Comment by cjohnson57** [comment]
I think if he deletes the branch you can still view the changes on the PR page

**Pull request closed without merging**
