### PR TITLE
Compressor update

### PR DESCRIPTION
**Pull request by CMuncey**
Update the compressor (again)

New compressor output: The output will now show every file it compresses, which makes the GUI's progress bar more accurate. Nothing needs to change in the python to make this work.

New dmaTable.dat: The dmaTable.dat file is now a list of files that should not be compressed. To add more items, just append the number of the file in ROM to the end of the file. Negative numbers will be treated as a file that should not exist, and will be removed from the ROM during compression (see Majora's Mask dma table for example).

New extended ROM size: If the compressor cannot fit the rom into 32MB, then it will increase the output size. This can cause issues with injection into a WAD or use on an EverDrive. I did not add any checks to the python code, but the current plan is to have it give a warning if it finds that the output ROM is too big, but then continue as normal. The python code will just have to stat the ROM file to find the size.

### CODE REVIEW

**Comment by r0bd0g** [comment]
If it's showing what file is compressing, could that spoil which dungeons are or aren't mq?

**Comment by TestRunnerSRL** [comment]
Hmm, i mean, the file no -> file name is always going to be the same. So like if you know Forest Temple is say file 500. Then if you see file 500 being compressed and last time you played it was vanilla, then you'd know that Forest is MQ this play. Or am I misunderstanding the info here.

**Comment by CMuncey** [comment]
It displays all file numbers always, regardless of if they're actually being compressed or just copied

**Comment by Zannick** [comment]
It does hang a bit sometimes at certain values of "x files remaining", so I suppose I could look up what the xth file from the end was.

The more explicit progress is nice on the GUI, though it ends up being only 80-100% (we could change the balance in python if necessary). On the other hand, it gets rather spammy on the commandline. I might like a "-q" or a "-v" option, depending on whether the granular version or the ratelimited version should be default, and then we can pick based on whether the GUI is running. Really minor wishlist item, though, I still want to test a few seeds first.

**Comment by CMuncey** [comment]
That may also be the python not being able to keep up, especially if you have an ARCHIVE.bin file, it goes by very fast.
I have been working on argument flags like that, but haven't implemented it yet due to being busy. I can add it in if you think it's something that's needed now. The actual compressor (this one is modified slightly for the rando) has all of the output on a single line that updates as files are handled. If that's something that the python/GUI could handle, that might be an easier option, though it would require changing that code, so db might be better suited for it.

**Comment by Zannick** [comment]
It's not necessary at the moment.

**Pull request merged**
