### PR TITLE
Refactor Custom Voices

### PR DESCRIPTION
**Pull request by matthewkirby**
So I set out to refactor the code for the custom voices. The original implementation used an external tool to patch the custom .wav files into a rom. This rom was diff-ed with a vanilla rom to make a .zpf patch file which was packaged in the this repo. The external tool worked by reading out the entire audiobank, audioseq, and audiotable, applying your changes to its data structures, then writing it all back into the rom. This meant that all of this data got shifted if any one of the custom sfx was a single byte less than the original. This caused the zpf patch files to basically need to rewrite the entire audio table to account for this shift and was resulting in patch files that were about 4MB each.

This has a second problem: if you used this method to make a patch file for each child and adult pack separately, they will have different offsets and you cannot apply two of these patches (it also moves the audio tables around for other code that may be relying on hard coded addresses). To handle this, the original implementation simply included a .zpf patch for every permutation of available sfx. As this is exponential with the number of packs, this probably isn't the best way to do this. 

I took a slightly different approach where rather than using the external tool and this whole process to create a .zpf file I instead patch the audio files into the rom directly. Not only does this take about 35MB of these audio patch files from the repo, but it also allows the voices to be mix and matched for child and adult without needing to create a new set of permutation.

The original plan was to put the .wav files themselves into the repo but converting from .wav to the .aifc format that is needed was proving difficult. I instead loaded each wav into the external tool mentioned above and exported them again as their raw binary. This has the added benefit that the voice actors do not need to worry about the raw audio of they used for the sfx floating around.

I am submitting this now as a draft because converting the wavs to the raw binary files is a little tedious and if this is not a direction that we want to go I would rather know now than before I spend more time doing that haha. 

For those concerned about file sizes when going from 8 .zpf files to about 80 .bin files. The 8 patches were about 34.7 MB (The repo is about 44MB total, so these make up a significant fraction of the total size). I have only converted the AdultFeminine pack so far but that half of the .bin files comes to a total of 364KB. The child pack should be similar and the silent pack is a single 892 byte file. So this actually comes with an enormous size improvement.

### CODE REVIEW

**Comment by matthewkirby** [comment]
In addition to porting the child feminine pack, I also plan to have the list of voice packs automatically generate from the contents of the Voices folder in the same manner as Models. While making a voice pack isn't trivial, this would allow anyone who did (or wished to use one from someone who did) to do so without needing to go edit SettingsList.py

- [x] Add support for the silent pack
- [x] Port child feminine pack to .bin
- [x] Dynamically build contents of the dropdown for child and adult sfx
- [x] Support random sfx pack option

**Comment by matthewkirby** [comment]
I guess I should also add...

Making these .bin files is not any harder than making the .zpf files. It is just inject the custom sound into the rom and extract it again vs injecting and saving the rom.

**Comment by Cuphat** [comment]
Hell yeah. Good work thus far and good luck with the rest of it. 👍

**Comment by cjohnson57** [comment]
Yeah this is a good direction, reducing the patch file size is definitely good

**Comment by matthewkirby** [comment]
This should be done! I tested briefly with all combinations of child and adult default, silent, and feminine voice packs. Every seed launched and I did not notice anything odd in about 30s-1min of playtime in each. Sounds were correct for all combinations. There is a chance I messed up converting 1 or 2 of the files to .bin but unfortunately I won't know until someone plays a seed and hears a sound that is wrong. That said, it is probably pretty unlikely that that happened (and its a very easy fix if it did).

Total size of the Voices directory was shrunk to 573KB from 34.7MB.

If you make your own soundpack called Artichoke, all you need to do is place the bin files into a folder in the Voices directory and title the folder AdultArtichoke for an adult pack or ChildArtichoke for a child pack. When you reopen the gui, your pack will be included in the correct dropdown and will be selectable both manually and with the random option.

You can now also mix and match. If you make your own adult pack, you can use any one of the existing child packs without any extra work and vice versa.

I didn't include the AdultXopar pack in here since I was afraid that sound of my choices might not align with the randomizer's ideals LUL

**Comment by matthewkirby** [comment]
One thing that I didn't do was check the length of the .bin files, I just load them and write them to the rom. This could yield weird results if you make a sound clip that is too long.

**Comment by matthewkirby** [comment]
I also wonder if it is worthwhile to remove the old .zpf files from the tree. Since I believe they will still be in there even once the files are removed. It won't impact people downloading the zip of the repo but will need to be downloaded on a clone

**Comment by Cuphat** [comment]
In the interest of getting this ready quickly, I did a bit of cleanup and pushed it to the PR branch. I moved the voice files into subdirectories by age (e.g. `data/Voices/Adult/Feminine` instead of `data/Voices/AdultFeminine`), cleaned up some code duplication, and reworked the case-sensitivity check to be a lot stronger.

**Review by Cuphat — APPROVED** [review]

**Comment by matthewkirby** [comment]
Fantastic! This was actually bothering me a lot that I was calling the exact same code for child and adult every time. Problem was that I wasn't sure what the best way to handle that was. Thanks for making that change!

**Pull request merged**
