### PR TITLE
Boulder shuffle, enemy drops, enemy soul shuffle, plus all of the changes from pots 3.0, plus Roman's branch

### PR DESCRIPTION
**Pull request by rrealmuto**
r0bd0g said he would review the logic if I PR'd it

### CODE REVIEW

**Comment by r0bd0g** [comment]
I dispute the accuracy of that statement...

**Comment by r0bd0g** [comment]
But if you all really want these features in the main branch of the project. I will commit to review the logic... in 2024.

**Comment by rrealmuto** [comment]
image

**Comment by fenhl** [comment]
This PR contains redundant changes from #2069. Please split this into multiple PRs by feature, or at least wait until #2069 is merged.

**Comment by cjohnson57** [comment]
I generally don't think an omnibus PR like this that combines several huge features is ever going to be reviewed, tbh

**Comment by rrealmuto** [comment]
it was mostly a joke because r0b said he would look at the logic if there was ever a chance that it would be merged. Thanks for poopooing on that dream though

**Comment by cjohnson57** [comment]
🥲

**Pull request closed without merging**
