### PR TITLE
Give full heal when buying Piece of Heart/Heart Containers

### LINKED ISSUE #170: Heart Piece bought from shop doesn't refill health
It does add to the heart piece counter. If you get a new container, you it add the 1 new container in health, but still does not heal.

OoT Randomizer Version 2.19.20 f.LUM  -  Seed: 94

Settings (MJ23A9MMTLAS9PSA):

Goron shop. I wonder if potentially related to how the chu bowling heart piece always heals you, regardless of what it is.

### PR DESCRIPTION
**Pull request by Cuphat**
Closes #170.

### CODE REVIEW

**Comment by TestRunnerSRL** [comment]
Now we'd just need to figure out how to make these items not heal for coop and from minigames.

**Comment by LostThePirate** [comment]
Healing both players in Multiworld is a feature, not a bug.

**Comment by TestRunnerSRL** [comment]
I mean, I'm sure the extra hp is always welcome, but it's a bug. It's really weird how multiworld gets all these extra heals that don't exist in single player. It's not like multiworld needs it and has lots of extra damage.

**Comment by Cuphat** [comment]
What about all the damage taken when you get dunked with hover boots. 🤔

**Comment by r0bd0g** [comment]
Yeah, the chu bowling round 2 heal is a little awkward...

**Comment by TestRunnerSRL** [comment]
Rebased and merged. It would be great if someone is able to figure out how to prevent the heals in the weird spots as well

**Pull request closed without merging**
