### PR TITLE
delet rando

### PR DESCRIPTION
**Pull request by BeeLuigi**
My uncle who works at nintendo said we had to stop so I guess this is it. 
It's been real my dudes.

Fixes all current and future issues.

### CODE REVIEW

**Comment by aofengen** [comment]
sounds promising. Tell me more

**Comment by DatXFire** [comment]
finally a change that's clearly well thought out, can't see any arguments against this

**Comment by darkangel93x** [comment]
nice #1000 commit haha :D

**Comment by Zannick** [comment]
This seems to be a 100% speedup. Very nice!

**Pull request closed without merging**
