### PR TITLE
Filter tags for list of tricks

### PR DESCRIPTION
**Pull request by Hamsda**
We have quite a lot of tricks, so I thought we could probably make use of this system we already have in place.
Just gave all the tricks some initial tags according to their location, MQ, and GS pretty much.

### CODE REVIEW

**Comment by r0bd0g** [comment]
Something like this has been sorely needed for a while, TBH.

Domain with Cucco is more relevant to River than Domain. Maybe the trick name should focus on the Sleepless Waterfall instead? (I guess a similar thing happens with the Water Temple Entry trick really being a Lake Hylia trick.)

I'm not sure how to deal with stuff that applies to both MQ and Vanilla. Most of them I see weren't tagged as MQ, but then there's something like "Forest Temple NE Outdoors Ledge with Hover Boots" which is tagged with MQ and Entrance, but it's really one or the other, not both at once. One that stands out to me is that Shadow Temple River Statue with Bombchu is marked as MQ despite applying exactly the same to both, where most tricks that apply to both were not marked as MQ.

Jabu Near Boss GS without Boomerang as Adult - Needs Entrance tag.

**Comment by Hamsda** [comment]
I just went through the list once, probably just missed some stuff. And I didn't make a "vanilla" tag, since MQ stuff is sorta the extra kid.

And regarding something like Domain/Water entry, you execute them in River/Lake, but they only impact the logic for the tagged areas was my reasoning.

**Comment by r0bd0g** [comment]
I was just thinking that in entrance rando those entrances are probably not going to domain or water temple.

**Comment by Hamsda** [comment]
Hmm fair point...

**Comment by Hamsda** [comment]
@r0bd0g made the adjustments to those tricks.
I also just got rid of the `Master Quest` tag... it felt weird as you pointed out.
Which tricks still need an `Entrance` tag? I couldn't spot any when scanning the list.

**Comment by r0bd0g** [comment]
I noticed a couple weird uses of escape characters with Jabu Jabu's Belly. There was an unneeded \' in one case, and a \" instead of an apostrophe in another.

**Comment by Hamsda** [comment]
Probably some whoopsies when regexing them over... I really dislike that `'` is the default string character when it causes so much trouble with English strings <.<

**Pull request merged**
