### PR TITLE
Fix: (No/Glitched Logic & Excluded Locations)

### LINKED ISSUE #912: No Logic & Excluded Locations
BooLuigi Today at 4:48 PM
Excluded locations are still (somewhat) used in No Logic seeds. They are set to be filled with junk in settings.load_distribution in line 57 of Main.py, and then removed in settings.remove_disabled() in line 80. This causes problems if you still have non-shuffled locations excluded when switching to No Logic. By the time the locations get filled, it can't find them in the disabled_locations list (line 527 of Plandomizer.py), which causes the seed generation to fail.

### PR DESCRIPTION
**Pull request by Dwood15**
Closes #912

### CODE REVIEW

**Comment by Dwood15** [comment]
Also removes Rando-Textizer :kappa:

**Comment by TreZc0** [comment]
This is actually quite bold to actually just submit it like that.
Doesn't fix the issue and removes something without mentioning it in the Title.
Way to use Github. Grats.

**Comment by rlbond86** [comment]
Fixes should be limited in scope anyway

**Comment by flagrama** [comment]
We told you that randotext was probably never going to be removed even though most support staff would prefer it gone. Congrats on making a PR that will never be merged?

**Comment by Zannick** [comment]
I can't accept this as a fix. For one, you shouldn't just remove text rando in an unrelated PR. Even though we like to joke about removing it as a fix for other problems with it, it's still a serious change that requires a very wide consensus.

I also disagree that the solution for this bug is to disallow the use of excluded locations for no/glitched logic. Players should still be able to decide that they don't want to bother with certain checks.

Lastly, please squash and/or rebase your branch when you make a PR so the commits are actually relevant. I don't really want to see an unrelated commit and its reversion.

**Comment by flagrama** [comment]
Looking at the GUI and the issue, it seems that the whole Detailed Logic tab gets disabled, when it should just disable everything except exclude locations. That way you should still get an error if you have a non-shuffled location excluded, but can rectify it just be removing it from the exclude locations list without having to change your logic settings first. Though I have not actually tried to run through the debugger with this, so it's possible there's more to it than the message transcribed in the issue linked.

I wouldn't strictly consider "Exclude Locations" logic to be ignored in No Logic. It's a setting that logic works around, much like a plando. Therefore, I agree with Zannick; it should be available for use for the No Logic setting.

**Comment by Dwood15** [comment]
Y'all took the whole `remove rando text` way too seriously, goodness. :/

Closing this, b/c looks like ppl want something different than "cant exclude locations" as the ui currently behaves.

**Comment by Dwood15** [comment]
I'll squash and avoid commitspam on my prs next time.

**Pull request closed without merging**
