### PR TITLE
Patch ROM from file

### PR DESCRIPTION
**Pull request by Hamsda**
So I don't know how close you guys are with the release of 3.0, but I got a first rough working version that allows to patch ROMs from a file that can be additionally generated during the regular world generation process.

The original idea was brought up in another issue (which I can't seem to find) regarding multi world generation, because creating multiple ROMs basically promotes sharing ROMs. But this also applies to racing, where we are currently often sharing ROMs instead of settings/seed. This would allow the race creator to make this file (I've been calling them `world files`) and share it, allowing others to very quickly patch their ROM. This helps people with bad PCs and obviously for multi world (where you can select which player number you want to pick out of the world file).

The thing is, sharing this file has the same security issue that sharing seed+setting has, in that people can have changed versions that allow to create spoiler logs without altering item placement. So it would need to be included in the compiled version with the altered salt to fully work (at least for the racing aspect).
My question would now be, should I hurry the hell up and get this into a polished form so it could actually be included in 3.0 or is it too late for that and it'll have to wait until 4.0?

### CODE REVIEW

**Comment by phixtyseven** [comment]
If we were to assume the meaningful portion of all NTSC 1.0 ROMs are identical, couldn't we just generate a binary patch that each race participant could apply to their own ROM?

**Comment by phixtyseven** [comment]
I've never used the multiworld feature before, so forgive me for my ignorance. But if I understand it correctly, couldn't the person setting up the race just generate a binary patch for each player number, and then distribute the patches to each player?

**Comment by Hamsda** [comment]
Ah yeah, that's the issue I was looking for... weird.

That is sort of the intent of these files, yeah. But they are just one combined file for one seed that contains all the information, because the generation process for one of the seeds currently does all that work anyways.

**Comment by phixtyseven** [comment]
It was hidden in the closed pull requests. I just happened across it the other day.

**Comment by Hamsda** [comment]
Yeah I looked in closed with me as an author, but didn't see it, oh well.

**Comment by Hamsda** [comment]
I rebased the branch to make sure there were no conflicts... didn't know it would create such a mess in here 😳 

Anyways, I got the UI basically how I wanted now and all the functionality seems to be working.

Selecting the `Create World File` checkbox will create an additional file during the regular world generation, the files I've been calling World Files (.wf). It's name looks like this `OoT_<settings>_<seed>_W<world_count>.wf`.

The text box allows to pick one of the WFs with a file dialog.

The additional `Player ID` spinbox is to select which world out of the ones saved in the WF will be used to patch the ROM. And the button next to it will start the patching from the selected WF.

**Pull request merged**
