### PR TITLE
Weirdshot Tunic Color Crash Hotfix

### PR DESCRIPTION
**Pull request by dotzo**
Recently it was discovered that a Kokiri Tunic green color component greater than 0x90 (iirc it starts at 0x93) will crash if you get a "weird" weirdshot.  Despite research by myself and mzx (and others), why this particular byte is causing issues is still unknown.  Until such time that it is, this will brickwall the green value in the Kokiri tunic to 0x90 on Glitched and No Logic settings.

### CODE REVIEW

**Comment by TestRunnerSRL** [comment]
The problem with cosmetic/non-cosmetic options affecting each other is that you might not know the settings. Like if you load from a patch file then you can't know if it's glitchless or not, and the value of the settings in those situations is effectively undefined. I'm not totally opposed to this safety net, but I'm worried that the holes are too big to be useful.

**Comment by TestRunnerSRL** [comment]
Also not sure why there's a check for `kokiri tunic`, because this doesn't handle `completely random` or `custom`

**Comment by dotzo** [comment]
Everything happens inside the loop, even custom and completely random.  colors is always set there, so checking there makes the most sense.  I had thought you were against patching it for all instances, but if not, then this can happen in Patches.py by just reading the byte directly.

**Comment by TestRunnerSRL** [comment]
Can't say I'm a fan of it affecting glitchless. I'm just saying that this check that you have in here doesn't work if you apply from a patch file. Also I misread the bit about `kokiri tunic`, I thought it was referring to the color not the tunic, my bad.

**Comment by dotzo** [comment]
I see what you're saying.  Testing, that check for settings doesn't break it when patching, it just doesn't correct it, but if you're giving out a Glitched Logic seed it's likely you'd know this and pass along the information or the person patching would know.  This would guarantee that anyone new to this weirdness wouldn't be affected by it when generating themselves.

**Comment by TestRunnerSRL** [comment]
Perhaps, but this this doesn't really fix the problem since if you wanted to do something like "random color" on a patch file, there's no way guarantee it'll be safe, no matter what kind of warning you have.

**Comment by dotzo** [comment]
Sure, but protecting the most affected group, those generating themselves, is more helpful than protecting no one.

**Comment by TestRunnerSRL** [comment]
wtv, I normally hate partial solutions, but cause it doesn't seem like you're likely find a proper solution I'll PR this. But I do think that this is unlikely to really fix much, but it can't hurt

**Comment by TestRunnerSRL** [comment]
wait, uh, I think you might've accidentally rebased this PR and deleted the commit, this is now the other PR?

**Pull request merged**
