### PR TITLE
Change Key Rings messages if they give Boss Keys

### LINKED ISSUE #1933: Minor Text Bug - Key Rings w/BKs displayed as "Small Key Ring"
When picking up a key ring, it says that you got a "Small Key Ring for [Temple]", even if it includes the boss key.

Could possibly lead to some confusion with full text shuffle+random settings, since players could assume that finding that textbox means that rings only have small keys.

It looks like the problematic code is here: https://github.com/OoTRandomizer/OoT-Randomizer/blob/e030eda61ec5438c6e65e234b5d8017fa5ede1f6/Messages.py#L295 - it *probably* should append either "Small Key Ring" or "Key Ring" depending on the settings.

### PR DESCRIPTION
**Pull request by GSKirox**
Fixes #1933 by updating the 5 Adult Temple Key Ring messages when they also give boss keys.
keyring_with_bk

### CODE REVIEW

**Comment by Cuphat** [comment]
`KEYSANITY_MESSAGES` is a defined only once and treated as static data otherwise and probably shouldn't be changed dynamically based on settings. With the tkinter GUI gone, this should only really matter when generating a batch of seeds, but if you had the boss keyring setting randomized, after it updates the text for one seed, all subsequent seeds would use the updated text regardless of setting.

**Comment by GSKirox** [comment]
Ah i see, i'm gonna think of another way to do that then.

**Comment by GSKirox** [comment]
Rewrote it so that KEYSANITY_MESSAGES is not modified. 
The new key rings messages are now added to it, and the choice to use either the with BK/without BK is now done in resolve_item_text_id() in item_table.c.
Which is the same method used by the textboxes of Small keys .

**Review by cjohnson57 — APPROVED** [review]

**Comment by rrealmuto** [comment]
I'm fairly certain that this PR is broken. Message ID's 0x9019 and 0x901A are previously used (for chu bags) but get used for some of the new small key ring messages. 

I'll fix it in the silver rupee PR that should have been merged before all of today's other PRs

**Comment by rrealmuto** [comment]
https://user-images.githubusercontent.com/5086838/236656764-1f3cceee-a8cf-43ad-a416-6ea6c85e9ae7.mp4

**Pull request merged**
