### PR TITLE
Simplify Goron City logic with event locations

### PR DESCRIPTION
**Pull request by Roman971**
Made Goron City logic (for a child fire source and stopping Link the Goron) a bit simpler by using event locations more efficiently.

### CODE REVIEW

**Comment by r0bd0g** [comment]
Stopping Link the Goron is also relevant for the Biggoron location.

**Comment by Zannick** [comment]
The net effect is to put Goron Shop and the Warp behind Child Fire/Stop Link which can deepen the tree a little, but that's usually negligible. The improvement to readability is a bigger win.

I'd like to suggest a modest improvement to start using the ternary more in rules that split on age, e.g.:
```py
(is_adult and 'Stop Link the Goron') or (is_child and can_play(Zeldas_Lullaby))
```
could be
```py
'Stop Link the Goron' if is_adult else can_play(Zeldas_Lullaby)
```

**Comment by Hamsda** [comment]
I think the ternary would make it less explicit, which reduces readability overall?

**Comment by Roman971** [comment]
> Stopping Link the Goron is also relevant for the Biggoron location.

Good catch, I will update the trade quest logic as well.

**Comment by r0bd0g** [comment]
I recently mucked with that and missed one of the cases myself.
(This'll make stopping him with blue fire so much easier later Kappa?)

**Comment by TestRunnerSRL** [comment]
I'd like to avoid using the ternary for now mainly because I'm worried it'll make parsing the rules files outside of python more difficult. As it is, it's mostly just conjunctions and disjuctions and function calls, which are all pretty simple.

**Pull request merged**
