### PR TITLE
Add initial 4.0 changelog, Update README

### PR DESCRIPTION
**Pull request by flagrama**
- Reorganizes the README to facilitate better navigation of the README and changelog.
- Links to OoTR website instead of AA's releases page.
- Updates BizHawk fishing bug Known Issue to recommend a user Hard Reset.
- Removes reference to Biggoron as a troublesome collection delay instance due to the bug fix for him. Doesn't remove the line entirely as it is still a  potential issue for other NPCs.
- Adds a changelog with many of the new features, updated features, and bugfixes coming to 4.0.
  - Split between New/Updated Features and New/Updated Options as some people on the Discord were confused about which things they could turn off or were always on.

<hr>
Original Message:

- Only includes things submitted through pull requests
  - Not everything in PRs is guaranteed to be here
- Doesn't include anything Multiworld as I'm unfamiliar and don't know what is new and/or bug fix
- Deciding between features and bug fixes is hard

### CODE REVIEW

**Comment by flagrama** [comment]
Made some changes to the README layout and added a navigation to it to quickly jump around as well.

**Comment by flagrama** [comment]
Pretty okay with this PR now.

**Comment by flagrama** [comment]
Also, an idea for keeping this manageable with new versions starting with 5.0 is to have a Changelog page on the wiki to link to as "Older Versions" at the top of Changelog section with a link to all of the older changelogs also as wiki pages.

**Comment by flagrama** [comment]
Should Readme.html just be removed? Looks like it was there just to be packaged with the binary.

**Comment by TestRunnerSRL** [comment]
Rebased and merged

**Pull request closed without merging**
