### PR TITLE
Death Mountain cloud color checks for Volvagia Blue Warp flag

### PR DESCRIPTION
**Pull request by GSKirox**
The cloud around Death Mountain has a flag to tell if it should be red (before killing Volvagia) or white (after).
This flag is set during one of the cutscenes after killing Volvagia, but since this cutscene is skipped in rando, the flag is never set and the cloud always stays red.
This change make it check instead for the "Took Volvagia blue warp", to ensure the correct color change.

This has a tiny drawback : the cutscene where this change take place is not fully skipped, and since the blue warp flag is set before it, the cloud will now be white instead of red during what is left of the cutscene.
But it's incorrect during one second and correct for the rest of the game, so overall it's more correct !

### CODE REVIEW

**Comment by fenhl** [comment]
> the cutscene where this change take place is not fully skipped, and since the blue warp flag is set before it, the cloud will now be white instead of red during what is left of the cutscene.

This cutscene will be fully skipped once dungeon reward shuffle (#1833) lands (PR soon™) so even this minor issue will be temporary.

**Comment by GSKirox** [comment]
Oh nice !

**Comment by engineer124** [comment]
For reference, here's the specific line that sets this flag in the new implementation of blue warps designed for dungeon reward shuffle (the one that skips all cutscenes):
https://github.com/fenhl/OoT-Randomizer/blob/7a851fdf618880b456c6431ccd55bc695767f54d/ASM/c/blue_warp.c#L85

**Comment by GSKirox** [comment]
Oh i wasn't aware dungeon reward shuffle completely fixed it 😅
Then yeah this PR will be completely useless once it gets in, since it sets the cloud flag properly.

**Pull request merged**
