### PR TITLE
Forbid small key on silver gauntlets chest

### PR DESCRIPTION
**Pull request by puddydoo**
This key placement results in bad logic where some of the doors in spirit temple require longshot just because child isn't allowed to open the door to this chest without having all the keys. There is no such problem with the mirror shield chest though.

### CODE REVIEW

**Comment by ETR-BTF** [comment]
You might want to check if Spirit is vanilla or MQ, since that chest has the same name for both versions of the dungeon and I don't really know how this would affect MQ Spirit key logic.

**Comment by r0bd0g** [comment]
I'm pretty opposed to arbitrarily banning one specific item on one specific check in this way.
And I would really rather not revisit the whole 'are the hands part of spirit debate', either...

As far as this particular change goes, I don't think you should ban the spirit key here in keysanity. There are many checks that could have spirit keys that can sometimes logically require longshot, so it doesn't make sense to single that one out.

**Comment by Hamsda** [comment]
Very opposed to this as well, just arbitrarily saying "not here".
Also longshot locked spirit is not "bad logic", it can actually be very interesting when you deduce it and are still looking for your longshot.

**Comment by r0bd0g** [comment]
As far as revisiting the "are the hands part of spirit" debate, some people think the correct option was actually part of spirit but no keys. Never a fan of inconsistency, for me this was the worst option lol. But it's more complicated now with the keysanity options for any dungeon and overworld, b/c you'd have to decide whether the hands are dungeon, overworld, or neither.

**Comment by Zannick** [comment]
I don't think we're going to accept this, sorry. You can always require there not be a key here with a Plando file if you don't want to have this situation occur in your seeds.

**Pull request closed without merging**
