### PR TITLE
Minor Changes

### PR DESCRIPTION
**Pull request by Cuphat**
A few minor changes.

First, fixes a couple of issues with settings/options names. "Random MQ Dungeon Count" should just be "MQ Dungeon Count". Ganon BK's vanilla option should be "Vanilla Location" for parity with the other dungeon items' vanilla options.

Second, a few changes to the logging. The log messages in the file output are now timestamped. Cleaned up a couple of log messages (there were a couple that didn't add 1 to world.id) and added a few more log messages in Fill.py to denote when each group of item is being placed.

### CODE REVIEW

**Comment by Cuphat** [comment]
Oh, I should also update the default presets in this PR. Note to self.

**Comment by Cuphat** [comment]
I updated the presets but now there is only one preset. Is there another cool preset that should exist besides default and the current weekly?

**Comment by Roman971** [comment]
Maybe a preset to match the multiworld tournament settings? That's the only relevant thing I can think of.

**Comment by Cuphat** [comment]
Good point, thanks for that reminder. Added.

**Pull request merged**
