### PR TITLE
Multiselect for misc. hints

### PR DESCRIPTION
**Pull request by fenhl**
The “Misc. Hints” setting is changed from a checkbutton to a multiselect, allowing the Temple of Time altar and Ganondorf's light arrow hint to be enabled and disabled independenly of each other.

A third option is added that controls whether warp song destinations are hinted on the warp song text box. If disabled, they all say “a mysterious place”. If warp songs aren't shuffled, this option has no effect.

### CODE REVIEW

**Comment by cjohnson57** [comment]
Upon launching the GUI on this branch, a couple of errors pop up from the 2nd line here in Settings.py get_settings_string:
```python
if setting.type == list:
                if len(value) > len(setting.choice_list) / 2:
```
The error is that bool has no length. This implies the value (which is grabbed from `value = self.__dict__[setting.name]`) is somehow getting set to bool, which would make sense if I was carrying over settings from another branch, but I cloned this branch into a fresh folder. As far as I can tell everything is set up properly in regards to making the setting a multiselect and changing its default to not be a bool. Maybe would be worth it to just check if value isn't equal to settings.type, and set value equal to settings.default if so?

If the errors are closed, the GUI works as expected from that point on, but misc hints will have none selected. The GUI will continue giving the error on startup until you choose at least 1 value for misc hints.

**Comment by fenhl** [comment]
I can't test the GUI but I had forgotten to update the default value for the setting and I think that might have been the cause. Can you confirm?

**Comment by cjohnson57** [comment]
Huh, I was checking for things that could be wrong with it and I could have sworn I checked the default and it looked right, my bad.

**Review by cjohnson57 — APPROVED** [review]
Yep, seems good now!

**Comment by Cuphat** [comment]
I got the GUI error too, but I believe it is a one-time thing when loading settings from version without this change.

**Comment by Cuphat** [comment]
I'm going to slot in a fix for the error itself, but the GUI needs to have some sanity checking on `MultipleSelect` settings. That is outside of the scope of this PR, however, and someone who knows their way around the GUI much better than myself should do it.

**Comment by cjohnson57** [comment]
Does that happen anytime a setting type is changed (ex. when forest was changed from a toggle to a combobox) or do other settings types already have checks to handle that?

**Comment by Cuphat** [comment]
Most other types have some sort of handling in the GUI which should prevent that from happening, I believe.

**Comment by cjohnson57** [comment]
Yeah makes sense then.

**Pull request merged**
