### PR TITLE
Don't start eyeball frog timer when getting the King Zora Thawed item

### PR DESCRIPTION
**Pull request by GSKirox**
If you get the item from King Zora after you thawed him while having the Eyeball Frog item in inventory, the timer for the trade sequence starts.
This is a situation that can't happen in the vanilla game (unless you do some item manipulation glitches of course), but can very much happen in randomizer, and is pretty inconvenient while having no real use.

This hack adds a check in the En_Kz_StartTimer function : https://github.com/zeldaret/oot/blob/main/src/overlays/actors/ovl_En_Kz/z_en_kz.c#L447
There is a convenient actor variable that checks if we're getting the trade item or not (isTrading, at 0x01F9 in memory), so we can just check if this is true. If true, do nothing, if not, we make sure that the first if condition of this function will return false, to avoid starting the timer.

Joining a plando to test this situation quickly (start at Domain with blue fire arrow/bow/magic/hook, and put the Eyeball frog at the Frozen waterfall skull).
[testkzfix.json](https://github.com/OoTRandomizer/OoT-Randomizer/files/13946971/testkzfix.json)

### CODE REVIEW

**Comment by r0bd0g** [comment]
This would also occur if the eyeball frog itself is on the zora tunic check. I would assume that case is fixed too?
How does 'hold R lol' work in randomizer, or what about the glitch to get tunic when showing the prescription? Does this change those behaviours?

**Comment by GSKirox** [comment]
Oh yeah this is a lot simpler than putting it on the waterfall skull 😅 Just tested and that is indeed also fixed.
I think Hold R lol has been fixed in rando, would make sense because you could get locked out of the Zora Tunic check.
But i can't find the relevant code that fixes it.

**Comment by flagrama** [comment]
> I think Hold R lol has been fixed in rando, would make sense because you could get locked out of the Zora Tunic check.
> But i can't find the relevant code that fixes it.

Maybe https://github.com/OoTRandomizer/OoT-Randomizer/blob/1827fbb8089d3fe3e816a297a5f3ce2c99a6e0c5/ASM/src/hacks.asm#L1818-L1825 ?

**Comment by GSKirox** [comment]
I removed that code, and tried Hold R lol again, and not only King Zora doesn't give the real item, but he doesn't even give the Eyeball Frog like in vanilla 😅 
My guess would be there's some other trade sequence code elsewhere that prevents the frog from being given.

In any case, this at least confirm Hold R hasn't been a thing in rando for a while.

**Review by fenhl — APPROVED** [review]

**Pull request merged**
