### PR TITLE
Possible plando lists fix/implementation

### PR DESCRIPTION
**Pull request by flagrama**
Used this plando as a test
```json
{
  "locations":
  {
    "Mido Chest Top Left":                                   {"item": ["Bow", "Light Arrows", "Magic Meter"]},
    "Mido Chest Top Right":                                  {"item": ["Bow", "Light Arrows", "Magic Meter"]},
    "Mido Chest Bottom Left":                                {"item": ["Bow", "Light Arrows", "Magic Meter"]},
    "Mido Chest Bottom Right":                               {"item": ["Bow", "Light Arrows", "Magic Meter"]},
    "Skull Kid":                                             {"item": ["Bow", "Light Arrows", "Magic Meter"]},
    "Ocarina Memory Game":                                   {"item": ["Bow", "Light Arrows", "Magic Meter"]},
    "Target in Woods":                                       {"item": ["Bow", "Light Arrows", "Magic Meter"]}
  }
}
```
Seems to work. It will not put bows on other locations once three have been filled, same with two magic meters as would be expected; however the lists themselves can have as many of an item placed as is randomly chosen as plando allows this in general.

An improvement might be making it so lists specifically don't exceed the item pool unless no item pool slots are left.

Scrubs and Shops were not tested but should work the same.

### CODE REVIEW

**Comment by LostThePirate** [comment]
If this works as intended, looks like a good QoL upgrade for plando.

**Comment by flagrama** [comment]
Realized I should drop some of the spoilers I generated for people to look at, so attaching those.
[plando tests.zip](https://github.com/TestRunnerSRL/OoT-Randomizer/files/4018293/plando.tests.zip)

**Comment by aplumafreak500** [comment]
One thing I want if this gets merged is blacklists in addition to the existing whitelists for items. Thus, you could enforce specific items *not* be present in those locations unless absolutely necessary per existing logic.

**Comment by flagrama** [comment]
@aplumafreak500 that was already a working part of plando. Just put a "!" before the name of each item you don't want included. So in the plando example above
`"Mido Chest Top Left":                                   {"item": ["!Bow", "!Light Arrows", "!Magic Meter"]}`
would ensure that there is never a bow, las, or magic on that location.

**Comment by flagrama** [comment]
Newest commit makes it so setting boss items in a list should work as well, so something like setting all child dungeons (and links pocket) to stones should be possible. Doesn't support setting 3 locations to the same 2 items. Could probably pull from the remaining prize pool if the list is empty, but I feel like users wouldn't want that happening to them.

[Child Dungeon Stones plando test.zip](https://github.com/TestRunnerSRL/OoT-Randomizer/files/4020942/Child.Dungeon.Stones.plando.test.zip)

Might work as a framework for ensuring you don't exceed the item pool until it is empty as well, but I don't know.

**Comment by flagrama** [comment]
And that commit should make it so that the item pool count gets exhausted before it will place items exceeding the item pool count when using lists. So now the first plando will have to set three bows, two magic and a light arrows before it will start randomly pulling from the list instead.

**Comment by Zannick** [comment]
> And that commit should make it so that the item pool count gets exhausted before it will place items exceeding the item pool count when using lists. So now the first plando will have to set three bows, two magic and a light arrows before it will start randomly pulling from the list instead.

Since we don't shuffle the plando list, this is going to skew the probability somewhat strangely, since it'll guarantee that the first 6 locations get, e.g., at most 1 LAs. If it won't create duplicates until it runs out of counts, like you said, and the order of placement is fixed, that would, I expect, make it more likely to place LAs (as a duplicate) at those overflow locations. Indeed, I generated 250 seeds using my stats script (with `['Bow', 'Magic Meter', 'Light Arrows']` among 8 locations: your 7 plus `LW Deku Scrub Deku Stick Upgrade`) and found the last two in my json file (`Target In Woods` + `LW Deku Scrub Deku Stick Upgrade`) had roughly even distributions of items (~30s), while the others conformed a bit better to the 50-33-16 dist one would expect from shuffling a multilist of 3+2+1.

Probably the best fix is to shuffle the location ordering before iterating over them.

**Comment by flagrama** [comment]
I did think that could be a concern, however I reasoned it away as most likely someone who is making a plando would probably have an idea of how they wanted the layout to look in the first place and would just be using the list to make it more interesting than a static item all the time.

However, if just shuffling the order of the locations would likely be enough to improve the situation in all cases I'm certainly not against it. I'll give it a shot.

**Comment by flagrama** [comment]
This seems to work better to me. Can you confirm?

**Comment by flagrama** [comment]
I quickly added that implicit conversion thing. I don't think it should break anything, but I'm not making any promises either. It makes it so you can just use
`"Mido Chest Top Left":                                   ["Bow", "Light Arrows", "Magic Meter"]`
instead of having to use this longer form
`"Mido Chest Top Right":                                  {"item": ["Bow", "Light Arrows", "Magic Meter"]}`
but that form will still work. I believe this is how people would expect lists to work actually.

**Comment by Zannick** [comment]
Yeah, it looks better to me as well. Thanks!

**Pull request merged**
