### PR TITLE
Add vanilla contents to all item locations

### PR DESCRIPTION
**Pull request by fenhl**
This is the first part of a refactor of `ItemPool.py`.

As originally suggested by @r0bd0g, this PR adds a column to the `location_table` in `LocationList.py` that lists which item is placed at each location in the vanilla game (or vanilla MQ). This should make it easier to reason about item pools. It could also be used to automatically generate the [vanilla](https://ootrandomizer.com/seed/vanilla) and [MQvanilla](https://ootrandomizer.com/seed/MQvanilla) plandos in the future.

I also added `"Vanilla"` and `"Master Quest"` categories to dungeon locations, which will allow much cleaner code in the `ItemPool` refactor, and fixed the inconsistent indentation in `location_table`.

### CODE REVIEW

**Comment by r0bd0g** [comment]
I want to point out that the scrubs that sell arrows or seeds do so depending on what age you are when you talk. Arrows as adult, seeds as child. So maybe a special type of item should be listed there, and then maybe later item pool could 50/50 whether they should be replaced by arrows or seeds.

**Comment by fenhl** [comment]
Looking at the current `ItemList.py`, it seems that the two items used by Deku scrubs, `Buy Arrows (30)` and `Buy Deku Seeds (30)`, have different vanilla prices (60 rupees for the arrows, 30 for the seeds). So I don't think we can just combine them into a single item. Instead, maybe just using the “defaults” as currently listed would be fine (which would result in a pool of 2×30 seeds and 5×30 arrows).

**Comment by r0bd0g** [comment]
You have to arbitrarily decide whether a scrub is arrow or seeds and there's just something about that that's never sat well with me. Which of the scrubs atm are being treated as seeds?

**Comment by fenhl** [comment]
The one that's being treated as seeds is in Dodongo's Cavern, while the ones that are being treated as arrows are in the Lost Woods, Lon Lon Ranch, Goron City, DMC, Lake Hylia, and Ganon's Castle.

**Comment by r0bd0g** [comment]
Hmm. So Lon Lon would make more sense as seeds since that's child-only. City, DMC, and Ganon's, arrows since adult-only. Lake, LW, and DC are all accessible as either age in vanilla though...

**Comment by fenhl** [comment]
I'd probably go with seeds for all 3 of these locations. Lake because it's right next to the owl, LW because it's near child spawn, and DC because it's a child dungeon.

**Review by Zannick — APPROVED** [review]
Looks informational rather than having an effect, right?

Going to hold off on merging for now due to conflict with #1176.

**Comment by fenhl** [comment]
Alright, I'll go ahead with the `ItemPool.py` refactor then, it will include these changes. I only PR'd this separately to minimize merge conflicts with other work (like #1176) later.

**Comment by puddydoo** [comment]
Should I go and merge this into #1176?

**Comment by Zannick** [comment]
No, please allow me to merge PRs as they are accepted. (It's actually quite a headache to deal with PRs that merge Dev into them after other PRs are accepted, just leave the branch as it is, without a strong reason to rebase).

**Pull request merged**
