### PR TITLE
Add setting to spawn gerudo guard outside the fortress gate

### PR DESCRIPTION
**Pull request by Elagatua**
First PR, feedback is welcome.

gerudo-guard

### CODE REVIEW

**Comment by ETR-BTF** [comment]
I think the tooltip should mention which ER settings force the Gerudo guard to be there. The tooltips of other settings that interact with one another also give info like this (e.g. forest, starting age, one major item per dungeon, skip child zelda)

**Comment by cjohnson57** [comment]
Honestly I don't think this setting is necessary for such a minor thing. I think we should either leave the guard as it is now, or just say screw it and make it always spawn. I'd be okay with just making it always spawn but I'd rather hear the opinions of others before doing that.

Either way, you'd need to edit logic for this.

**Comment by r0bd0g** [comment]
The guard had to be moved to fixed non-repeatable access issues stemming from ER. And then in card shuffle, it's moved because it would be lame if you randomly find gerudo card and then get locked out of fortress since you can't reverse anymore. There were objections mainly on 'spirit of vanilla' grounds, iirc, to applying this change where it was not actually needed, keep the vanilla gameplay aspect of having to decide whether to open the gate or not to have the option to reverse later, or force yourself to have to walk through valley if you need to return to fortress. I think I would suggest that this setting has such a clunky interaction with other settings, and constitutes such a minor change that it'd be better to just always move the guard than have this setting. I don't actually think the guard should always be moved, but if it's agreed that something should change, I would suggest the guard just always be moved.

**Comment by Elagatua** [comment]
I don't have strong feelings about whether this actually gets merged into master; it was necessary for a game mode in my fork and I was surprised to find the guard missing randomly in one of my seeds when I thought the guard was spawned there across all settings already.

**Comment by Cuphat** [comment]
> Are any logic changes needed, actually? You wouldn't think that it would matter since the guard was already moved for all situations where it did.

Yeah, I don't think any logic changes are necessary. Any entrance rando that has the potential for opening the gate to be required for access moves the guard. If the guard isn't moved, that means you have access to getting caught by the guard (if you don't have the Gerudo Card) or access to crossing the bridge (if you do have Gerudo Card, which you'd have obtained by freeing the carpenters).

> I don't have strong feelings about whether this actually gets merged into the main repo; it was necessary for a game mode in my fork and I was surprised to find the guard missing randomly in one of my seeds when I thought the guard was spawned there across all settings already.

I feel like this is the kind of setting that could exist but not be shown in the GUI. If anyone wanted to use it for their specific needs, they can set it via plando or in their settings.sav and use the CLI.

**Comment by Elagatua** [comment]
I can remove all the UI stuff and update the PR if that's the direction you'd like to go.  I don't need the setting present in the gui.

**Comment by Cuphat** [comment]
> I can remove all the UI stuff and update the PR if that's the direction you'd like to go. I don't need the setting present in the gui.

Add `'optional': True,` to the `gui_params` of the setting and then you can remove it from `settings_mapping.json` without the GUI screaming at you.

**Comment by Zannick** [comment]
RFC @TestRunnerSRL
I agree that it doesn't need to be a GUI option but would prefer just having the guard there regardless of setting.

**Comment by r0bd0g** [comment]
Here's an old discussion where this change was originally implemented: https://github.com/TestRunnerSRL/OoT-Randomizer/pull/675

**Comment by mracsys** [comment]
I wouldn't mind seeing this revived as a QoL change. I always forget it's not a thing in non-ER seeds.

**Comment by cjohnson57** [comment]
Superseded by #1655, sorry

**Pull request closed without merging**
