### PR TITLE
hint changes

### PR DESCRIPTION
**Pull request by Hamsda**
First off, regarding the frog ocarina minigame change, I have heard the desire for this a few times and think it is reasonable. Depending on song placement, this is one of the hardest checks in the game to make, so it should be included in the alwaysLocations.

I generated quite a few test seeds for the tourney distribution and was overall pretty happy with the changes. Having a guaranteed copy for the alwaysLocations and giving a slightly increased chance to woth spots should feel much better.
This still allows the interesting situation where different spots in the same area get picked for woth, so runners need to keep a count to realize if there are multiple woth spots.
Overall I hope this makes the tourney distribution a bit more consistent and slightly better, but hopefully not too good.

The overpowered distribution I added removes the dungeon and overworld hints, which are pretty useless in almost all of the cases. Remaining are just woth, item locations (quite useful most of the time), and the good locations (to know about annoying checks).
It is mainly aimed for "fast settings" or multi world fun runs, where basically every hint you get will yield useful information. It is in no way intended to be "balanced", hence the name.

During testing I noticed one thing, that might be confusing for competitive settings:
Duplicates for anything besides trials/alwaysLocations are not guaranteed.
If they get picked with just one gossip stone left, the hint will still be placed but obviously just once.
I am not sure if a count of e.g. 2.5 should guarantee 2-3 hints or if 1-3 would be acceptable in this case as well.

### CODE REVIEW

**Comment by TestRunnerSRL** [comment]
This seems reasonable, although I think we should reconsider the names. I think we should call them something like `Balanced`, `Strong`, `Very Strong` respectively, and possibly add a `Weak` and `Useless`.

**Comment by r0bd0g** [comment]
I agree on changing the names. Particularly the name "tourney" I think should go...

Along with adding Frogs as always, there were plans to remove poes and biggoron from always if your poe count or adult trade item were within certain ranges...

**Comment by Hamsda** [comment]
Yeah I thought about the changes to Biggoron and Poes, but couldn't figure out a quick way without making special cases for them :/

**Comment by Hamsda** [comment]
I'm not sure if weak and useless hints would be appealing. If you don't want to play with hints, turn them off or don't read them.
The balanced distribution is balanced in the sense that it uses a bit of everything of the hint types instead of just the good stuff, not that it is the "middle ground" option.

**Pull request merged**
