### PR TITLE
Reset Treasure Box Shop state on death with bonk damage

### LINKED ISSUE #1663: Dying in the Treasure Chest Game after opening a door lets you cheese the minigame
While this is (presumably) a vanilla bug, I don't think it was accessible until bonko (= OHKO bonks) was added. For that reason I am not sure if this should be classified as a rando bug to be fixed. If it's decided to not remove/fix this, then should it be part of logic? A fix should keep in mind to not patch the Ocarina Items glitch for cheesing this minigame.

### PR DESCRIPTION
**Pull request by mracsys**
Resetting the Treasure Box Shop via death or Sun Song does not fully reload the scene. Doors remain unlocked, but chest contents are replaced and the vendor sells another key. This is a known bug in vanilla, and the behavior should not be changed for glitched players.

Bonk damage unintentionally allowed players to abuse this mechanic. To prevent this, the bonk damage function is extended to reset temp flags, chest flags, and small key count for the Treasure Box Shop scene if it is the current scene and bonk damage will kill the player.

GZ shows the temp and chest flags are all zero on scene load. I wipe all of them instead of trying to isolate just the doors and chests.

If someone has time this should be checked on hardware. Tested on PJ64 dev.

Only fixes the bonko portion of #1663

### CODE REVIEW

**Comment by r0bd0g** [comment]
Thoughts of MW ice traps?

**Comment by mracsys** [comment]
I don't see a way to address that and not hurt glitched playthroughs. If someone can think of a way around the glitched use case, more power to them. The bonk fix has its own damage routine, whereas ice traps use whatever method regular damage sources use.

The goal was to prevent accidentally breaking the rules for glitchless/standard. MW ice traps requires:
1) OHKO or player health close to zero
2) Another player has access to ice traps for the player

It's much less likely to be an accident in this case. Even if it is, it gives one extra chance per death, which is unlikely to be a benefit, especially without OHKO to enable deaths from additional traps.

**Comment by r0bd0g** [comment]
Is using death in glitched all that viable?

**Comment by mracsys** [comment]
Whether or not it's viable, if it's possible I don't think it should be touched.

**Comment by r0bd0g** [comment]
I would still like to know what it would entail. It's possible that the methods are generally banned in glitched rulesets outside of 'anything goes', and if you're in anything goes land, every change affects how glitches work.

**Comment by ETR-BTF** [comment]
> I would still like to know what it would entail. It's possible that the methods are often banned in glitched rulesets outside of 'anything goes', and if you're in anything goes land, every change affects how glitches work.

Suicide by explosives using Restricted Items?

**Comment by r0bd0g** [comment]
Restricted items how?

**Review by cjohnson57 — APPROVED** [review]

**Pull request merged**
