### PR TITLE
Add Skulltula House misc hints

### PR DESCRIPTION
**Pull request by exodus122**
Added new misc hints for the House of Skulltula. The cursed residents (10, 20, 30, 40, and 50) will tell you which item they have if the setting is enabled. You can select any combination of those 5 (in case people only want 30, 40, and 50 hinted, for example). To accomplish this, I modified the misc hints system to support hinting which item is in a specific location. Previously misc hints was just for hinting the location of a specific item. Also modified the conditions for the always and sometimes hints so you won't get them if the misc hint is turned on.

### CODE REVIEW

**Comment by fenhl** [comment]
You'll want to add the new hint locations to the region files in both `data/Glitched World` and `data/World`.

**Comment by r0bd0g** [comment]
Check that you can still get 200r after you have 100 tokens.
I would assume in that case the hint text would go away and you would have to talk to them to find out what the prizes are.

Oh you have talk to each of them to find out what their prizes are in turn.

**Comment by fenhl** [comment]
> Check that you can still get 200r after you have 100 tokens.

This is unnecessary since this PR doesn't change any behavior.

**Comment by r0bd0g** [comment]
I remembered the suggestion being to have the guy in the middle say what all of the rewards are.

**Comment by exodus122** [comment]
I don't know why it failed

**Comment by exodus122** [comment]
It passes the unit test now

**Review by cjohnson57 — APPROVED** [review]
This is awesome, great job

**Pull request merged**
