### PR TITLE
Tooltip typo

### PR DESCRIPTION
**Pull request by Tyrusss**

### CODE REVIEW

**Comment by DatXFire** [comment]
“The” in Bottom of the Well should not be capitalized.

**Comment by Tyrusss** [comment]
I was always taught that the definitive article is capitalised when it's part of a name, such as 'The Well'

**Comment by DatXFire** [comment]
Might be a British thing? As far as my knowledge goes you never capitalize an article unless it is the first or last word of a title. In any case it’s inconsistent with the other capitalizations such as a few lines below, or the logic files /data/World/Bottom of the Well.json

I’m fine with whatever, as long as it’s consistent.

**Comment by Tyrusss** [comment]
I agree with you on the consistency part.
Changed it

**Pull request merged**
