### PR TITLE
Cow Sanity

### PR DESCRIPTION
**Pull request by KevinPal**
Adds an item to each cow location:
- 1 in Links house
- 1 in Impas house
- 2 in LLR stables
- 2 in LLR tower
- 1 in GV
- 1 in a grotto in HF
- 1 in a grotto in DMT
Still need to do the cow in MQ jabu

Not meant for 4.0, but here so this can be played with/tested/reviewed

### CODE REVIEW

**Comment by r0bd0g** [comment]
HF Grotto Cow logic incorrect as Fire Arrows + Explosives do not reach the cow. (That said I'd want to see first if the song will reach through the webs or not.)

**Comment by OlafurKrH** [comment]
Wow and just when I thought you couldn't make the game MORE random, you think of this...

Yes please.

**Comment by r0bd0g** [comment]
Can you please add parentheses? I think the operator precedence is correct for this, but it's bad form.

**Comment by r0bd0g** [comment]
Thanks. It's just better if the code doesn't make you google operator precedence. :p

**Comment by KevinPal** [comment]
Merged fixes for cow in house

**Comment by r0bd0g** [comment]
In vanilla you need an empty bottle to get something from a cow.
But I'm gonna guess this is not the case anymore? Maybe I should actually try this out before asking stupid questions?

**Comment by Cuphat** [comment]
Yeah, I believe it patches out the need for a bottle (for the initial item, not subsequent milkings).

**Comment by KevinPal** [comment]
As Cuphat said, you don't need a bottle to get the initial item, but still do if you want to get milk.

**Comment by KevinPal** [comment]
Fixed the Cow in Jabu MQ, and rebased

Cowsanity should be fully working

**Comment by TestRunnerSRL** [comment]
Rebased and merged

**Pull request closed without merging**
