### PR TITLE
added adult_trade_option

### PR DESCRIPTION
**Pull request by Hamsda**
This PR adds a setting called `logic_earliest_adult_trade` that allows to set which item is the earliest in the adult trade sequence that will show up.
It mainly aims to give users a setting to reduce variance between seeds where Biggoron is required and one either has to do barely anything or almost the entire adult trading sequence.

I'm not sure what the default setting of this should be, so I just set it to Pocket Egg to mimic the seeds that were created before the option got added.

Created a bunch of test seeds and it worked as expected.

Since I'm a dummy and have no clue how to use command line arguments for the rando, I'm not sure if the help would look good.

### CODE REVIEW

**Comment by Hamsda** [comment]
They are logically the same but you might be able to skip some steps if you get an item that might regularly have a timer.

Though the alternative you suggested is also quite nice, that allows people to determine how long of a trade quest they wan't to do.

I don't care either way, I can change it to the latter. We just need some opinions on this I guess?

**Comment by Tyrusss** [comment]
There's also the possibility (rare as it may be) that some people enjoy the trade sequence, and would rather start with the Pocket Egg. With the option how it is now, even if they chose Pocket Egg, there would still be the possibility of them getting a claim check, leading to frustration. I think r0bd0g's suggestion would be best for this.

**Comment by TestRunnerSRL** [comment]
Another suggestion is maybe be able to set a min/max item so you can specify the range. It'll allow for kinds of configurations, but the problem is that it's also less intuitive to use an option like that. I think that kind of behavior is something I would've liked to do for all the options like this (trials, skulltulas, poes), but tkinter doesn't really have a range slider widget. There's some implementations online but I kinda didn't delve into it too deep. Also since this has text options instead of numbers, it makes it a bit harder to put into a slider. In general not really a fan how all these options behave in a different way

**Comment by Hamsda** [comment]
Okay so this is the best solution I could come up with:
Changed it to be two text boxes, one for the earliest and one for the latest item in the trade sequence. 
This allows people to select a certain range they are okay with, the entire thing if they want full random, or just a single item (the last for the lazy or the first for the masochists 👌 ).
Failsafe for people selecting an earlier item in the chain as the later option is built in and will just flip them around (not sure if I this should be communicated better?).
Also I moved the `logic_no_trade_biggoron` option right above this and made the boxes disable if `logic_no_trade_biggoron` is checked, because then they don't really matter.

**Comment by TestRunnerSRL** [comment]
This is ok, but I do feel it's a bit clunky. Also I should bring up that I was hoping to have a feature that would make is so that the trade quest is not forced to chain, meaning each trade item could give a random item. Makes the items a lot more viable and less garbage to check. Would probably involve some UI code stuff that I don't really understand

**Comment by Hamsda** [comment]
That sounds interesting as well and yeah, with the apparent limitations of the UI (and my even more limited knowledge) this was the best I could come up with.
I think it'll at least give people the option to reduce annoyance or go ham on the randomization, so thats good at least :)

**Pull request merged**
