### PR TITLE
Change Ganon's Castle text to a readable color

### PR DESCRIPTION
**Pull request by phixtyseven**
Replace black (47) with red (41)

Black text is difficult to read in regular text boxes. I would imagine
it was not intended for this purpose. Light blue seems a better option,
being neutral in color theming while still highlighting the topic.

Did I say light blue? I meant red. In-game text refers to Ganondorf in
red, thus...red.

### CODE REVIEW

**Comment by TestRunnerSRL** [comment]
I mean, red is used as the general highlight color for everything, so that logic is a bit..

I'm fine changing it, though. I wanted ganon to be a different color but yeah.

**Comment by flagrama** [comment]
Ehh, red is a bit of a bother because that means Fire Temple and Ganon's Castle are going to have the same color making it harder to identify with just a glance while mashing, right? With the in-game key counter I guess it isn't a huge problem though.

**Comment by TestRunnerSRL** [comment]
All colors will have the problem, except black, which is mostly illegible

**Comment by phixtyseven** [comment]
Originally I felt it should be light blue, like the Light Medallion/Temple. It just sorta sounded right. But then I looked through the text and felt I erred in my judgment. Every reference to Ganondorf is either red or white. I assumed it was their intention, but you're right it's kind of a silly point when red is pretty much the default highlight.

It's hard for me to say which is better. I suppose white may even be fine; it wouldn't be confused with the fire or ice dungeons. So long as it isn't black, because it looked unpolished.

**Pull request merged**
