### PR TITLE
Add Invisible Chests option

### PR DESCRIPTION
**Pull request by mracsys**
Toggle to make all chests in the game invisible without Lens of Truth.

Rooms in OoT have a flag for Lens behavior to either show (default) or hide actors. This is used for places like the central room of Bottom of the Well to have "fake" walls that can be seen through with the Lens. Unfortunately it does not appear possible to have both behaviors for different actor types in the same room. To work around this, chests are not rendered at all if Lens is not active in these rooms. If Lens is active, the chests get drawn but are not culled by the Lens overlay. In other rooms with default Lens behavior (show actors), invisible chests work normally and get culled by the overlay.

Tested on N64, Retroarch, and Project64. Crashes loading the title screen on Wii Virtual Console. I have no idea how to debug that. Hopefully someone else does.

This is my first major ASM project. Styling/method comments are super appreciated.

### CODE REVIEW

**Comment by fenhl** [comment]
What's the reasoning for not adjusting the logic? If it's just that no one's done the work, I'd be interested in working on it.

**Comment by fenhl** [comment]
I don't think “it's just a meme setting” justifies having logic behave inconsistently. If it lands in the main branch, people will want to play with the setting casually anyway. A trick could be added to make the logic behave as if the chests were visible. Alternatively, the existing “lensless region x” tricks could be extended to include all chests.

**Comment by ETR-BTF** [comment]
Not changing logic would also mean that chests that normally require the lens+magic (like the spirit chests) still do while other invisible chests don't. That seems confusing, especially if it affects woth/path hints in a seed.

**Comment by cjohnson57** [comment]
> Not changing logic would also mean that chests that normally require the lens+magic (like the spirit chests) still do while other invisible chests don't. That seems confusing, especially if it affects woth/path hints in a seed.

I agree with this- I think it's fine to not require lens in logic for every chest in the game when this setting is on, but I do think it should be adjusted so that other invisible chests don't require lens either. I'd almost want to say you could just have enabling this setting automatically enable all lensless tricks as well, but not sure if it would be desirable since there are other things besides chests that consider lens.

> I think it's worth mentioning in the tooltip that the feature does not currently work on Wii VC.

Unfortunately I don't think it'll get merged until it works on VC. @engineer124 any ideas about this?

**Comment by r0bd0g** [comment]
To address the lens logic issues created by this would be too much of an upheaval imo. There's no great way to do it, so it's probably better off no address. Anyway, we have a lot of weird settings already; I really don't think we need this one. Feels like a lot of meme setting PRs coming in lately. I almost feel like if you want to be accepting PRs like these we need to hide them in some out of the way "memes" tab.

**Comment by mracsys** [comment]
I've been writing a lot of these with something like MM's Gimmicks tab in mind. If it makes more sense I can put them all in draft until after a GUI rework to reclaim/expand space for something like that.

image

**Comment by r0bd0g** [comment]
Honestly if you want to put a tab and it's like "Memes" and you click and there's a big text at the top that says "Warning: Don't." you can basically put whatever you want in there.

**Comment by mracsys** [comment]
Wii VC is fixed. It did not like jumping back to an offset on $ra. No idea why. Instead of handling everything in one function for inverted lens, I have separate functions to hide or show chests in these rooms hooking into relevant points in the branch logic.

**Comment by fenhl** [comment]
There seemse to be an issue with this PR where if the setting is off, chests are visible before they spawn, allowing the textures of chests that fall from the ceiling, such as those in the GTG lobby, to be peeked.

**Comment by r0bd0g** [comment]
Are you sure they would not be visible before spawning regardless, if using the lens?

**Comment by fenhl** [comment]
I checked on Dev and the chests are still invisible with lens before being spawned.

**Comment by cjohnson57** [comment]
> There seems to be an issue with this PR where if the setting is off, chests are visible before they spawn, allowing the textures of chests that fall from the ceiling, such as those in the GTG lobby, to be peeked.

That's a pretty major issue imo, once this is fixed I'll review.

**Comment by mracsys** [comment]
There's also an issue with Treasure Chest Game due to the lens inversion setting in the room. Activating lens shows the chests again like it does elsewhere but does not let you see the key/rupee items. I have two options:

1) Never show the chests even with lens, allows the key to be seen but not obvious there is a chest to open.
2) Disable chest hiding for this scene.

I'm leaning towards 2 for usability even though it means some chests will be visible before opening.

**Comment by cjohnson57** [comment]
So 2 just means chest game would always act like it normally does? Yeah that seems like the better of those options to me

**Comment by cjohnson57** [comment]
Actually, would 1 only affect when invisible chests is turned on? If so, that'd be okay since invisible chests already requires pretty deep game knowledge

**Comment by Hexocyte** [comment]
As I mentioned at #1492, this makes the chests appear in front of red ice and flame circles even when the setting is off.

red ice chest screenshot

That might be good for making it easier to see the chest textures with Chest Appearance Matches Contents, but otherwise it doesn't make sense to change when Invisible Chests is disabled.

**Comment by mracsys** [comment]
Red ice transparency effects have been fixed. Effects with the setting off should also be resolved now. For treasure chest game, I disabled invisible chests here to keep the game beatable.

**Review by cjohnson57 — APPROVED** [review]

**Comment by fenhl** [comment]
Wait so is this going to be merged without logic changes now? I'm still interested in working on the logic.

**Pull request merged**
