### PR TITLE
Generic Event support

### PR DESCRIPTION
**Pull request by Zannick**
Event items don't have any rom functionality, bytes, etc associated with them, they're just markers for accomplishing certain tasks (eg. winning) or reaching certain locations. This provides a way to bypass defining event items and locations in their respective lists, by automatically creating Locations and Items from provided event names.

Adds a separate section to the region json that lists "events". During world generation, these will create a Location, push an item named (event) there, and lock it.

Playthrough generation will omit items not explicitly defined in the items table, so these will not clog up the playthrough.

This relaxes the access rule parsing by allowing potential typos, but tracks event items used in order to throw an error if a typo is made or an item alias (like "Longshot") is used outside of can_use. (And good thing, too, since I made three typos!)

EDIT 2019-06-01:
The rules parser now automatically creates internal event "subrules" for parse-time functions and aliases:
* `at` replaces `can_reach(<Region>)` checks
* `here` replaces all the `as_age` checks
* `here(can_plant_bean)` replaces `can_use(Magic_Bean)`

The parser can now also interpret string values as item names, which has been applied for the event items defined in the new rules.

I've kept a few of the region changes I put in an earlier version, and a small handful of events explicitly defined in logic. This is still around a 20%+ speedup running all the spoiler unittests.

### CODE REVIEW

**Comment by Roman971** [comment]
1. I think the events should be placed above locations in logic files. It makes more sense since they are usually referenced by locations in the same region, and never the reverse.

2. Shouldn't the Bomchu Salesman be a NPC location with no patching data like Zeldas Letter or the bowling bombchus? It seems weird and inconsistent to keep it an event location even though it gives an item and can be disabled.

3. In my opinion, trial locations should still appear in the playthrough. It's useful to be able to tell which trials are required directly from the playthrough, and when they can be completed.

4. I think the `eventlocations` dict in ItemPool.py should be renamed to something like `alwayslocations` which is more accurate since: 1. it's not limited to event locations, 2. it only contains a small subset of event locations which are actual locations defined in the location table.

5. Why did you make `Big Poe Kill` an event location? I think it's fine as a Drop location, especially since it contains a Drop item and should show up in the playthrough like other bottle contents.

6. I see that you moved the entrance playthrough sphere building at the bottom part of the final spheres collection, but isn't that going to make them inaccurate and desynced with the item playthrough by one sphere? The idea of the entrance playthrough is to show which entrances were unlocked in each sphere of the item playthrough, so it's very important to keep them perfectly synced.

7. In `load_regions_from_json`:
```python
    # Allow duplicate placement of events for overworld locations.
    if 'dungeon' not in region:
        lname = new_region.name + ' ' + event
```
Why is this limited to overworld locations? We might need to have duplicate event locations in different regions inside dungeons at some point so is there a reason for this limitation?

8. There are a bunch of can_reach calls left in State.py for trade quests, it would probably be a good idea to handle those as well while you're at it. There is also one as_child_here left for beans but I don't know if you want to add an event location for each bean.

**Comment by Zannick** [comment]
Thank you for the thorough review. I'm going to spend some time working on these suggestions, but I'll answer them really quickly.

1. Will do.
2. The explicitly defined events are kind of weird. I'll make Salesman an NPC.
3. I'll add the items back to the table, that will make them show up again. Should I consider Deku_Tree_Clear, Water_Temple_Clear as well? Closed Forest is very obvious, but maybe refilling the lake is necessary without needing anything from Water.
4. Will do. Thinking `fixedlocations` or `special_locations`.
5. I don't know. I'll revert that.
6. I see what you mean. I think I can fix that by collecting the items at the bottom of the loop.
7. I didn't like the idea of having locations named "Gerudo Training Grounds Lobby Gerudo Training Grounds Beamos Clear" even if they didn't show anywhere, and I didn't want to make event locations be unique, and I didn't want to generate event item names from region names. But this solution is sloppy, so thanks for calling me out on it. I can fix that to something else... "(event) from (region)" ought to be less bad.
8. I will probably revamp can_use(Magic_Beans) to use event locations. For trade quest (and mask quests) I am not yet sure of a solution other than event locations. Glitched logic still has a ton of lambdas, too, might not get around to it in this PR.

**Comment by Zannick** [comment]
That should be 1-7 taken care of. I'm going to work on Beans next, but depending on complexity, it might go in a followup PR.

**Comment by Zannick** [comment]
Ok, very minor thing I'm noticing: because I'm treating event items as normal items for the purpose of playthrough generation, the spheres sometimes look off because an event item is hidden in a sphere. eg. Song of Storms in sphere 2 and a BotW check in sphere 4, with items in sphere 3 but nothing relevant. I don't know if there's a good way to fix that without adding in events to the exit processing in Playthrough.

**Comment by Zannick** [comment]
So based on a discussion today, I'm going to rework this to generate events from the as_either_here etc and can_reach functions, so we don't need to mess so heavily with all the logic json.

**Comment by Zannick** [comment]
The rules parser now automatically creates internal event "subrules" for the as_age functions, and the newly added "remote" function (replaces can_reach(region), entrances not supported yet), which is the closest thing we have to having the same location in multiple regions. Also, there's no longer any difference between as_age and as_age_here.

Magic Beans now use an as_child check, and can_use(Magic_Bean) has been removed from everywhere.

I've kept a few of the region changes I put in an earlier version, and a small handful of events explicitly defined in logic. This is still around a 20%+ speedup running all the spoiler unittests.

**Comment by Roman971** [comment]
Alright, I like this for the most part but there are a few things I think could be improved in the new remote/subrules stuff:

1. It's not a big deal but I think `remote` is too much of an abstract name and we should use something like `at`, `in` or `within` to explicitly show that the player should have been able to perform the action in that other region.

2. Since you are converting everything to a "can have done something somewhere" model, I think it could be a good idea to make everything consistent and get rid of `as_age` and `as_age_here` checks entirely, and instead use a `here(rule)` condition, with the rule including the age checks when necessary. This would be the same as your current `remote(region, rule)`, but with the region automatically set as the current region, which should make the implementation very simple as well.

3. I'm not a huge fan of how beans are handled now. It would probably be a good idea to create a `can_plant_beans` state method to make bean rules a bit simpler, now that `Magic Bean Pack` is a thing. However, if you go for option mentioned in my 2nd point, I don't think you would even need to remove `can_use(Magic_Bean)`, since you could just do `here(can_use(Magic_Bean))` without any of the `as_child` stuff. Also, I think you forgot to remove the Plant Bean stuff in `load_regions_from_json`.

4. I think TR agreed on this as well but event items should probably be referenced as strings with spaces instead of using underscores, to make quick search/replace easier. I see you did that for `remote` calls, which is nice, and the same should probably be done when referencing event items that have the same name as their location.

6. This is very minor but the Bombchu Salesman should probably be moved up with NPCs in the location table instead of being left among Events.

5. Why is there an inconsistency between glitchless and glitched logic for `Pierre`, shouldn't glitched logic have a `Bonooru` event as well? Or maybe the `Bonooru` event shouldn't exist at all since it could simply be inlined now. Not sure which one you wanted to go with in the end. 

Also, this is kinda unrelated but looking over this made me realize glitched logic doesn't actually fully support the child lake control option in logic. I think the `Underwater Bottle` location should be accessible in some cases thanks to that option. Though Zoras Domain and Water Temple access doesn't matter since it's always true in glitched logic.

**Comment by Zannick** [comment]
1.   Yeah, I wanted to use "from" originally, but that's a python keyword and I didn't think "from_" would be all that great. But `here` and `at` pair pretty well, so I'll do that. Otherwise I might want to do `here_` and `from_` just for consistency in the metarules.
2.   Yup, sounds good. That will make them both be the same code.
3.   `here(can_use(Magic_Bean))`: do you mean that `can_use(Magic_Bean)` is now just `is_child and (Magic_Bean or Magic_Bean_Pack)`? I'm fine with that, but it means the checks as written would be `is_adult and here(can_use(Magic_Bean)) ...`
4.   Ah, I remember something of that discussion right when I joined the twitch chat last week. This is not an easy thing to do with the parser, since it can't tell the difference between strings that are items and strings that are regions, locations, entrances, settings, etc, while in the middle of parsing the json files, without a judicious list of possibilities, or... hm... very specific contexts. I think we can do it, as long as a string strictly can be recognized as:
     1. a region, if the first arg to `at()`
     2. a setting string, if a comparator in a Compare
     3. an event item, otherwise
5.   Will fix that.
6.   Will fix that.

**Comment by Roman971** [comment]
2. Sorry I got confused while writing the last bit there for beans. I think it would have to be something like `is_adult and here(can_plant_beans)`. `can_plant_beans` being implemented as `is_child() and has_anyof('Magic Bean', 'Magic Bean Pack')`.

4. Can you not use single quote strings directly in the rule, by doing `'Goron Woods Warp Open'` instead of `Goron_Woods_Warp_Open`? I didn't look over the new parsing code in detail so I may be missing the problem here.

**Comment by Zannick** [comment]
2. that sounds like what I was aiming for.
3. Yes, you can, but the parser uses the python AST library, which means that we have to add a visit_Str method to translate `'Goron Woods Warp Open'` to `lambda state: state.has('Goron Woods Warp Open')` and I realized that we have region strings in places like `can_reach('Goron City')` and settings strings in places like `bridge == 'medallions'`, but since these are contextual, we don't really have to call `visit()` on them (ordinarily we do, we visit everything in the tree), and thus we won't mix them up or modify it the wrong way. Anyway, that was me detailing both the problem and a possible solution discovered as I was typing it up. So I'll work on that.

**Comment by Zannick** [comment]
This should all be done now.
Thanks again for your thorough comments, I really appreciate it.

**Comment by Roman971** [comment]
Looks good to me but I'm not really a fan of the `_planted_bean` allias, it feels a bit too much "magic" imo. 
Is there a reason to not just use `here(can_plant_beans)` like we discussed? It's barely longer and I think creating a state method is much clearer than hiding the implementation behind an allias changed at parsing time.

Also, why did you end up going for `from_` and `here_` instead of `at` and `here`?
I feel like `from` makes it sound like the player should be coming **from somewhere**, while  in reality what you're  writing is that the player should be able to fulfill some condition **at a certain location**.

**Comment by Zannick** [comment]
I felt `from_` made more sense as in "you can get this location here by doing this, or **from** this other region by doing this". In the cases like Volvagia, there was no condition at the other location, it was "have these items or reach this region", and I felt `at('Fire Temple Upper')` didn't sound better than `from_('Fire Temple Upper')`. That is,
> I feel like `from` makes it sound like the player should be coming **from somewhere**, while in reality what you're writing is that the player should be able to fulfill some condition **at a certain location**.

coming from somewhere is kind of what I was going for, more than "at another region, fulfill this condition". [Of course, we could require the rules be explicit: `at('Fire Temple Upper', True)` and that might make better sense?]

I recall thinking that I couldn't do `can_plant_bean` to mean `here(is_child and (...))` so I really just confused myself there. I didn't like `here(can_plant_beans)` quite as much and I don't really think much of the difference between defining a State method vs a parse-time alias. I'm aiming long-term to get a better understanding of the graph, but it can wait and I can make it a State method.

**Comment by Roman971** [comment]
I think enforcing a rule is fine, and makes sense. It becomes essentially the same as in-lining a location rule, which always requires at least `True` as well.

On the whole `from` vs `at` topic, it's a different problem and we should deal with it in a different PR, but I think most cases where `from` would make more sense should actually be removed, and the need for it should be avoided by moving the location to a proper region with multiple entrances. I feel like most cases like that are places where `can_reach` was abused instead of making a new region. This can be seen especially in the recent dungeon logic additions and in glitched logic, and it applies to most `can_reach(entrance)` calls as well.

I think the only real cases where a `can_reach` (or any equivalent) should be used is when we want to indicate that an action should be doable in a completely different place, but that action isn't relevant enough to be worth a new event location.

Obviously there are cases where making a separate region just for one location feels kinda bad, but I still think it would be cleaner in most situations to do just that. If a chest is located on a ledge accessible in multiple ways, then it would make sense to make that ledge a separate region with the accessibility rules in the appropriate exits. Although I could see exceptions being made for things like "GS Forest Temple Outdoor West", but those are rare at least.

**Pull request merged**
