### PR TITLE
Add ludicrous item pool

### PR DESCRIPTION
**Pull request by mracsys**
Ludicrous item pool makes every check in the game a major item. Each major item, excluding Gold Skulltula Tokens, Triforce Pieces, trade items, and Ruto's Letter over 4 copies, is duplicated until all junk items are replaced.

### CODE REVIEW

**Comment by dewiniaid** [comment]
Didn't look at the PR, but one comment:

Seeds starting at 20 hearts can actually be dangerous -- never finding pieces of heart or heart containers means you never get full healed, and 20 hearts does not last forever if you're only an average-skill player.

It might be better to leave the hearts alone and simply replace the rest.  Players can still manually choose to have 20 starting hearts to get your current behavior.

**Comment by Zannick** [comment]
The player would have to rely on fairies, Great Fairies, potions, milk, and heart drops? Does this wind up being a hardship, when you're guaranteed major items pretty quickly?

**Comment by mracsys** [comment]
20 starting hearts is removed. Rebased for the item pool refactor.

**Comment by fenhl** [comment]
Would it make sense to fill non-letter bottles with as many big Poes as required for the reward? It seems in the spirit of giving you _all_ the things and could lead to some interesting situations.

**Comment by fenhl** [comment]
It also seems strange to me that the number of Ruto's letters depends on the number of checks rather than always being fixed at 3 or 4 (except with open fountain).

**Comment by r0bd0g** [comment]
I recommend against increasing the number of Ruto's Letters as while that does make letter more accessible, it makes bottle a less accessible item. You would ALWAYS have to find two of them before you could use bottle in seeds where KZ is not yet accessible. So for example if you need to do Ice or something to get SoT to go back in time, the plentiful item pool starts working against you.

**Comment by Cuphat** [comment]
> I not sure you should be increasing the number of Ruto's Letters as while that does make letter more accessible, it makes bottle a less accessible item.

I think I agree with this: it should probably be more like Plentiful where there's two Letters and two normal bottles.

> Does this PR allow you to collect more than 4 bottles? If so, which bottle actually ends up being overwritten?

Nope.

**Comment by mracsys** [comment]
Ludicrous will now add a max of 2 letters.

**Comment by fenhl** [comment]
It's worth noting that ludicrous still removes all health upgrades. This should probably be adjusted to match the behavior in plentiful, especially since heart wincons are now merged.

**Comment by mracsys** [comment]
Ludicrous health upgrades now mirror plentiful, all heart containers except for the Treasure Chest Game piece and 3 spare pieces for the full container.

**Comment by cjohnson57** [comment]
Would you mind adding some ludicrous unit tests? Try to make different settings situations to stress-test it

**Comment by cjohnson57** [comment]
Also, does this work with key rings? It seems to just add extra normal keys as far as I can tell

**Comment by mracsys** [comment]
Will do on the unit tests.

Key rings is an oversight. That'll be easy to do, just adding to the list of duplication candidates.

**Comment by mracsys** [comment]
Unit tests added and key rings supported.

**Comment by cjohnson57** [comment]
The Ludicrous doesn't play well with starting items, I get a lot of Fill errors with 4 items remaining to be replaced or the not enough junk error

**Comment by cjohnson57** [comment]
The 4 items remaining seems to specifically be from starting with bottles, the latter just happens if I start with too many items.

**Review by cjohnson57 — APPROVED** [review]

**Pull request merged**
