### PR TITLE
Give rupee difference when finding wallet with MAX_RUPEES

### PR DESCRIPTION
**Pull request by rlbond86**
This PR modifies the behavior of the "start with max rupees" option. Previously, finding a new wallet with this option selected would completely fill the new wallet (e.g., finding the Adult Wallet would also provide 200 rupees). The new behavior is to give the difference in max rupees (e.g., finding the Adult Wallet provides 101 rupees = 200 - 99).

### CODE REVIEW

**Comment by LostThePirate** [comment]
That's... no longer Max Rupees. Unless you're updating the setting name and tooltip to reflect this working very differently, I strongly oppose this change. ...I oppose it anyway, because Max Rupees SHOULD give the MAX, that's working as intended and giving the players what is desired by that kind of setting, but I oppose misleading settings names more.

**Comment by rlbond86** [comment]
It's called START with max rupees, not GET max rupees every time you upgrade your wallet

**Comment by rlbond86** [comment]
Though the setting string should be updated

**Comment by Zannick** [comment]
I get that the purpose is to make the behavior more in line with the name, but it is kind of a convenience thing that wallets come with their full amount of money in them, and I don't see much of a benefit from changing that to "the 200-rupee wallet comes with 101 rupees". If you envision vanilla behavior as the Skulltula family handing out empty wallets, then the randomizer behavior with this option is finding a wallet on the ground with a bunch of money in it.

If you would like to update the name to match the behavior, something like "Wallets start with max rupees"?

**Comment by bliven-was-taken** [comment]
I find the current method way more enjoyable than I would this change. If something has to be changed, which I’m not sure I even agree with, I would much prefer the name of the setting to be changed over changing the implementation of the setting. It’s such a nice QoL feature as it is.

**Comment by Hamsda** [comment]
Yeah I agree with both lost and bliven, strongly opposed to this change. 
The setting is mostly used by the multi world community, because shops and scrubs are sort of standard for us, so we like the reduced tedium just getting our wallets filled back up.
This implementation seems like a weird middle ground that doesn't seem to fit well. Either have the wallets stay empty or fill them completely, imo.

**Pull request closed without merging**
