### PR TITLE
Fix Ganon towerless death warp

### PR DESCRIPTION
**Pull request by rattus128**
Fix the no-tower-collapse Ganon death warp by modifying the entrance
table rather than the loading zone. The entrance table catches both the
ganondorf kill and the death warp.

Dying to Ganon will drop you straight back in the fight where the
player can retry with 3 hearts, farm fairies and fight on, or savewarp
out to the tower start.

The actual implementation of the Ganon death warp is irregular compared
to other bosses. Most other bosses use a comparison logic on the last
entrance used to drive a substitution of the save-state entrance-index
before running the normal death warp code. Ganon doesn't do this,
instead there must be another hardcoded check out there somewhere
implementing the special case. But since there is no substitution we
can get away with completely change the entrance index of Ganon. So
fully overwrite the tower collapse to be Ganon.

Note that save warps are driven off scene indexes which is unchanged so
they are unaffected.

### CODE REVIEW

**Comment by r0bd0g** [comment]
Doesn't a death there normally refill health?

**Comment by Cuphat** [comment]
I believe tower collapse is what refills your health. Not getting destroyed by Ganondorf is actually a much bigger deal with collapse skip on because you don't get the collapse heal.

**Comment by r0bd0g** [comment]
Oh, do you not get a full heal after dorf with collapse skip on?

**Comment by mzxrules** [comment]
@r0bd0g I believe Ganondorf heals you after the battle, if I remember correctly from when I was working on my hard mode rom hack.

@rattus128 I'm not a fan of modifying the entrance table to fix this. Locating the proper write to the next entrance index isn't hard to do. Function 8009DA10 sets up spawn related variables when dying, and 8009DA42 (rom B139A2) is the address of the immediate of the OP that will set where you spawn when dying during the tower collapse sequence or ganon boss fight. Additionally, addresses 8009DA64 to 8009DA80 exclusive would be a good place to throw in a hook to solve the healing problem

**Comment by rattus128** [comment]
@mzxrules . Thanks for those details. The death warp fix looks pretty straightforward changing that immediate.

Following a discussion in discord with @Cuphat , it was suggested that the correct behavior for the healing problem might also include the heal after defeating Ganondorf to be consistent with vanilla behavior. This is currently not happening when tower skip is collapsed. So to fix the heal, the hook would need to be on entry to the Ganon fight scene rather than death handling if this is the desired behavior.

Any thoughts on what the desired behavior should be @TestRunnerSRL ?

**Comment by rattus128** [comment]
New version up. I have used the immediate pointed by mzx and I have hooked scene entry to fix both health fill events. I don't know the proper way to pass a config through to C code so I just check text for the tower-collapse change code. If theres a better way i'll V3 tommorow.

**Comment by r0bd0g** [comment]
Doesn't the health refill normally have a sound when you spawn?

**Comment by rattus128** [comment]
New version up.
Im hooking scene entry to fix both health fills. If there's any guidance on how I should pass the tower collapse config to C code for use in an if ill update accordingly.

**Comment by rattus128** [comment]
Magic refill might I think. It has an animation too that ramps up the magic level in save state frame by frame.

**Comment by r0bd0g** [comment]
In my head I hear the heart refill sound at the start of the collapse.

**Comment by mzxrules** [comment]
> if (*(uint16_t *)0x8009DA42ull == 0x0517 &&

The N64 uses 32 bit addressing, so casting the pointer address to an unsigned 64 bit int is overkill. A signed integer will work just fine here. That said, this check is unnecessary. You can just set your health at the hook I had suggested, since the fight normally restores your health to maximum.

The better variable to write to to restore your health is the s16 var Save Context + 0x1424. It's normally set to 0x140 whenever you trigger the cutscene/respawn on top of tower collapse. This increments health over a number of frames, playing the heart beeping sfx. Writing here instead of your main health has the additional benefit of not needing to check max health, since the code stops incrementing your health once you reach max.

**Comment by rattus128** [comment]
V3 up. No more magic pointer, using the 1424 fill but keeping the hook at scene entry to catch ganondorf kill refill along with the death warp refill.

**Comment by mzxrules** [comment]
looks a lot cleaner. seems good

**Comment by rattus128** [comment]
V4 has ASM generation committed, no other changes

**Comment by TestRunnerSRL** [comment]
This is merged and git is being dumb

**Comment by phixtyseven** [comment]
👍 for rebuilding the rom patch in a separate commit. Makes for a pretty 🌳 .

**Pull request closed without merging**
