### PR TITLE
Add flag to co-op context to make the world send its own items

### PR DESCRIPTION
**Pull request by fenhl**
This adds a flag to the co-op context (the versioned section of memory used as an interface for multiworld plugins) that controls whether the game will set an outgoing item override if the player finds an item for themself. The flag is disabled by default (which matches the behavior before this PR) and must be enabled by any multiworld plugin that wants to make use of this feature. The new field fits into an alignment gap so the size and layout of the co-op context are unchanged, but I've incremented the version to 3 so multiworld plugins can check whether the feature is supported.

This feature would allow mostly automating the item tracking for restreams of multiworld races as a feature of the multiworld server, therefore reducing the number of volunteers required for a restream, without requiring the players to install anything other than the multiworld plugin itself, and without exposing any new information to the players.

### CODE REVIEW

**Comment by fenhl** [comment]
Also added `Notes/coop-ctx.md` documenting the co-op context, similar to the auto-tracker context docs added in #1575.

**Comment by cjohnson57** [comment]
TR has concerns about this PR, saying it would require updating the co-op script, and that the new field should be at the end of the struct instead of the middle and then require more extensive testing

**Comment by fenhl** [comment]
Would the script update need anything other than a case for v3 to be treated the same as v2?

**Comment by cjohnson57** [comment]
Not sure tbh, just passing TR's words along, can ping him here or in discord to ask

**Comment by fenhl** [comment]
> TR has concerns about this PR, saying it would require updating the co-op script,

Addressed in TestRunnerSRL/bizhawk-co-op#61.

> and that the new field should be at the end of the struct instead of the middle

This seems to have been a misunderstanding. Adding the new field in the middle is fine since that part of the context was previously an alignment gap, so no existing fields are moved.

> and then require more extensive testing

I've merged this PR into [my fork of the randomizer](https://github.com/fenhl/OoT-Randomizer) and am currently working on adding explicit support for it to [Mido's House Multiworld](https://github.com/midoshouse/ootr-multiworld), i.e. having the clients enable the flag and having the server filter the new items and expose an API for item tracking.

**Comment by fenhl** [comment]
I did a quick test on my branch using MH MW and can confirm that sending and receiving items still works.

**Comment by fenhl** [comment]
It works as expected for item tracking purposes as well.

**Comment by fenhl** [comment]
We just completed a 14-person multiworld on my branch and there didn't seem to be any issues related to this PR.

**Review by cjohnson57 — APPROVED** [review]

**Pull request merged**
