### PR TITLE
Added new dual hints & updated hint distro for league settings for Season 5

### PR DESCRIPTION
**Pull request by Natheirean**
New dual hints are as follows:
1) HC/OGC Fairy
2) Pierre/Hammer chest in Fire Temple
3) Zora's Domain Child checks

### CODE REVIEW

**Comment by alkalineace** [comment]
I'm not sure about adding HC/OGC and Fire Temple hint for every seed. This impacts incredibly heavily RSL for example.

I think it's fine for league, but the changes as you made them will affect both RSL and Mixed Pools at least for the HC/OGC - making this one a no as it is. For Fire Temple, it's less severe but the existence of both MQ and skullsanity makes this worthy of having at the very least a conditional dual hint.

I think there's a way to only add it to the hint distribution file for league, but not in the main rando - but dual hints being different than sometimes makes this slightly more complicated.

**Comment by r0bd0g** [comment]
The hint for child domain checks does work. I don't think the other two dual hints are appropriate for main rando.

I don't think the two fairy checks are related enough. They're not really in the same area and the requirements differ so vastly. Steps would need to be taken to make sure that interior ER is off before that hint could be shown, as was done with the regular hints for those fairies. The purpose of dual hints was for when a hint for one check wasn't enough to let you skip much of anything. This hint is trying to do something else. The individual fairy hints are already pretty good hints by themselves.

Fire Temple would make more sense hinting hammer chest and highest goron -- since for highest goron at least sometimes you might have to fight the flaredancer to reach that also. The location and requirements of the scarecrow and hammer chests are still too disparate to hint together imo. Scarecrow check has the extra problem that there are two nearby skulls where a hint won't help that much if they're shuffled -- dual hints are supposed to be addressing this kind of scenario, but this hint can't do anything to help with that. I don't think disabling this dual hint if skulltulas are shuffled does anything to resolve that issue with it, since the nearby skulltula problem is not unique to the dual hint and affects the regular scarecrow hint equally.

If you insist on having those two dual hints, you should make them specific to league.

**Comment by Natheirean** [comment]
I don't exactly see how you can make an argument for this heavily impacted RSL. Its a chaos distribution, you might see what, 1 dual hint per seed, if that? Plus I don't think the fire temple one I added could ever be chosen if MQ is enabled, those are different checks with different location names. I don't know the hint distribution for mixed pools, so I can't comment on that one. The Fire temple one is also what has been used in SGL (pretty much a straight copy over), so we figured keeping the 2 locations it hinted consistent with what players have already seen makes the most sense.

HC/OGC don't have similar item requirements, but I feel like its basically the same "area". Its in the same place on the map basically and seemed to fit in that sense. I do agree with the interior shuffle one since you don't know which fairies are where in that so I can edit in a conditional for it to not populate with interior shuffle on

I also don't know how much I agree with the skulltula argument for fire temple. You still have Pierre hintable when skulls are shuffled, so that runs in to the same exact issue that already exists.

Our biggest concern for league is that the pool of dual hints that the team liked was very small, we only had 5 that we used for least season which had the usage very repetitive. If these are going to be rejected and there's a way to add these only for league, some direction for how to do that would be appreciated.

**Comment by fenhl** [comment]
There is currently no way to add custom dual hints via the hint distribution, but I think that's a feature that should be added regardless of whether this PR is accepted.

**Comment by Natheirean** [comment]
If tokensanity is a concern for the fire temple hint, I can also add a conditional on that, but we should probably also add a conditional for the pierre sometimes then if we go through with that.

**Comment by alkalineace** [comment]
ZD is a really good hint and i'm actually surprised nobody thought of that before.

With the addition of no interior entrance for HC/OGC, it feels much better ; i'm still not super convinced it fits what dual hints are created for, but it upsets much less entrance modes.

I have to agree with r0bd0g : the checks in Fire Temple are very separated and it would make more sense to hint both Highest Goron and Hammer chest. SGL is done on another branch so current Dev might not even have known it was implemented like that there.

I agree for removing Pierre sometimes hint if dungeon skulls are shuffled.

The dual hints pool is much more thin than the sometimes hint pool because it is that much more powerful.
You are hinting twice as many checks as sometimes hints.
I could look and try to think of a little more dual hints if the worry is the pool : 
- Right-side 2 checks in Ice cavern ? (would need dungeon skulls off)
- BOTW Fire keese + Like-Like ? (would need dungeon skulls off)
- Red and Blue poes in Forest temple ? (very slow checks so i feel this one would help)

**Comment by Natheirean** [comment]
The idea behind the Fire Temple hints is that those 2 checks are the furthest out of the way and are not peekable without committing all the way. Highest Goron is peekable on the way to hammer (assuming CSMC at least, which I understand not every setting uses but feels very common at least in the race scene.

**Comment by r0bd0g** [comment]
I don't think dual hints should be used like, "here's two random sometimes hints jammed together", which is what the fairy and fire temple hints are doing. They should be used in cases where the two checks make more sense hinted together. Switching Fire to highest Goron makes a lot more sense for what dual hints are for, since then you can leave Fire without having to fight the 2nd Flaredancer. (I'd never heard of that SGL hint. I wasn't given any chance to talk them out of it lol.)

Yeah I think just nobody thought of child domain before lol.

**Comment by Natheirean** [comment]
I don't see how having Fire Pierre/Hammer is any different than having spirit left/right hands. Both are different item requirements, are sometimes hints on their own. We also have Iron Boots Chest and Serenade locations as a dual as well, both being sometimes individually. Obviously I don't have the final say in this as these were just want items for next league season, but there is precedent in these types of hints that are already in the distribution. 

I get the argument of dual hints being more powerful than sometimes, but that is true for any dual hint. That level of balance should be held in the hint distribution amounts, not the hints themselves in my opinion.

**Comment by tnt175** [comment]
As the person who added the dual hints in the first place, my goal was to group up pairs of sometimes hints that, under some settings, turned rather useless due to another adjacent check having their own hint. (last room of Ice Cavern been the one example that annoyed me the most) True, the initial list of dual hints has its weak ones due to me trying to populate it. (The desert collosus GSs one been the weakest imo)

Reminder that we also have the hint upgrade system to handle single-dual overlap cases too.

While both of the spirit hands may have different requirements, the fact that one the more common methods of getting them was getting on adult side then longshot to child side made that dual hint a more obvious one to do

Truth to be told, I'm not sure if the Fire Pierre/Hammer is a good one, either. What truly makes the furthest reach of fire annoying is the combination of hammer and deepest goron. While perculiar, Fire Pierre is not that much of an issue. Under my logic for dual hints, the hint of the flame dancer is more inconvienced by deepest goron lacking an hint rather than Pierre. (altho even there, there is still the compass chest to take into account). In the end, the distance between the checks is the reason why I'm more iffy about that perticuliar hint (same reason why I was partial about the Skull Kid/Darunia hint in a early version of the PR, altho SGL went and made it on their side, so that particuliar hint might have more value that I though)

> There is currently no way to add custom dual hints via the hint distribution, but I think that's a feature that should be added regardless of whether this PR is accepted.

On the early stages of my PR back in the day, I had the dual/multi version of the disable hint type. None of the hints I did back then had it so the addition was judged unneccessary for now, but I could see it having some use for this case. I also had the idea of having a system for a palyer to add their own custom dual/multi hints, but my brain melted trying to come up with a way to do it and just moved on.

**Comment by Natheirean** [comment]
Gonna leave my final notes here on this until we get confirmation/denial on whether these would get merged in or not, but at least why we as a league org chose these.

Domain: This one didn't seem to have as much contention as the other 2, so I'll leave it brief. 2 Locations near each other that are often skipped, especially if Jabu is a stone.

Fire Temple: Reason why we don't like highest Goron/hammer is because of compass chest existing. To "full clear", you'd have to still go to compass chest, and at that point highest Goron is 2 room changes away that takes a matter of seconds. Meanwhile scarecrow chest actually takes a decent amount of time commitment, requires an extra item (hookshot & scarecrow song or longshot with trick), and is the only check on the way up that is not peekable with CAMC. Also makes it safer to try fire temple w/o hookshot if you have hammer early and bolero/hovers. It also helps that this is an SGL hint so there will be some community familiarity with it already. I do agree with concerns over the skulls and think its fair to remove this dual from the pool in case of skullsanity, as well as adding that conditional to the sometimes hint for Pierre sometimes hint,

HC/OGC: I kind of equate this to something similar of hinting child/adult fishing(again, SGL hint not in the main dev atm). "Same" item location that is out of the way and is a decent time commitment to check. And there is already previous precedent having different item requirements for checks in the hint like Royal Family Tombs,  Water River Checks, Several of the item/skulltula duals

Either way, once we get a list of which(if any) are good to merge, league will be set to finalize our settings

**Comment by r0bd0g** [comment]
If you don't have the means to climb up from compass chest to highest goron directly (no sot or hovers), highest goron+hammer go pretty well together because checking them can be both locked by defeating the flare dancer (especially if chest textures aren't on so you can't just peak and see if it's important). The compass chest is not really that nearby when the flaredance might be in the way. The hint also would have the potential to get better under vanilla maps/compasses, where maybe that entire arm of the dungeon could be eliminated. So I think the hint works pretty well in most settings already, and has potential to be better if certain other settings are on. It would play a lot better with randomizer as a whole than the pierre+hammer hint would.

A fishing dual hint was PR'd originally and I disagreed with it for the same reasons I disagree with the combo castle fairy hint. (I'm not sure what became of that hint? I think we changed it to adult fishing + above the lab PoH? But I'm not sure what the current state of it is.)

Do you think sometimes hints in general are too weak? It doesn't feel like you want dual hints, but rather just stronger sometimes hints. (Maybe you really could just add a new hint type that hints two actually random sometimes on the same stone, I dunno.)

**Comment by tnt175** [comment]
Its not that sometimes hints are weak. Some sometimes hints are very useful at resolving a location that can be very isolated from others (GTG Toilet Room, for example, that can be blocked off by a stray Irons compared to the rest of GTG).

The problem is that some sometimes hints fall down in value under some settings. (Again, last room of Ice Cavern. Getting the hint for the item check isnt as useful because it totally paired with the song check, which is made even worse with songsanity on)

Imo, this is about getting info on the location (if its dead or not), not the items themselves (odds are that the items are not required, anyways). The sometimes hint for Wasteland chest without skullsanity is as powerful as the dual hint for Wasteland Chest+GS when skullsanity is on.

(also, yeah, fishing dual hint was a thing at first in the PR, but was in fact replaced by the adult been ride hint, altho SGL also added that particuliar one too)

**Comment by cjohnson57** [comment]
I have to agree with the other comments, ZD is good, HC/OGC fairy is fine with the interior change, but the FiT ones feel weird

**Comment by r0bd0g** [comment]
I don't think castle fairies are fine as a dual hint. Both of those locations have sometimes hints that are perfectly good hints on their own. There's no advantage to hinting them together over hinting any other two arbitrary sometimes hints together.

(It's probably not worth adding this point, but I don't think the relationship between the two locations allows for some kind of improved hint wording over hinting two arbitrary locations, because I think I'd prefer dual hints to just hint the two locations in sequence anyway, rather than in parallel like what's currently done -- I think dual hints would be easier to comprehend that way.)

If you insist on castle fairies, I guess nothing stops both fishings dual hint from coming back. Dual hint Meadow Sheik and Saria after that. (Both rolling Gorons too far...)

**Comment by Natheirean** [comment]
I will note that any distribution for static formats can always exclude individual hints based on their hint distribution, if they even use duals at all. The ONLY hint distributions that are in main dev right now that even use dual hints (minus dual always hints, which not sure how often those even get pulled), are league (average of 2.0 per seed) and chaos (average of 1.0-2.5 per seed depending on always hints). This is partially why I'm a bit confused on why there's so much hesitation towards duals in the pool when almost no formats use them anyways.

**Comment by cjohnson57** [comment]
As far as I can tell people love dual hints, many custom hint distros probably use them

**Comment by fenhl** [comment]
The mw3 and mw3_woth distros also use Dual hints, via the upgrade system.

**Comment by fenhl** [comment]
Adding a feature to allow defining custom dual hints via a hint distribution doesn't seem doable short term. Maybe we could add these new dual hint definitions to the code so the league hint distro can access them, but have them disabled by default?

**Comment by cjohnson57** [comment]
> I have to agree with the other comments, ZD is good, HC/OGC fairy is fine with the interior change, but the FiT ones feel weird

**Comment by cjohnson57** [comment]
My bad, accidentally clicked a button lol

**Comment by Cuphat** [comment]
What is happening here?

**Comment by Natheirean** [comment]
I had to close it to merge the changes from dev, it would not auto-sync

**Comment by Natheirean** [comment]
I believe it should all be correct now. Fire Temple Dual was removed, Domain and Castle Duals are still there with the interior conditional on the castle dual.

**Pull request merged**
