### PR TITLE
Plando: Refactor pattern dict items

### PR DESCRIPTION
**Pull request by flagrama**
~~Depends on: #990~~ Dependency has been merged
~~[Cleaner diff based on dependency](https://github.com/flagrama/OoT-Randomizer/compare/plando-tests...flagrama:refactor-pattern_dict_items?expand=1)~~

~~Hopefully this makes it more readable than the mess that was there before.~~

### CODE REVIEW

**Comment by flagrama** [comment]
The following is kind of a lot of stuff done, including accidentally making it possible for Vanilla and MQ dungeon locations to be defined in the same distribution file: https://github.com/flagrama/OoT-Randomizer/compare/refactor-pattern_dict_items...flagrama:refactor-2?expand=1

I'm not ready to push it onto this PR yet. I'd like to maybe try to figure out more test cases that are relevant and ensure these changes don't break anything honestly. It might also have behaviour that the dev team doesn't desire for plandomizer.

Aside from trying to put my code changes into a more distinct location from the normal plandomizer in an attempt to make both easier to read, what it does is try to only check the relevant locations in the plando `fill` and `fill_bosses`. Initially doing this caused all location keys to "work" because invalid ones were skipped, which isn't great because a user _probably_ wants to know if one of their intended settings is getting skipped.

So then I made sure the location existed by using LocationFactory. Since LocationFactory checks if a location exists _at all_ this makes it possible to have locations that aren't present in the world currently still defined. The best example is having Vanilla and MQ locations for a dungeon included in a distribution file, which makes plandomizer actually compatible with the MQ dungeons option.

The only major issue I see with this is stuff like maybe Gold Skulltula locations will get skipped if defined but not using the right settings, or stuff like that. I might want to try to ensure a location exists and is in the pool, however with "random" settings options and the "randomize all settings" option, this might work better for how some people want to use plandomizer. Alternatively I could only allow this to be done if a relevant setting is randomized.

**Comment by flagrama** [comment]
Added a more proper MQ/Vanilla dungeon check to the above diff.

**Comment by Zannick** [comment]
If this is ready for review, can you rebase and force push to make a more accurate diff + list of commits?

**Comment by flagrama** [comment]
I'll probably redo what changes I want and force push them to this branch at some point. I'll mark it ready for review once I do, though I don't have any specific plans for doing so currently.

**Comment by flagrama** [comment]
> Restore simpler original implementations of pattern_dict_items and pull_random_element
>
> Add get_item to and move nearly all of the special case item handling from fill to it
>
> Allow fill to exceed item pool values but do not duplicate items that cause issues if no more unused items exist in the supplied record

I believe these are all of the changes I wanted to make. All tests seem to pass fine.

**Pull request merged**
