### PR TITLE
Twk/minor

### PR DESCRIPTION
**Pull request by phixtyseven**

### CODE REVIEW

**Comment by TestRunnerSRL** [comment]
kinda wary about this cause of two reasons. First, the ASM folder doesn't need to exist to run the randomizer (and it doesn't on the web patcher currently), and this would throw an error if it doesn't. Second, kinda worried about moving the file which might break the web patcher for all I know.

**Comment by rattus128** [comment]
@TestRunnerSRL Should the first commit fixing the python3 shebangs and source be cherry-picked? I have the same change in my tree to get the ASM scripts/build.py to run on Linux. It is possible to fix Linux dev by changing the default py at the environment level, but the shebang fix obsoletes this and avoids the confusing error message. I can rebase and make it a fresh PR if that helps.

**Comment by phixtyseven** [comment]
Fair points. I'll just remove it for now.

**Comment by TestRunnerSRL** [comment]
Rebased and merged

**Pull request closed without merging**
