### PR TITLE
Wasteland at night requires song of storms or sword

### PR DESCRIPTION
**Pull request by puddydoo**
The poles in haunted wasteland are very difficult to see at night, but the flashes from song of storms make them visible. So going between the monument and the bombchu salesman area should require daytime, song of storms, or a trick. Only in ER could the player ever be required to cross wasteland at night, but I think it presents a significant accessibility issue in those cases.

### CODE REVIEW

**Comment by LostThePirate** [comment]
I've never once used SoS to help see, I didn't even know that was a thing. This seems pretty unintuitive to add to default logic, I don't imagine anyone will receive a WotH SoS and think that it's for crossing the first part of the Wasteland. Simply swinging your sword clears the dust briefly, so until Master Sword Shuffle becomes a thing, I guess I fail to see what this would add beyond further confusion from hints.
I appreciate the effort to make the Wasteland more accessible to beginners, but I'm not sure this is the right approach.

**Comment by puddydoo** [comment]
With the addition of sword as a requirement, it seems that this would not change generation at all until sword shuffle is added because anyone who crosses quicksand or does reverse wasteland as child would also enable this trick.

**Comment by r0bd0g** [comment]
Fun fact: If you die, the sandstorm goes away until the next reload.

**Comment by r0bd0g** [comment]
There is technically the possibility that you would need a fairy for something immediately across wasteland, and the death strat would not be possible to keep the fairy through... Luckily, the wasteland structure has a fairy!

**Pull request closed without merging**
