### PR TITLE
Add setting to show seed info

### LINKED ISSUE #1334: [Feature Request] Multiworld ID Identification
When generating a multiworld ROM, instead of "File 1", you instead have "File {ID}", so that you can be 110% confident that you're on the correct ROM.

### PR DESCRIPTION
**Pull request by fenhl**
This is a modified version of #1182 that adds the feature as a regular setting rather than a cosmetic option, addressing the concerns raised in <https://github.com/TestRunnerSRL/OoT-Randomizer/pull/1182#discussion_r572269622> and <https://github.com/TestRunnerSRL/OoT-Randomizer/pull/1182#issuecomment-775428074>.

~~This does not address [the readability issue on N64](https://github.com/TestRunnerSRL/OoT-Randomizer/pull/1182#pullrequestreview-585794274) since I don't know how to fix that.~~ Mostly fixed by increasing the font size.

Closes #1334.

### CODE REVIEW

**Comment by fenhl** [comment]
I increased the font size and while it's not ideal (there's some weirdness going on where the text is clearly smaller than the dungeon info on the pause screen despite being called with the same size parameter), it seems to be readable on N64 now: Photo of the new file select message

I had to decrease the maximum length of the message from 48 characters to 42 to avoid getting part of the message potentially lost to overscan.

**Comment by cjohnson57** [comment]
I clicked on this and was surprised to see it was updated recently- Is there any particular reason to not merge this as it is now?

**Comment by ETR-BTF** [comment]
Does this also show the MW world ID number?

**Comment by fenhl** [comment]
Yes, the world number is displayed above the hash, as seen at <https://github.com/TestRunnerSRL/OoT-Randomizer/pull/1182#issue-748351729>. This might be lost to overscan on some screens though, maybe placing it to the right of the hash would be better.

**Comment by fenhl** [comment]
Alright, should be good to go now.

**Comment by cjohnson57** [comment]
Has this latest version been tested on console as well?

**Comment by fenhl** [comment]
The photo posted above is of a console display. Since then only the positioning of the world number text has been changed.

**Review by cjohnson57 — APPROVED** [review]
Seems good to me, love the custom message functionality.

**Pull request merged**
