### PR TITLE
Change Hylian and Deku shield items to be Major

### PR DESCRIPTION
**Pull request by dotzo**
Updated the ItemList.py to include HylianShield and DekuShield as Major items.

### CODE REVIEW

**Comment by r0bd0g** [comment]
This will not play well with 1 major item per dungeon.
I'm not sure people on chest contents will want this though? Especially if they're not playing with shuffled shops.

**Comment by fenhl** [comment]
What's the motivation for this PR? I don't think it makes much sense to have capacities and BGS as minor items but shields as major.

**Comment by dotzo** [comment]
Shield is vital to a lot of glitch tech and having it be in small/untextured chests is an issue sometimes.


Also BGS is a major item.

**Comment by r0bd0g** [comment]
BGS is major but it's allowed to be foolish. I'm not sure if you have to make an exception for shields as well to allow them to be foolish. You probably do?

And yeah I consider shields to be a refill item? It's also weird then that not in logic bombchus would minor items still.

**Comment by fenhl** [comment]
Here's the function that determines whether an item is major: https://github.com/TestRunnerSRL/OoT-Randomizer/blob/ef810492f8f9b8a22e4f0fbda7d8383ee6b90f08/Item.py#L132-L159

Since it's not a token and it's not an advancement item (i.e. an item where the “progressive” column in the item table is `True`), BGS is not a major item.

**Comment by r0bd0g** [comment]
Then how does this PR make those shields major?

**Comment by fenhl** [comment]
It changes the “progressive” entries of the shields in the item table to `True`.

**Comment by ETR-BTF** [comment]
Seems a bit weird to me that shields would be classified as major but chus wouldn't. Why don't you just continue to open small chests until you've found your shields, just like you do with that first chu pack?

**Comment by fenhl** [comment]
It should be noted that this PR doesn't modify the chest appearances for shields.

**Comment by r0bd0g** [comment]
> It changes the “progressive” entries of the shields in the item table to `True`.

But that same field is true for both Biggoron Sword and Giant's Knife?

**Comment by ETR-BTF** [comment]
New PR #1725

**Pull request closed without merging**
