### PR TITLE
Add inventory/equipment/status icons to file menu

### PR DESCRIPTION
**Pull request by rlbond86**
This PR adds icons when loading a save file that show the obtained items in that save, similar to the display available in ALttPR. An example is shown [here](https://imgur.com/a/JFHqcSm). The icons show Link's inventory items, equipment, songs, status items, and counts of rupees, skulltula tokens, and Triforce pieces (if applicable). If Triforce hunt is not used, the icon instead shows whether Link has obtained the key to Ganon's Tower.

The Master Sword icon is enabled if the Door of Time is open, regardless of whether Link is currently carrying it.

### CODE REVIEW

**Comment by rlbond86** [comment]
Patch file for testing

[OoT_F7A0E_pr_985.zip](https://github.com/TestRunnerSRL/OoT-Randomizer/files/4176280/OoT_F7A0E_pr_985.zip)

**Comment by Roman971** [comment]
Since ER is a thing, door of time being opened doesn't necessarily imply being able to travel through time.

**Comment by aofengen** [comment]
Does it work for all three files? Or just file 1?

**Comment by rlbond86** [comment]
Works for all three

**Comment by rlbond86** [comment]
@Roman971 updated description to reflect this.

**Comment by Roman971** [comment]
I don't know about showing the Master Sword only if the Door of Time is open. What if you start as adult with Door of Time closed?

In my opinion the Master Sword icon should just behave like any other item and be based on whether you have it or not.

**Comment by rlbond86** [comment]
If you start as an adult with closed door of time, the Master Sword is shown dim. It is not useful to have the icon reflect your current equipment state of the Master Sword. Similarly, the "Ruto's Letter" icon remains lit once you have used the letter, and the Child Trade icon has the Mask of Truth even if you swap to another mask temporarily.

The point of the icons is to reflect the progress of your save file, not to reflect what inventory you currently have.

**Comment by Zannick** [comment]
If you want to show the progress, why not have icons like Door of Time, King Zora, and the Kakariko Well for representing opening the Door, moving King Zora, and draining the well, respectively? I would rather add icons than use inventory item icons to mean variously "this is in my inventory now" (the rupee count is suggesting this) and "I've obtained it at some point" (Ruto's letter) and "I've opened the door of time" (master sword). This will be confusing.

Shields can be lost. Do they turn off? If we're concerned with showing progress, should it turn off only if the player hasn't yet found a shop selling the shield?

The example is very cluttered, and I'm not really liking the contrast with the parts of the file select that show the heart count and dungeon rewards (it's very empty... but I know that with all the medallions and stones and hearts it's pretty full). Do you have a shot of ALttPR's as a reference? Maybe we should adjust that too so it's one consistent "this is what you have" UI.

**Comment by Roman971** [comment]
I believe Triforce Hunt is already handled.

As for the whole progress stuff, I still think this display should simply show things based on your current inventory, with the exception of ruto's letter perhaps. Either way I agree with getting rid of the confusion between items and quest status.

**Comment by rlbond86** [comment]
I don't really have the talent to make my own icons. If someone wants to provide them they could be added. Shields disappear when lost, mostly because it's not trivial to figure out if the player has access to a shop with a shield, so I suppose doing something similar with the Master Sword is consistent. A door of time icon would help perhaps. What about the mask icon? Currently it shows the how far in the trade sequence the player is, even if you go back and grab an earlier mask. 

Triforce hunt is supported.

There is no available space inside the file area with the medallions. The area is certainly cluttered but what other choice is there? There are a lot of items and little screen space. 

ALttPR's opening menu is visible here: https://youtu.be/9C3f_yH3rkM

**Comment by rlbond86** [comment]
I've updated the code to only show the master sword if the player has it (i.e., if Link is an adult). Additional icons could be added in a later PR.

**Pull request closed without merging**
