### PR TITLE
More one-way entrances

### PR DESCRIPTION
**Pull request by puddydoo**
Owl drops, spawns, and warp songs can lead to the reverse side of entrance types that were excluded before, because these sides lead to the overworld.

### CODE REVIEW

**Comment by Roman971** [comment]
A lot of these entrances aren't included in the one-way pools by design, which I'll try to explain here so we're all on the same page.

Dungeon exits have a lot of implications we don't really want. One thing is they enable dungeon-ER style situations, by, for example, allowing child to get inside Forest Temple, Fire Temple and Ice Cavern. Another is they can circumvent some requirements to reach dungeons, by allowing Deku Tree to be entered without sword+shield in Closed Deku, or allowing DC to be entered by simply walking back as child if you spawn at its exit without any speed/momentum.
Also in general I'd say adding dungeon exits doesn't really bring much positive, since they are in areas where there are a lot of other entrances to pick from (warp pads, kokiri forest, kakariko village...).

Grave exits would be kinda weird to include right now since their entrance being excluded is purely technical, but they don't do much anyway since graveyard doesn't really need more possible entrances, so I'm not in favor of including them.

Interior exits shouldn't be included in the owl drop pool either imo, because they don't add much to the table and make things a bit weird, but I can't think of any real issues with them right now.

**Comment by fenhl** [comment]
Why does this remove graves from valid warp song destinations?

**Comment by puddydoo** [comment]
> Why does this remove graves from valid warp song destinations?

Added them back now that it prioritizes the Nocturne entrance and this would prevent the other grave entrances (on the graveyard side) from being selected anyway.

**Comment by Zannick** [comment]
I think I agree with Roman that grave exits and interior exits aren't worth it. Dungeon exits don't sound like a good idea either, but it's a little mitigated if we only add dungeon exits when dungeon shuffle is on. However that could still require/allow using an owl to get into a blocked DC as Roman said. I think that specific entrance would be too esoteric a possibility to require, and yet would come up so rarely that it wouldn't be worth being a trick. Mixed feelings in total.

**Comment by Zannick** [comment]
I am going to err on the side of not accepting this, since I'm not convinced it's an improvement.

**Pull request closed without merging**
