### PR TITLE
Lake Hylia lake control gossip stone obfuscation

### PR DESCRIPTION
**Pull request by dotzo**
Places spawning of the gossip stone behind either ER or the child can control setting.

### CODE REVIEW

**Comment by Cuphat** [comment]
You'd need to actually change logic too if you want this to be a thing.

**Comment by r0bd0g** [comment]
I'm confused where lake refill is even defined and what the logic on it is?

A big objection people had with gold scale water was the potential to lock yourself out of the dungeon if you didn't have iron boots. This change would put that back into default logic without a trick option.

**Comment by dotzo** [comment]
Currently it works the same as the old trick did, only the morpha heart is in logic with gold scale and everything else requires irons. The only difference is the ability to re-enter the temple but as you can do nothing logically there's no point outside of ER.  With this change, turning on "child can lower water" is basically the stand-in for the gold scale trick, as it will replace the gossip stone without shuffling the entrances.
I personally have no plans of reworking the logic to re-include the trick.  I'll PR any changes if you want to work on it.

**Comment by r0bd0g** [comment]
What? The morpha heart is not supposed to be in logic. You can leave the heart behind and miss it forever.

**Comment by Roman971** [comment]
In keysanity there is more than just the Morpha Heart in logic with gold scale.

**Comment by dotzo** [comment]
would it be cleaner to take the entire dungeon out of logic without irons? effectively removing the gold scale trick altogether if it's not an ER related thing?

**Comment by Cuphat** [comment]
Water Temple entrance needs to hard require Iron Boots, unless dungeon ER is disabled, at which point still everything in Water Temple has to hard require Iron Boots except for Morpha (blue warp, not heart).

Basically the two options that aren't convoluted as hell is the gossip stone and scales in logic, or scales not in logic.

**Comment by rattus128** [comment]
This is exactly the logic complexity that TR rejected in the initial ER work, and highlights the fact that the change is not actually ER specific.

Rando has significant precedent for altering vanilla behavior for the sake of removing non-repeatable access. The most obvious example is moving sheik from the pedestal in ToT which in its vanilla behavior makes the entire child world a non repeatable access. Fundamentally there is not a lot of difference on this one, just in scale of impact i.e. its fixing just the water temple, and not the entire child world.

The change proposed ignores keysanity, and the discussions largely ignores it too. This is a regression to keysanity by putting easy trickless checks back out of logic again. There are a large number of settings combinations, involving any form keysanity, keysy or ER than invalidate the "cant do anything without irons anyway" assumption. That and the torches longshot trick can now be properly defined.

You should at least add keysanity and keysy to all your settings that opt-in the stone, but at that stage I really really gotta question why not just leave it there.

**Comment by dotzo** [comment]
Look at the code, it's compatable with ER and keysanity now. The logic will function just as though the stone was never placed there, still requiring iron boots to enter water temple and for every check inside by extension. If the stone is there, you have your gold scale entry.

This change would never have happened if ER were not implemented and as such one could argue, as I am, that that is the sole reason for its existance and as such should not exist outside of settings where that is relevant. 

Arguing that any chage is okay simply because other things have changed leads to a clear slippery slope whereby the game becomes unrecognizable as OoT.  Keeping the integrity of the base game is paramount should we want to maintain that this is an ITEM randomizer build for Ocarina of Time and not a completely new game built on the code written by others prior to 1998.

Removing Shiek was necessary as one could easily go out of logic to adult and softlock themselves by being unable to complete forest temple.  That is not the case here as there is no gameplay shift which is irreversible and the logic will dictate the Iron Boots are in a check prior to Water Temple. 

Other access changes such as the boulders in front of Fire and the wall in front of BotW are also contingent on ER being enabled, so why should this be any different?

**Comment by dotzo** [comment]
And to TR: I implore you to not let ER take over randomizer.  The *significant* proportion of changes to 5.0 are directly related to this setting which a not insignificant portion of the community will likely ever play.  It's my judgement that anything related to this mode of gameplay should be relegated to only be active when that mode is active, and by and large this is the case. 

This gossip stone is a glaring example of when that isn't the case, so it is simply my goal to rectify that inconsistency.  Maintaining the vanilla gameplay of OoT as much as we possibly can is, in my opinion, imperative to keeping legitimacy of the product.  

The changes ER employs violates this paradigm in many locations and I would hate to see that menality bleed into the base game.

**Comment by rattus128** [comment]
> Look at the code, it's compatable with ER and keysanity now. The logic will function just as though the stone was never placed there, still requiring iron boots to enter water temple and for every check inside by extension. If the stone is there, you have your gold scale entry.
> 
```
      (((Progressive_Scale, 2) and (shuffle_dungeon_entrances or child_lake_hylia_control or Lake_refill))  or can_use(Iron_Boots)) and
```
The new logic does not let you into water in keysanity, which is what I am saying is the problem. Yes this is 4.0 behaviour, but dev head currently allows you into water without Irons in keysanity/keysy, which is a good thing and is directly reverted by this work.

But I'm coming around to the idea of making this conditional on the full list of affected setting which might be a workable compromise. It may actually be as simple as doing this in patches/ASM:
```
if (small_keysy || small_keysanity || bk_keysy || bk_keysy || ER || logic_water_torches) {
    spawn_stone();
}
```

This will add the stone under any condition where it is logically useful. You don't need any diff to the logic if you do this.

I also suggest that we kill child_lake_control completely and leave the water up for child. Ive played enough dungeon ER seeds to not notice it as impactful and it add options complexity to the options for little value.

> This change would never have happened if ER were not implemented and as such one could argue, as I am, that that is the sole reason for its existance and as such should not exist outside of settings where that is relevant.
> 

Its quite common in software for a new feature to trigger a broader refactor. Waters non-repeatable was well known as an issue and ER has to implement a logic workaround for this as a pre-existing issue. 

> Arguing that any chage is okay simply because other things have changed leads to a clear slippery slope whereby the game becomes unrecognizable as OoT.

I'm not arguing any change is OK. I'm arguing that killing non-repeatable access with minimally intrusive changes is OK. Non-repeatables are difficult for the fill algo and logic which is the randos primary function.

> Keeping the integrity of the base game is paramount should we want to maintain that this is an ITEM randomizer build for Ocarina of Time and not a completely new game built on the code written by others prior to 1998.
> 
> Removing Shiek was necessary as one could easily go out of logic to adult and softlock themselves by being unable to complete forest temple. That is not the case here as there is no gameplay shift which is irreversible and the logic will dictate the Iron Boots are in a check prior to Water Temple.
> 

We could easily do the logical equivalent on Sheik by gating all of is_child on Forest Medallion. Its super jank for child start, but it actually would be kinda ok in the new adult start. I posted in #suggestions.

> Other access changes such as the boulders in front of Fire and the wall in front of BotW are also contingent on ER being enabled, so why should this be any different?

**Comment by dotzo** [comment]
I'll just come right out and say that should the stone appear in any setting which isn't directly related to non-vanilla dungeon access, i.e. ER or the specific child control setting, I'll no longer be affiliated with this project.  This is a HARD line for me.  Adding actors to the game where they shouldn't be, especially because it's a gossip stone which was clearly only used because the overlay was already loaded and you couldn't figure out how to do a switch, is NOT okay in a project of this scale.  

This strays WAY too far into significant romhack territory, compromises the integrity of the base game, and in my opinion is disrespectful to the original that we all so love.

**Pull request closed without merging**
