### PR TITLE
Temporarily make scarecrow less buggy

### PR DESCRIPTION
**Pull request by phixtyseven**
This slightly breaks logic if the option to start with Scarecrow's Song
is enabled, since the ocarina is no longer required to utilize Pierre.

I would have liked to mess with the assembly directly, perhaps changing
the check to Link's idle state, rather than his ocarina state.
Unfortunately I haven't figured out how to get the build script to work
with the compile-c option.

In the meantime, this change will prevent Pierre from being so
apparently buggy to players.

Relevant to TestRunnerSRL/OoT-Randomizer#295.
This partially reverts commit f96a31f80bf94c66d996f3d5a2170ec51480a63e.

### CODE REVIEW

**Comment by mzxrules** [comment]
why remove the code from hacks.asm?

**Comment by TestRunnerSRL** [comment]
tbh, I kinda rather just get a proper fix. We're just replacing one unreliable behavior with undesirable behavior. I'm not sure what needs to be done to make the the current version work however....

**Comment by phixtyseven** [comment]
@mzxrules
I originally attempted to change the line with a simple org injection, but after running the build script and running the randomizer, I was getting some sort of error involving the dma table. I could only get it to do what I wanted by reverting the other commit and writing the change in Patches. A better developer would start troubleshooting and figure it out, but I had no idea what the problem was and I've been feeling pretty lethargic in general.

**Comment by phixtyseven** [comment]
@TestRunnerSRL
Yeah, I had a feeling. My thinking was just that, after seeing some discussion in the discord and among players, that it would be better to get rid of the obvious bug so players wouldn't waste their time thinking about it. But I would kinda agree. As it is, logic is correct, and I don't think the behavior is too unreliable as long as you're familiar with it.

I'd be happy to play with it more myself, I just configured the tools improperly somehow.

**Pull request closed without merging**
