### PR TITLE
[WIP] Minimal update system

### PR DESCRIPTION
**Pull request by KevinPal**
This was something I've sort of had for a while, but I just cleaned it up and got it working after #849. Works by using the github api to compare the current version to the latest, and downloads only the necessary files ~~changes~~ (I just download the whole file now, easier than downloading and patching parts of the file. Can be done though). 

Main benefit would be for non git users who don't want to whack the entire folder and redownload the GUI for non GUI changes. This would not pair well with people actually using git, and at the moment won't work well with forks. 

This currently works by running python Update.py, but some cleanup/error handling + GUI work is needed, but I wanted to see peoples thoughts before working more on it.

### CODE REVIEW

**Comment by Nicholas-Steel** [comment]
Neat, would be really useful for people that setup shortcuts to the generator and don't like having to manually download a zip, navigate to the install location and replacing the contents of a folder any time an update releases..

**Comment by KevinPal** [comment]
Really simple, they would just need to change the URL to point at their repo/branch instead of TRs. I was also thinking that they could put a branch and fork in the version file after the FLUM thing, so that the branch and fork would also show on the gui

**Comment by TestRunnerSRL** [comment]
So a few things would need to be done to make something like this usable:
1) The updater needs to be versioned as well an self-updatable
2) This update needs to be ran while the GUI is not running. There's a good chance you need to recompile. But still needs to be initiated from the GUI
3) I think this whole diffing thing is neat, but if you're really far behind, you really should just download the whole thing.
4) We /might/ need to move the updater into a different repo to make this work properly, but it might be safe to stick it in a folder.

So the main approach I would see is that the main code has a check where it tries to update the updater if needed. Then it spawns an updater proc that will wait until the main proc ends, and then the main proc terminates. Once the update process is done, the updater will restart the main proc and then terminate.

**Comment by KevinPal** [comment]
By the main code/proc, do you mean the GUI? Or would the GUI call a process that tried to update the updater, and then call the updater. Either way, how would we update that process? One possible way would be to force a hard manual update if the code that updates the updater needs to be updated.

For 3, it can only look back to a maximum of 100 versions, minus the number of big releases. So for example this could update from 1.0, 2.0, 3.0, and 4.0 to latest (tested from 2.0), or from latest - 96 versions to latest. Would we want to force hard manually updates when going to a major revision? I'm also not sure what's a good number of versions to allow to update form.

For 1/4 , this could be stuck in a folder along with a version file for the updater. Maybe have an extra config file in there too of versions to force hard updates from?

**Comment by Zannick** [comment]
Is there still interest in this?

**Comment by ianfife** [comment]
> Is there still interest in this?

Yes

**Comment by cjohnson57** [comment]
This has been sitting abandoned for quite some time, but an update system would be really cool to have, so feel free to reopen if you work on it again!

**Pull request closed without merging**
