### PR TITLE
Add convenience settings for faster start

### PR DESCRIPTION
**Pull request by rlbond86**
This branch adds the following settings:

1. "Start with max rupees" - The player begins the game with 99 rupees.
2. "Start with Deku equipment" - The player begins the game with 10 Deku sticks and 20 Deku nuts (which normally can be bought or obtained by killing enemies in the starting area). Additionally, if playing without shopsanity, the player begins with a Deku shield equipped (which can also be bought).
3. "Start with fast travel" - The player begins the game with the Prelude of Light and Serenade of Water songs learned (but no ocarina) and the Farore's Wind spell (but no magic meter). These three items increase Link's mobility around the map, but don't actually unlock any new items or areas.

The "start with fast travel" option required some minor rework of the ItemPool logic (to remove the three mentioned items and replace them with junk items) and of the Fill logic (to place minor items in the songlist to compensate for its smaller size if not shuffling songs). Additionally, the song cutscenes are disabled, since two song locations will now provide an item instead of a song.

### CODE REVIEW

**Comment by r0bd0g** [comment]
Farore's Wind does potentially unlock one location. If you're going to start with progression items that actually do things, then you must at some point collect the item so that it can be used in the logic.

**Comment by rlbond86** [comment]
What location can Farore's Wind unlock? You can only use it to access rooms you've been to before.

I tried to figure out how to get song cutscenes to work properly for some spots but not others, but there are a lot of song-related patches and some of them seem to apply to all song locations at once. Of course, feel free to take a stab at it.

**Comment by flagrama** [comment]
The one Gold Skulltula in Water Temple's central pillar is the only one I can think of: https://github.com/TestRunnerSRL/OoT-Randomizer/blob/f6662b0ec7a832236aac3e3778397a6a3e92ec21/data/World/Water%20Temple.json#L47-L52

Don't know if there is any MQ dungeons that allow something similar.

**Comment by TestRunnerSRL** [comment]
While out of logic, keep in mind this does affect open forest. Logic says that you can't use warp song until you can leave forest.

@r0bd0g Wnfortunately no. Allowing non-songs appear at song locations involved rewriting the song cutscene code and was pretty involved. It might be possible to make it not do that, but would involve a lot of work, so someone else might want to look at it.

@rlbond86 In general I like this option, but I don't think it should really matter if things are progression or not. I think it would be great if this could be generalized more. like being able to start with any items. It could be something kinda like the "disabled_locations" list, except it would be a list of all items. It would be a bit of work in implement the UI correctly. To make the Fill algorithm take into account items that you start with, just make the world.state collect those items before the fill algorithm in the ItemPool generation. The same thing is done for keys in keysy. Then you'd want to make it so that you replace items from the item pool with junk for any item you start with. Would also need to somehow enforce not allowing you to start with items that don't exist in the pool, like 5 hookshots or 50 HC. If this is something you don't want to tackle, I'll merge this and implement this myself.

**Comment by rlbond86** [comment]
I've added the relevant calls to world.state.collect(), but I don't have time right now to add a more general version. I do think it's a cool idea though. If you want to merge this change as-is and work on it more that's fine with me.

**Pull request merged**
