### PR TITLE
Cap Maximum Hearts to 20

### PR DESCRIPTION
**Pull request by Cuphat**
Pieces of Heart and Heart Containers will no longer give extra hearts after the player has reached 20 hearts.

https://youtu.be/uYYDMmjgp9s

### CODE REVIEW

**Comment by ETR-BTF** [comment]
Does the player's health still get restored completely?

**Comment by Cuphat** [comment]
> Does the player's health still get restored completely?

Yes.

**Comment by r0bd0g** [comment]
What's this for?
This isn't something that should normally happen, and if it does I don't see why the glitches shouldn't behave as they normally would.

**Comment by ETR-BTF** [comment]
Nice!

**Comment by r0bd0g** [comment]
In theory you'd expect either the randomizer to balk at such an item pool, or the person making the plando to know what they were getting themselves into.

**Comment by ETR-BTF** [comment]
> If it's just about plandoing hearts, in theory you'd expect either the randomizer to balk at such an item pool, or the person making the plando to know what they were getting themselves into.

Indeed, this PR kills my evil plando idea of making all junk items Heart Containers and challenging the player to finish the seed before the game crashes lmao.

Tho this also protects users when they dupe Heart Pieces/Containers (e.g. grotto GS Token duping) and in case there are issues in the future. I'm not sure if the extra health and heat timer you'd get from 20+ hearts are all that valuable.

**Comment by Cuphat** [comment]
> If it's just about plandoing hearts, in theory you'd expect either the randomizer to balk at such an item pool, or the person making the plando to know what they were getting themselves into.

That's certainly an alternative that could be done, but I think there is more legitimate scenarios of adding extra heart sources to an item pool than there are for exceeding 20 hearts in a rando. That's just my opinion though. OoT3D Rando apparently did something similar, though they apparently turned heart pieces/containers to blupees at 20 hearts.

**Comment by r0bd0g** [comment]
What if I want to have so many hearts the screen stops updating so I can GIM without crashing?

**Comment by Cuphat** [comment]
So you're going to hope that some location you can dupe a lot of is a Heart Container so that you can break your file so that you can do GIM in a randomizer?

**Comment by r0bd0g** [comment]
Maybe!

**Review by cjohnson57 — APPROVED** [review]

**Pull request merged**
