### PR TITLE
Allow hint distribution configs to define explicit ordering of hint location placements

### PR DESCRIPTION
**Pull request by Elagatua**
Adds two new optional keys to each hint type dict in the hint distribution files, `remove_stones` and `priority_stones`.  The values for these keys are both arrays, for example: 
```    
"distribution":          {
    ...
    "always":          {"order": 3, "weight": 0.0, "fixed":   0, "copies": 2, "remove_stones": [        
        "ToT (Left)",
        "ToT (Left-Center)",
        "ToT (Right-Center)",
        "ToT (Right)",
        "HF (Cow Grotto)",
        "HC (Storms Grotto)"
    ]},
    "junk":            {"order": 4, "weight": 0.0, "fixed":   2, "copies": 1, "priority_stones": [
        "HF (Cow Grotto)",
        "HC (Storms Grotto)"
    ]},
    "barren":          {"order": 5, "weight": 0.0, "fixed":   4, "copies": 1, "priority_stones": [
        "ToT (Left)",
        "ToT (Left-Center)",
        "ToT (Right-Center)",
        "ToT (Right)"
    ]},
    ...
}
```
All locations in `remove_stones` will be excluded as possible locations for the associated hint type.

All locations in `priority_stones` will be moved to the top of the list during hint placement of that hint type.  In the above example, `HF (Cow Grotto)` would be chosen before `HC (Storms Grotto)` because it appears first in the list of priority stones.  

These keys allow certain types of hints to be placed in specific locations.  The above is an example from the SGL 2023 settings hint distribution that is currently under testing:

That specific distribution ensures that junk hints are always placed at `HF (Cow Grotto)` and `HC (Storms Grotto)` and that 4 barren hints are always placed at the Temple of Time (if barren locations exist).

### CODE REVIEW

**Comment by fenhl** [comment]
This feels like a roundabout and error-prone way of achieving the goal of setting specific hint stones to specific hint types. I think a system to do that directly would make more sense, e.g.:

```json
"fixed_stone_types": {
    "ToT (Left)": "barren",
    "ToT (Left-Center)": "barren",
    "ToT (Right-Center)": "barren",
    "ToT (Right)": "barren",
    "HF (Cow Grotto)": "junk",
    "HC (Storms Grotto)": "junk"
}
```

**Comment by Elagatua** [comment]
Yeah, I think you have a point there.  The context for why I did it that way is so that there was an explicit priority.  In TFB, I always wanted the ToT hints to be placed in exactly the same order (power, wisdom, courage), so just associating a hint type with them would not have been enough to make the order explicit.  

in addition, using the dictionary approach would still require something very similar to the `remove_always_stones` behavior since always hints get placed before anything else, regardless of what the hint distribution dictates. (this may be a bug, but i didn't want to change anything extra during the initial TFB dev). so unless the locations in the dict are excluded from the always hint locations, you could still get an always hint placed there instead of the "priority" hint.  

your approach does avoid the edge case of "there aren't enough barrens, so non-junk hints get placed on HC Storms" though.  i'm willing to go back and try and rework it, if you still think it's worthwhile after reading the above, just let me know. @fenhl

**Comment by fenhl** [comment]
> Yeah, I think you have a point there. The context for why I did it that way is so that there was an explicit priority. In TFB, I always wanted the ToT hints to be placed in exactly the same order (power, wisdom, courage), so just associating a hint type with them would not have been enough to make the order explicit.

Maybe the fixed gossip stone specification could be extended to not only allow specifying hint type but also some parameters (such as the goal in the case of goal-count hints).

> in addition, using the dictionary approach would still require something very similar to the `remove_always_stones` behavior since always hints get placed before anything else, regardless of what the hint distribution dictates. (this may be a bug, but i didn't want to change anything extra during the initial TFB dev). so unless the locations in the dict are excluded from the always hint locations, you could still get an always hint placed there instead of the "priority" hint.

I don't think this is a bug, but fixed stones could still be handled before Always hints.

> your approach does avoid the edge case of "there aren't enough barrens, so non-junk hints get placed on HC Storms" though. i'm willing to go back and try and rework it, if you still think it's worthwhile after reading the above, just let me know. @fenhl

I'm just giving my personal opinion here. Might be worth asking @cjohnson57 or @Cuphat what they think.

**Comment by Elagatua** [comment]
Planning on going back and improving this because SGL will benefit from some of the suggestions, just haven't had time recently.

**Comment by Elagatua** [comment]
@fenhl i've updated the implementation and the description for this.  i think the hint distribution file is laid out in a much more logical way, and now removed and priority locations can be independently defined for each hint type.

**Comment by cjohnson57** [comment]
So this seems fine to me, fenhl's way of doing it could be a separate but similar functionality.

I'll see about merging it today assuming the conflict isn't too bad for me to feel confident resolving it myself

**Comment by Elagatua** [comment]
Yeah I incorporated fenhl's suggestion into my improved implementation.  the reason i didn't go with their original suggestion is because my method preserves the explicit ordering of the selection of specific locations, while using a dictionary as the root object could lead to unpredictable ordering, since key iteration order is not guaranteed in dictionaries.  i went ahead and took care of the conflict as well since it was easy to resolve.

**Review by cjohnson57 — APPROVED** [review]

**Pull request merged**
