### PR TITLE
Fix 'Randomize Main Rule Settings'

### PR DESCRIPTION
**Pull request by Cuphat**
This feels hacky as shit and I don't like it but it works for now.

### CODE REVIEW

**Comment by Zannick** [comment]
I've got a fix for the specifically known set of issues but I'll look closer at this later as well. I definitely have struggled to understand how `get_dependency` is supposed to work...

**Comment by Cuphat** [comment]
My main problem with it is that despite `check random` being a thing, it is still considered disabled when Randomize Main Rule Settings is on because it adds a dependency to it as far as I can tell. Trying to debug these lambda functions is apparently just not knowledge I have so I went with a band-aid fix that at least seems to work even if it is an ugly garbage hack.

**Comment by Cuphat** [comment]
Looks like you went with a slightly less hackish approach and just handled the two settings that like to break often. I'll close this to take it out of the PR queue.

**Comment by Cuphat** [comment]
Reopened because it is a more "permanent" fix to the problem now that we have more setting dependencies. Before the release we should either merge this or make a similar fix to last time addressing the specific settings that are issues, or both. Right now the one that stands out the most is Small Keys: Any Dungeon and Dungeons Have One Major Item, which can collide when settings are randomized.

**Review by Zannick — APPROVED** [review]

**Pull request merged**
