### PR TITLE
Fix Dead Hand Spawns

### PR DESCRIPTION
**Pull request by engineer124**
This addresses https://github.com/TestRunnerSRL/OoT-Randomizer/issues/1384

There is a small possibility in MQ Shadow Temple that Dead Hand will spawn outside room collision in the basement and fall. Full explanation on why this happens here:

https://discord.com/channels/274180765816848384/759842532963385354/893073109538721802

TLDR, Dead Hand spawns slightly offset from the center of the room in all 5 instances (1 vanilla botw, 1 mq botw, 1 vanilla shadow, 2 mq shadow). However, due to room geometry and it being the largest offset, this issue is most noticeable in the basement of mq shadow.

This moves all 5 instances of Dead Hand to be in the exact center of the room, fixing the bug where DeadHand falls. This was done for all cases since there is indeed an extremely small possibility of DeadHand falling Out Of Bounds in Vanilla dungeons. However, if the dev team thinks the fix should be only for the basement of MQ, then I'm happy to take out the other instances and only move DeadHands spawn in the basement of mq shadow.

I tested 40 spawns in the basement of mq shadow for DeadHand and they successfully spawned every time.

### CODE REVIEW

**Comment by r0bd0g** [comment]
"Spirit of Vanilla" says I need to be opposed to this, sorry.

**Comment by engineer124** [comment]
I should add that in my explanation in discord, I cover the astronomically low odds of Dead Hand spawning outside collision in the hover boots room and in the lens room. This actually only applies to MQ and turns out the odds are even lower in Vanilla for those two rooms, as Dead Hands spawn is even closer to the center of the room (not exact though)

**Comment by engineer124** [comment]
> Want to point out there's a conflict with this and the dungeon shortcuts PR that would need to be resolved if both are to be accepted. Logic changes will be necessary to make them compatible.

I took a look through the dungeon shortcuts PR but I saw nothing that would indicate a conflict. Nothing about this PR changes any logic, or is dependent on any logic or setting other than if mq is chosen or not. The mq dungeons changes the mq data file directly, so no conflicts there. And changing the deadhand spawn locations in vanilla dungeons only checks if mq has been selected or not. This applies universally, no logic is involved for that.

**Comment by mracsys** [comment]
I believe r0b is referring to the lens requirement+trick added onto MQ 2nd Dead Hand because of this bug. It's not inherently incompatible, but some may feel it would be unnecessary with this fix. I don't have an opinion either way.

**Comment by engineer124** [comment]
Ah, I see. Okay yeah in that context the conflict does make sense. I also don't have an opinion either way, I'm content with just giving the devs an option to choose from.

**Comment by r0bd0g** [comment]
Dead Hand never spawning OoB would at minimum need tooltip changes. Probably strength would be fair came even without lens or trick. Then there's a new debate probably has to happen regarding consumables b/c the odds are so low that you would actually be unlucky enough to run out. I'm pretty convinced you should always be able to spawn him without running out of explosives. Din's is probably the simplest way unless you get really unlucky. Even bow probably wouldn't be that bad, there are both magic and arrow drops in the area. What do the enemies in that area drop b/c there could possibly be an unlimited supply if you've got some time to kill.

**Comment by Zannick** [comment]
I'm perfectly happy to fix vanilla bugs if it improves the gameplay experience. I'm not sure I would appreciate the value of Dead Hand sometimes not appearing in MQ, and I'm not sure I'm familiar enough with MQ to comment on the consumables thing (though I know we have plenty of situations already that don't consider how tedious it might be to replenish rupees/consumables).

**Comment by r0bd0g** [comment]
The only thing that really needs to be worried about is that one of the tooltips in dung shorts mentions dead hand falling OoB. You just need to reword that if both this and that PR are to be merged. I'm planning to start a logic update in maybe April or so, and at that time I'll revisit whether that trick we added for dung shorts is still needed.

**Review by Zannick — APPROVED** [review]

**Comment by fenhl** [comment]
This happened in today's RSL race (on 6.2.19 R-1): <https://clips.twitch.tv/PiercingSolidDonkeyDogFace-2i8bxt18iGc6bVBz>

**Pull request merged**
