### PR TITLE
Rework DMC logic to fully support overworld ER

### PR DESCRIPTION
**Pull request by Roman971**
In Overworld ER, you may not be able to reset your timer at the Darunia's Chamber and Mountain Trail crater entrances so the logic has to be updated so we can properly support 3 hearts accessibility without a tunic.

This rework splits each main crater region (Lower, Upper and Central) into 2 regions: one "Limited" which is accessible from other regions in the crater, and another region corresponding to having access to a nearby entrance (to reset your timer) or being able to use a Goron Tunic. The "Limited" region is essentially a subset of the original region which contains everything that should be accessible from other areas of the crater.

A new small region is also created, called "Death Mountain Crater Lower Ladder Area", that contains the DMC deku scrub which should be accessible as child from the Upper area as well as the Lower area in ER. Until now, this scrub was only in logic from Upper but I think it makes sense to add it in logic when coming from the Darunia's Chamber entrance. Players can bait a scrub shot then jump down as child quite easily.

For reference, the cases where you may have limited access because you can't reset your timer with a nearby entrance are as follows:

- Everything in the Upper area is in logic only if you have a tunic or can reset your timer at either the boulder grotto or the Mountain Trail entrance. This applies to both climbing the ladder from Lower and riding the bean from Central.

- Going from Central (Bolero) to Upper is not in logic by going through the Lower area (with hover boots or hookshot) if you don't have a tunic and can't reset your timer at a Lower entrance (hammer grotto, fairy or Darunia's Chamber). It's only in logic in that case by riding the bean directly to the Upper area.

- Going from Upper entrances to the Central Area is not in logic if you don't have a tunic and can't reset your timer at a Lower entrance. This includes entering Fire Temple as well as reaching the Bolero location and volcano HP (with hover boots).

@r0bd0g @Zannick We've talked about this before so please let me know what you think about this particular solution.

We still have to decide whether or not climbing from Lower to Upper should be in logic without "Fewer Tunic Requirements" but it's kind of unrelated since it applies to non-ER. Either way, it could be changed just as easily as before even with those changes.

Edit: Removed the mention about the Bolero location and volcano HP being in logic from Upper without a tunic since this is no longer the case (see comments/commits).

### CODE REVIEW

**Comment by r0bd0g** [comment]
Lower to Upper should be a fewer tunic requirement thing. I think you have about 4s to spare on 3 hearts? It's actually pretty tight.

**Comment by r0bd0g** [comment]
Reading through this and I have no idea if this is actually correct, lol.
I question whether it captures all the nuance, but I'm too tired right now to actually try to parse this out.

**Comment by Zannick** [comment]
I usually get Lower to Upper with 1s to spare by using a hookshot to get up the ladder, though I'm not the fastest. It *is* a bit tedious to duck in, refill to 3 hearts, and duck out to reset the timer back to full after every time I void out, though, so I'd say it should be a trick.

I definitely got confused trying to write feedback on the new graph. Initially I was reading the Limited areas as the regions accessed from outside, and that almost led me to note that Ladder Area wasn't accessible by child. But I read your description more carefully, and now I see how you implemented the timer reset as (eg) Upper Limited -> Summit -> Upper. I like that a lot. Part of my confusion was based on reading "Limited" to mean "what I can reach without Tunic" but then Bolero goes directly to Central...

1. We could alleviate the confusion with some better region names. Instead of "Limited", maybe "Nearby"? I would make the other regions (from outside DMC) "Local" as well (and rename Ladder Area "Ladder Nearby"/"Ladder Area Nearby") so we get a consistent + obvious naming scheme: where entering DMC always puts you in a "Local" region with access to the appropriate Nearby regions, and without tunic/tricks your only exits from a Nearby region go out of DMC.

1. For the Ladder logic to Upper, I'd suggest adding in a tunic-or-trick requirement, eg. `logic_crater_lower_to_upper or can_use(Goron_Tunic)` or `is_adult and (logic_... or Goron_Tunic)`. I don't have a strong opinion on whether it should be `fewer_tunic_requirements` or a separate trick. It may apply to non-ER but I think requiring Lower->Upper on 3 hearts is more likely to be a progression blocker in ER than non-ER so it seems reasonable to me to take care of it here.

**Comment by Roman971** [comment]
Sorry for the delayed answer, I didn't have time to work on rando dev in the last few weeks but I should be able to do stuff again now.

I will have to think more about it but I will probably change the naming with "Nearby" and "Local" as you suggested, or something similar. Not 100% sure what's better but I agree about getting a consistent and obvious naming scheme, including the Ladder Area region name.

On the topic of Lower to Upper logic as adult, I also think climbing up the ladder without a tunic should require "Fewer Tunics Requirements". But as I said I prefer keeping it to a later separate PR since this one is only supposed to fix the ER logic for DMC, so it shouldn't include any change that affects non-ER.

**Comment by Roman971** [comment]
Rebased and changed the naming pattern with "Local"/"Nearby" as suggested.

**Comment by Zannick** [comment]
Great! Can you double-check whether the `Lower Nearby -> Central Nearby` exit should be `Lower Local -> Central Nearby`? As is, it puts a tunicless route with Hover Boots in logic from Upper to get Sheik...

**Comment by r0bd0g** [comment]
So I dunno for sure that it'd work without having tried, and it would probably be a lot more regions? But I feel like each entrance to the crater should be a region, and each goal and exit from the crater is a region, and you then should be able to precisely define exactly what's allowed in what circumstances... I find this implementation difficult to trace where exactly you're allowed to go and when, in order to verify that it's correct.

**Comment by Roman971** [comment]
@Zannick It's like that in purpose but I guess getting to Sheik from upper with 3 hearts and no tunic is a bit tough as is unless you do the proper rolls, even though it's completely doable. I don't mind changing it for now but I think it might belong in the Fewer Tunic Requirements trick, similarly to `Lower Local -> Upper`. 
What about the volcano HP though? Should it be in logic from Upper with 3 hearts and no tunic like it is currently or should it be changed just like Sheik? I don't mind changing it either, and handling them separately is completely doable too.

@r0bd0g We discussed about that solution before and the main issue I have with it is you would have to list every single goal/exit from every entrance, including the ones you can reach with a tunic. There are quite a lot of goals/exits and entrances in the crater so I don't think that implementation would end up viable. 
If we only had to deal with goals/exits you can reach without a tunic I think it would be fine, but having to handle tunic requirements as well means every entrance should have rules to every goal/exit, which adds a lot of complexity and duplication.

**Comment by Zannick** [comment]
So with `logic_crater_bean_poh_with_hovers` off (or no Hovers), the PoH requires riding the bean. The spot for that is even further into Central, and then you have to ride the bean. Maybe worth timing to see what it would take. I don't think either the PoH or Sheik from Upper with no tunic should be in logic without Fewer Tunic Requirements at minimum, but I'd want all the tricks in FTR to be roughly the same difficulty, so I think the PoH probably deserves to require tunic when coming from Upper unless it's a lot easier than I imagine.

**Comment by Roman971** [comment]
For the bean ride it doesn't matter because you must be able to play Bolero in order to plant the bean in the first place anyway.

But I agree this whole situation is probably not something that logic should expect by default so I will remove both Sheik and the volcano PoH from logic when coming from Upper without a tunic, for now at least. And we can discuss whether or not they should be included in the FTR changes that will have to be done anyway once this gets merged.

**Comment by r0bd0g** [comment]
Planting the bean, and the GS are child-only so you won't need to do anything special with those. Besides those, there are 8 entrances, 7 exits, 3 goals, and a gossip stone. Did I miss any? So from each of the 8 entrances you would need to exit to those 11 areas. It's a lot of bloat but you'll know it works...

**Comment by r0bd0g** [comment]
Thinking about it some more, some of the logic for traveling around the crater could get pretty verbose if done like that. :p

**Pull request merged**
