### PR TITLE
Refactor Logic Rules

### PR DESCRIPTION
**Pull request by puddydoo**
"No Logic" is moved out of "Logic Rules" and into "Guarantee Reachable Locations" because this option is really the opposite end of the spectrum from "All Locations Reachable".
Accordingly, the "Logic Rules" dropdown is replaced by a Glitched logic toggle. "Guarantee Reachable Locations" is also moved to the Main Rules tab.

### CODE REVIEW

**Comment by ETR-BTF** [comment]
> "Enabling this changes the logic so that it can require the use of movement-oriented glitches. This is not compatible with entrance shuffle".
Glitch logic considers more than just movement-oriented glitches. It also considers glitches that lower item requirements for locations. Furthermore, glitch logic is also incompatible with MQ.

I'm worried that refactoring the logic settings like this will cause confusion leading to users generating seeds they cannot beat or did not wish to play.

**Comment by ETR-BTF** [comment]
What it looks like
image

**Comment by puddydoo** [comment]
"Movement-oriented glitches" doesn't sound like a good description to me either but that's how the option was described before so I carried it over.

**Comment by LostThePirate** [comment]
I think that is plainly a terrible idea...
I think trying to slap Logic settings and Reachability settings into one is a bad idea.
I think calling No Logic anything other than No Logic is a bad idea.
I think "Required Only" is vague enough to be useless as a label.
I'm strongly opposed to basically all of this.

**Comment by puddydoo** [comment]
It now looks like this:

Logic Rules:
- All Locations Reachable
- All Goals Reachable
- Beatable at Minimum
- Not Guaranteed Beatable

**Comment by LostThePirate** [comment]
Not "most of" the Glitchless enableable tricks; all of them are in base Glitched Logic, along with a giant pile of other things. Until Glitched 2.0 is ready (and Glitched gains its own tricks list), Glitched is still all-or-nothing; if you enable it, it uses its own fixed, distinct logic.

**Comment by puddydoo** [comment]
If a better description is needed then it has to be written first because the main branch literally just says "Movement-oriented glitches are likely required".

**Comment by ETR-BTF** [comment]
> Not "most of" the Glitchless enableable tricks; all of them are in base Glitched Logic, along with a giant pile of other things. Until Glitch 2.0 is ready (and Glitch gains its own tricks list), Glitched is still all-or-nothing; if you enable it, it uses its own fixed, distinct logic. This tooltip description waters down just how much additional glitch knowledge is expected/required for Glitched.

Maybe this until 2.0 is ready:
"All glitchless logic tricks as well as most glitches short of Item Manipulation and Wrong Warp are considered in logic. For a detailed description of what's in logic, please visit the Glitch Logic wiki page."

And yeah that tooltip description already existed before this PR.

**Comment by DuskTheUmbreon** [comment]
I agree with Lost - No logic doesn't feel like it's really part of ALR. It really feels that it should stay part of the actual logic settings.

ALR on versus ALR off doesn't change what you need to know to beat the game. You don't need to learn anything new to have a chance of succeeding with ALR off if you've practiced with ALR on.

However, when changing the logic rules, you _need_ to know new things to be able to beat it. If you go from glitchless to glitch logic you *need* to learn a lot of glitches to have a chance in hell of making it, and going from glitch to no logic you need to learn even more on top of that.

Because of that, I also have a bit of concern that people are going to end up turning off logic by accident. With it being part of the logic setting itself, I feel people are far more likely to leave it on glitchless if people don't know what it does, since they'll go "Oh I don't know glitches I want it on glitchless". Even if they have no idea what "No logic" means they'll still recognize what glitchless means. I don't feel they'll have that same recognition with ALR, though.

However, *if* this is going to be merged, I would suggest changing this
> This is not compatible with entrance shuffle or Master Quest.

to this
> This is currently not compatible with entrance shuffle or Master Quest.

since I'm actively working on making it compatible with both of those.

**Comment by Zannick** [comment]
I kind of get where you're coming from comparing No Logic to No Locations Guaranteed Reachable, but I'd rather keep the lower end of logic as "Beatable at Minimum" and leave "turn off all logic" as a metaphorically giant red switch. In that I have to agree with the other reviewers. Same with the glitch toggle, which seems more like a follow-on to the No Logic change.

Changing "Required Only" to "Beatable at Minimum" might be a worthwhile change, but if you want to pursue that, let's make a separate discussion for it.

**Pull request closed without merging**
