### PR TITLE
Triforce Hunt

### PR DESCRIPTION
**Pull request by KevinPal**
Adds a new Bridge Option called Triforce Hunt

This mode adds a new Item to the game, which is a piece of the Triforce.
Collecting 20 of these allows you to spawn the Rainbow Bridge
There are 35/30/25/20 pieces available in plentiful/ balanced/scarce/minimal

Triforce count is displayed on pause screen.

Current triforce model:
image
game1

I will try and add a better texture for the triforce instead of a solid color.

Pause screen display:

game

This needs to be tested a lot. I have done a full seed on mupen64plus with no issues, and project64d seems to run fine. I am unable to test this, but this needs to be testing on hardware
- [x] N64 hardware
- [x] VC

Triforce count is stored in unused scene word in scene x48, but should probably be moved somewhere else.

### CODE REVIEW

**Comment by Roman971** [comment]
Unless I'm reading this wrong, you forgot to change the glitched logic file with the new rainbow bridge condition. Nice to see I'm not the only one forgetting to support glitched logic when changing stuff.

Also I don't know if this intentional for now since there is a TODO there, but there isn't any cryptic version for the "Triforce Piece" hint. Just pointing it out so it doesn't get forgotten.

**Comment by KevinPal** [comment]
I've updated the glitched logic file, I didn't even realize that existed. Also I forgot about that TODO, thanks for catching it. Suggestions for what the cryptic hints should be would be nice.

**Comment by KevinPal** [comment]
Also noting that so far on VC there seems to be a bug where there's around a 50% chance that the Winner heart piece message and effects come up instead of the triforce text box, but you still get the Triforce piece.  This is hopefully not related to it being on VC.

Thanks @Cuphat for testing

**Comment by TreZc0** [comment]
Amazing!

**Comment by OlafurKrH** [comment]
This has all my YES on it. I will try this out on my next run.

**Comment by KevinPal** [comment]
- Triforce text should no longer display the Winner heart piece message (hopefully)
- Triforce count display temporarily appears on screen whenever you collect a piece
- Triforce count display shows how many pieces are required
- The number of triforce pieces required (20) is less hardcoded, and should be configurable if we want

I'm pretty sure there are no console specific issues. Thanks to all who tested.

Shop Sanity is still broken.

**Comment by KevinPal** [comment]
Shopsanity should be working

**Comment by churnthing** [comment]
Shopsanity does seem to be working on VC, I was able to buy a triforce piece.

**Comment by MelonSpeedruns** [comment]
Yo Kevin, I was wondering if I could have a shot at making a new 3D model for the triforce piece, I was considering making it so it shines like the actual in-game triforce model. Would you be fine with a .zobj of the model?

**Comment by KevinPal** [comment]
@MelonSpeedruns So currently I don't have a good way to put an actual texture on the model. That's why it is just a solid color. I will be looking into that, but that will probably be post 5.0. 
As for the model its self, I use a .obj file, which pretty much everything can export to (Make sure to triangulate faces). 
Finally, for the sprite, it needs to be 16x16 (I know, oot is really low res). I made a sprite sheet of 16 16x16 triangles tiled horizontally to make the animation.

I'll upload the files I used here later, but the process isn't super generalized yet.

**Comment by MelonSpeedruns** [comment]
I gotcha, well you know, the zelda modders already figured out how to import custom models for a long while now, and even animations to them: https://cdn.discordapp.com/attachments/388362040105762836/603010080782155779/2019-07-22_18-46-07.mp4 So it really wouldn't be hard to import your triforce model with a texture, and with a metallic surface.

**Comment by MelonSpeedruns** [comment]
There you go for the icon: https://i.imgur.com/tVE7dSL.png 16x16 as well! By the way, would you happen to have Discord? I think it would be better to talk there instead of spamming the comment section.

**Comment by KevinPal** [comment]
@MelonSpeedruns  Yeah I'm in the discord. Ping me at @shadeslayer55. Pretty sure we've talked there before.

**Comment by Roman971** [comment]
This doesn't seem to be compatible with starting items? I'm not sure how important it is but I think ideally we should support starting with a configurable amount of triforce pieces through plando. `SaveContext.give_item` would have to be updated to handle triforce pieces somehow, although the scene flags part of the save context is not defined in there but that shouldn't be too hard to add since it's literally the next thing after `gs_tokens` which is the last thing currently defined in the save context addresses.

Also on the plando side of things, I think this breaks at least partially if you try to set a custom count of triforce pieces in the pool, even though it would be nice being able to do just that. The triforce pieces count is currently hardcoded in a specific way through `world.triforce_count` so I think all that would be needed is to make sure that value is set based on the pool once it is completely generated and altered by the distribution file if there is one.

And this is very minor but the whole `can_build_rainbow_bridge` method could make use of `state.has_all_of` to tidy it a bit, and that's probably slightly more efficient too.

**Comment by TestRunnerSRL** [comment]
Something else I've noticed that somewhat minor is that the unittests currently fail for triforce hunt with ALR off because they are specifically looking for the Triforce at ganon as the win condition.

**Comment by Roman971** [comment]
Yeah, unit tests need to be fixed to handle playthroughs having a different win condition in this mode.  Currently, unit tests expects all worlds to have one and only one "Triforce" item in the playthrough, which means tests fail when triforce hunt gets randomly enabled in fuzzing tests. So it should be updated to look for a certain number of triforce pieces instead when triforce hunt is enabled.
Also, adding a unit test dedicated to triforce hunt is probably a good idea.

I don't know if @Zannick wants to take a look at it himself but either way I think ideally we should handle it before it gets merged.

**Pull request merged**
