### PR TITLE
More Minor Changes

### PR DESCRIPTION
**Pull request by Cuphat**
First commit fixes a few errors in the default presets. Whoops.

Next, the locations in the playthrough spheres in the spoiler log are now sorted so that those are consistent between generations.

Finally, fixes shop wallet logic when the price is above 500 rupees.

### CODE REVIEW

**Comment by Cuphat** [comment]
Two more minor commits added. One to fix #836 and one to make the Bunny Hood trade actually fill even a Tycoon's Wallet, as he would if such a wallet was actually in vanilla.

**Comment by TestRunnerSRL** [comment]
A couple things, unsure if sorting the playthough by name makes the most sense. Not sure the best way to go about doing it, but will result in some dungeon locations be separated from the rest. Might just be something we deal with until we decide to start grouping things by area.

Setting the wallet progressive to 3 while is not incorrect will basically make it impossible for them to be considered barren even though in non-plandos, you will never need more than 2. Would be nice if we could determine the most amount of wallets needed by the max price of any (major?) item and used that for the progressive value.

**Comment by Cuphat** [comment]
Sorting playthrough by name isn't ideal but I'm not sure what better method to use to sort it, and any sorting is better than a random whack-a-fuck in a lot of cases.

Does my newest commit resolve your issue with the wallets or did I miss something else?

**Comment by TestRunnerSRL** [comment]
yeah that seems fine. One day we'll make the barren logic a lot more elegant. Glad you made sure to add to the copy.

**Pull request merged**
