### PR TITLE
Setting to remove age requirements from items and equipment

### PR DESCRIPTION
**Pull request by mracsys**
EDIT: Keeping as a draft until/if GUI rework provides a place for less serious options.

Makes the following usable as child:
* Megaton Hammer
* Adult Trade Item
* Biggoron Sword
* Mirror Shield
* Goron Tunic
* Zora Tunic
* Iron Boots
* Hover Boots

Makes the following usable as adult:
* Deku Sticks ~~(might crash on some platforms, only tested emulator)~~ (fixed in rando elsewhere)
* Boomerang
* Child Trade Item
* Kokiri Sword
* Deku Shield

No logic changes are included or planned.

### CODE REVIEW

**Comment by ETR-BTF** [comment]
Can you make Hookshot work as child? Zfg once showed on stream that the only reason it doesn't work as child is because the tip isn't loaded because 1 number is off. But loading the Hookshot tip as child without unloading other things in return might make the game unstable? I'm not sure how feasible this is. Timestamped zfg highlight video below.

https://www.youtube.com/watch?v=eWjqg6LchcQ#t=9m14s

**Comment by mracsys** [comment]
I see two ways to get child hookshot working:

1) Always load the object as child like adult, and figure out what other objects can be removed or loaded on demand
2) Change the hookshot to not require the tip to be loaded (may not be possible if the object contains more than graphical assets).

I'd also want to at least get the red dot working if not the whole model. Zfg's clip doesn't show it. Decomp can help, but it's not trivial. There are other things I want to hack into first as well. Any of the asm wizards looking for something to do are very welcome.

**Comment by dewiniaid** [comment]
> EDIT: Keeping as a draft until/if GUI rework provides a place for less serious options.

I kind of think a "Quirks" tab could eventually be useful.

I've had a few different "experiments" regarding multiworlds that would be nice to be able to define there:

- The mirrored PVP ice trap duel multiworld settings (generate N worlds for N*2 players, flip ice traps to go to opponent worlds)
- Mirroring hints (P1 has hints that belong in P2's world and vice versa)

Those are unrelated to this PR, but other candidates for such a tab.

**Comment by matthewkirby** [comment]
Out of curiosity, what is still missing here?

**Comment by mracsys** [comment]
The only technical blocker is getting hookshot working as child. Beyond that there is the logic debate. Feedback from glitchless was this needs to be in logic or hardcoded to only the No Logic setting. Glitched/No Logic community sees it as redundant to equip swap, which it is.

**Comment by r0bd0g** [comment]
Logical hookshot as child will break the Spirit Temple logic. I mean technically you can already get to adult side glitchlessly with crazy dance, but at least that's clearly not something we would intend. In this case, with logic for wrong age items, I don't think we can just say "Hey please don't use the hookshot here unless you really know what you're doing?". A lot of features or suggestions have been butting heads with Spirit logic lately and I'm not really sure what to do about it. I'd have to think very hard about what are the logical implications -- if I recall correctly it was very not good, but it's been a while since the last time I considered what it would mean.

Besides that one limitation, you would have to overhaul the entire logic of everything. It's a huge project. And of course going forward anyone making a new setting that impacts on logic will have to take this setting into account. I still think we should have a category for settings that are something you can turn on just for fun, but are not fully supported.

**Comment by ETR-BTF** [comment]
Should Child be allowed to use Strengths 2 and 3 too? According to Three Pendants in Discord it's relatively trivial to implement.

> As memory serves, a child has no issue lifting the Golden Gauntlet pillars, as far as programming is concerned, sure one small check in the code may need to be changed, but nothing more extreme than that.

**Comment by mracsys** [comment]
Discussion with the repo maintainers on Discord indicated this is unlikely to be accepted. Given this has been open almost a year with a blocking feature, I am closing the PR and keeping this on my branch going forward.

**Pull request closed without merging**
