### PR TITLE
Many QoL Changes and Bug Fixes

### PR DESCRIPTION
**Pull request by fig02**
QoL
  * Speed up boulder lifting
  * Speed up Gold Gauntlet boulder lifting
  * Speed up learning Windmill song 
  * Speed up learning Malons song
  * Speed up Kakariko gate opening and closing
  * Set pos after Great Fairy so that speedrunners can properly backwalk out again ;)
  * Twinrova waits for player to reach the top platform before starting, preventing early snipes

Bug Fixes (some vanilla, some rando)
  * Prevent Collection Delay from the Carpenter Boss when mashing through the text with an item in hand
  * Gray note songs do not play back when learning them, adding consistency and preventing suns song from causing bugs
  * Empty Bomb fix improved to work in all scenarios
  * Fast warp song hack now sets transition to white fade so that it is consistent
  * Royal Family Tomb moves out of the way instantly 
  * Fix Zelda from being frozen at the start of the final battle
  * Drop ruto before entering Big Octo room if miniboss has been defeated

### CODE REVIEW

**Comment by r0bd0g** [comment]
(Please don't get me wrong I think these are neat, in general.)

"Twinrova waits for player to reach the top platform before starting, preventing early snipes"
I don't like the way this was done. I don't think it helps that much, and when they fire early now it's hard to tell where they're coming from. They'll start firing while they're still up above the ceiling sometimes. If I had to suggest a better way of doing it I guess I would suggest bringing in abbreviated preboss cutscene that leaves everything in the same position as vanilla, and then if you die to the fight and come back you get the same start as previous versions of rando?

"Speed up learning Malons song"
I don't like that this one doesn't visibly reload the room after learning the song. You should be able to play sun's song after learning the song and spawn next to Malon. This what occurs but it's done in a hacky way where there's no reason apparent reason that it should work. The visible reload of the room is your cue that your spawn position has changed. In some previous versions of the randomizer, the cutscene was cut short and playing sun's (assuming the game actually lets you do that) would not spawn you at Malon, and this new behaviour is reminiscent of that. I suggest at least adding some kind of fade to white after learning the song.

**Comment by fig02** [comment]
I can try to delay them being able to shoot when coming from above, but im not going to make a custom abbreviated cutscene, at least not in this short amount of time if people are trying to push out this next release.

Ill try to find a compromise with the malon thing but I personally dont see an issue with how it is now

**Comment by Roman971** [comment]
The description for the "Enable Useful Cutscenes" setting needs to be updated to match the fact that the Twinrova cutscene is always skipped now.

**Review by Zannick — APPROVED** [review]

**Comment by fig02** [comment]
a load was added to malon and twinrova now rises out of the middle platform and the fight begins in the exact same position as vanilla

**Comment by r0bd0g** [comment]
Great work!

I'm curious if you die and come back, do they still rise out of the platforms? Vanilla behaviour for that is the crap we've been used to since the beginning... Doesn't matter much either way.

**Pull request merged**
