### PR TITLE
Adult dampe heart piece checks for chest spawning and not chest being opened

### PR DESCRIPTION
**Pull request by KevinPal**
On chest size matches contents, you can see that the hookshot chest has nothing and run past it, but this won't let you get the heart piece the second time since it checks for if you opened the chest. This changes it to check if the chest has spawned, so you are not forced to open the hookshot chest.

### CODE REVIEW

**Comment by rattus128** [comment]
Did you snag those two bin files in the diff by accident?

**Comment by r0bd0g** [comment]
Not getting a heart piece if you don't open the chest is... sort of vanilla behaviour? I think in vanilla though it checks if you've got a hookshot.

**Comment by flagrama** [comment]
It is vanilla behaviour, but kind of annoying when you already know the item is junk. Why do you have to waste time opening the chest when the whole point of the setting is seeing you don't have to?

**Comment by r0bd0g** [comment]
And while we're at it just give both archery prizes if you score over 1500 on the first race.

**Comment by flagrama** [comment]
Does this give both prizes, or just let you skip the hookshot chest? I thought it was the latter. You should still need to do both races, just you should be able to skip the first one. My suggestion for the former on the Discord was mostly a joke.

**Comment by r0bd0g** [comment]
I read it that you still had to do both races. I just feel that if the plan is let you skip opening the chest, why not skip needing to spawn it too. It's dumb they make you race again even if your time is good enough on the first go around. Same with archery, I got 1500 already, so give me the prize.

**Comment by rattus128** [comment]
Theres was already some agrees in dev-bug-reports for the two checks in one
race approach.

**Comment by KevinPal** [comment]
With this, you do need to race twice. It just skips needing to open the chest. I did accidently add those two bins to the diff, ill remove them

**Comment by KevinPal** [comment]
Removed extra binary files

**Comment by TestRunnerSRL** [comment]
Rebase and merge

**Pull request closed without merging**
