### PR TITLE
Split Various Advanced Tricks

### PR DESCRIPTION
**Pull request by r0bd0g**
Sorry for the absurdly inflated line count.
I didn't update the readme to reflect these new options.
Reordering the trick list is a task for another time.

### CODE REVIEW

**Comment by phixtyseven** [comment]
Why is git diffing json like this

**Comment by r0bd0g** [comment]
I bulk uploaded my world files.

**Comment by r0bd0g** [comment]
Diff settings->Hide Whitespace Changes, to see the truth.

**Comment by r0bd0g** [comment]
Doing this I noticed and fixed an accidental reversion. There was one change to these files since I last downloaded.

**Comment by phixtyseven** [comment]
I (finally) figured it out. Your committed files just have carriage returns in them. I'm not sure why vim wouldn't detect it like it usually seems to, but whatever.

What editor did you use?

**Comment by r0bd0g** [comment]
Notepad.

**Comment by phixtyseven** [comment]
Sounds like you know how to party

**Comment by r0bd0g** [comment]
The conflict is b/c I fixed the accidental reversion with the guarantee_hint on ganon.

**Pull request merged**
