### PR TITLE
Prepare Big Octo, altar, and compass hints for mixed pools boss ER and dungeon reward shuffle

### PR DESCRIPTION
**Pull request by fenhl**
Several parts of the randomizer currently assume that each dungeon contains exactly one medallion or stone. If boss arenas were to be included in mixed pools ER, or if dungeon rewards were to be shuffled into the main item pool, this assumption would no longer be correct. This PR makes things work in those cases:

* The dungeon reward info screen in the pause menu is updated with support for any hint area, not just dungeons and root. This increments the auto-tracker context version to 3. Example from my WIP mixed pools bosses branch: A screenshot of the dungeon reward info screen, listing medallions in several hint areas, most of which aren't dungeons.
* Using the same system also used for the Dampé diary and Ganondorf hints, a set of dungeon rewards is selected to be hinted at the altar, allowing duplicates to be present using item pool changes.
* Text for the dungeon rewards is added to the hint list. The altar hints normally prevent them from being used except in always hints. Compass hints currently don't, but compass reachability checks could in theory be added to change this.
* The item preview before the Big Octo fight is adjusted to remove the assumptions of the room behind Jabu's boss door being a boss arena and of the item found there being a dungeon reward. To handle non-boss-arena regions, a breadth-first search is started at the boss door (with regions belonging to Jabu proper ignored), and a random item from the first sphere of regions with shuffled items is used. Some location types are preferred over others to ensure that the dungeon reward and not the boss heart is selected if a boss arena is found (including when ER is off). For non-dungeon-reward items, the Zora sapphire item model is currently used. **Help needed** to always use the appropriate model here. If the item is an ice trap, the text box uses the name of the cloak item with vowel mangling like in shops. If no item is found, the text box is changed accordingly. Again, **help needed** to also make the actor invisible in that situation.
* A new behavior for compass hints (`CFG_DUNGEON_INFO_REWARD_NEED_COMPASS` = 2) is added where each compass hints the location of its dungeon's vanilla reward (e.g. the Deku Tree compass always hints the location of the Kokiri emerald). This is currently unused but is intended to be enabled when mixed pools boss ER and/or dungeon reward shuffle are on, since these settings both invalidate the aforementioned assumption made by the current behavior (`CFG_DUNGEON_INFO_REWARD_NEED_COMPASS` = 1).
* The access rules for exiting the boss rooms other than Queen Gohma's and King Dodongo's are changed to `False` to match gameplay. They were previously set to `True` to work around an optimization that was removing `False` entrances, which would then crash the ER. This is fine without mixed pools, but can create unbeatable seeds if a boss room is placed in the Spirit temple or at the Kokiri Forest end of the Lost Woods bridge. I deleted the offending optimization, which is probably not very useful anyway.

I'm sending this as a separate pull request rather than including it in a PR for mixed pools boss ER for 2 reasons:

1. Mixed pools hasn't quite made it to Dev yet (there's still a limitation with which overworld entrances can lead to which other entrances that needs to be lifted) and so I will be opening mixed pools bosses as a PR to Dev-R, but I think this is a rather large change for @Roman971 to be maintaining there.
2. This also benefits dungeon reward shuffle, which could then be implemented mostly independently of mixed pools boss ER.

### CODE REVIEW

**Comment by r0bd0g** [comment]
Did that optimization account for things like tricks that cause entrances to always be false? So perhaps it was a bit more useful than it appears at first glance idk? Maybe there's a hack you could do where the entrance checks for an item that doesn't exist.

**Comment by fenhl** [comment]
I made the adjustments for #1608. That PR added songs on pre-completed dungeons to the starting items, so I extended the behavior to include songs on songs when the song location is in a dungeon.

**Comment by fenhl** [comment]
This PR is now included in <https://ootrandomizer.com/generatorDev?version=devFenhl_> and people have already found 2 bugs, which are now fixed (though the fixes aren't on the web generator yet):

* Renamed the `Gohma Boss Room` region to `Queen Gohma Boss Room` to make it match the location names, which is required to make this line work:
https://github.com/TestRunnerSRL/OoT-Randomizer/blob/1b9d750cb68e1acef73c79992cebfde25ba9569f/Patches.py#L2073
* The MQ info in the pause menu had an off-by-one error resulting from me not updating code properly when I removed the free reward from the list (since it's handled separately now), so MQ info for the wrong dungeon would be displayed.

**Comment by r0bd0g** [comment]
"Renamed the Gohma Boss Room region to Queen Gohma Boss Room to make it match the location names, which is required to make this line work"
I don't know what this is for but you should think of a way to do this that doesn't rely on such precise region and location naming.

**Review by cjohnson57 — APPROVED** [review]

**Comment by fenhl** [comment]
Combined with #1694, all unit test including those requiring a base rom pass again.

**Pull request merged**
