### PR TITLE
Redefine State functions as global json rules

### PR DESCRIPTION
**Pull request by Zannick**
Create a global json file `data/LogicHelpers.json` which contains the definitions of rules that were previously State functions.

Performance change is negligible.

### CODE REVIEW

**Comment by r0bd0g** [comment]
When TR implemented shopsanity originally it required logical access to the ability to buy refills from the shop. That's why has_bow, has_slingshot, and has_bombs exist. It doesn't make any sense anymore, but I guess it was left around in case one day we decided to ensure logical access to drops again, rather than just assuming it from rocks or something. So that's why it existed, anyway. Any reason has_bombs was left alone?

**Comment by Zannick** [comment]
Only because `'Bomb Bag'` isn't `'Bombs'`. :P

Although, we can move these into the parser as well, and then we don't need to touch the logic, and we still gain mostly the same effect. Let me do that instead...

**Comment by r0bd0g** [comment]
Hmm? has_bombs() is just has(Bomb Bag) isn't it?

**Comment by TestRunnerSRL** [comment]
Most of those rules I added were later turned into `has('thing')`, so they ended up being duplicate. tbh I'm not really sure the `has('thing')` paradigm is better for performance tho

**Comment by Zannick** [comment]
There's a minor improvement in switching `has_bow` to `Bow` etc because the generated function calls `has('Bow')` instead of calling `has_bow()` which calls `has('Bow'). It's minor because most of the State calls aside from `can_use` are both cheap and infrequent. Anyway, this should be mooted by my next improvements here to automatically do that optimization.

**Comment by Roman971** [comment]
So when are we moving all the state methods to a json helpers file using the same syntax as the access rules? That would make it easy to just replace the helpers with their definition at parsing time to avoid those inefficient function calls. Also we would no longer have duplication between state methods and the parser like what you're doing here with `can_use`. Helpers could also easily support `at` conditions and things like `is_child`/`is_adult` that state methods no longer support, which is quite unfortunate.

**Comment by TestRunnerSRL** [comment]
So looking over the PR, I'm not a fan of the state functions being hardcoded (and duplicated) into the parser. I agree with roman that I think the goal here should be to move most (if not all) of these rules from state into some kinda of json form that the parser would then read and optimize. I think this change takes us away from that. Also I don't know how I feel about there being a `has_one` function, since I really question how much speed gain that is really bringing to the table.

**Comment by Zannick** [comment]
I wasn't intending to leave it duplicated, and sorry for not pushing up my changes after r0bd0g's feedback (I may have been hasty in PRing this). I was in the process of moving everything from State into the parser. Here's my current state if you want to see what I was up to; sorry I can't flip this into a draft PR.

I do like the json idea, and I agree it'll be great for nearly everything, but I am not sure how it will work for parameterized functions like `can_use` and `can_play`...

What are the requirements for writing code in json? Last time I believe we said it was desirable to have the code be both python and javascript compliant, but I think that might make `can_use` a bit messy (especially if we keep the code as one big expr). Or, if we provide each separately, we either have all 17 songs listed separately for `can_play`, or we use regexes:
```
"can_play\(([^)]*)\)": "has_ocarina and \1",
"can_use\((Goron|Zora)_Tunic\)": "is_adult and \1_Tunic or Buy_\1_Tunic",
```
or named arguments
```
"can_use(item)": "..."
```

Or, we decide that these are complicated meta-rules that have to be handled specially. Either way, I can start with the easy ones and we can go from there.

As for `has_one`, it's testing around 2-5% improvement right now; the main distinction is that `d.__contains__` is faster than retrieving the entry and comparing it to 1, and roughly 80% of the single-item checks only need `count=1`. (I suppose the parser could handle this directly, too.)

Let me test and PR the other things separately, and I'll use this PR for the json stuff when it's ready.

**Comment by TestRunnerSRL** [comment]
I think parameter support with named arguments is pretty reasonable. I would avoid regex as that will make things pretty hairy. You should be able to accomplish all those uses with conjunctions and disjuctions as has been done. `can_use` might just need a special handler in the parser like `has`.

**Comment by Roman971** [comment]
I think all special names resolved by `can_use` should be moved outside of that method. So for example, in the json file we would have things like `"Longshot": "(Progressive_Hookshot, 2)"` and `"Sticks": "Buy_Deku_Stick_(1) or Deku_Stick_Drop"` (which would also remove the need for `has_sticks`).
With all those special cases out of the way, `can_use` is really just item groups + the condition with which each item group should be handled. Whether or not we want to define those in the json file or in the parser is up to us, but I think we should avoid hardcoding those things in the parser as much as possible. Ideally, people reading/editing logic should never have to look at the parser.

**Comment by Zannick** [comment]
I think using conjunctions is going to be too messy, and if we want to support having these rules translate easily into javascript or python, the `in` operator is out. The most straightforward thing is to split it up into separate rules, like `can_shoot(arrow)`, `has_epona`, `can_use_magic(spell_or_lens)`, etc., as opposed to writing complicated logic to handle specialization.

For the special names, we could just go ahead and make them the "use" rule:
```json
"Sticks": "is_child and (Buy_Deku_Stick_1 or Deku_Stick_Drop)",
"Longshot": "is_adult and (Progressive_Hookshot, 2)",
"Scarecrow": "is_adult and Progressive_Hookshot and can_play(Scarecrows_Song)"
```
But it might be better to maintain a convention that uppercase words are items only, and if so we'd have to name things `use_sticks` or `can_use_sticks`, etc.

**Comment by Roman971** [comment]
Item names should never include their usability conditions. At least not until we decide to change everything to `has` instead of `can_use`, in which case we would need some pattern for cases where we actually want to test having the item instead of being able to use it right now.

I think `can_use` is fine to keep even if it's a bit messy at first. It will be slightly more difficult to implement but overall I think it should keep things simpler if we can just use `can_use` on everything like we can currently.

**Comment by Zannick** [comment]
Here's what it looks like to start with. I've made `Scarecrow` be an alias just like an item with the `is_adult` condition, since it doesn't conflict with any real items. Meanwhile, `"Goron_Tunic": "'Goron Tunic' or Buy_Goron_Tunic"` is the neat trick that lets us alias item names without infinite recursion.

Feedback welcome while I continue work: I'll be migrating and removing the rest of the State functions, then documenting how rules.json works.

**Comment by Roman971** [comment]
This looks like a good start to me. I suggest naming the file `Helpers.json` or something similar to emphasize its purpose.

For the `can_use` implementation, I think it's reasonable to handle it with a series of `item == ItemName` but in that case I think each set of matching items should be moved to its own rule. 
So for example we would have rules of the form `"is_type(item)": "item == ItemName1 or ..."`.
And then we can write `can_use` with a series of `is_type(item) and <condition to use this item>`.

I really don't like having a `has_epona` function which acts as a `can_use_epona`, so I think the `is_adult` should be taken out of `has_epona` and moved in the `can_use` instead. Or you could rename the function to something like `can_ride_epona` or `can_use_epona`, in which case we probably wouldn't even want to use it through `can_use`, and since it's a special case and rarely used I think that would be fine as well.

I'm not sure how `Scarecrow` and `Distant Scarecrow` should be defined but I'm also not a fan of having the `is_adult` in there. I'll have to think more about how we could handle it.

Slightly worried that this `'Goron Tunic'` and `Goron_Tunic` difference is going to be very confusing in the future so I'm not sure about that part.

**Comment by Zannick** [comment]
All done, thank you, and I annotated the `'Goron Tunic'` thing to hopefully explain it better.

**Comment by Roman971** [comment]
Looks mostly good to me, although the helpers file will definitely need some cleanups and more spacing/formatting to make it easier to read.

The only thing I really don't agree with is the whole `"Bow": "'Bow'"` pattern, which you mention as what would be used if we wanted to include ammo in the bow checks. If we ever added ammo to bow checks, we wouldn't use `Bow` for these, we would use a separate condition which checks for both having a Bow and ammo access. The reason for this is that some situations would still require checking that you just have a Bow and not necessarily the ammo for it. The main example I can think of in the current logic are the archery minigames. And this applies to other ammo based items like Slingshot. This is the reason we had `has_bow` and `has_slingshot` in the first place.

I think in general we should never use this pattern where we override an item name with a new condition **unless** we can guarantee that the original item would never be checked on its own. So for example, I think tunics and bottle consumables are fine to override, because they would never be checked on their own without their `Buy_` equivalent. But in my opinion those should be considered exceptions.

Also, for the cases where we need to add/set a rule dynamically (outside of the logic files), wouldn't it be better to just write the wanted rule in the string rule format and run the parser on it? This would probably not support `at`/`here`, and there might be some cases where we still have to write the actual lambdas (thinking mostly of `stone_reachability`) but I think it should cover most cases. This should remove the need for the `get_alias` method entirely.

**Comment by Zannick** [comment]
> Also, for the cases where we need to add/set a rule dynamically (outside of the logic files),  wouldn't it be better to just write the wanted rule in the string rule format and run the parser on it? [...] This should remove the need for the `get_alias` method entirely.

`get_alias` is there so we don't have to define, say, `guarantee_hint` in two places, and `state.guarantee_hint()` will resolve exactly the same. And when we need to change a spot's rules dynamically like for shop rules, we can also use it to retrieve `found_bombchu`. Oh, do you mean make a rule like `'found_bombchu'` and put that through the parser? That would work and wouldn't be redefining it.

**Comment by Roman971** [comment]
Yeah I mean doing something like `.add_rule(world.parser.parse_rule("found_bombchus"))` or `.add_rule(world.parser.parse_rule("is_adult"))`.

We would probably have a Location/Entrance method called `add_string_rule` to make it simpler so we can just do `.add_string_rule("found_bombchus")`, or just add a case for string parameter in `add_rule`.

**Comment by Zannick** [comment]
So I chose to leave `add_rule` as-is for now, because we can make the lambdas outside the loop and use them inside without needing to re-parse every time. And we can always revisit that later.

**Pull request merged**
