### PR TITLE
Increases link's forward speed while wearing the bunny hood

### PR DESCRIPTION
**Pull request by krimtonz**
Makes the bunny hood increase link's speed by 1.5x when worn.  Only for forward walking movement.  Doesn't affect rolls, backwalking, sidehopping, or sidewalking speeds.  Does not affect jumping distance either.

### CODE REVIEW

**Comment by r0bd0g** [comment]
uhhhhhhhhhhhh

**Comment by r0bd0g** [comment]
It seems weird to me to bring over the MM bunny hood functionality, without also doing the same for the goron mask. Both or nothing imo.

**Comment by Nicholas-Steel** [comment]
Adding those faithfully would require 1,000x the work, both in terms of coding and in terms of logic adjustments...

**Comment by r0bd0g** [comment]
That was a joke >_>.

People I think would expect "start with fast travel" to include the bunny hood? But that would cause some weird logic changes...

It would also be annoying to play with b/c the masks unequip on every load, so you'd have to put it on constantly, and you'd basically be out a c button for the entire time.

**Comment by Nicholas-Steel** [comment]
I figured it was a joke lol. I think in Suggestions on Discord people were saying to make it a DPad function.

**Comment by kdjmonaghan** [comment]
To constructively contribute to this instead of posting multiple concurrent memes, enforcing bunnyhood to remain equipped over loading zones shouldn't be that hard to do.

Binding to D-PAD up seems to be a concern as some people want L functionality on Gamecube Controllers to remain bound... although, I personally see no need for L functionality (minimap toggle in rando is pointless, just enforce it to be on when map/compass are obtained or at all times).

Idealistically the best case scenario is adding bunnyhood to the item pool which does not effect the context of the CTQ item, but is applied to D-PAD up on item being collected either by means or finding it in a chest / being awarded it or the CTQ item becoming the bunnyhood.

Either way this is additional work and I'm sure a lot of casuals, or, rando players in general, especially in a glitchless ruleset (Krim has also got the Bunnyhood to work as Adult) would be greatly appreciated for many.

**Comment by flagrama** [comment]
What about just passively increasing the movement speed while Bunny Hood is actively in your inventory? (but still let adult Link wear it if it is equipped to a C-Button because it is funny?? :D) Maybe makes it too "free", but it does solve the issue of equipping it (and reequipping it on new area) without forcing it to occupy a C-Button, nor interfering with VC's D-Pad mapping.

Honestly I think it'd be hilarious if you could figure out a way to always have it equipped while in the inventory. Just everyone eventually running around with bunny ears in races with no way to turn them off other than switching masks.

**Comment by rlbond86** [comment]
Even just increasing movement speed in Hyrule Field would speed the game up considerably, and there'd be no potential logic changes.

**Comment by TestRunnerSRL** [comment]
Rebased and merged. This PR is mostly meaningless in the current form because of how hard it is to get the bunny hood. Will probably need to look into changing this after the trade quest rework

**Pull request closed without merging**
