### PR TITLE
Fix 8 note Sun's Song with Randomize Ocarina Notes

### LINKED ISSUE #472: Sun Song in Non-Day change scenarios.
**Describe the bug**
I experienced a glitch with the Sun Song inside of dungeon like areas that would stun Redeads / Gibdos or the Graveyard Sun Song Chest. The game would freeze after the song leaving Link standing there with the Ocarina to his mouth, never loading the Freezing Gibdo's / Sun Song Chest. It is the same for both Young and Adult Link. I've been playing on RetroArch Core Nintendo / Nintendo 64 (ParaLLEl N64) in Exclusive Full Screen mode has given me the best results to play the randomizer. I have done well over 20-30 runs of the game as new patches come out I start over almost every time. The current version of the OoT Randomizer is 3.12.3 f.LUM. I usually do not get the Sun Song til late but this last play thru I got it early and of all other times I have used it, it has worked just fine until this last build. Possible causes could have been that the Random Song notes made the Sun Song 8 notes long, or that the song is trying to make the day change where it normally souldn't.

**To Reproduce**
The setting string I used was BAWQ8DS67XMDAAJMW6EPGAE5NAVA : and the seed was M5VMBVJ9UZ

**Expected behavior**
Normally on previous runs the Sun Song would go through and Link would put away his Ocarina and play would resume and either Redeads / Gibdos would freeze or the Sun Song Chest would appear.

**Screenshots**
N/A

**Randomizer Version Numer**
3.12.3 f.LUM

**Platform**
RetroArch Core Nintendo / Nintendo 64 (ParaLLEl N64) in Exclusive Full Screen mode for Windows 10 x64

**Additional context**

### LINKED ISSUE #1326: Playing suns song in graves/grottos softlocks (random notes?)
https://www.twitch.tv/videos/1050054315

https://ootrandomizer.com/seed/get?id=805082

Tested on pj64 v3.0 and RA
PJ64 save file: https://discord.com/channels/274180765816848384/438698093354156032/851913530806108220

Notable enabled settings: random notes & text rando

Softlocks in graves and grottos, but not graveyard itself. In the OW "[i]t "softlocks" the same way but then unfreezes on the wolf howl/cuckoo"

### PR DESCRIPTION
**Pull request by flagrama**
Should fix #1326 and fix #472

Confirmed to work for the seed mentioned in #472 should probably be tested with a reproducible seed on a more modern version though.

### CODE REVIEW

**Comment by flagrama** [comment]
This has also been confirmed to work on a 6.0 seed that had the issue. Marking ready.

**Comment by Cuphat** [comment]
For posterity, here's a ZIP containing the 6.0 seed - spoiler log, a patch without the fix, and a patch with the fix: https://cdn.discordapp.com/attachments/438698093354156032/933206492390260798/OoT_47901_9VWMGJAPKK.zip

**Review by Cuphat — APPROVED** [review]

**Comment by ETR-BTF** [comment]
Unfortunately, it seems that this PR did not fix #1326, or at least not the part about suns song not working properly in the symphony room in MQ Spirit. We just received another report of this bug happening on v6.2.133 M-7 (mracsys). Seed and Settings String are "0K7OXFUQLF" and "BSABRLEASJH2EAEQA8YKA8B9LZZLTZ9U57SLVCDDEJLEASEBAAABSAGAC2AXSF6XMCV3WGZKQYVB7JKLAAUBAANV6EA6JLABKE" respectively. Sun's Song was "v><<v><<".

**Comment by flagrama** [comment]
Someone should get the duration from the seed with a quick code edit. If it's longer than 260 then it can't be extended to 260 by this "fix". Knowing if there is some pattern such as "is a power of 2" could also be useful. Probably useful to get the durations of the previous test seeds too.

**Pull request merged**
