### PR TITLE
 Open Kakariko Gate: Obtaining Zelda's Letter Opens Mask Shop 

### PR DESCRIPTION
**Pull request by Cuphat**
This is going to get denied but fuck it. Please don't hate me, TestRunner.

This re-adds Open Kakariko Gate and if Open Kakariko Gate is enabled, obtaining Zelda's Letter will open the Happy Mask Shop without showing the letter to the Kakariko guard.

Open Kakariko Gate in its 4.0 state was basically a superfluous option, this removes an entire trip to Kakariko as a child to do the mask quest, making it less of a useless piece of shit.

### CODE REVIEW

**Comment by TestRunnerSRL** [comment]
I don't immediately hate the idea, but I think this requires a bit of open discussion, so I'll probably hold on this until post-5.0

**Comment by Roman971** [comment]
In glitchless logic, the "open_kakariko" condition should be located in both of the `Kakariko Village <-> Kakariko Village Behind Gate` exits instead of being in the `'Kakariko Village Gate Open'` event. 
It's important in overworld ER because you may not have access to the `Kakariko Village` which is where `'Kakariko Village Gate Open'` is, and going through the gate from the back is a logic trick, not default logic.

**Comment by Cuphat** [comment]
I added `open_kakariko` to the `Kakariko Village Behind Gate -> Kakariko Village` exit and kept it on the `Kakariko Village Gate Open` event. That should be pretty much equivalent to having it on both exits except it collects the event earlier, right?

**Comment by Roman971** [comment]
It's not exactly equivalent (since it's an event vs a direct check in the exit rule), but it won't change the effective logic. The only thing it should ever affect is the playthrough spheres.
I would argue it's not very consistent though. The event is supposed to represent the player action of "opening the gate", which isn't required if you play with open kak.
It doesn't really matter for this specific case but it's the kind of things I think we should avoid doing to keep the logic for events/actions clear.

**Comment by Cuphat** [comment]
That's fair, it just seems a bit weird that the gate open event would trigger anyway on Kakariko access + Zelda's Letter.

**Comment by Hamsda** [comment]
This may be better suited for Discord, but has there been any discussion/ideas about how the *child* trade sequence might get reworked, if at all?
I like this as an intermediary idea though.

**Comment by TestRunnerSRL** [comment]
Child trade quest rework is part of the trade quest rework, yes.

**Comment by TestRunnerSRL** [comment]
As for this PR, I dunno. I'm not against having a speedup option to skip this initial back and forth in the trade quest, but I don't think that open kak has anything to do with that. You should be able to open the gate with either the letter or the keeton mask (because you can close the gate with keeton mask)

**Comment by Cuphat** [comment]
> (because you can close the gate with keeton mask)

Huh? I've never heard of this.

**Comment by flagrama** [comment]
Hit no when he asks if you he can have the mask.

**Comment by TestRunnerSRL** [comment]
Yeah it's pretty funny tbh. That guard is so spiteful.

**Comment by Cuphat** [comment]
> As for this PR, I dunno. I'm not against having a speedup option to skip this initial back and forth in the trade quest, but I don't think that open kak has anything to do with that. You should be able to open the gate with either the letter or the keeton mask (because you can close the gate with keeton mask)

Alright. I was on the practice ROM testing things anyway, so I decided to test the spiteful guard to try to find this flag. It turns out that there is no flag because him closing the gate out of spite isn't permanent - if you reload the area, the gate is opened again.

**Comment by TestRunnerSRL** [comment]
That's interesting, I didn't know that. I'm pretty sure if you give it to him while the gate is closed he does open it. But not I wonder if that once again is only temp and doesn't set the flag?

**Comment by LostThePirate** [comment]
> 
> 
> I don't immediately hate the idea, but I think this requires a bit of open discussion, so I'll probably hold on this until post-5.0

We're very post-5.0 by now, lol.
I'm still in favor of adding this option in, I think it would be a nice speedup that brings back a feature that many miss and gives it some added utility in the form of skipping an otherwise required (tedious) step in the Child Trade Quest.

**Comment by Cuphat** [comment]
> That's interesting, I didn't know that. I'm pretty sure if you give it to him while the gate is closed he does open it. But not I wonder if that once again is only temp and doesn't set the flag?

The flag to open the mask shop is the same as the flag to open the gate though. Not sure what would happen if you just literally were given Keaton Mask instead of Zelda's Letter without the mask shop opening, I assume it wouldn't set the flag and would be temporary, I'd have to check on the practice ROM.

> We're very post-5.0 by now, lol.
> I'm still in favor of adding this option in, I think it would be a nice speedup that brings back a feature that many miss and gives it some added utility in the form of skipping an otherwise required (tedious) step in the Child Trade Quest.

Yeah, I still 100% stand by this PR and hope it is merged soon.

As a side note, it's not in this PR but I feel like this PR should remove the elevation of the Skull Mask hint to always on tournament hint distribution. That's probably a discussion for the next time that tournament hints are fucked with, though.

**Comment by Cuphat** [comment]
This PR is crying in agony. It wants to be merged. 🤔

**Comment by Zannick** [comment]
> I guess technically this could just use the flag and not undo the gate bugfix and be 'Open Mask Shop' instead of 'Open Kakariko' and it'd only open the gate when you got Zelda's Letter. That might confuse people more though I feel like.

I would actually like that better (the closed behavior makes for interesting ER imo), though it would change the setting to multiple-choice to do both. Like 'Kakariko Gate/Mask Shop' with options of 'Vanilla', 'Open', and 'Zelda' (i.e. visiting Zelda opens the Gate).

**Comment by Cuphat** [comment]
> 
> 
> > I guess technically this could just use the flag and not undo the gate bugfix and be 'Open Mask Shop' instead of 'Open Kakariko' and it'd only open the gate when you got Zelda's Letter. That might confuse people more though I feel like.
> 
> I would actually like that better (the closed behavior makes for interesting ER imo), though it would change the setting to multiple-choice to do both. Like 'Kakariko Gate/Mask Shop' with options of 'Vanilla', 'Open', and 'Zelda' (i.e. visiting Zelda opens the Gate).

That's a pretty good idea. I just made this change, tested it, and pushed it.

I also decided to go ahead and toss in the Complete Mask Quest option from my older PR on this subject (#559). All that one does is sets the proper flags to unlock all the masks when the mask shop opens. Since the trade quest rework seems to be in perpetual limbo and it is a simple option to add  with the changes already made to open the mask shop, I think it's a good thing to include for those who want it.

**Comment by AvoryGWAF** [comment]
I think the primary reason I wanted Open Kak Gate is because of Weird Egg Shuffle. I liked having Epona's Song, Talon's Minigame, Zelda's Lullaby, Saria's Song, Skull Kid Piece of Heart, Frogs 2, and Deku Theater upgrades locked behind a certain item I had to find but I hated having to save and quit every time I wanted to go to death mountain as child. This also allowed some checks to be accessible without explosives or access to time travel. Darunia's Joy, Heart Piece above DC, SoS grotto near GC, Goron Shop, Hot Fodder Goron, Chest near GC, a decent chunk of DC, Spinning Pot. 

The Always Open behavior I feel like is great for the scenario of Weird Egg Shuffle. With it opening on Zelda's Letter it seems like just a QoL change. Closed behavior in ER is always a gamble. Sometimes it makes things fun and interesting. Sometimes it's just an inconvenience. The most fun scenarios are when you unlock it having no idea what's on the other side. The worst scenarios force you to save and quit to get back to the other side. 

I really see merits with any of these options. I would love if this got merged.

**Comment by Cuphat** [comment]
I don't fully trust the toolchain I compiled this last rebase with so make sure to recompile it to make sure it's not broken on merge. :)

**Pull request merged**
