### PR TITLE
Add SoA icon to file menu

### PR DESCRIPTION
**Pull request by rlbond86**
This PR adds the SoA icon to the file menu. The Hylian shield and Mirror shield are also shrunk one pixel to fit better.

### CODE REVIEW

**Comment by r0bd0g** [comment]
Ooh nice!
Is that the correct order for card and soa on the quest status screen? I forget which order they come in.
Of course the obvious issue to see is that strength, scale and magic a little lopsided where they are now. I wonder if there's some other information you could fill it with? You could centre them above the songs but then they don't align with the items above, hmm...

**Comment by rlbond86** [comment]
They are in the correct order.

**Comment by rlbond86** [comment]
Here is an alternative format. Poor SoA is a bit lonely (SoA x=6F, y=51, size=0A).
Glide64_THE_LEGEND_OF_ZELDA_03

**Comment by rlbond86** [comment]
Third option (SoA x=4F, y=51, size=09; skull x=5A, y=50, size=0B, dl=0C)
Glide64_THE_LEGEND_OF_ZELDA_04

**Comment by r0bd0g** [comment]
I think it would make sense to put card and soa together and maybe have magic be the lonely one?

**Comment by rlbond86** [comment]
Yeah that really does not look good :/

**Comment by rlbond86** [comment]
I've updated to use Option 2 above, I think that is the smallest change which is probably best at this point.

I also made the shields 1 pixel smaller since they were weirdly big.

Glide64_THE_LEGEND_OF_ZELDA_05

**Comment by r0bd0g** [comment]
Is the gold skulltula token always present? There's a flag actually that gets set the first time you collect a token, that makes the token symbol appear on the quest status. I dunno if it might already do this currently but I'd suggest not having the token symbol appear on file select until you collect 1 token, for consistency with how the quest status screen operates.

**Comment by rlbond86** [comment]
I originally had that but it got changed after some discussion in the discord.

**Comment by rlbond86** [comment]
I can grey it out:

Glide64_THE_LEGEND_OF_ZELDA_06

**Comment by rlbond86** [comment]
Other option is just to do this but I think it might look a bit strange 
Glide64_THE_LEGEND_OF_ZELDA_08

**Comment by Zannick** [comment]
Dimmed with a 0 looks good to me. Thanks!

**Comment by Zannick** [comment]
Is this ready to go?

**Comment by rlbond86** [comment]
Yes, good to go

**Comment by fig02** [comment]
a bit late to the discussion since this is already merged, but imo there is no need to dim the icon at all

**Pull request merged**
