### PR TITLE
Add support for choosing from multiple names for items and locations during hint generation

### PR DESCRIPTION
**Pull request by Zeimyth**
Gossip stone hints have a meaningful impact on randomizer playthroughs. The first time experiencing the hints, it can be a fun puzzle to try to figure out what locations and items are being referred to. However, the more you play, the more the hints might as well just list the vanilla names for the things they talk about.

This PR attempts to add some more variety to the hint system, as well as lay the foundation for more variety to be easily added by others in the future. It does so without destroying any of the existing hints that players are used to (with a few notable exceptions in the commit "Replace some misleading item hint names").

I endeavored to add meaningful new names for most items and a few locations. Additionally, I made some quality of life improvements around the hints list system.

### CODE REVIEW

**Comment by TestRunnerSRL** [comment]
You also changed a lot of line lengths and made some of the location hints longer. Can you verify that they show up in the game okay?

**Comment by Zeimyth** [comment]
I restored the uniqueness hint for the green rupee. I was torn on removing that hint (and the Zora's flippers one, as well) because I understood the intent of them, even if I felt they were a bit misleading, so hopefully this new green rupee hint is a reasonable compromise.

I also removed some of the more flagrant offenders of hints that refer to vanilla item locations. There were a few I didn't remove but that I considered removing, such as:
- mountain clothing/lake clothing
- green girl's tune, child's forest melody
- adult's forest melody
- Jabu Jabu's prize
- every boss' reward
- Dampe's keepsake

Let me know if any of these in particular still feel too much like a reference to the vanilla locations. I'm not very attached to any particular hints; I just wanted to add plenty of new ones to help demonstrate the value of my overall changes. :)

Testing for lines that are too long will be a bit more manual work. At one point while playtesting my changes, I did come across a line that had gotten too long (in particular, an old version of the progressive scale, "vertical swim depth", combined with the Forest Temple floormaster chest hint, "Deep in the forest, shadows guard a&chest containing", caused the last line of text to spill over the bounds of the text box. That's what prompted me to adjust the text wrapping of so many location text boxes to begin with. I will do a more thorough check to make sure that the longest item hints don't overflow when combined with the longest location hints.

**Comment by Zeimyth** [comment]
@TestRunnerSRL All modified location hints have been tested in game. A few felt awkwardly short on some lines, so further adjustments were made. The main issue that caused text to run over was the combination of the gerudo fortress key ("a get out of jail free card") combined with horseback archery ("They say that mastery of horseback&archery grants"). Both of those hints existed before my changes. I modified the horseback archery location hint to resolve this issue. In the future, I would love to design a system to automatically word wrap for all types of hints, like a more intelligent buildHintString(), but that belongs in a different pull request.

**Comment by TestRunnerSRL** [comment]
So one I still have a problem with:
"Jabu Jabu's Prize"for boomerang. Dampe's keepsake I'm also not really a fan on but I'll keep it since it's probably somewhat well known at this point.
"a guaranteed 1/32 chance" for the WINNER HP. The location hint is fine, but this shouldn't be on the HP. I doubt many people even know there is a WINNER HP

**Comment by TestRunnerSRL** [comment]
And yeah having a better hint builder would probably be good. the main thing is I don't really know exactly how the spacing of letters work, since the text is not monospace. You'll need to get some kind of font for oot and then test the width in pixels or something

**Comment by TestRunnerSRL** [comment]
I'm sure there's stuff AA will want to change since he's a lot more attached to the hint than I am. But implementing more hint options like this is something I've always wanted and just never got around to doing. Also I'm not creative with hint texts.

**Pull request merged**
