### PR TITLE
Force patch cosmetics when 'cosmetics_only' is used.

### PR DESCRIPTION
**Pull request by Cuphat**
Fixes cosmetic patching issues with the web version.

### CODE REVIEW

**Comment by TestRunnerSRL** [comment]
hmm, I don't know if this is the issue, and this shouldn't really be the cause of the problem?

**Comment by Cuphat** [comment]
Maybe not? It sounded like a case of music not getting restored properly, which would make sense given that the base ROM already has music restored and thus the cosmetic patch wouldn't include that. If I'm wrong, feel free to toss this in the bin, I just took a guess and went with it.

**Comment by TestRunnerSRL** [comment]
The thing is that the cosmetic patch is based off of the post patched file, not the vanilla. So I wouldn't want to bring something like this in unless I knew it worked. The point of the forced updates is only added because the eng/jpn roms that both are supported but the patchfile doesn't know which one it is. But the cosmetic patches shouldn't have that kind of problem.

**Comment by Cuphat** [comment]
Yeah, I guess I didn't read far enough into `cosmetic_patch` to see what it actually does.

**Pull request closed without merging**
