### PR TITLE
Require bombchus to buy from Carpet Merchant with "Bombchus in Logic" (fixed)

### PR DESCRIPTION
**Pull request by rlbond86**
Redo of #942 that fixes a crash at the Bombchu Bowling Alley.

### CODE REVIEW

**Comment by r0bd0g** [comment]
The logic previously intended the salesman only to be a source of first bombchus, not refills, as purchasing these refills at 200r a pop is too arduous. If he can currently be a refill source in this PR, then this is a logic bug, imo.

**Comment by rlbond86** [comment]
Would it make sense to simply disallow the Carpet Man as a location if `bombchus_in_logic` is True?

**Comment by rlbond86** [comment]
Alternatively it could be removed as a location entirely

**Comment by flagrama** [comment]
I wouldn't necessarily remove it as a location as it's very possible to make him a randomized item in the future.

**Comment by Zannick** [comment]
I don't think it makes sense to completely remove a location no matter how inconvenient it is. I guess I should have asked before, but what's wrong with keeping Carpet Merchant as an initial source of Bombchus (and not refill)? That would mean we don't require bombchus to purchase from him even with bombchus in logic on. (And I'm not very happy with the message he gives you if you don't have Bombchus unlocked in this case.)

If we simply switch him back to providing `Bombchus` (and requiring bombchus) then this will effectively make him never required but still a location.

**Comment by r0bd0g** [comment]
I think making him a source of bombchus but not refills is exactly how it works right now?
Anyway if you want to go forward with this, you can either just make it a redundant bombchu source or make his logic False, and somehow remove it as a location that can appear on the list, for now?

**Comment by Zannick** [comment]
I meant in this PR, if we change him back to provide bombchus.

**Comment by rlbond86** [comment]
There was a discussion of this on Discord, basically it's dumb that it's the one thing that's not randomized. So for Bombchus in Logic at least it makes sense to disallow getting the Bombchu item since it's never random at all.

**Comment by Zannick** [comment]
> So for Bombchus in Logic at least it makes sense to disallow getting the Bombchu item since it's never random at all.

```json
"has_bombchus": "(Buy_Bombchu_5 or Buy_Bombchu_10 or Buy_Bombchu_20 or Bombchu_Drop) and (bombchus_in_logic or Bomb_Bag)",
"found_bombchus": (bombchus_in_logic and (Bombchus or Bombchus_5 or Bombchus_10 or Bombchus_20)) or (not bombchus_in_logic and Bomb_Bag)",
```

Well, `Bombchu_Drop` counts as a Bombchu refill even when chus "aren't" in logic, so this could still require one to take trips to the Carpet to finish MQ dungeons regardless of that setting. I agree that it's silly not to randomize the Merchant, but I think setting up the Merchant logic to make it easier will get us closer to that point.

If the merchant was randomized, what should be the restrictions on purchasing from him? What are the vanilla restrictions? I think `found_bombchus` would make the most sense. And what I meant above, was that by having him logically provide `Bombchus` while requiring `found_bombchus` would keep his location in logic but it would never be progressing logic to buy from him. That state seems to me to be the closest to providing a randomized item for him, at which point that would change.

**Comment by flagrama** [comment]
Vanilla restrictions are "having 200 rupees in your pocket" like it is without this PR.

**Comment by rlbond86** [comment]
Seems unnecessary due to upcoming plans

**Pull request closed without merging**
