### PR TITLE
Fix alpha of dim skulltulla token

### PR DESCRIPTION
**Pull request by rlbond86**
This PR removes the dimming of the skulltulla token with 0 tokens owned.

### CODE REVIEW

**Comment by rlbond86** [comment]
Last one, i promise

**Comment by fig02** [comment]
a good time to bring up, I wasnt able to comment before the last one was merged:
I really dont think that dimming the skulls when you dont have any is even necessary. I understand the intent is because in the pause menu you technically dont get an icon until you have your first one, but in practice it doesnt really mean anything.

It just makes the left hand side of the display look uneven when youre starting with a new file, in my opinion

**Comment by rlbond86** [comment]
I have no strong feelings whatsoever. What do you think @Zannick

**Comment by Zannick** [comment]
I don't care that much, though I agree 'old' is bad.

**Comment by rlbond86** [comment]
Yeah, I guess it's a bit unbalanced with it dimmed. I'll undim since nobody else seems to have an opinion and @fig02 is fairly convincing

**Comment by r0bd0g** [comment]
In that case how about a hack that makes the token always appear in the pause menu even at 0 lol.

**Comment by rlbond86** [comment]
No

**Pull request merged**
