### PR TITLE
[RFC] Bugfix for spirit non-repeatable-access in special interior ER

### PR DESCRIPTION
**Pull request by rattus128**
Pretty complex update for what is ultimately a bug, but after a ton of back and forth with r0b, this is the least impactful logic we could come up with.

Despite its significant complexity, we go to the effort of detecting ammo based non-repeatable-access (or its abscence by getting logic on the ammo refills) as in most seeds, ammo refills are usually available quickly.

The other solution is to require logical access to spirit as both ages, but that is problematic in no-ALR, as it will not be able to place all keys if child spirit is in-accessible. Leave this in as a logical alternative to the ammo option anyway.

Also carve out an exemption if ER (special interiors) is off.

### CODE REVIEW

**Comment by rattus128** [comment]
MQ tomorrow

**Comment by r0bd0g** [comment]
I don't think this will end up merged... There are a couple of minor issues if we do end up deciding to go with a solution like this though? In the end I don't think sticks can actually be used for any NRA that I could think of. Fairies are relevant even if OHKO is off. And Bomb Bag should be sufficient to replace bombchu in all the places that matter. Of course there are other possible NRAs but I think fairy and explosives are the best we could do.

**Comment by Zannick** [comment]
This is heavily outdated at this point, so I'm going to close and ask that you reconstruct the logic changes against current Dev if an issue still exists in this mode today.

**Comment by r0bd0g** [comment]
The issue still exists and I think we've decided the best solution is to hope it doesn't screw anybody over.

**Pull request closed without merging**
