### PR TITLE
Thieves' Hideout entrance shuffle

### PR DESCRIPTION
**Pull request by puddydoo**
Same as my gerudo-fortress fork of dev-r but while in that fork the Thieves' Hideout pool has its own setting, here they are just included with "All Indoors" because the other individual pools don't have settings on this branch. (Excluded from simple indoors because every room has multiple exits)

There is an extra heart piece on the balcony of Gerudo's Fortress as child, but since it is not always accessible, it is not included as a location and is just there.

### CODE REVIEW

**Comment by Hamsda** [comment]
Not a fan of having GF shuffled personally. Especially with random settings, if you happen to get 4 carpenters, that would be a royal pain.

**Comment by Zannick** [comment]
Interesting. Some of dev-r will make it over eventually. I would prefer this be a separate setting of some sort so it's excludable/not a terrible surprise.

**Comment by Roman971** [comment]
Hideout entrances are excluded from ER by design. I don't think having them shuffled is desirable in general, and I know very few people would like it, so if we did add those entrances it would definitely have to be a separate option.

**Comment by puddydoo** [comment]
I agree it should be a separate option so I'm making this a draft until the refactor making the other pools separate options is merged.

**Comment by cjohnson57** [comment]
This branch appears largely out of date. I know there is some interest in this feature, feel free to reopen on a fresh branch!

**Pull request closed without merging**
