### PR TITLE
Extend one-way restriction to hint areas

### PR DESCRIPTION
**Pull request by fenhl**
As a frequently suggested quality-of-life change, this PR changes the restriction for one-way entrances (spawns, warp songs, and owl drops) to be based on the hint area rather than the scene of the target entrance. This fixes issues like one warp song going to Kakariko and another to an interior in Kakariko, or an owl drop going to the Bolero pad with a spawn point in DMC upper.

### CODE REVIEW

**Comment by r0bd0g** [comment]
I'm not sold on this feature. In ALR it means the only warp to crater goes to bolero or the only warp to GY goes the the warp pad. Maybe warps required for reachability reasons should be accepted? but I don't know how to calculate that.

**Review by cjohnson57 — APPROVED** [review]
I'm glad the spoiler lists one-way entrances first as it made checking this a lot easier, lol.

I understand r0b's concerns, but I think the change is overall for the better.

**Comment by r0bd0g** [comment]
Does this PR allow the vanilla layout of Prelude and Adult spawn to the same location? If not then I really suggest that Owls and Spawns need not be included in the restriction.

**Comment by fenhl** [comment]
An issue came up on my branch with high failure rates which I believe is caused by this PR. Marking as draft for now until that's cleared up. A potential fix could be to handle entrances connected to placed one-ways first.

**Comment by cjohnson57** [comment]
How bad does it seem to be? I ran it 10 times manually and got 1 failure, and didn't get any from the fuzzer- I figured this would increase failure rate a bit but it seemed within acceptable limits from my testing, which wasn't that extensive tbf.

**Comment by fenhl** [comment]
All failures all the time on mixed pools is what it currently seems like.

**Comment by cjohnson57** [comment]
Ah, yeah that makes sense if it's an issue for mixed pools.

**Comment by fenhl** [comment]
The latest commit fixes a bug where the entrance currently being connected wasn't being considered for the purpose of the hint area check. On my branch, with the settings on which the high failure rate was discovered, this fix reduced the failure rate from 89/128 to 29/128. I'll apply this PR to Dev-R and get some stats for it as well, including a baseline failure rate.

**Comment by fenhl** [comment]
On Dev-R with similar settings, this feature (including the fix) increased failures from 68/512 to 109/512. Some of that increase is expected simply because the number of valid world layouts is reduced, but I'll try connecting regions with one-ways first to get that number down a bit.

**Comment by r0bd0g** [comment]
I already have a lot of trouble rolling full ER seeds on Dev-R. A few seeds ago I had 4 failures before getting one success, and each gens for over 5 minutes before failing.

**Pull request merged**
