### PR TITLE
Randomize Adult Potion Entrances

### PR DESCRIPTION
**Pull request by rattus128**
commit 5db820068608e1436718c0152c212a1ef19b9716 (HEAD, rattus/adult-potion)
Author: rattus128 <rattus128@gmail.com>
Date:   Thu Jul 18 23:50:21 2019 +1000

    Randomize the Adult potion shop
    
    In all-interiors and above, randomize the adult potion shop.
    
    The carpenter will still block child zoning out, even if child comes
    in the backdoor blind, but blind one-way locks are a part of high level
    ER already (like zoning into a dive tunnel). So keep the vanilla
    behaviour.

commit 493543e5367c376c2db62b18435f46e18f5a46aa
Author: rattus128 <rattus128@gmail.com>
Date:   Thu Jul 18 23:47:03 2019 +1000

    Add logic for Adult Potion shop ER
    
    Define the Kakariko backyard as a seperate region, and move the potion
    back-door, grotto and grannys potion shop there.
    
    Access the backyard via the rooftops requires the man_on_roof trick.
    Child can chicken in during the day and adult can use a hookshot.
    
    This also fixes a logic bug where child had access to the back grotto
    without a daytime check (chicken is needed!).

commit 527c16d7b59a80ed2d3a6c6244b5ea4492e05f43
Author: rattus128 <rattus128@gmail.com>
Date:   Thu Jul 18 23:52:10 2019 +1000

    Make interior entrance placement restrictions data driven
    
    This idea that some entrances need to be specifically restricted is
    general enough that it should be data driven to easily add more.
    Useful for the adult potion shop.
    
    It took some squinting to figure out how this implements restrictions
    on cutthroughs, so add a wall-of-text explaining what's going on.

### CODE REVIEW

**Comment by Hamsda** [comment]
So what region would a hint belong to for an item in the Kak potion shop if say the front is in Kak but the back is in Kokiri Forest?

**Comment by r0bd0g** [comment]
I have no idea how ER works I guess, lol. Does windmill entrance really need to be accessible as both ages? Adult could cut through dampe's grave to get there... I guess the idea is to stop something like, exiting windmill as adult and spawning in the back alley...?

Adult shouldn't need man on roof to get back there without hookshot, IMO. You can jump from the fence by the windmill entrance and grab the fence by the hag potion shop. I don't think this jump is obscure like jumping from the watchtower or jumping onto the potion shop roof. Even if you think the jump is hard for some reason, Hover Boots would make it easy.

**Comment by TestRunnerSRL** [comment]
The hint issue is somewhat problematic. I'm still unsure how to best handle it. I think the best workaround I can think of is that shop region is not considered for any hints except for barren, in which case both entrances would count. This way if you got something woth, there would be at least 1 major item not in the shop still which you should check (woth does not imply there is only 1), and barren would ensure that both connected areas would have anything good in a subarea. That being said this is still kinda hacky and I'm not sure this is the best approach. Another idea is to just consider the potion shop it's own major area and have it's own hint, but I don't think that really fixes the problem either

**Comment by r0bd0g** [comment]
The easy way out is to consider the shop only from the front entrance. Similar to windmill/dampe's grave, except you don't have to walk quite as far to get from the back entrance to the front entrance's checks >_>.

**Comment by BeeLuigi** [comment]
Weird suggestion: shuffle it but connect both sides to the same area. That would limit it to areas that have 2+ interiors though. And you'd have to make sure to place it early enough that it's still possible.

**Comment by Zannick** [comment]
I think "front entrance only" makes sense for hint purposes, and we could separate the hints for Dampe's Grave and Windmill in such a case. Probably the best way to do that is to add a json field that indicates the exit to consider as the "front door" for hints (or just use only the first exit... but that's dangerous).

**Comment by rattus128** [comment]
@r0bd0g . Fence jump put in default logic.

**Comment by rattus128** [comment]
So to resolve the hints issue, i have settled on the solution where placement of the two doors is restricted to the same hint region. There are many good reasons to do it this way for 5.0.

1: The hints problem. There is no ambiguity.

2: Minimizes OW structural impact. From some dev-public-talk discussions on this and in discussion with what to do with gerudo fortress interior ER, it was mentioned that the goal of ER at all levels is to not change the structure of the overworld. Link should simply not have access to interior cut-throughs to get around the overworld. If this is to happen, it should happen at a higher level of ER above OW ER. The windmill and spirit temple cutthrough do set a precendent here, but they are Vanilla anomolies in their own right. The potion shop less so (see point 4).

3: Avoids ToD overworld access. This is technically not an issue, but worth mentioning anyway. Currently the logic guarantees time-of-day flow to all areas of the overworld. This would be revoked with an overworld cutthrough from door-to-door. The logic does support this, however this would be a major unprecedented opening of new logic so close to 5.0 release.

4: Forwards consistency with Gerudo Fortress ER. There is an argument to use the front door as the hints definition for Adult Potion Shop. This can not be said of Gerudo Fortress ER, where there isn't any clear notion of a front door for the carpenter jails. So avoid creating a precedent that would be difficult to follow. Gerudo fortress ER could similarly be restricted to have its cutthroughs localized to avoid the GF "hub" problem similarly mentioned in dev-public-talk

**Comment by Roman971** [comment]
I think this is a good compromise for now. I just want to mention I personally never considered it a bad thing for ER to have connectors like this that can change the structure of the overworld. We already have some and they are interesting in their own way. The real issue is with the gerudo fortress hideout which is kind of a dungeon, and while it could be interesting to shuffle it around, it would really have to be another level of interior ER, not force included in the currently available settings.

Also a few minor things with the current changes:
1. I don't think we need the rooftop region anymore. It looks like the only way it serves a purpose right now is for child access to the backyard at night but I still don't think binding the "man on roof" logic trick to that access is a good thing, nor is it even relevant with the current ER settings.
2. In my opinion, the "Kakariko Backyard" region should be called "Kakariko Village Backyard" instead to make it clearer and better sorted in spoilers.
3. Do we really need to mention in the ER tooltip that both entrances to the potion shop are placed in the same hint area? I feel like users don't need to know that, it won't give them any information, and that tooltip is already long enough so we should only add really meaningful stuff to it.

**Comment by rattus128** [comment]
Thanks, all changes below made.

> I think this is a good compromise for now. I just want to mention I personally never considered it a bad thing for ER to have connectors like this that can change the structure of the overworld. We already have some and they are interesting in their own way. The real issue is with the gerudo fortress hideout which is kind of a dungeon, and while it could be interesting to shuffle it around, it would really have to be another level of interior ER, not force included in the currently available settings.
> 
> Also a few minor things with the current changes:
> 
>     1. I don't think we need the rooftop region anymore. It looks like the only way it serves a purpose right now is for child access to the backyard at night but I still don't think binding the "man on roof" logic trick to that access is a good thing, nor is it even relevant with the current ER settings.
> 
>     2. In my opinion, the "Kakariko Backyard" region should be called "Kakariko Village Backyard" instead to make it clearer and better sorted in spoilers.
> 
>     3. Do we really need to mention in the ER tooltip that both entrances to the potion shop are placed in the same hint area? I feel like users don't need to know that, it won't give them any information, and that tooltip is already long enough so we should only add really meaningful stuff to it.

**Comment by r0bd0g** [comment]
Why is getting back there at child night not relevant? And if it's not, why check at day?

**Comment by Roman971** [comment]
We don't technically need to check for at day either currently. Basically there are no restrictions at day in the overworld, and child doesn't have any indoor connectors which could be day only, so if child has access to Kakariko Village, then it has access to it at day as well.
Also, being able to get back there at night is never useful because there is nothing that could be night only back there for child, since child doesn't have any connectors and there is nothing restricted to night inside grottos/interiors.
That's why the logic for getting to the back was "True" until this.

But this is only true for the current ER settings. If we started shuffling things with slightly different options, the day/night difference could become relevant. So I think we should try to reach and maintain an accurate ToD logic even if some of the checks are **currently** irrelevant.

If you want we can already reword the "man on roof" trick to something that encapsulates getting to the back at night for child, or add a new trick, but I think it's fine (and probably better) to keep that kind of changes for the day getting there at night as child actually becomes relevant.

**Comment by r0bd0g** [comment]
I agree that we should keep tod logic accurate even if it doesn't matter. But I think for as long as it doesn't matter I would just silently use the manonroof and not bother rewording it for now.

**Comment by rattus128** [comment]
What happens if dampes grave is on the Kak backyard grotto, can the cutthrough create a day-only overworld situation for child? @Roman971

**Comment by rattus128** [comment]
I have gone back to man-on-roof logic but havent changed tooltips etc.

**Comment by r0bd0g** [comment]
Child can't cut the whole way through dampe's?

**Comment by rattus128** [comment]
Height?

**Comment by r0bd0g** [comment]
I haven't personally tried it but I remember being told child was too short.

**Comment by rattus128** [comment]
Ok that all adds up to Romans conclusion. This will future proof the logic
while we get to go to 5.0 with no ToD OW.

No further update needed.

**Pull request merged**
