### PR TITLE
moved the gossip stone in lake hylia over out of the way

### PR DESCRIPTION
**Pull request by dotzo**
image

### CODE REVIEW

**Comment by TestRunnerSRL** [comment]
I had kinda intentionally moved it it right above the WT entrance, but I don't really have a problem with it being moved. I don't really like how far over it is. Can it be moved to the right more to where that corner is?

**Comment by dotzo** [comment]
How about over here?  The corner just to the right of the bridge is commonly used for a wess setup.
image

**Comment by TestRunnerSRL** [comment]
Yeah that's good

**Comment by Nicholas-Steel** [comment]
Just have it teleport to different spots on the island depending on the time of day when you load in to Lake Hylia? It can be the Wandering Gossiper.

**Pull request merged**
