### PR TITLE
Add CI checks to ensure presets are sorted and no settings are missing

### PR DESCRIPTION
**Pull request by fenhl**
Follow-up to #1861. Having `presets_default.json` in a normalized format like this will make it easier to diff, including across forks, and will ensure PRs of new settings will set appropriate values in Easy Mode and Hell Mode. I've filled in the settings that were missing with their defaults, except for a couple cases in Easy Mode and Hell Mode.

### CODE REVIEW

**Comment by cjohnson57** [comment]
Is this something that can be fixed automatically using the `--fix` flag?

**Comment by fenhl** [comment]
No, because I want `--fix` to be noninteractive and I think contributors adding new settings should consider what's appropriate for each preset (especially Easy Mode and Hell Mode) rather than just using the default everywhere.

**Comment by cjohnson57** [comment]
I don't see an error message for the settings being unsorted, it feels like it'd be hard for someone adding a preset to know what they did wrong and be able to fix it

**Comment by fenhl** [comment]
It currently just says “presets not formatted correctly”. I guess that check could be done twice, once before sorting the reference and again after sorting, with the second error message being “presets not sorted” and auto-fixable.

**Comment by cjohnson57** [comment]
Yeah, I just feel like putting the burden of sorting all of our 900 settings on the preset maker by themselves is a bit much

**Review by cjohnson57 — APPROVED** [review]

**Pull request merged**
