### PR TITLE
Add soft resets (now fully resets the system)

### PR DESCRIPTION
**Pull request by louist103**
Same as the last time I did this but now it fully resets the game.  On WiiVC it resets the emulator and on n64 (and emulators) it acts like the reset button was pressed.  
Something important is that the website will need to be updated to be able to inject Homeboy into the WAD.
The readme might need an update as well for this for people who generate a ROM offline.

### CODE REVIEW

**Comment by TreZc0** [comment]
Since this is requiring massive changes to the website infrastructure and would render gzinject useless (as far as i understand?), this needs to be talked about internally.

**Comment by TreZc0** [comment]
Besides, injecting homeboy with its massive feature set and potential on its own is a very impactful decision, so it will have to be evaluated individually.

**Comment by dragonbane0** [comment]
This needs to be evaluated and discussed indeed. Outside of that, you seemingly included some release files in this PR, like the readme and version.py from the 6.0.0 release.

**Comment by Zannick** [comment]
This branch may be based on 6.0? We can figure out how to rebase it.

**Comment by flagrama** [comment]
Based on conversation in the gz Discord, this may also be doing a hack to work around a Dolphin bug that happens on resets. You should not add workarounds for emulator bugs, that's how you eventually end up with emulator-only issues, or something breaking on an emulator update in the future. [I have added the known workaround for the bug to the wiki](https://wiki.ootrandomizer.com/index.php?title=Dolphin#GFX_FIFO_Unknown_Opcode_on_Resetting).

This would likely also need its own specific gz patch. The homeboy patches will use IOS60 instead of IOS9 which is significantly faster for loading and resetting the ROM, along with other things that are needed for gz, but may not be needed for rando.

**Comment by cjohnson57** [comment]
Looks like this PR was never given proper consideration. @louist103 if you're still interested and update it to latest, I could try to call together some discussion about it and get some testing done.

**Comment by louist103** [comment]
> Looks like this PR was never given proper consideration. @louist103 if you're still interested and update it to latest, I could try to call together some discussion about it and get some testing done.

I would update it.  I just need to find the homeboy code I edited.

**Comment by dragonbane0** [comment]
Injecting Homeboy into rando is probably not something that will happen at this point. For a different rando project I am however developing an WiiVC inject that will go live in the coming weeks. It seems like a good idea to me to implement your hook into that, so I will keep this in mind

**Comment by louist103** [comment]
> Injecting Homeboy into rando is probably not something that will happen at this point. For a different rando project I am however developing an WiiVC inject that will go live in the coming weeks. It seems like a good idea to me to implement your hook into that, so I will keep this in mind

Well homeboy isn't injected into the rom.  Its only injected into the `WAD` if VC is used.

**Comment by dragonbane0** [comment]
Yeah that's what I'm referring to

**Comment by cjohnson57** [comment]
Sounds like this should be closed then, but hopefully it makes it into db0's project as I'd still like to see this.

**Comment by dragonbane0** [comment]
Your call, I definetly want to implement this, so I would like to keep it open as a reminder. But either way works for me

**Pull request closed without merging**
