### PR TITLE
Implement Sandstorm Transition Patch

### PR DESCRIPTION
**Pull request by mzxrules**
I imported the sandstorm transition fix I wrote for Beta Quest like two years ago. The way it works is like so:

It tests if the game is attempting to run transitions 0x0E or 0x0F
If so, it checks to see if gameplay_field_keep is loaded.
If gameplay_keep is loaded, then the transition effect is unchanged. Otherwise, transition effect 4 is used as a replacement.
In order to fit these changes within the space of the original function, I overwrite part of case 0

I've only done minimal testing of this patch, and it seems to work as expected, but I'd like to see more people test this to verify it works OK.

### CODE REVIEW

**Comment by ETR-BTF** [comment]
I've tested this fix for market -> wasteland transitions and back on
- pj64 v2.4+ (GlideN64)
- pj64 v2.4+ (paraLLEl)
- dolphin v5.0-14095
- wii vc
and on all platforms there were no issues other than the fade out to black of the transitions to wasteland being much faster than other fade outs. Dusk said they'd test Everdrive/N64 and Bizhawk when they wake up.

I was unable to test the other transitions (exiting windmill (#1158), exiting dampe's grave and exiting fire temple (#915)) because those require ER features currently exclusive to Roman's fork and I don't know how to rebuild with armips. However, if others were to provide a patch file I'd be happy to test those transitions as well.

**Review by Zannick — APPROVED** [review]

**Comment by Roman971** [comment]
We should probably still look into fixing the issue without disabling the transition once environment stuff is decompiled and/or documented, but if this works as intended it should be fine as a temporary workaround. (And on a slightly related note, we should also look into fixing fog glitches without disabling the fog state changes entirely)

**Comment by ETR-BTF** [comment]
I was able to test the other transitions using a patch file made by mracsys on the same platforms (except vc) and no issues there either. Everdrive and vc were tested by mracsys. 

What I said about faster fade outs is most likely just vanilla behavior. I never realized that the wasteland transitions are slightly faster and grotto transitions slightly slower than "normal" loading zone transitions.

**Comment by mzxrules** [comment]
> We should probably still look into fixing the issue without disabling the transition once environment stuff is decompiled and/or documented, but if this works as intended it should be fine as a temporary workaround. (And on a slightly related note, we should also look into fixing fog glitches without disabling the fog state changes entirely)

The transition isn't disabled, non-entrance shuffled rando should play the same animations as vanilla. It only affects entrance rando, and only marginally. The "proper" fix for rando would be to extract the textures/dlists? from gameplay_field_keep and store them either in the payload or gameplay_keep, but I don't think the effort is really worth it when the problem only affects entrance rando, where players expect scene links to be inconsistent.

**Pull request merged**
