### PR TITLE
Adding 'Random Choice' Option for various settings.

### PR DESCRIPTION
**Pull request by Blueteeth0711**
These settings include Gossip Stones, Hint Distribution, Damage Multiplier, Item Pool, and Ice Traps.

### CODE REVIEW

**Comment by r0bd0g** [comment]
How does this PR handle Multiworld? I think random choice previously would result in different settings across all worlds (everyone with a different number of trials, for example). But if your PR actually does that, I worry some combinations of settings might not actually be compatible.

**Comment by Blueteeth0711** [comment]
Hmmm good call out on the multiworld.  I did not test this only single player.  I will try it out.  Ideally do we want each player to have different random choices or the same?

**Comment by r0bd0g** [comment]
I would expect random choice to vary across the world the same way that other random choice settings do (I think they do do that, right?). But again if this is extended to more options there are definitely some things that aren't going to work.

**Comment by Zannick** [comment]
I was pretty confident that randomized settings are resolved before performing world setup, so all worlds have the same random settings, but let's double-check and test more to be certain?

**Review by Zannick — APPROVED** [review]

**Comment by r0bd0g** [comment]
Alright so, we've just realized that randomized settings are supposed to be different between world in MW, and somehow this regressed and we thought it was the intended behaviour.

**Comment by Blueteeth0711** [comment]
Hey sorry life became busy and I haven't been able to look at this.    Sounds like right now there is a regression that prevents me from actually testing this correctly?  Should I wait before messing with this more?

**Comment by r0bd0g** [comment]
Yeah hopefully randomized settings will be fixed soon-ish to allow MW to have different starting age, numbers of trials, etc.

**Comment by cjohnson57** [comment]
Hey! This PR looks pretty simple, and seems to have just fallen through the cracks (partially due to #1392). If you update it to work on latest, I'd be happy to review it!

**Comment by cjohnson57** [comment]
Since the author hasn't expressed interest in updating it I'll close this for now

**Pull request closed without merging**
