### PR TITLE
Grammatical error and consistency fixes

### PR DESCRIPTION
**Pull request by Mast3rGenius**
Fixed some grammatical errors and made it more consistent.

### CODE REVIEW

**Comment by flagrama** [comment]
Do you have a wiki account? The [4.0 changelog there](https://wiki.ootrandomizer.com/index.php?title=Changelog) should match whatever is here.

You are inconsistent with the use of the accented e for Dampe, but I think it should be avoided just so it is easy for people to Ctrl+F to it if they need to find it quickly.

Also technically full sentences in bulleted lists should end in a period.

**Comment by Mast3rGenius** [comment]
> Do you have a wiki account? The [4.0 changelog there](https://wiki.ootrandomizer.com/index.php?title=Changelog) should match whatever is here.
> 
> You are inconsistent with the use of the accented e for Dampe, but I think it should be avoided just so it is easy for people to Ctrl+F to it if they need to find it quickly.
> 
> Also technically full sentences in bulleted lists should end in a period.

1. I don't have a wiki account
2. I will fix the inconsistencies
3. Ctrl+F doesn't account for accents
4. I will fix the full sentences in bulleted lists too. I wanted to do the basics and clean up later.

**Comment by flagrama** [comment]
I disagree. Whatever you are using Ctrl+F in may do that, that's not how the firefox browser works at least. These changelogs are primarily viewed by users in browser.

image

**Comment by Mast3rGenius** [comment]
> I disagree. Whatever you are using Ctrl+F in may do that, that's not how the firefox browser works at least. These changelogs are primarily viewed by users in browser.
I'm pretty sure most people use chrome over firefox.

**Comment by Mast3rGenius** [comment]
> > I disagree. Whatever you are using Ctrl+F in may do that, that's not how the firefox browser works at least. These changelogs are primarily viewed by users in browser.
> 
> I'm pretty sure most people use chrome over firefox.

**Comment by flagrama** [comment]
Doesn't matter what most people use. It should be consistent between browsers if the whole point of the change is to be more consistent :P

**Comment by Mast3rGenius** [comment]
Not the whole point, I fixed incorrect info and misspellings. I focused mainly on the 5.0 changelog which is what I meant as basics and ripped out periods to prepare for the 4.0 fixes.

**Comment by Mast3rGenius** [comment]
This should be ready, but Dampe still has an accented e if you want to change that back.

**Comment by TestRunnerSRL** [comment]
While I think compatibility across browsers is important, people probably will just search for `damp` anyways. So I don't really have a strong feeling about this one way or the other. One is spelled correct, but one is what people would actually search for.

**Pull request merged**
