### PR TITLE
Update Changelog

### PR DESCRIPTION
**Pull request by LostThePirate**
Updated the Changelog section of the Readme to include additions/changes through 4.15.6. Rearranged much of the changelog to place like info with other like info; grouped similar changes together under new headers in New Features; added Updated Options section to distinguish from New Options.
Additional revisions will surely be needed before 5.0 (as well as fixing my inevitable typos), but hopefully this will be less daunting to others to take on from here.

### CODE REVIEW

**Comment by LostThePirate** [comment]
Looked back over it; fixed a typo and added two lines I missed.

**Comment by Nicholas-Steel** [comment]
Could you maybe include some more examples of problems with using PJ64? The Kakariko Bazaar crashes if you enter it as an adult I think? Something about going from Death Mountain Trail to Kakariko at night time can also cause a crash? Maybe ask on Discord for greater clarification of the crashes.

**Comment by LostThePirate** [comment]
1- What does PJ64 crashes have to do with the changelog?
2- Someone else can change documentation for that, as my goal was to only update the changelog section itself.
3- Whoops, an actual typo.
4- It's new, so it gets a mention in New Features. Can be elaborated on in New Options I guess?
5- As of 4.15.6, no, isn't merged and so wasn't included.
6- Whatever, nobody likes any proposed phrasing this, so I don't really care.

**Comment by flagrama** [comment]
Maybe mention which cutscenes are restored with the Useful Cutscenes setting?

As for the fishing thing, even though it is outside scope of what you intended here, I still don't think anybody has verified that the bizhawk bug does not exist with the new changes, so there's no way to even know if it should be removed now or not.

**Comment by Nicholas-Steel** [comment]
1) was more to do with the readme section just above the change log.

**Comment by LostThePirate** [comment]
Ok, a few minor fixes there.

**Comment by Cuphat** [comment]
"Dungeons Onlys" sticks out at me and has been bugging me for a while, shouldn't it be "Dungeons Only"?

**Comment by Roman971** [comment]
Still not a fan of how the whole ER stuff is described now. It no longer mentions which pools are randomized, and there are some descriptions like the one for "All Indoors & Overworld" that don't really describe what it does.
Describing new settings by listing their options works decently in most cases but ER is more complicated than most settings so it doesn't really fit there imo.
Anyway, if we are going to go by options listing, it would probably be better to use wordings close to the actual option descriptions found in the GUI so they match and players already know what they are looking at when they use the UI. The current GUI options may not be the best either though but my point is they should somewhat match and we can improve them at the same time if needed.

On another topic, I don't think gerudo guards were actually changed to prevent softlocks. If you get caught by a gerudo guard as child in non-ER, there is still a possibility for the game to softlock if you have a hookshot. Overworld ER handles that case since in that mode you can end up getting caught by gerudo guards without using glitches, but I think the vanilla behavior is still in effect otherwise.

Also, this is pretty minor but the fact that great fairies now properly refill your health and magic on the first visit might be worth mentioning in "Bug Fixes".

**Comment by TestRunnerSRL** [comment]
I don't think the changelog should describe the entire spec of how ever feature works. The purpose of the changelog is to describe briefly all the new changes. If people want more info, they can check out more info on the wiki/gui or whatever. I don't really find the details about pooling to be important for most people getting started or just having the general understanding of what the mode is. I also don't think it really makes much sense to have them match only to change later, since the 5.0 changelog is not changing later.

I think you're mistaking that "softlock" commit with something else. That's been around for a long time and was one of the early changed in 5.0. Basically involves backflipping while getting caught and the guards can't catch up to you anymore and the game softlocks. Also the whole getting caught by the guards with the hookshot is not a softlock because you can always savewarp out.

**Pull request merged**
