### PR TITLE
Add filter dropdown for excluded locations

### PR DESCRIPTION
**Pull request by rlbond86**
also fixed error where Phantom Ganon was hinted to be in the Shadow Temple

### CODE REVIEW

**Comment by r0bd0g** [comment]
Luckily I don't think anything actually uses the boss location hint texts.

**Comment by TestRunnerSRL** [comment]
Not going to add this to 4.0 since this is too significant of a gui change

**Comment by rlbond86** [comment]
From the user's POV it's just one text box but it is a decent amount of new code. I just personally find the enormous list of locations difficult to navigate and tried to improve it.

**Comment by TestRunnerSRL** [comment]
Yeah I get that, it's just that I don't want the webdevs to try to implement this now

**Comment by rlbond86** [comment]
seems logical

**Comment by TestRunnerSRL** [comment]
Rebased and merged

**Pull request closed without merging**
