### PR TITLE
Several minor fixes

### PR DESCRIPTION
**Pull request by ETR-BTF**
- Fixed inconsistency with ruto's/rutos letter
- Shortened a hint that was unintentionally made overly descriptive
- Changed the names and descriptions of (MQ) Shadow lens tricks to be less ambiguous

Unit tests passed.

### CODE REVIEW

**Comment by flagrama** [comment]
I think you also need to change all of the presets that use those tricks.

**Comment by Roman971** [comment]
`"Market Market Dog Lady"` still needs to be fixed btw.

**Comment by Roman971** [comment]
And #1050 should probably also be addressed with those fixes.

**Comment by ETR-BTF** [comment]
Thank you.

**Comment by r0bd0g** [comment]
It's "House of Skulltula", not plural.

**Comment by ETR-BTF** [comment]
There you go, r0bd0g.

**Comment by r0bd0g** [comment]
Alright, lol.
One of these days I'll convince somebody to remove the s on Gerudo Training Grounds as well or maybe that one's a lost cause.

**Pull request merged**
