### PR TITLE
Decompressor source update

### PR DESCRIPTION
**Pull request by CMuncey**
Added source code for decompressor
Recompiled on all platforms to make executable match source code

Still needs ARM64 version. I don't have a compiler which can compile for it nor a computer which can test it.

Tested on all platforms. Seems to work as intended, but should be tested more before merging. To do so, copy/paste the executables for your operating system, remove ZOOTDEC.z64 from rando folder, then create a seed. For Windows testing, please copy/paste both executables as your python version may not match your operating system version (32 vs 64 bit).

### CODE REVIEW

**Comment by Zannick** [comment]
Thanks! We should dredge up a way to compile+test for ARM64, at least for devs.

**Comment by flagrama** [comment]
Can probably figure out a way to use a cross-compiler much like we do with MIPS. Hopefully a lot less complicated than setting everything up to work with an n64 console too.

**Comment by CMuncey** [comment]
I can probably do it on my phone. I'll look into it tomorrow, I'm somewhat busy tonight

**Comment by Zannick** [comment]
Thanks!

**Pull request merged**
