### PR TITLE
Fix broken formatting of excluded locations tag system & a moderate rework of existing tags

### LINKED ISSUE #1801: Exclude Locations tags improperly formatted
Many of them don't have trailing commas. This causes the tag list to include a lot of single characters.

### PR DESCRIPTION
**Pull request by ETR-BTF**
This PR fixes #1801 (fix by @damdayou) and cleans up some of the existing locations and tricks tag while also adding many new ones. The tags are now also mutually consistent in their names. Unit tests passed.

~~Turns out the issue was indeed the lack of trailing commas. Opening as a draft initially because I want to add and change some tags while I'm at it. The PR also fixes white space issues in a couple of places.~~

Before:
image
image

After: 
image

### CODE REVIEW

**Comment by r0bd0g** [comment]
Some things I noticed as I glanced:
- GC Pot Freestanding PoH lists Goron City twice.
- Frog Ocarina Game is the only frog check lacking the 'minigames' tag.
- Some two-word tags shouldn't be combined into one word. (Examples include RupeeTower, FlyingPot, and SmallCrate.)

I think the comma only mattered if there was only one tag. If you check one of the busted tags you should see all the locations listed have only the one.

**Comment by ETR-BTF** [comment]
> Some things I noticed as I glanced:
> 
> * GC Pot Freestanding PoH lists Goron City twice.
> * Frog Ocarina Game is the only frog check lacking the 'minigames' tag.
> * Some two-word tags shouldn't be combined into one word. (Examples include RupeeTower, FlyingPot, and SmallCrate.)

Fixed in the latest commit.

How do people feel about adding tags for the jail keys and boss heart containers? Pretty much every other location has a tag for the source of the item (chest, freestanding, pot, npc, etc.) but those are lacking such tags.

**Comment by ETR-BTF** [comment]
Thoughts on adding age tags? Child/Adult/Both Ages?

Edit: I guess "Both Ages" would be pointless as it's identical to "All" lol.

**Comment by ETR-BTF** [comment]
I wanted to add age tags for locations too, but the problem is that both glitchless and glitch logic use the same tags but the age requirements differ between logic setting. I could make separate tags for both logic settings, or I could just abandon the idea. It was also suggested to add tricks tags for the items that you're skipping or using with the trick, but I'm not sure how useful that would be and it might just bloat the list of tags. I also don't see the value of the existing "Skulltula House" tag for locations.

**Comment by damdayou** [comment]
Following discussion on dev-public-talk, a simple change preventing future such mistakes would be to replace
```
        if filter_tags is None:
            self.filter_tags = None
        else:
            self.filter_tags = list(filter_tags)
```
with
```
         if filter_tags is None:
            self.filter_tags = None
        elif isinstance(filter_tags, str):
            self.filter_tags = [filter_tags]
        else:
            self.filter_tags = list(filter_tags)
```
in Location.py on line 32. With this change, final commas in tag lists are not needed anymore (they are optional). I can submit an independent PR if needed.

**Comment by r0bd0g** [comment]
Maybe you're going a little too ham lol.
I'm not gonna verify the tags on all these tricks are still correct so hopefully they are.

**Comment by ETR-BTF** [comment]
@damdayou that works, thank you! I'll include it in this PR.

**Comment by ETR-BTF** [comment]
> Maybe you're going a little too ham lol. I'm not gonna verify the tags on all these tricks are still correct so hopefully they are.

Most tricks mention for what ages they're relevant, and for many others it's obvious based on whether Link can even get there as the other age. There were a couple where I wasn't sure, but you answered my questions in Discord. I believe that the tags are mostly correct. If not, we have plenty of time to find out before the next release.

**Comment by ETR-BTF** [comment]
There are many more tags that could be added still, but I'll leave things here for now.

**Comment by r0bd0g** [comment]
I mean for example, quick glance, the Spirit Lobby jump is not a child trick. (I mean very peripherally it can logically open things up for child because you would have to find less adult items before we can require you to Boomerang the skull with only 1 key, perhaps that's where the confusion comes from?, but you don't actually perform the trick as child.)

(I think the UI bug caused by the improper formatting on the tags is a solid candidate for 7.0.1, so perhaps there's not as much time as you might think, and maybe why this PR goes a little farther than necessary right now.)

**Comment by ETR-BTF** [comment]
I'll take another look at the Spirit trick tomorrow.

Ah, I was not expecting this to be considered for a 7.0.1 hotfix. If that is the case, then feel free to merge just the commit that adds damdayou's fix and I'll redo the rest of this PR after, or I can create a separate PR for the fix (whichever is preferred).

**Pull request merged**
