### PR TITLE
Add cosmetic option to disable dpad dungeon info

### PR DESCRIPTION
**Pull request by mracsys**
image

Adds a cosmetics toggle to disable the dpad dungeon info menus, including on patches with the menus enabled. This makes pause buffering equip boots inputs while on the item screen easier. It's already possible to do in the brief window between unpausing and gameplay resuming, but can be precise as mashing will continue to equip/unequip during this window.

If accepted, the feature should be revisited once either mixed pools bosses or boss reward shuffle are merged.

I couldn't make sense of the cosmetic version number. I incremented by one instead.

Tested on patch files from this feature branch, 6.2 stable (web), and 6.2.218 dev (web). It only affects patch files generated from this branch as expected with no regressions that I could see on other versions.

### CODE REVIEW

**Comment by r0bd0g** [comment]
I don't think this counts as cosmetic. It changes what your inputs do in some cases. Cosmetic options should only be for things that don't impact what players are able to do.

Can you patch on this branch in order to remove the dpad menus from current dev seeds? If so it's kind of a problem; I can't imagine that would be race legal, and it could be tricky to spot it happening if people do this without realizing they shouldn't.

If this option is really going to be accepted, the dpad menus should just be removed imo. They're not worth breaking the ideal of cosmetic options have no gameplay impact.

**Comment by mracsys** [comment]
> Can you patch on this branch in order to remove the dpad menus from current dev seeds? If so it's kind of a problem; I can't imagine that would be race legal, and it could be tricky to spot it happening if people do this without realizing they shouldn't.

No, I checked before making this public.

**Comment by cjohnson57** [comment]
We actually discussed this in a dev chat the other day so I'm going to be rehashing some points from that conversation.

I think this is a bit silly still. In most cases, you can just unpause and then use the d pad for boots. If you're buffering a hover boots equip, you can still use the d pad if you go to any other menu, losing you maybe a second. In an average glitched seed, how many times do you buffer a hovers equip? (Not asking that rhetorically, I'm actually unsure) But I can't imagine it's more than like... 10. So you lose maybe 10 seconds in a glitched seed. Given that I really don't see this as necessary and this is an option I could see being confusing to a newcomer, so I'm feeling lukewarm about adding it.

However, I wouldn't consider this in its current state at all since it completely removes access to those menus. Some alternatives we discussed previously were:

* Still having access to the new menus when using A + Dpad
* Being able to cycle through menus while holding A using Z/R

I would also ask the description to be changed, saying a summary menu can be accessed by holding A since it does not display the same information as the submenus.

**Comment by TreZc0** [comment]
I think it's good to add this as a merely cosmetical toggle.
However, yes, we probably need to add an alternative to access the menus if this option is disabled - so imo, adding the "having to press A" to use the d-pad menus when this setting is disabled is the way to go.

**Comment by r0bd0g** [comment]
Whatever alternative you come up with, it should just be how it always works. I don't like the cosmetic option affecting gameplay, and I don't think we should maintain two different ways of opening the menus.

**Comment by cjohnson57** [comment]
> Whatever alternative you come up with, it should just be how it always works. I don't like the cosmetic option affecting gameplay

I do get this but it's such a minute difference I think it's acceptable

> and I don't think we should maintain two different ways of opening the menus.

I agree with that but the masses have dictated it

**Review by cjohnson57 — APPROVED** [review]

**Pull request merged**
