### PR TITLE
trick-ify goron city pot with flower

### PR DESCRIPTION
**Pull request by dotzo**
People have been asking for this for potential removal from weekly settings.  Also aligns this with using a flower in DMT as both being a trick.

### CODE REVIEW

**Comment by r0bd0g** [comment]
Why the bottom of the list man...

**Comment by r0bd0g** [comment]
The actual hardest thing that's in default logic with just strength btw is throwing the bomb flower at the soil gs in DMT.

**Comment by r0bd0g** [comment]
This is not a trick though so I don't understand why we need a trick for it.

**Comment by flagrama** [comment]
Counter argument: If you throw a bomb in and get neutral face nothing at all comes out if you don't have a bomb bag. It being a situation the game doesn't account for (it doesn't even give rupees, just absolutely nothing) is enough for me to consider it potentially a trick honestly.

**Comment by r0bd0g** [comment]
Wouldn't them not accounting for it be bomb drops coming out?

**Comment by r0bd0g** [comment]
Anyway if something must be changed I would prefer it to be that it always works the first time you throw a bomb in. But ofc that would be much harder to implement.

**Comment by Zannick** [comment]
I don't know what the threshold is for something to be a trick. Needing a gif for "how to do it consistently" seems like a good argument in favor of it being a trick, especially since it looks like a setup is involved.

FWIW I've never realized GS Mountain Trail Bean Patch could require Strength as an option to kill. It's probably very rare that that arises in practice. Is that difficult to do? I might be similarly in favor of that being a trick. (Oh dear, that will make two tricks on the same GS.)

**Comment by r0bd0g** [comment]
I don't know if DMT soil GS hard b/c I've personally never tried it, lol. It didn't matter b/c you could always just get a stick in Goron City, and after ER was implemented I never went back to check.

**Comment by r0bd0g** [comment]
Sometimes video games have things in them that are hard. I really don't believe this is a trick.

**Pull request merged**
