### PR TITLE
Shuffle Frog Song Rupees

### PR DESCRIPTION
**Pull request by Cuphat**
Adds an option to shuffle the 5 Purple Rupees rewarded from playing the non-warp songs other than Song of Storms to the Zora's River frogs.

### CODE REVIEW

**Comment by fenhl** [comment]
Frogs in the Rain is a sometimes hint so the new checks probably should be as well.

**Comment by r0bd0g** [comment]
I'm not convinced this should be optional. This is a very different case from medi/carpet as those are normally repeatable. These checks are 1-time rewards from NPCs. Perhaps they should have always been shuffled? See also: 40 skulltulas, which also normally just gives a 1-time refill item (or at least it's only a refill item when chus in logic is off). Instead you could decide whether or not to disable those new locations in the various presets? (But what if you liked having those guaranteed purple rupees...)

There's a bit of a related thing here where there are one-time reward rupees from a minigame... Rounds 1 and 2 of ocarina memory. Even from the very first release there were no rounds 1 and 2; it just went straight to the final 8-note round. At some point, the final round was changed from 8 to 5 notes. I suggest bringing back all three rounds and disabling rounds 2 and 3 by default in most presets?

**Comment by cjohnson57** [comment]
I'm inclined to agree with r0b, but I don't think it's too big a deal either way

**Comment by fenhl** [comment]
It might also make sense to rename the Frogs in the Rain location for consistency with the new ones.

**Review by cjohnson57 — APPROVED** [review]

**Pull request merged**
